### ISSUE TITLE
Cannot use knative-source-yaml loader

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1005]
If I've understood it correctly, a loader can be selected explicitly or by language in camel-k-runtime.

But there's no way to explicitly select a loader in the operator traits.
And if I set language to `knative-source-yaml` instead of `yaml`, the loader is selected, but automatic dependencies resolution does not work, because `knative-source-yaml` is not a language recognized by the operator.

@lburgazzoli is there another way to use it in 1.0.0-M2?

**Comment by lburgazzoli** [comment]
As far as I remember you was supposed to add the `loader` field to the `SourceSpec` while working on kanative related things :)

**Comment by nicolaferraro** [comment]
"As far as I remember" is not credible when said by you ;)

But yeah, you may be right.. and that's the missing piece.. let me work on it!
