### ISSUE TITLE
No interface for setting the number of pods on which an integration is to be deployed

### ISSUE THREAD

**Issue by rhn-support-kboone** [apache/camel-k#1032]
Camel K exposes an interface for setting the affinities of multiple integration pods with physical nodes on OpenShift/Kubernetes. However, there is no interface for controlling the number of pods assigned to a specific integration in the first place. 

A work-around is to do "oc edit it [integration]" or "kubectl edit it [integration]" and add the section ".spec.replicas" with the desired value. Note that this entry will not exist initially, and must be created.

**Comment by rhn-support-kboone** [comment]
I've just realized that if I change .spec.replicas using "oc edit it", the integration is no longer visible when I do "kamel get it". I don't know if that is significant or not. I can still use "oc" to manipulate the integration, it's just the kamel utility that doesn't seem to work.

**Comment by lburgazzoli** [comment]
@astefanutti this should be possible now right ?

**Comment by astefanutti** [comment]
yes, it is possible, also with `kubectl scale`.
