### ISSUE TITLE
Running without a platform

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1047]
Some people don't like the fact that you have to create a platform before being able to run an integration, especially in contexts like OpenShift where you don't need to provide any special configuration but you can use the default one as all parameters are automatically discovered.

Can we think to generate a default platform in contexts where the default one can work?

**Comment by oscerd** [comment]
+1

**Comment by nicolaferraro** [comment]
This is especially useful when you install camel k globally (and also knative sources). Once you do it, people can create those objects from the OCP console in any namespace and see them running.

**Comment by abouchama** [comment]
+1

**Comment by nicolaferraro** [comment]
Let's move this to milestone 5.
