### ISSUE TITLE
When kamel is launched from inside a container, it is using the serviceaccount of this container instead of the user configured in kubeconfig

### ISSUE THREAD

**Issue by apupier** [apache/camel-k#1048]
kamel CLI command are returning this kind of error
`Error: integrations.camel.apache.org is forbidden: User "system:serviceaccount:che:che-workspace" cannot create resource "integrations" in API group "camel.apache.org" in the namespace "che"`

although the current user is minikube (and which is admin so have all rights):

```
sh-5.0$ kubectl config view --template='{{ range .contexts }}{{ if eq .name "'$(kubectl config current-context)'" }}Current user: {{ .context.user }}{{ end }}{{ end }}'
Current user: minikube
```

**Comment by nicolaferraro** [comment]
Is the KUBECONFIG env var set in your case?

**Comment by apupier** [comment]
> Is the KUBECONFIG env var set in your case?

no it is not.

And when I set it to $HOME/.kube/config , it works!

I think it would be nice to follow the same behavior than kubectl to pick the user.
If too complicated, maybe an intermediate step can be to provide more guidance to users in error message to explain from where the user has been resolved? (would it be really easier to implement?)

**Comment by nicolaferraro** [comment]
Currently the logic search for some files that are only present only in containers, in order to determine which credentials to pick. We should reverse the logic prefer KUBECONFIG or ~/.kube/config to the container service account.
