### ISSUE TITLE
camel-k-maven-plugin must not contain any of these characters \/:"<>|?* but found > @ line 16, column 18

### ISSUE THREAD

**Issue by abouchama** [apache/camel-k#1056]
Hello,

After running the following example:

```
git clone https://github.com/abouchama/CamelK-customerAPI
kamel run customer-api.xml \
    --open-api customer-api.json \
    --name customers \
    --dependency camel-undertow \
    --dependency camel-rest \
    --property camel.rest.port=8080 
```
This end with the following error in the camelk operator pod:

> {"level":"info","ts":1573500771.1264646,"logger":"camel-k.trait","msg":"Apply trait: camel"}
> {"level":"info","ts":1573500771.1273205,"logger":"camel-k.trait","msg":"Apply trait: gc"}
> {"level":"info","ts":1573500771.1273396,"logger":"camel-k.trait","msg":"Apply trait: rest-dsl"}
> {"level":"info","ts":1573500771.127784,"logger":"camel-k.maven","msg":"executing: mvn -Dopenapi.spec=/tmp/rest-dsl735823832/0/openapi-spec.json -Ddsl.out=/tmp/rest-dsl735823832/0/openapi-dsl.xml --batch-mode -Dmaven.repo.local=/tmp/artifacts/m2 --settings /tmp/rest-dsl735823832/0/settings.xml","timeout":"3m45s"}
> [INFO] Scanning for projects...
> [ERROR] [ERROR] Some problems were encountered while processing the POMs:
> [ERROR] 'build.plugins.plugin.version' for org.apache.camel.k:camel-k-maven-plugin must not contain any of these characters \/:"<>|?* but found > @ line 16, column 18
>  @ 
> [ERROR] The build could not read 1 project -> [Help 1]
> [ERROR]   
> [ERROR]   The project org.apache.camel.k.integration:camel-k-rest-dsl-generator:1.0.0-M3 (/tmp/rest-dsl735823832/0/pom.xml) has 1 error
> [ERROR]     'build.plugins.plugin.version' for org.apache.camel.k:camel-k-maven-plugin must not contain any of these characters \/:"<>|?* but found > @ line 16, column 18

**Comment by abouchama** [comment]
After investigation, the pom generated in /tmp/rest-dsl735823832/0/pom.xml has the following unauthorized character in the version of the camel-k-maven-plugin: `<version>&gt;=1.0.5</version>`.

By removing this character `&gt;=` everything works as expected

**Comment by astefanutti** [comment]
Thanks a lot for the report!

It may have been fixed already with dcfb8a36795998b83f25057666ab278d9efadc48, which we'll be released in the next milestone. If you have the chance to test on `master`, that'd be great. Otherwise we'll have a look ASAP.

**Comment by abouchama** [comment]
Thanks lot @astefanutti 

You are right, this has been fixed by changing the value of `.spec.build.runtimeVersion` the integration platform:

````
$ oc get integrationplatforms.camel.apache.org camel-k -o yaml | yq read - 'spec.build.runtimeVersion'
>=1.0.5
$ oc edit integrationplatforms.camel.apache.org camel-k 
$ oc get integrationplatforms.camel.apache.org camel-k -o yaml | yq read - 'spec.build.runtimeVersion'
1.0.5
```

**Comment by abouchama** [comment]
The issue is still present on 1.0.0-M4:

```
$ oc get integrationplatforms.camel.apache.org camel-k -o yaml | yq read - 'spec.build.runtimeVersion'
>=1.0.7
```

**Comment by astefanutti** [comment]
It's normal to have a version constraint in the integration platform. The fix in 96ffc51 and /or dcfb8a3 make sure it's not directly used in the integration.

Could you check the integration status field?

**Comment by abouchama** [comment]
Hi @astefanutti , below how you can reproduce it:
```
$ kamel install
Camel K installed in namespace knativetutorial
$ oc get integrationplatforms.camel.apache.org camel-k -o yaml | yq read - 'spec.build.runtimeVersion'
>=1.0.7
```
and i run the following in order to fix it:
```
$ oc get integrationplatforms.camel.apache.org camel-k -o yaml | yq w - 'spec.build.runtimeVersion' 1.0.7 \
| oc apply -f -
Warning: oc apply should be used on resource created by either oc create --save-config or oc apply
integrationplatform.camel.apache.org/camel-k configured
```

**Comment by astefanutti** [comment]
@abouchama it’s normal to have `>=1.0.7` in the integration platform. Can you check the integration deploy correctly without applying the work around?

**Comment by abouchama** [comment]
@astefanutti without this change we got the following error in the camelk operator once we deploy the integration with `kamel run customer.xml`:

```
{"level":"info","ts":1573500771.1264646,"logger":"camel-k.trait","msg":"Apply trait: camel"}
{"level":"info","ts":1573500771.1273205,"logger":"camel-k.trait","msg":"Apply trait: gc"}
{"level":"info","ts":1573500771.1273396,"logger":"camel-k.trait","msg":"Apply trait: rest-dsl"}
{"level":"info","ts":1573500771.127784,"logger":"camel-k.maven","msg":"executing: mvn -Dopenapi.spec=/tmp/rest-dsl735823832/0/openapi-spec.json -Ddsl.out=/tmp/rest-dsl735823832/0/openapi-dsl.xml --batch-mode -Dmaven.repo.local=/tmp/artifacts/m2 --settings /tmp/rest-dsl735823832/0/settings.xml","timeout":"3m45s"}
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'build.plugins.plugin.version' for org.apache.camel.k:camel-k-maven-plugin must not contain any of these characters /:"<>|?* but found > @ line 16, column 18
@
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR] The project org.apache.camel.k.integration:camel-k-rest-dsl-generator:1.0.0-M3 (/tmp/rest-dsl735823832/0/pom.xml) has 1 error
[ERROR] 'build.plugins.plugin.version' for org.apache.camel.k:camel-k-maven-plugin must not contain any of these characters /:"<>|?* but found > @ line 16, column 18
```

**Comment by astefanutti** [comment]
@abouchama have you re-created the integration?

**Comment by abouchama** [comment]
@astefanutti even if you recreate the integration, the only way is to remove `>=`

**Comment by lburgazzoli** [comment]
@astefanutti what fails is the generator of the route dal from openapi, I think there’s a leftover somewhere
