### ISSUE TITLE
Doc and/or command should be changed - kamel install

### ISSUE THREAD

**Issue by cmoulliard** [apache/camel-k#106]
When we execute the command `kamel install` to deploy the CustomResourceDefintion, then we get this error

```
./kamel install
Error: failed to get resource client: failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(camel.apache.org/v1alpha1, Kind=IntegrationContext): no matches for kind "IntegrationContext" in version "camel.apache.org/v1alpha1"
```

This error is gone when running this command `./kamel install --cluster-setup`

I suggest to update the doc and make the error reported more user's friendly

**Comment by nicolaferraro** [comment]
Yes, it was supposed to give a user friendly message and ask the user to login as admin.

Technically `kamel install` should do `kamel install --cluster-setup` plus other things, so I expect you did a `oc login -u system:admin` between the two invocations. Isn't it?

**Comment by cmoulliard** [comment]
Yes. I did a `oc login -u admin -p admin` which is `cluster-admin`'s role  before
