### ISSUE TITLE
Remove requirement for PVC on vanilla Kube

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1069]
We need a PVC only when caching is enabled, but for normal Kaniko build and push we can initialize the tar.gz in an init-container and then push it to the registry via the Kaniko pod (with data shared using a node local directory volume).

We can also disable image caching by default (caching is a simple but problematic piece, don't really know why). When caching is enabled we can mount the PV for the cache only.

wdyt @astefanutti ?

**Comment by astefanutti** [comment]
I agree Kaniko caching causes too much trouble compared to the benefits. I think the the init container approach makes sense.

**Comment by astefanutti** [comment]
I've started working on implementing the init container strategy. It's a bit more involved than I anticipated originally as it requires disentangling the scheduling logic from the build logic, and impacts the Build API, but I think it's worth the effort and it will ease supporting Tekton as build strategy eventually (#682).
