### ISSUE TITLE
Camel K doesn't support kubernetes services of type loadbalancer

### ISSUE THREAD

**Issue by pabloxtiyo** [apache/camel-k#1070]
Hi Guys, do you know how to change/modify the service that camel k creates by default from ClusterIp to LoadBalancer?
im running this command:: 
kamel run StackDriverWebHookRoute.java --dependency=camel-rest --dependency=camel-restlet -n arch --dev

but service is always a ClusterIp
![image](https://user-images.githubusercontent.com/6226571/69370561-cb47d700-0c63-11ea-848e-ca6ba9863458.png)

**Comment by astefanutti** [comment]
Thanks for the feedback. There is currently no option to set the service type, though it should be straightforward to add an option to the service trait.

**Comment by sschere** [comment]
I've faced the same issue, and solved by creating an adicional service as LoadBalancer. Let's say your service deployed using kamel run is being called "rest-dsl", then below kubectl cli will create a new service called "rest-dsl-lb". Then you can keep kamel deploying into a NodePort type and the LoadBalancer will redirect to that. I hope that helps:

`kubectl expose service rest-dsl --name rest-dsl-lb --port=80 --type=LoadBalancer --target-port=8080`

**Comment by tadayosi** [comment]
Right now Service trait only has `NodePort` bool flag but we should introduce a new property `Type` that accepts `ClusterIP`, `NodePort`, and `LoadBalancer` and deprecate the `NodePort` bool flag.
