### ISSUE TITLE
Example Request: CamelJmsToFileExample.java

### ISSUE THREAD

**Issue by RnD-John** [apache/camel-k#1079]
Please provide a JMS to File example that runs on camel-K.

The regular camel example is here: https://github.com/apache/camel/tree/master/examples/camel-example-jms-file

Thank you,
-John

**Comment by davesargrad** [comment]
Hi @RnD-John 

I've tried to create one myself, since I have been trying to understand how dependencies are on packages such as org.apache.camel.component.jms are included.

The sample I've tried is just to take the camel-k Sample.java and to begin to import packages that relate to your JMS interest.

Using the following code, I see the sample pod fail to run properly

`import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.CamelContext;
import org.apache.camel.ProducerTemplate;
import org.apache.camel.component.jms.JmsComponent;

public class Sample extends RouteBuilder {
  @Override
  public void configure() throws Exception {
	  from("timer:tick")
      .log("Hello Camel K!");
  }
}
`

The error I see in the POD log follows

![image](https://user-images.githubusercontent.com/48793689/69553926-fa658d80-0f6e-11ea-93ae-5724dc6e6da7.png)

**Comment by RnD-John** [comment]
@davesargrad - When attempting to run a similar test to what you describe, I received the same dependency errors. 

I also tried to run the camel based example without explicitly requesting the packages (assuming that camel-k may automatically include them for me). That results in unknown symbol errors.

I thought my approach might be fundamentally flawed so I just posted it as a feature request. Thank you for the help.

-John

**Comment by davsclaus** [comment]
Camel K only detects components in the route DSL, eg like to("jms:xxx") etc. Java import statements are "just noise", and if you add a import for a component that are unused like you do, then you get this error, unless you tell Camel K to add camel-jms as dependecy from the command line arguments.

**Comment by davesargrad** [comment]
Thanks @davsclaus 
How would I add [camel-jms](https://mvnrepository.com/artifact/org.apache.camel/camel-jms) as a dependency from the command line?

Assume for example, that I need the following:
```
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-jms</artifactId>
    <version>2.24.1</version>
</dependency>
```

How would I invoke kamel to build an integrationplatform that contains the proper dependency?

**Comment by davesargrad** [comment]
The full code that Im trying to get running:

```
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.CamelContext;
import org.apache.camel.ProducerTemplate;

import org.apache.activemq.ActiveMQConnectionFactory;

public class Sample extends RouteBuilder {
  @Override
  public void configure() throws Exception {

        ConnectionFactory connectionFactory = new ActiveMQConnectionFactory("tcp://mali.corp.sensis.com:61616");
        
        // Note we can explicit name the component
        context.addComponent("test-jms", JmsComponent.jmsComponentAutoAcknowledge(connectionFactory));

	  from("test-jms:queue:sargradtest.queue")
      .log("Got a message !");
  }
}

```

**Comment by davsclaus** [comment]
See docs
https://camel.apache.org/camel-k/latest/configuration/dependencies.html

**Comment by davesargrad** [comment]
@davsclaus 

This is what I have tried:

`kamel run -d mvn:org.apache.activemq.activemq-core:5.5.1 -d mvn:org.apache.activemq.activemq-camel:5.5.1 Sample.java`

The error that shows up in the camel-k-kit builder is:

![image](https://user-images.githubusercontent.com/48793689/69570734-6a374080-0f8e-11ea-9d09-c7b719d9a9ad.png)

**Comment by lburgazzoli** [comment]
Looks liek the GAV is not in the right format, try with:

    mvn:org.apache.activemq:activemq-core:5.5.1

note the : between groupId and artifactId

**Comment by davesargrad** [comment]
> Looks liek the GAV is not in the right format, try with:
> 
> ```
> mvn:org.apache.activemq:activemq-core:5.5.1
> ```
> 
> note the : between groupId and artifactId

Wow!! That worked!

**Comment by davesargrad** [comment]
The only problem with the running route is access to the camel context. 

The code I am trying to use:
```
public class Sample extends RouteBuilder {
  @Override
  public void configure() throws Exception {

        ConnectionFactory connectionFactory = new ActiveMQConnectionFactory("tcp://mali.corp.sensis.com:61616");

        // Note we can explicit name the component
        context.addComponent("test-jms", JmsComponent.jmsComponentAutoAcknowledge(connectionFactory));

          from("test-jms:queue:sargradtest.queue")
                .log("Got a message !");
  }
}

```

The Error:
![image](https://user-images.githubusercontent.com/48793689/69572269-c8195780-0f91-11ea-9ac0-4374fb0daf11.png)

**Comment by lburgazzoli** [comment]
I think it is getContext()

**Comment by davesargrad** [comment]
@lburgazzoli 
You are right yet again.

Incrementally closer.

![image](https://user-images.githubusercontent.com/48793689/69572755-d0be5d80-0f92-11ea-9851-d2461ca322ec.png)

**Comment by lburgazzoli** [comment]
looks like it lacks one of the spring classes, thus I do not know which artifact provides it, likely to be spring-core

**Comment by davsclaus** [comment]
Yeah you need all of the JARs for the activemq-client, as its using the JMS client, so you should have that as dependency, and also maybe one of the connection pools. 

You can use the activemq component instead of jms as its for ActiveMQ 5.x. Where you can say

-d camel-activemq to tell it to add this component which should come with the JMS Client and connection pool et all.

**Comment by davesargrad** [comment]
@lburgazzoli and @davsclaus 

Thanks guys.
I'll see if I can do what you are suggesting..

Great to have your feedback.

**Comment by hguerrero** [comment]
@lburgazzoli my PR #1067  with AMQP examples cover the usage of JMS client with Qpid, but the manage of ConnectionFactory apply to any other component using that type of configuration.

**Comment by davesargrad** [comment]
@davsclaus  and @lburgazzoli 

You guys gave me what I needed to get this working.

The following command line successfully runs the JMS integration

 kamel run -d mvn:org.apache.activemq:activemq-all:5.5.1 -d mvn:org.apache.activemq:activemq-camel:5.5.1 Sample.java

Sample.java
```
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.CamelContext;
import org.apache.camel.component.jms.JmsComponent;
import org.apache.camel.ProducerTemplate;

import javax.jms.ConnectionFactory;

import org.apache.activemq.ActiveMQConnectionFactory;

public class Sample extends RouteBuilder {
  @Override
  public void configure() throws Exception {

        ConnectionFactory connectionFactory = new ActiveMQConnectionFactory("tcp://activemq.svc.ip:61616");

        CamelContext context = getContext();
        // Note we can explicit name the component
        context.addComponent("test-jms", JmsComponent.jmsComponentAutoAcknowledge(connectionFactory));

          from("test-jms:queue:sargradtest.queue")
                .log("Got a message !");
  }
}
```
I was able to receive data from a real ActiveMQ service.

![image](https://user-images.githubusercontent.com/48793689/70060521-b39c1700-15b0-11ea-9521-da02793ae33b.png)

**Comment by davsclaus** [comment]
Yeah and we are also working on fixing so camel-activemq works nicer OOTB
https://issues.apache.org/jira/browse/CAMEL-14220

So all you need is to just set
camel.component.activemq.brokerURL=tcp:xxxx

Then it comes with all dependencies included as well

**Comment by RnD-John** [comment]
@davesargrad et all,
Thank you for working through this. I will give this a shot.
-John

**Comment by RnD-John** [comment]
**Question:**
How do I pass my connection factory URI as an argument?

**Background:**
I was able to connect to an ActiveMQ broker using the code posted here. Upon trying to parameterize the code so that I can pass in the queue name and the URI from the command line, I found that I can only use the --property command to set sub-strings within the Camel-K DSL portion.

using the command:
kamel run -d mvn:org.apache.activemq:activemq-all:5.5.1 -d mvn:org.apache.activemq:activemq-camel:5.5.1 -p my.message="It WORKED" -p my.message2="STILL" -p my.queue="camelktest" -p my.uri="<myFQDN>" --name "ParameterizedBAMQ" BasicAMQ.java 

on the file:
BasicAMQ.java:
`import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.CamelContext;
import org.apache.camel.component.jms.JmsComponent;
import org.apache.camel.ProducerTemplate;

import javax.jms.ConnectionFactory;

import org.apache.activemq.ActiveMQConnectionFactory;

public class BasicAMQ extends RouteBuilder {
  @Override
  public void configure() throws Exception {

        ConnectionFactory connectionFactory = new ActiveMQConnectionFactory("{{my.uri}}");

        CamelContext context = getContext();
        // Note we can explicit name the component
        context.addComponent("test-jms", JmsComponent.jmsComponentAutoAcknowledge(connectionFactory));

          from("test-jms:queue:{{my.queue}}.queue")
                .log("{{my.message}} {{my.message2}} ! ${body} ");
  }
}`

I get the error:
Exception in thread "main" java.lang.IllegalArgumentException: Invalid broker URI: {{my.uri}}

How do I pass my connection factory URI as an argument?

**Comment by davesargrad** [comment]
Hi @RnD-John 
Did you figure out the answer to your last question? 

@nicolaferraro perhaps you have some insights on how a parameter can be passed into the "route code". The "my.uri" above is a perfect example of something that should not be hard-coded. I'd think its easy to pass this in on the "kamel" command line.

**Comment by RnD-John** [comment]
@davesargrad I was out of the office for a few days; however, I still don't have a great solution for this. The best solution I have come up with is to utilize file io to read the desired values from a from a file on the disk. In general, I'd still like to see what @nicolaferraro or others recommend in terms of potential 'native' support.

**Comment by nicolaferraro** [comment]
Native support will come with properties when we switch to Camel 3.0.1 (next version is expected to support Camel 3.0.0).

For the time being a possible solution is to use env variables:

```
ConnectionFactory connectionFactory = new ActiveMQConnectionFactory(System.getenv("MY_URI"));
```

And:

```
kamel run --env MY_URI=xxx TheIntegration.java
```

It's more a workaround waiting for property-based configuration, but it should work.

**Comment by lburgazzoli** [comment]
You can also use

```java
public class BasicAMQ extends RouteBuilder {
    @PropertyInject("my.uri") 
    String uri;

     ....
}
```

Then you should be able to provide `my.uti` value either from a configmap or env var.

**Comment by davesargrad** [comment]
> You can also use
> 
> ```java
> public class BasicAMQ extends RouteBuilder {
>     @PropertyInject("my.uri") 
>     String uri;
> 
>      ....
> }
> ```
> 
> Then you should be able to provide `my.uti` value either from a configmap or env var.

Hi @lburgazzoli 
Oddly, I see the annotation PropertyInject in[ older versions of came](https://www.javadoc.io/doc/org.apache.camel/camel-core/2.20.4/org/apache/camel/PropertyInject.html)l.

Its not in the newest [javadoc](https://www.javadoc.io/doc/org.apache.camel/camel-core/3.0.0-RC1/index.html).

**Comment by lburgazzoli** [comment]
camel-core as been modularized in camel 3, the javadoc for the annotation is here: https://www.javadoc.io/doc/org.apache.camel/camel-api/latest/index.html

**Comment by davesargrad** [comment]
> camel-core as been modularized in camel 3, the javadoc for the annotation is here: https://www.javadoc.io/doc/org.apache.camel/camel-api/latest/index.html

Thanks @lburgazzoli !! Good to know

**Comment by RnD-John** [comment]
@lburgazzoli, using the @PropertyInject Method is throwing the following error:

>Exception in thread "main" org.apache.camel.RuntimeCamelException: org.joor.ReflectException: java.lang.reflect.InvocationTargetException
        at org.apache.camel.RuntimeCamelException.wrapRuntimeCamelException(RuntimeCamelException.java:52)
        at org.apache.camel.k.listener.RoutesConfigurer.load(RoutesConfigurer.java:69)
        at org.apache.camel.k.listener.RoutesConfigurer.accept(RoutesConfigurer.java:51)
        at org.apache.camel.k.listener.AbstractPhaseListener.accept(AbstractPhaseListener.java:32)
        at org.apache.camel.k.main.ApplicationRuntime$MainListenerAdapter.lambda$invokeListeners$0(ApplicationRuntime.java:152)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.apache.camel.k.main.ApplicationRuntime$MainListenerAdapter.invokeListeners(ApplicationRuntime.java:151)
        at org.apache.camel.k.main.ApplicationRuntime$MainListenerAdapter.beforeStart(ApplicationRuntime.java:125)
        at org.apache.camel.main.MainSupport.beforeStart(MainSupport.java:114)
        at org.apache.camel.main.MainSupport.run(MainSupport.java:76)
        at org.apache.camel.k.main.ApplicationRuntime.run(ApplicationRuntime.java:70)
        at org.apache.camel.k.main.Application.main(Application.java:42)
Caused by: org.joor.ReflectException: java.lang.reflect.InvocationTargetException
        at org.joor.Reflect.on(Reflect.java:876)
        at org.joor.Reflect.create(Reflect.java:698)
        at org.joor.Reflect.create(Reflect.java:662)
        at org.apache.camel.k.loader.java.JavaSourceRoutesLoader.load(JavaSourceRoutesLoader.java:47)
        at org.apache.camel.k.listener.RoutesConfigurer.load(RoutesConfigurer.java:67)
        ... 17 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.joor.Reflect.on(Reflect.java:873)
        ... 21 more
Caused by: java.lang.NullPointerException
        at java.net.URI$Parser.parse(URI.java:3042)
        at java.net.URI.<init>(URI.java:588)
        at org.apache.activemq.ActiveMQConnectionFactory.createURI(ActiveMQConnectionFactory.java:168)
        at org.apache.activemq.ActiveMQConnectionFactory.<init>(ActiveMQConnectionFactory.java:131)
        at BasicAMQ.<init>(BasicAMQ.java:17)
        ... 26 more
<

I updated my script as follows:
`import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.CamelContext;
import org.apache.camel.component.jms.JmsComponent;
import org.apache.camel.ProducerTemplate;

import javax.jms.ConnectionFactory;

import org.apache.activemq.ActiveMQConnectionFactory;

public class BasicAMQ extends RouteBuilder
{
    //standard java, need to inject properties to use them//
@org.apache.camel.PropertyInject("{{my.uri}}")
private String uri;
@org.apache.camel.PropertyInject("{{my.component}}")
private String component;
ConnectionFactory connectionFactory = new ActiveMQConnectionFactory(uri);


    @Override
    public void configure() throws Exception
    {
        CamelContext context = getContext();
        // Note we can explicit name the component
        context.addComponent(component, JmsComponent.jmsComponentAutoAcknowledge(connectionFactory));

        //DSL starts here, can directly use {{}} syntax for properties//
        from(component+":queue:{{my.queue}}.queue")
        .log("{{my.prefix}} ${body} ");
    }
}
`

I run with the command:
kamel run -d mvn:org.apache.activemq:activemq-all:5.5.1 -d mvn:org.apache.activemq:activemq-camel:5.5.1 -p my.uri="<MY_URI>" -p my.component="test-jms" -p my.queue="camelktestParametric" -p my.prefix="Got a message: " --name "ParameterizedBAMQ" BasicAMQ.java

**Comment by lburgazzoli** [comment]
property inject do not require {{}}

**Comment by RnD-John** [comment]
using the values as keys directly also throws the error...
@org.apache.camel.PropertyInject("my.uri")
private String uri;
@org.apache.camel.PropertyInject("my.component")
private String component;

**Comment by RnD-John** [comment]
@lburgazzoli, The PropertyInject method is desirable because everything can come from command line properties or from a config map. **I'd still like to get this method to work if possible.**

@nicolaferraro, In the mean time, I tested the environment variable method and that worked as expected.

> 
> 
> Native support will come with properties when we switch to Camel 3.0.1 (next version is expected to support Camel 3.0.0).
> 
> For the time being a possible solution is to use env variables:
> 
> ```
> ConnectionFactory connectionFactory = new ActiveMQConnectionFactory(System.getenv("MY_URI"));
> ```
> 
> And:
> 
> ```
> kamel run --env MY_URI=xxx TheIntegration.java
> ```
> 
> It's more a workaround waiting for property-based configuration, but it should work.

**Comment by lburgazzoli** [comment]
So I have a route like:

```java
import org.apache.camel.PropertyInject;
import org.apache.camel.builder.RouteBuilder;

public class Sample extends RouteBuilder {
  @PropertyInject("my.url")
  String url;

  @Override
  public void configure() throws Exception {
    from("timer:tick")
      .setBody().constant(url)
      .log("${body}");
  }
}
```

The I do run it with:

    kamel run --dev -p my.url=test examples/Sample.java

And what I see in my toute is:

```
[2] 2019-12-12 21:19:31.752 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.ContextConfigurer@3c9d0b9d
[2] 2019-12-12 21:19:31.760 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.RoutesConfigurer@7ee955a8
[2] 2019-12-12 21:19:31.763 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.RoutesDumper@6ac13091
[2] 2019-12-12 21:19:31.793 INFO  [main] RuntimeSupport - Looking up loader for language: java
[2] 2019-12-12 21:19:31.805 INFO  [main] RuntimeSupport - Found loader org.apache.camel.k.loader.java.JavaSourceRoutesLoader@6f96c77 for language java from service definition
[2] 2019-12-12 21:19:32.536 INFO  [main] RoutesConfigurer - Loading routes from: file:/etc/camel/sources/i-source-000/Sample.java?language=java
[2] 2019-12-12 21:19:32.537 INFO  [main] ApplicationRuntime - Listener org.apache.camel.k.listener.RoutesConfigurer@7ee955a8 executed in phase ConfigureRoutes
[2] 2019-12-12 21:19:32.555 INFO  [main] BaseMainSupport - Using properties from: file:/etc/camel/conf/application.properties
[2] 2019-12-12 21:19:33.023 INFO  [main] ApplicationRuntime - Listener org.apache.camel.k.listener.ContextConfigurer@3c9d0b9d executed in phase ConfigureContext
[2] 2019-12-12 21:19:33.024 INFO  [main] DefaultCamelContext - Apache Camel 3.0.0-RC3 (CamelContext: camel-k) is starting
[2] 2019-12-12 21:19:33.028 INFO  [main] DefaultManagementStrategy - JMX is disabled
[2] 2019-12-12 21:19:33.180 INFO  [main] DefaultCamelContext - StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
[2] 2019-12-12 21:19:33.192 INFO  [main] DefaultCamelContext - Route: route1 started and consuming from: timer://tick
[2] 2019-12-12 21:19:33.196 INFO  [main] DefaultCamelContext - Total 1 routes, of which 1 are started
[2] 2019-12-12 21:19:33.199 INFO  [main] DefaultCamelContext - Apache Camel 3.0.0-RC3 (CamelContext: camel-k) started in 0.173 seconds
[2] 2019-12-12 21:19:33.200 INFO  [main] ApplicationRuntime - Listener org.apache.camel.k.listener.RoutesDumper@6ac13091 executed in phase Started
[2] 2019-12-12 21:19:34.223 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - test
[2] 2019-12-12 21:19:35.196 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - test
```

So the properties binding works

**Comment by davesargrad** [comment]
> So I have a route like:
> 
> ```java
> import org.apache.camel.PropertyInject;
> import org.apache.camel.builder.RouteBuilder;
> 
> public class Sample extends RouteBuilder {
>   @PropertyInject("my.url")
>   String url;
> 
>   @Override
>   public void configure() throws Exception {
>     from("timer:tick")
>       .setBody().constant(url)
>       .log("${body}");
>   }
> }
> ```
> 
> The I do run it with:
> 
> ```
> kamel run --dev -p my.url=test examples/Sample.java
> ```
> 
> And what I see in my toute is:
> 
> ```
> [2] 2019-12-12 21:19:31.752 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.ContextConfigurer@3c9d0b9d
> [2] 2019-12-12 21:19:31.760 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.RoutesConfigurer@7ee955a8
> [2] 2019-12-12 21:19:31.763 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.RoutesDumper@6ac13091
> [2] 2019-12-12 21:19:31.793 INFO  [main] RuntimeSupport - Looking up loader for language: java
> [2] 2019-12-12 21:19:31.805 INFO  [main] RuntimeSupport - Found loader org.apache.camel.k.loader.java.JavaSourceRoutesLoader@6f96c77 for language java from service definition
> [2] 2019-12-12 21:19:32.536 INFO  [main] RoutesConfigurer - Loading routes from: file:/etc/camel/sources/i-source-000/Sample.java?language=java
> [2] 2019-12-12 21:19:32.537 INFO  [main] ApplicationRuntime - Listener org.apache.camel.k.listener.RoutesConfigurer@7ee955a8 executed in phase ConfigureRoutes
> [2] 2019-12-12 21:19:32.555 INFO  [main] BaseMainSupport - Using properties from: file:/etc/camel/conf/application.properties
> [2] 2019-12-12 21:19:33.023 INFO  [main] ApplicationRuntime - Listener org.apache.camel.k.listener.ContextConfigurer@3c9d0b9d executed in phase ConfigureContext
> [2] 2019-12-12 21:19:33.024 INFO  [main] DefaultCamelContext - Apache Camel 3.0.0-RC3 (CamelContext: camel-k) is starting
> [2] 2019-12-12 21:19:33.028 INFO  [main] DefaultManagementStrategy - JMX is disabled
> [2] 2019-12-12 21:19:33.180 INFO  [main] DefaultCamelContext - StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
> [2] 2019-12-12 21:19:33.192 INFO  [main] DefaultCamelContext - Route: route1 started and consuming from: timer://tick
> [2] 2019-12-12 21:19:33.196 INFO  [main] DefaultCamelContext - Total 1 routes, of which 1 are started
> [2] 2019-12-12 21:19:33.199 INFO  [main] DefaultCamelContext - Apache Camel 3.0.0-RC3 (CamelContext: camel-k) started in 0.173 seconds
> [2] 2019-12-12 21:19:33.200 INFO  [main] ApplicationRuntime - Listener org.apache.camel.k.listener.RoutesDumper@6ac13091 executed in phase Started
> [2] 2019-12-12 21:19:34.223 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - test
> [2] 2019-12-12 21:19:35.196 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - test
> ```
> 
> So the properties binding works. I think your issue is that the connection factory is instantiated at class constructions, you should move it to the `configure` method as the injection happens after the class has been constructed, before that the url is null

Good clean example... Ty

**Comment by RnD-John** [comment]
per @lburgazzoli 
> I think your issue is that the connection factory is instantiated at class constructions, you should move it to the `configure` method as the injection happens after the class has been constructed, before that the url is null

**This fixes the issue**. Thank you for the assistance. For those interested, the new code is as follows:

> import org.apache.camel.builder.RouteBuilder;
> import org.apache.camel.CamelContext;
> import org.apache.camel.component.jms.JmsComponent;
> import org.apache.camel.ProducerTemplate;
> import org.apache.camel.PropertyInject;
> 
> import javax.jms.ConnectionFactory;
> 
> import org.apache.activemq.ActiveMQConnectionFactory;
> 
> public class BasicAMQ extends RouteBuilder
> {
>     //standard java, need to inject properties to use them//
>     @PropertyInject("my.uri")
>     private String uri;
>     @PropertyInject("my.component")
>     private String component;
> 
>     @Override
>     public void configure() throws Exception
>     {
>         ConnectionFactory connectionFactory = new ActiveMQConnectionFactory(uri);
> 
>         CamelContext context = getContext();
>         context.addComponent(component, JmsComponent.jmsComponentAutoAcknowledge(connectionFactory));
> 
>         //DSL starts here, can directly use {{}} syntax for properties//
>         from("{{my.component}}:queue:{{my.queue}}.queue")
>         .log("{{my.prefix}} ${body} ");
>     }
> }

Run via:

> kamel run -d mvn:org.apache.activemq:activemq-all:5.5.1 -d mvn:org.apache.activemq:activemq-camel:5.5.1 -p my.uri="<MY_URI>" -p my.component="test-jms" -p my.queue="camelktestParametric" -p my.prefix="Got a message: " --name "ParameterizedBAMQ" BasicAMQ.java
