### ISSUE TITLE
error building image: getting stage builder for stage 0: MANIFEST_UNKNOWN: "manifest unknown

### ISSUE THREAD

**Issue by athishsreeram** [apache/camel-k#1080]
https://github.com/abouchama/CamelK-customerAPI.git

➜  ~ kamel version
Camel K Client 1.0.0-M4
➜  ~
➜  ~ minikube version
minikube version: v1.1.0

➜  route git:(master) ✗  kamel run Customer.java --dev\
        --name customers \
        --dependency camel-undertow \
        --dependency camel-rest \
        --property camel.rest.port=8080
integration "customers" updated

` text_fields  timer_off  refresh  exposure_zero  file_download
INFO[0000] Downloading base image 10.105.185.86/default/camel-k-kit-bnbm3p7kqcn52k5g91l0:57989 
2019/11/23 07:05:28 No matching credentials were found, falling back on anonymous
INFO[0000] Error while retrieving image from cache: MANIFEST_UNKNOWN: "manifest unknown" 
INFO[0000] Downloading base image 10.105.185.86/default/camel-k-kit-bnbm3p7kqcn52k5g91l0:57989 
2019/11/23 07:05:28 No matching credentials were found, falling back on anonymous
error building image: getting stage builder for stage 0: MANIFEST_UNKNOWN: "manifest unknown
`

**Comment by nicolaferraro** [comment]
Seems similar to #998 . I'm trying to get in touch with Kaniko to sort this out.

**Comment by nicolaferraro** [comment]
There have been some releases that fixed cache issues.. This may be related to one fixed in Kaniko 0.10.

**Comment by nicolaferraro** [comment]
It remains stuck on Kaniko `0.14.0`. I've opened https://github.com/GoogleContainerTools/kaniko/issues/886

**Comment by keyone** [comment]
It works if I restart the minikube again

**Comment by davsclaus** [comment]
Yeah I had that today as well on minikube. I had set a LimitRange with memory settings that was low 25Mi to 100Mi. And then when I deployed a new Kamel integration where it needed to build a new kit, then the builder pod OOME and then it was kinda toasted ever since. Even if I removed the LimitRange for memory, then new builds also failed with that MANIFEST error.

Restarting minikube worked.

**Comment by nicolaferraro** [comment]
@astefanutti I'm doing incremental builds with your patch in #1121 and it is working. Is this fixed by disabling the Cache?

**Comment by astefanutti** [comment]
@nicolaferraro possibly. There are other changes that may affect, yet I think it worth re-testing upgrading Kaniko after #1121 is merged.

**Comment by nicolaferraro** [comment]
No longer seeing this error, with both Kaniko 0.9 and 0.14.
Closing this as fixed by #1121.

We can reopen it in case the error is still there.
