### ISSUE TITLE
kamel - Allow to configure memory and cpu settings

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#1091]
When running small integrations it would be nice to make it easier to specify memory limits, so the pod wont take up too much memory.

For example being able to set the request and limit setting

   kamel run foo.xml --memory-limits=100 --memory-requests=25

Setting CPU settings can be done similar

   kamel run foo.xml --cpu-limits=2 --cpu-requests=1

This should be done in the deployment definition

```
   resources:                                                                                                                            │
│      limits:                                                                                                                             │
│        memory: 100Mi                                                                                                                     │
│      requests:                                                                                                                           │
│        memory: 25Mi
```

**Comment by jamesnetherton** [comment]
You can do this with the container trait:

https://camel.apache.org/camel-k/latest/traits/container.html

**Comment by davsclaus** [comment]
Ah perfect. btw what does .auto option do ?

**Comment by jamesnetherton** [comment]
Auto can automatically configure some extra things based on the environment. I.e for the container trait it can create a service. There's a few lines about it in the docs here:

https://camel.apache.org/camel-k/latest/traits/traits.html#_configuration
