### ISSUE TITLE
kamel scale integration to zero not possible

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#1094]
If you just want to scale a integration to zero (eg to stop it) then the operator will start it afterwards, so you can only delete it

    kamel run --name polyglot routes.xml beans.groovy JavaRoute.java

   kubectl scale deployment --replicas=0 polyglot

And then the operator creates a new polyglot integration, when k8s has scaled it down

Maybe we need a command on kamel so you can stop an integration, either via scale

    kamel scale --replicas=0 polyglot

**Comment by nicolaferraro** [comment]
I think we support scaling via `oc` or `kubectl` iirc (@astefanutti).

```
kubectl scale it polyglot --replicas 0
```

**Comment by astefanutti** [comment]
Yes, it's possible to scale the integration either with:

    $ kubectl scale it polyglot --replicas 0

Or:

    $ kubectl patch it polyglot --type='merge' -p '{"spec":{"replicas":"0"}}'

For some reasons (concurrency control IIRC), `kubectl scale` mandates to have the `.spec.replicas` already set for it to work. So you can use the latter command to set the field initially, or use `kubectl edit it polyglot` alternatively.

**Comment by davsclaus** [comment]
I tried the #1 above and then the kamel k operator sees the "change" and then start another pod with the integration. eg the operator dont know it was scaled down on purpose.

**Comment by astefanutti** [comment]
There is a bug with a recent change done in the GC trait that comes into the way of rescaling. I working on a PR right now that should fix the issue.
