### ISSUE TITLE
Kamel run --property-file

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#1102]
Add option `--property-file` to allow to refer to a file that becomes the `application.properties` file in the integration.

Today I can only configure this via `--property` on the CLI and have to set each command like that. It would be nice to have your own custom .properties files which you can refer to.

**Comment by lburgazzoli** [comment]
At the moment you can workaround this by using ConfigMaps but we are also thinking about [user profiles](https://github.com/apache/camel-k/issues/934)

**Comment by lburgazzoli** [comment]
You can now use env vars or configuration files: https://github.com/apache/camel-k/issues/1108
