### ISSUE TITLE
Support for using ENV variables in kamel binary

### ISSUE THREAD

**Issue by bouskaJ** [apache/camel-k#1103]
I would like to use ENV variables instead of `kamel` binary parameters. 

For instance
```
export KAMEL_INSTALL_MAVEN_REPOSITORY=http://mynexus.com
kamel install
```
would have the same result as
`kamel install --maven-repository http://mynexus.com`

**Comment by lburgazzoli** [comment]
Superseded by https://github.com/apache/camel-k/issues/1108
