### ISSUE TITLE
Investigate integration with Keda

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1107]
I'm starting to evaluate possible integrations with [Keda](https://github.com/kedacore/keda) which can expand our auto-scaling/scaling-to-zero capabilities also to non-http components.

Integration may be done through the Keda GRPC API. We can include in Camel some per-component meta extensions that will run in a meta-pod and will give to Keda the required metrics to automatically scale our integrations.

**Comment by welshstew** [comment]
This would be wonderful +1

**Comment by arthurdm** [comment]
+1
