### ISSUE TITLE
Review usage of version constraints

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1126]
We use by default camel-version ">= x.x.x" and runtime.version ">= y.y.y". But not having a precise version caused problems when e.g. a catalog for some reason is not present and it should be created.

I wonder why we don't default to a specific version and use constraints only when the user opt for them..

**Comment by lburgazzoli** [comment]
I remember we introduced constraints when runtime and camel were moving much faster and we added them for convenience but I do agree that now we should to stick to fixed versions
