### ISSUE TITLE
Add a specific label to the integration pod

### ISSUE THREAD

**Issue by abouchama** [apache/camel-k#1129]
It can be useful to pass a label in `kamel` command that will be set in the integration pod.

This can help for example to group pods under the same service in OpenShift.

**Comment by jcordes73** [comment]
At least an "app" label should be added to the integration pod, otherwise it will not be visible at all in the topology view.

**Comment by nicolaferraro** [comment]
This can be now done with:

```
kamel run Routes.java --label app=pippo -t owner.target-labels=app
```

The new topology view displays integrations even without app.
