### ISSUE TITLE
Trying to get sample RestWithUndertow working.

### ISSUE THREAD

**Issue by davesargrad** [apache/camel-k#1130]
I am running the restwithundertow example, as follows:
`kamel run -t ingress.host=benin.corp.sensis.com --name=rest-with-undertow --dependency=camel-rest --dependency=camel-undertow RestWithUndertow.java`

"benin.corp.sensis.com" is the k8s master. 
![image](https://user-images.githubusercontent.com/48793689/70456495-35da7e80-1a7c-11ea-8ae5-4264321103ba.png)

The integration is running. The pod is running on worker "spain".
![image](https://user-images.githubusercontent.com/48793689/70456594-64f0f000-1a7c-11ea-8ebe-a468c7380265.png)

I cant seem to browse to the service. I'm not even sure if I should browse on port 80, or port 8080 (I've tried both).
![image](https://user-images.githubusercontent.com/48793689/70456812-e3e62880-1a7c-11ea-81e7-e9df84499f02.png)

![image](https://user-images.githubusercontent.com/48793689/70456844-f4969e80-1a7c-11ea-9fec-1ee193f17ada.png)

The pod doesnt seem to show any activity on "hello". I've tried both spain and benin as my ingress host. Neither seem to have worked.

![image](https://user-images.githubusercontent.com/48793689/70456882-0e37e600-1a7d-11ea-8e8d-624aa61b9569.png)

**Comment by nicolaferraro** [comment]
Afaik, you should use a subdomain like `-t ingress.host=xxx.benin.corp.sensis.com` and then use `http://xxx.benin.corp.sensis.com/hello` (or `https`) to get your service. Your cluster DSN should be configured accordingly.

Camel K should create an ingress for the integration. Can you check it with `kubectl get ingress -o yaml`?

**Comment by davesargrad** [comment]
Hi @nicolaferraro 

The yaml for my ingress follows:
![image](https://user-images.githubusercontent.com/48793689/70531098-3d546300-1b22-11ea-8262-caf984549867.png)


I'm not sure what you mean by using an xxx subdomain of my host benin? I'm also not sure what you have in mind with the cluster DNS.

Camel-K did create the ingress you see above.

**Comment by davesargrad** [comment]
I'm not exactly sure what the ClusterIP is in the following 10.111.224.187. Should I be able to ping this?
![image](https://user-images.githubusercontent.com/48793689/70531348-be135f00-1b22-11ea-89a9-de43ca3c7f62.png)

**Comment by davesargrad** [comment]
![image](https://user-images.githubusercontent.com/48793689/70531702-780acb00-1b23-11ea-9e96-3392df4c6176.png)

**Comment by davesargrad** [comment]
![image](https://user-images.githubusercontent.com/48793689/70531744-8f49b880-1b23-11ea-8991-a304b1ce61df.png)

**Comment by davesargrad** [comment]
I can ping the endpoint that shows up in the rest-with-undertow service 
![image](https://user-images.githubusercontent.com/48793689/70531869-dafc6200-1b23-11ea-933e-3e6807ac6162.png)

**Comment by davesargrad** [comment]
![image](https://user-images.githubusercontent.com/48793689/70623563-680aee00-1bec-11ea-8de1-00960685650c.png)

**Comment by davesargrad** [comment]
As you see above, I got this working. I think it didnt work because of a proxy related issue. I've tweaked the way I handle no_proxy

![image](https://user-images.githubusercontent.com/48793689/70623742-be782c80-1bec-11ea-8760-9f18bbc14909.png)

**Comment by lburgazzoli** [comment]
@davesargrad can we close this one then ?

**Comment by davesargrad** [comment]
@lburgazzoli Yes Sir.. Closing. Ty!
