### ISSUE TITLE
Camel-k install on azure fails.

### ISSUE THREAD

**Issue by mrganeshraja** [apache/camel-k#1138]
I am unable to install camel-k to Azure aks cluster I get this error **"Error: No Auth Provider found for name "azure"**. I have made sure I have loggged in, I am able to issue other kubectl commands to query the cluster but when I try to install camel-k I always end up getting No Auth provider error. On other hand I am able to install camel-k on minikube from the same camel CLI.

`
~/Downloads/camel-k-client-1.0.0-M4-mac-64bit/kamel install
Error: No Auth Provider found for name "azure"
Usage:
  kamel install [flags]

Flags:
      --base-image string          Set the base image used to run integrations
      --build-strategy string      Set the build strategy
      --build-timeout string       Set how long the build process can last
      --camel-version string       Set the camel version
      --cluster-setup              Execute cluster-wide operations only (may require admin rights)
      --example                    Install example integration
      --global                     Configure the operator to watch all namespaces. No integration platform is created.
  -h, --help                       help for install
      --http-proxy-secret string   Configure the source of the secret holding HTTP proxy server details (HTTP_PROXY|HTTPS_PROXY|NO_PROXY)
      --kaniko-build-cache         To enable or disable the Kaniko Cache in building phase (default true)
      --kit strings                Add an integration kit to build at startup
      --local-repository string    Location of the local maven repository
      --maven-repository strings   Add a maven repository
      --maven-settings string      Configure the source of the maven settings (configmap|secret:name[/key])
      --operator-image string      Set the operator image used for the operator deployment
      --organization string        A organization on the Docker registry that can be used to publish images
  -o, --output string              Output format. One of: json|yaml
  -p, --property strings           Add a camel property
      --registry string            A Docker registry that can be used to publish images
      --registry-insecure          Configure to configure registry access in insecure mode or not
      --registry-secret string     A secret used to push/pull images to the Docker registry
      --runtime-version string     Set the camel-k runtime version
      --skip-cluster-setup         Skip the cluster-setup phase
      --skip-operator-setup        Do not install the operator in the namespace (in case there's a global one)
      --trait-profile string       The profile to use for traits
  -w, --wait                       Waits for the platform to be running

Global Flags:
      --config string      Path to the config file to use for CLI requests
  -n, --namespace string   Namespace to use for all operations

Error: No Auth Provider found for name "azure"`

**Comment by nicolaferraro** [comment]
Azure is not a provider that we tested so far.

I guess the problem is related to some auth missing in the kubernetes go-client we use under the hood: https://github.com/kubernetes/client-go/tree/master/plugin/pkg/client/auth/azure

Other than that, Camel K also needs a container registry to push built images to. @mrganeshraja does Kubernetes on Azure provide a default container registry?

**Comment by mrganeshraja** [comment]
@nicolaferraro no I dont't think Azure has default container registry.  I was having a look at client code `https://github.com/apache/camel-k/blob/master/pkg/client/client.go` this is missing the azure import I think. I have no knowledge of go lang If you point me to the right direction, I will be able to contribute a fix and also help test azure provider.

**Comment by nicolaferraro** [comment]
That would be awesome @mrganeshraja. Fortunately the fix should not require advanced go skills. I think that adding a simple import of

```
_ "k8s.io/client-go/plugin/pkg/client/auth/azure"
```
even in the `cmd/kamel/main.go` should be sufficient for making it work with Azure. It would be awesome if you could test the change in your environment.

You can find instructions on how to build the project in the [Developer's guide](https://camel.apache.org/camel-k/latest/developers.html).

**Comment by mrganeshraja** [comment]
@nicolaferraro - I added a fix by adding a azure client import line to main.go file and build the code locally. I was able to run kamel install <registryaddress> without any azure provider errors and successfully connect to my azure cluster. 

However I need your input to resolve build warnings that I am getting now after I have modified main.go 

`go test -c -tags="integration knative" ./e2e/*.go
go test ./...
?   	github.com/apache/camel-k/cmd/kamel	[no test files]
?   	github.com/apache/camel-k/cmd/manager	[no test files]
?   	github.com/apache/camel-k/cmd/util/doc-gen	[no test files]
?   	github.com/apache/camel-k/cmd/util/doc-gen/generators	[no test files]
?   	github.com/apache/camel-k/cmd/util/json-schema-gen	[no test files]
?   	github.com/apache/camel-k/cmd/util/license-check	[no test files]
?   	github.com/apache/camel-k/deploy	[no test files]
?   	github.com/apache/camel-k/e2e/util	[no test files]
?   	github.com/apache/camel-k/pkg/apis	[no test files]
ok  	github.com/apache/camel-k/pkg/apis/camel/v1alpha1	(cached)
?   	github.com/apache/camel-k/pkg/apis/camel/v1alpha1/knative	[no test files]
ok  	github.com/apache/camel-k/pkg/builder	(cached)
?   	github.com/apache/camel-k/pkg/builder/kaniko	[no test files]
ok  	github.com/apache/camel-k/pkg/builder/runtime	(cached)
?   	github.com/apache/camel-k/pkg/builder/s2i	[no test files]
?   	github.com/apache/camel-k/pkg/client	[no test files]
?   	github.com/apache/camel-k/pkg/client/clientset/versioned	[no test files]
?   	github.com/apache/camel-k/pkg/client/clientset/versioned/fake	[no test files]
?   	github.com/apache/camel-k/pkg/client/clientset/versioned/scheme	[no test files]
?   	github.com/apache/camel-k/pkg/client/clientset/versioned/typed/camel/v1alpha1	[no test files]
?   	github.com/apache/camel-k/pkg/client/clientset/versioned/typed/camel/v1alpha1/fake	[no test files]
?   	github.com/apache/camel-k/pkg/client/informers/externalversions	[no test files]
?   	github.com/apache/camel-k/pkg/client/informers/externalversions/camel	[no test files]
?   	github.com/apache/camel-k/pkg/client/informers/externalversions/camel/v1alpha1	[no test files]
?   	github.com/apache/camel-k/pkg/client/informers/externalversions/internalinterfaces	[no test files]
?   	github.com/apache/camel-k/pkg/client/listers/camel/v1alpha1	[no test files]
ok  	github.com/apache/camel-k/pkg/cmd	(cached)
?   	github.com/apache/camel-k/pkg/cmd/builder	[no test files]
?   	github.com/apache/camel-k/pkg/cmd/operator	[no test files]
?   	github.com/apache/camel-k/pkg/controller	[no test files]
?   	github.com/apache/camel-k/pkg/controller/build	[no test files]
ok  	github.com/apache/camel-k/pkg/controller/integration	(cached)
?   	github.com/apache/camel-k/pkg/controller/integrationkit	[no test files]
ok  	github.com/apache/camel-k/pkg/controller/integrationplatform	(cached)
ok  	github.com/apache/camel-k/pkg/gzip	(cached)
?   	github.com/apache/camel-k/pkg/install	[no test files]
ok  	github.com/apache/camel-k/pkg/metadata	(cached)
?   	github.com/apache/camel-k/pkg/platform	[no test files]
ok  	github.com/apache/camel-k/pkg/trait	(cached)
?   	github.com/apache/camel-k/pkg/util	[no test files]
ok  	github.com/apache/camel-k/pkg/util/camel	(cached)
?   	github.com/apache/camel-k/pkg/util/cancellable	[no test files]
?   	github.com/apache/camel-k/pkg/util/controller	[no test files]
?   	github.com/apache/camel-k/pkg/util/defaults	[no test files]
?   	github.com/apache/camel-k/pkg/util/digest	[no test files]
ok  	github.com/apache/camel-k/pkg/util/envvar	(cached)
?   	github.com/apache/camel-k/pkg/util/indentedwriter	[no test files]
ok  	github.com/apache/camel-k/pkg/util/knative	(cached)
ok  	github.com/apache/camel-k/pkg/util/kubernetes	(cached)
?   	github.com/apache/camel-k/pkg/util/kubernetes/customclient	[no test files]
?   	github.com/apache/camel-k/pkg/util/kubernetes/log	[no test files]
?   	github.com/apache/camel-k/pkg/util/log	[no test files]
ok  	github.com/apache/camel-k/pkg/util/maven	(cached)
?   	github.com/apache/camel-k/pkg/util/minishift	[no test files]
?   	github.com/apache/camel-k/pkg/util/monitoring	[no test files]
?   	github.com/apache/camel-k/pkg/util/openshift	[no test files]
ok  	github.com/apache/camel-k/pkg/util/registry	(cached)
?   	github.com/apache/camel-k/pkg/util/source	[no test files]
ok  	github.com/apache/camel-k/pkg/util/sync	(cached)
?   	github.com/apache/camel-k/pkg/util/tar	[no test files]
ok  	github.com/apache/camel-k/pkg/util/test	(cached)
?   	github.com/apache/camel-k/pkg/util/watch	[no test files]`

**And secondly** how can push the snapshot images to docker.io - I am able to build images locally but not able to push images to docker.io and because of that Kamel Operator installation fails in cluster failing to find the snapshot image.

`
events:
  Normal   Scheduled  28m                   default-scheduler                 Successfully assigned default/camel-k-operator-655477cbf4-58swh to aks-nodepool-23065501-4
  Normal   Pulling    26m (x4 over 28m)     kubelet, aks-nodepool-23065501-4  Pulling image "docker.io/apache/camel-k:1.0.0-M5-SNAPSHOT"
  Warning  Failed     26m (x4 over 28m)     kubelet, aks-nodepool-23065501-4  Failed to pull image "docker.io/apache/camel-k:1.0.0-M5-SNAPSHOT": rpc error: code = Unknown desc = Error response from daemon: manifest for apache/camel-k:1.0.0-M5-SNAPSHOT not found: manifest unknown: manifest unknown
  Warning  Failed     26m (x4 over 28m)     kubelet, aks-nodepool-23065501-4  Error: ErrImagePull
  Warning  Failed     8m3s (x85 over 28m)   kubelet, aks-nodepool-23065501-4  Error: ImagePullBackOff
  Normal   BackOff    3m3s (x107 over 28m)  kubelet, aks-nodepool-23065501-4  Back-off pulling image "docker.io/apache/camel-k:1.0.0-M5-SNAPSHOT"
`

**Comment by nicolaferraro** [comment]
Build errors are strange. Are you using the right version of go?
Anyway, you're welcome to submit a PR with your change and have our CI test it for you.
We're close to cutting a RC1 release that will be available start of next week.

To test a snapshot version, the quickest way is to login to:
- login to your docker hub with `docker login`
- `make images`
- `export VERSION=1.0.0-RC1-SNAPSHOT` (or whatever version you've in Makefile)
- `export DOCKER_HUB_ID=myuser` (replace `myuser` with your docker hub id)
- `docker tag apache/camel-k:$VERSION $DOCKER_HUB_ID/camel-k:$VERSION` 
- `docker push $DOCKER_HUB_ID/camel-k:$VERSION`
- `kubectl delete deployment camel-k-operator` (to cleanup previous installation, if present)
- `kamel install --operator-image $DOCKER_HUB_ID/camel-k:$VERSION`

That should be sufficient to run the operator. Some additional args to pass to `kamel install` are required to configure Camel K to build images on Docker Hub, so you can run integrations: https://camel.apache.org/camel-k/latest/installation/registry/dockerhub.html.

**Comment by mrganeshraja** [comment]
thanks @nicolaferraro will you be able to add me as contributor so that I can push my branch and create a PR.

**Comment by nicolaferraro** [comment]
> thanks @nicolaferraro will you be able to add me as contributor so that I can push my branch and create a PR.

No need to add special permissions, you're allowed to fork the repo and create a PR from there ;)

**Comment by mrganeshraja** [comment]
@nicolaferraro I have created a PR. I will carry on testing locally now with my setup. I will let you know if I find any more issues. Also shouldn't we amend the documentation to add section on using Camel-k on Azure (aks) - that could be useful and comforting to users coming from Azure.

**Comment by nicolaferraro** [comment]
Thanks, it would be nice if you could continue testing on Azure and write something down for the website, like we have for [gke](https://github.com/apache/camel-k/blob/master/docs/modules/ROOT/pages/installation/gke.adoc)
