### ISSUE TITLE
Set the IntegrationConditionServiceNotAvailableReason only when the service trait is disabled

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-k#1149]
In the context of https://github.com/apache/camel-k/pull/1142, the TestApplyPrometheusTraitWithServiceDoesNotSucceed test shows that the IntegrationConditionServiceNotAvailableReason could be set while the service trait is enabled.

**Comment by lburgazzoli** [comment]
Not sure about that as the reason is also used to signal errors or other conditions for which the service cannot be enabled, see https://github.com/apache/camel-k/blob/8a719066009fae5cade8001958ab3ec6708bc1e6/pkg/trait/service.go#L71-L95

**Comment by aldettinger** [comment]
Indeed, we could imagine that the aborted service trait configuration cases mentioned above would not be covered then. Stepping back a bit, it looks that the implicit assumption that only the service trait is creating the service is respected at this stage. So I'm gonna close this issue, feel free to re-open if I missed something.
