### ISSUE TITLE
Introducing Traits

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#115]
What is a trait?
It's a high level "feature" of Camel K, but if I say "feature" you think to a completely different thing in the Camel/Karaf world, so let's call it "trait" for now.

Some examples of traits I've in mind:
- "dependencies": when activated, if you run a integration that uses a known component URI, the component is added to the classpath (already implemented, but it wasn't called a trait)
- "expose": when activated, Camel K adds a service and a ingress to the deployment
- "rest": when activated, Camel K adds and configure a rest environment (e.g. with netty-http or undertow) to expose rest endpoint
- "openapi": adds openapi 2.0 libraries (Swagger) and configure them (this seems a Karaf feature). It also adds information on the apis on the deployment so that the apis can be discovered
- "cron": converts a long-running timer into a Kubernetes cronJob, enabling the necessary configuration on the runtime
- "knative-idler": binds the deployed integrations to knative, so that they can be scaled to 0 to save resources
- "graal": compiles the integration with graal

So traits are **complex features** that a user can **enable/disable**, or in some cases also **configure**. They're like "enrichers"/"generators" in the fabric8 maven plugin (for those who know it). But differently from f-m-p, we should document them.

When a trait is not enabled/disabled by the user, Camel K tries to **determine the best configuration** of each trait for the application. E.g. the "rest" trait can be enabled automatically when I'm using rest in my integration, the "cron" trait can be enabled if I have a single route that starts with timer (and a configured long delay) and it needs to have a specific configuration so that the engine can trigger the integration correctly.

Let's discuss about this.

What do you think @lburgazzoli, @dmvolod, @oscerd, @valdar, @onderson?
Is it a good abstraction over the features we've talked about in the dev mailing list?

**Comment by nicolaferraro** [comment]
I've create a "Traits" project to handle subtasks: https://github.com/apache/camel-k/projects

**Comment by lburgazzoli** [comment]
+1

**Comment by lburgazzoli** [comment]
I think that we should "split" our current operator into smaller services that implement one or more traits to be installed according to the environment and/or the operator's configuration.

Make sense ?

**Comment by nicolaferraro** [comment]
Well, if we talk about the specific lifecycles associated to traits in custom resources, I think we don't need to add new services, as it's the role of the operator to update CRs and related kubernetes objects to reflect the configuration set by the user. We need to abstract the code associated to the traits from the main state machine, but we can define internal modules for that, we don't need to split the operator into physical distinct services. It adds complexity.

E.g. if instead of creating a Deployment, the operator needs to create a CronJob, that is just internal logic that we just need to modularize (interceptors?) to make it more maintainable. Same if we need to expose a service.

A different thing is when a trait requires something at infrastructure level.

E.g. if I have a integration `from("kafka:topic").to("log:msg")` and I want to shutdown the integration when there are no new messages in the `topic`, maybe I'd activate a distinct "watchdog" service to handle it.

The "maven-builder", that is now embedded in the operator is another service that will be externalized, although I don't know if there'll be a `s2i-build` trait or it will be a general cluster configuration.
The "graal-builder" is something we should think to create outside the operator, enabled by a trait.

In my view, the operator should continue to handle the state machine, creating, destroying and interacting with external services to perform some actions in order to move the state forward. Traits are one of the sources the operator will use to decide if a external service should be started or not.

**Comment by oscerd** [comment]
The idea of trait fit perfectly what we would like to see with Camel-K

**Comment by dmvolod** [comment]
+1 Excellent idea!
For example, we can add traits with [gRPC to JSON proxy generator following the gRPC HTTP spec](https://github.com/grpc-ecosystem/grpc-gateway) which is not so easy in Java.

**Comment by lburgazzoli** [comment]
@nicolaferraro should we close this ?

**Comment by nicolaferraro** [comment]
Yes, I think traits are now "embedded" in the way we work.
