### ISSUE TITLE
Add condition/status to monitor running state of the integration

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1171]
A condition should signal if the integration is actually running and not in error (or any other state), no matter the number of replicas (should work also with 0).

We set the desired number of replicas in the status, but it should be empty if unspecified. Another field should map the current number of replicas. Another field should contain the number of ready replicas.

These fields are useful in order to do assertions on the integration state in scripts or testing tools.

**Comment by astefanutti** [comment]
The number of replicas in the status is the actual number of replicas. It should be straightforward to reconcile the number of ready replicas as well. The number of desired replicas is set in the spec.

**Comment by nicolaferraro** [comment]
Right! :+1:

**Comment by astefanutti** [comment]
Having the number of ready replicas would be useful to trigger the GC as well.
