### ISSUE TITLE
Abilty to disable sidecar injection in knative services

### ISSUE THREAD

**Issue by kameshsampath** [apache/camel-k#1173]
Related to #1172 ,  the `kamel` tool should make it possible to add the `annoations` or atleast an option to disable sidecar injections on the Knative services created by Camel K. I usually add the `istio-injection.istio.io/enabled: false` to all my Knative services which does not need mesh.

**Comment by kameshsampath** [comment]
wondering if we could add that to the knative service trait like `isito-injection.enabled=false`

**Comment by lburgazzoli** [comment]
We have an `istio` trait, see https://camel.apache.org/camel-k/latest/traits/istio.html

**Comment by kameshsampath** [comment]
Thanks Luca missed that ;)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
