### ISSUE TITLE
Camel-k with Spring boot 

### ISSUE THREAD

**Issue by pchakina** [apache/camel-k#1176]
Hi,
Based on previous posts, i found that SB support was removed with Camel-k.
Please confirm on this. 
We have few services which was build using Spring boot with Camel with SB fat jar.
We are planning to migrate those services using SB with camel-k to make them server-less
Please share your inputs , How can we use Camel-k in this scenario? Appreciate your help

Do u have any plan to support SB (fat Jar) with Camel-k on knative?

Thanks,
pchakina

**Comment by lburgazzoli** [comment]
no we don't
