### ISSUE TITLE
kamel CLI - Allow to specify a namespace to use instead of default

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#1184]
Instead of installing Camel K in the default namespace which can get crowded, its nice to install it in a different namspace.

But then you need to have `-n mykamel` for all the CLI commands to operate on this namespace.

I wonder if we can have the CLI set a namespace to use

**Comment by squakez** [comment]
What about if we mimick `kubectl` CLI? If you want to stick to a namespace you must runt `kubectl config set-context --current --namespace=default` this would change the kube config file. I think we don't have any `kamel` config file, but we could use env vars or if it makes sense creating a config file to serve the scope.

**Comment by essobedo** [comment]
Should be fixed by https://github.com/apache/camel-k/pull/3599
