### ISSUE TITLE
Resource group endpoints is that a left over from old Camel version

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#1187]
Just upgraded from M4 to RC1 and noticed that my resource groups have endpoints, but its not associated with a api group name of camel.apache.org.

Just creating this ticket to not forget

![Screenshot 2020-01-10 at 06 41 04](https://user-images.githubusercontent.com/477100/72128758-31073400-3374-11ea-9ad1-7ae061771737.png)

**Comment by nicolaferraro** [comment]
Is that `endpoint` CR related to Camel K? Don't think so..

**Comment by davsclaus** [comment]
Okay yeah it doesnt have any api group that says camel
