### ISSUE TITLE
Add an init/scaffold subcommand

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1188]
We can make it easier to start working on a new integration by providing a `kamel init` or `kamel scaffold` command.

`$ kamel init myroute.groovy`
Generates a the file:

myroute.groovy
```
// camel-k: language=groovy

// you can write your routes here

```

But it's more interesting with Java:
`$ kamel init Integration.java`

Integration.java
```
// camel-k: language=java

import org.apache.camel.builder.RouteBuilder;

public class Integration extends RouteBuilder {
  @Override
  public void configure() throws Exception {
    // you can write your routes here
    
  }
}
```

**Comment by zregvart** [comment]
Would be nice if a test template was added also.
