### ISSUE TITLE
Kafka Producer

### ISSUE THREAD

**Issue by waytoharish** [apache/camel-k#1189]
Hi,
I am trying to write a Kafka Producer.I am able to send the even to Kafka Topic  but consumer side my message is NULL.

public class SampleKafkaProvider extends RouteBuilder {
  @Override
  public void configure() throws Exception {
	log.info("About to start route: Kafka Server -> Log ");

 
           
 
    restConfiguration()
            .component("undertow")
            .host("0.0.0.0")
            .port("8080");

        rest()
            .get("/hello")
            .to("direct:kafkaproduce");

        from("direct:kafkaproduce")
        .routeId("DirectToKafka")
        .to("kafka:{{consumer.topic}}?brokers={{kafka.host}}:{{kafka.port}}")
        .setHeader(Exchange.CONTENT_TYPE, constant("text/plain"))
        .log("Hello World")
        .transform()
        .simple("Hello World"); 
        
}

**Comment by lburgazzoli** [comment]
@waytoharish is this still an issue ?
