### ISSUE TITLE
Verify registry connection on install

### ISSUE THREAD

**Issue by haris-zynka** [apache/camel-k#1192]
I was trying to deploy local JFrog registry and connect it to Camel K. As I have no idea how to do this it still fails but the actual problem is that I cannot know until I try to push new camel K script. Then I get `Error from server (BadRequest): container "kaniko" in pod "camel-k-kit-boe43ei8411sjk3086d0-builder" is waiting to start: PodInitializing` which I guess indicates that I've put in some wrong details for registry.

Is it possible to add extra option like --fail-no-registry, if not by default activated, to verify registry connection and fail if not successful with error printed out, instead of me doing a lot of kubectl and kamel commands just to verify that I have once again failed to connect them.

Just to be sure to mention script works 100% as it runs on Azure Kubernetes Cluster connected to Azure Container Registry. I just want to connect local registries to save some money while testing.

BTW if anyone has advice on how to link properly local JFrog Container Registry with Apache Camel please post comment. I tried by providing registry as hostname of my PC, localhost, ip address on local network, ip address in docker network, using `registry-auth-server` by adding additional /artifactory/api/docker and without it. Nothing works for now.

**Comment by clojj** [comment]
@haris-zynka 
Hi, I also tried Camel-K 1.0.0 Release on azure.. with no success.
Could you provide details, as to how you managed to install 'kamel' with ACR registry ?
Thanks

**Comment by haris-zynka** [comment]
> @haris-zynka
> Hi, I also tried Camel-K 1.0.0 Release on azure.. with no success.
> Could you provide details, as to how you managed to install 'kamel' with ACR registry ?
> Thanks

I've used RC1. After that it stopped working. And I tried to revert it back to RC1 it still failed. However you need to put "./kamel install --registry YOUR_AZURE_REGISTRY_DOMAIN.com --registry-auth-username YOUR_USERNAME --registry-auth-password SECRET_PASSWORD". I don't think it works anymore but try [this post](https://dev.to/greenroommate/apache-camel-k-on-aks-quick-setup-1lm0). However I don't use Camel anymore so I don't know what's happening and how to link new ones.
