### ISSUE TITLE
Disabling traits does not reflect in camel-k  integration

### ISSUE THREAD

**Issue by kameshsampath** [apache/camel-k#1208]
**Platform**: minikube 1.6.2
**camel-k**: 1.0.0.RC1

When we  do `kamel run` with `--trait <trait-name>.enabled=false`  I see the camel logs showing Applying trait 

e.g. 

```shell
kamel run --dependency camel:log --dependency camel:bean get-started/echoer.yaml --trait istio.enabled=false --trait jolokia.enabled=false --trait prometheus.enabled=false
```

```json
camel-k-operator-5d74595cdf-77gwr camel-k-operator {"level":"info","ts":1579105299.3057547,"logger":"camel-k.trait","msg":"Apply trait: jolokia"}
camel-k-operator-5d74595cdf-77gwr camel-k-operator {"level":"info","ts":1579105299.3057587,"logger":"camel-k.trait","msg":"Apply trait: prometheus"}
```

**Comment by astefanutti** [comment]
The Jolokia and Prometheus traits are a bit special as they currently rely on the Fabric8 base image behaviour, that activates Jolokia and Prometheus by default. So to de-activate them, the traits have to be applied.

I agree it's counter-intuitive. It will incidentally solved with #394.
