### ISSUE TITLE
helm.sh entries in go.sum

### ISSUE THREAD

**Issue by cunningt** [apache/camel-k#1231]
I'm getting the following errors trying to build

go: finding helm.sh/helm/v3 v3.0.0
go: helm.sh/helm/v3@v3.0.0: unknown revision helm.sh/helm/v3.0.0

and

go: finding helm.sh/helm/v3 v3.0.1
go: finding github.com/improbable-eng/thanos v0.3.2
go: finding github.com/imdario/mergo v0.3.6
go: helm.sh/helm/v3@v3.0.1: unknown revision helm.sh/helm/v3.0.1

It looks like these lines are the issue?   https://github.com/apache/camel-k/blob/master/go.sum#L979-L980

**Comment by astefanutti** [comment]
The go.sum file has changed and the `helm.sh/helm/v3` module versions have changed as a result. Let me close this. Feel free to re-open if that's still an issue.
