### ISSUE TITLE
Add a "master" trait

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1234]
We can provide a trait for automatically configure the master component (or route policy?).

The trait should give the pod service account enough privileges to read/watch pods and read/write/watch configmaps, then configure some defaults.

It's likely that we don't need anything from runtime as the component can be automatically configured like [here](https://github.com/nicolaferraro/camel-leader-election/blob/074181c05996a24e54097eadd07add19322c4770/src/main/resources/application.properties#L5-L7).

It's important that we always generate a new service account for the integration (no matter if we use master), unless the user specifies his own service account in spec.
Roles should be bound to the pod service account.

**Comment by lburgazzoli** [comment]
relates to https://github.com/apache/camel-k/issues/259
