### ISSUE TITLE
Dead link from readme to trait documentation

### ISSUE THREAD

**Issue by apupier** [apache/camel-k#1249]
https://github.com/apache/camel-k/blame/master/README.adoc#L361 pointing to https://camel.apache.org/camel-k/latest/traits.html leadign to a 404

**Comment by apupier** [comment]
correct link is https://camel.apache.org/camel-k/latest/traits/traits.html

**Comment by apupier** [comment]
will provide a PR

**Comment by apupier** [comment]
(but I don' thave rights to assign the issue to me)

**Comment by jamesnetherton** [comment]
Fixed by #1250.
