### ISSUE TITLE
Allow to inject data from externally crafted secrets

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1261]
Let's say a broker is installed inside the same namespace as my integration. The broker is secured and provides a secret with authentication data: username and password.

Can I inject those two fields in my integration?
Afaik, currently we can inject only secrets containing a "xxx.properties" file.

Is this the case?
@jamesnetherton , @lburgazzoli , @astefanutti

**Comment by lburgazzoli** [comment]
We now support only properties but it won't be to complex to load any kind of property however some additional properties may still be required, like to set those properties to a component:

    camel.component.jms.connection-factory.host = {{my-other-property}}

Mind opening an issue on camel-k-runtime ?

**Comment by nicolaferraro** [comment]
Yeah, we can still load automatically `.properties` files in the secrets, plus make the content of each entry of a secret available in a `secrets` namespace, so users can reference them by name, e.g.

```
camel.component.xxx.password = {{secrets.broker.authToken}}
```

Thinking big (for the far future), we can also provide an addon module where we add auto-configuration for connecting to known systems.. this require some effort to be maintained, but a user would be able to do:
```
kamel run integration.groovy --connect activemq:mybroker
```
... and have all `camel.component.activemq.xxx` properties set.

**Comment by nicolaferraro** [comment]
Ref: https://github.com/apache/camel-k-runtime/issues/239

**Comment by lburgazzoli** [comment]
> Yeah, we can still load automatically `.properties` files in the secrets, plus make the content of each entry of a secret available in a `secrets` namespace, so users can reference them by name, e.g.
> 
> ```
> camel.component.xxx.password = {{secrets.broker.authToken}}
> ```

We can use properties functions like 

    {{secret:$secret-name:property-name}}

so your example will become:

    camel.component.xxx.password = {{secret:broker:authToken}}

I did it in the past for Karaf and blueprints, need to resurrect that code :)
