### ISSUE TITLE
Expose operator related metrics

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#1267]
It may be valuable to expose some functional metrics to Prometheus, like quantiles for build times

**Comment by david-martin** [comment]
CR Metrics can also be useful.
The operator-sdk has some built in metrics that can be used.
https://github.com/operator-framework/operator-sdk/blob/e128b9e5d147ef43fbca46b8ddb5037a9b1e3cbd/proposals/metering-operator-metrics.md#L1
