### ISSUE TITLE
CLI log could use some kind of feedback when waiting for pod to spin up

### ISSUE THREAD

**Issue by bfitzpat** [apache/camel-k#1283]
We're shifting over to using `kamel log [integration]` instead of `kubectl logs-f [podname]` for displaying logs in the VS Code extension and I've noticed that while waiting for the kit to build and the first integration pod to deploy, there is just... nothing. Without any kind of user feedback, some users may wonder if the integration will ever spin up.

It's great once it gets started and does everything we could want, including shifting to a different pod after an update and redeploy to avoid getting stale, which is something that occurred frequently when we were using the kubectl logs approach. 

Would it be possible to display something like `Waiting for [integration] container to start...` or perhaps have some message displayed to the user (anything really) indicating that work is going on behind the scenes? 

Invoking the CLI and then waiting on the log takes a very long time initially and it would be nice to possibly show *something* to the user during that period. Even a simple "..." showing that it's still chugging away waiting for containers to get going would be preferable to dead silence I think.

**Comment by phantomjinx** [comment]
Starting to poke around the binaryb go code so alright if I have a look at this?

**Comment by phantomjinx** [comment]
Create PR https://github.com/apache/camel-k/pull/1793
