### ISSUE TITLE
kamel version should report version number in offline mode

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#1298]
When you have no k8s/os cluster running, then you get an error. 

But would still be good to know the kamel binary version.

❯ kamel version
Error: cannot get command client: could not locate a kubeconfig
Usage:
  kamel version [flags]

Flags:
  -h, --help   help for version

Global Flags:
      --config string      Path to the config file to use for CLI requests
  -n, --namespace string   Namespace to use for all operations

Error: cannot get command client: could not locate a kubeconfig
  ~/workspace/camel-k   master ❯

**Comment by nicolaferraro** [comment]
Does it happen also on RC2? I though this was fixed.. there's also a test

**Comment by davsclaus** [comment]
RC1

**Comment by nicolaferraro** [comment]
Should be fixed by d07c6ed2a6f555553ca8a936a9e8ae7640641d72

Please reopen if it's not the case ;)
