### ISSUE TITLE
Add superfast builds for dev clusters

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1305]
I've been hacking with image builds and created https://github.com/container-tools/spectrum which can be used to cut down build times on Minikube/dev clusters to few seconds:
- ~20 seconds for the first build
- ~5 seconds for subsequent ones

Time to download maven artifacts excluded, but it can run in "routine" mode, so the m2 is cached in the operator.

I'm adding it to Camel K.

**Comment by oscerd** [comment]
Impressive!
