### ISSUE TITLE
Cannot append/override stored properties

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1323]
After running an integration with e.g.
```
kamel run app.groovy -p a=1 --save
```

Then it's no longer possible to use properties:
```
kamel run app.groovy -p xxx=2
```

The same happens with dependencies.
In both cases, we should append properties/dependencies together.

We should also add some tests about this.

**Comment by lburgazzoli** [comment]
I don't think this is possible with the libraries we use for the CLI as cobra + viper define a hierarchy where to find values for the flags which as today is:

- CLI flag
- environment
- file

So if you set something from the CLI with a flag, that flag overrides every value you may have eventually set through file or env var.

**Comment by lburgazzoli** [comment]
btw, I was thinking to replace _cobra + viper_ with https://github.com/urfave/cli as it has a lot less dependencies and looks simpler, at that point we can try to implement the _append_ behaviour but I would do it post 1.0 and document that the current set-up is about to set default values

**Comment by nicolaferraro** [comment]
Agree, our current setting is a bit over-complicated.. and that CLI seems exactly what we need
