### ISSUE TITLE
Hide platform traits

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#1328]
Some traits are platform traits and disabling them would make the platform unstable or not behaving as expected so, should we hide them and make them not configurable from the user ?

**Comment by nicolaferraro** [comment]
Yeah, but some of them have options. Maybe we can react by throwing an error when the user tries to disable them. The doc already states this in a warning.

**Comment by lburgazzoli** [comment]
we can remove the "enabled" flag or add a struct tag to instruct how to handle them

**Comment by tadayosi** [comment]
I'll take a look at this after finishing other tasks.
