### ISSUE TITLE
Support for local development using containers

### ISSUE THREAD

**Issue by hguerrero** [apache/camel-k#1339]
Add capabilities to run a _limited_ version of the integration locally using the local container runtime (docker, podman) for local development.

**Comment by lburgazzoli** [comment]
Not sure if it is what you are looking for but you can actually run the runtime from maven, like: https://github.com/apache/camel-k-runtime/tree/master/examples

**Comment by hguerrero** [comment]
Looks like in the correct direction, is there any docs I can take a look?

**Comment by luszczynski** [comment]
It would be very nice to run camel-k locally just using an OCI runtime.

**Comment by toonalbers** [comment]
Using the camel-k-runtime packages is a good option! A downside for me is that it lacks the automatic dependency resolution that the kamel binary provides through the builder: you now have to explicitly set the dependencies in the pom.xml. Extracting that functionality from the builder / kubernetes would be difficult I think.

**Comment by lburgazzoli** [comment]
We do plan to provide a kamel subcommand to inspect sources and provide some info about what they requires but having a full camel-k experience is out of scope.
