### ISSUE TITLE
Provide description in JSON output for traits

### ISSUE THREAD

**Issue by apupier** [apache/camel-k#1358]
VS Code tooling is providing completion based on `kamel help trait --all -o json`.
It would be nice to provide description in the json output for trait and their properties to improve help to users.

**Comment by nicolaferraro** [comment]
It requires a bit of work but this can be done. We can use a variant of the `cmd/util/doc-gen` to generate offline a yaml containing the trait descriptions in `/deploy` and then use it in the `kamel help trait` command to provide the missing descriptions.

**Comment by nicolaferraro** [comment]
Fixed by https://github.com/apache/camel-k/pull/1430
