### ISSUE TITLE
Detect components from xxx.properties

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1363]
If I set:
```
camel.component.twitter-search.xxx
```

The `camel-twitter` component should be added to the set of dependencies automatically.

Also because the new property-binding mechanism goes in error otherwise.

We should inspect direct properties and property-files.
We may extend the search also to linked secrets and configmaps.

**Comment by michaelwjoyner** [comment]
@nicolaferraro See me when you can, I think I might be able to do this one. I have some questions

**Comment by nicolaferraro** [comment]
Maybe we can close this in favor of https://github.com/apache/camel-k/issues/1449
