### ISSUE TITLE
Adding the http4  dependency causes the deployment of an integration to fail

### ISSUE THREAD

**Issue by lmorandini** [apache/camel-k#1386]
I have an OpenStack/Kubernetes/Istio/Knative cluster with Camel-K 1.0.0.-RC2 on it.

When the http4 module is loaded, as in: `../camel-k/kamel run  ../camel-k/examples/Sample.java  --name=sample --dependency camel-http4 --dev` the build fails with 
```
...
Integration sample in phase Error
Integration sample in phase Error
Progress: integration "sample" in phase Error
Error: integration "sample" deployment failed
```
...but when that module is not loaded, the `Sample.java` example works as expected (loading the `http` module is fine too).

**Comment by lburgazzoli** [comment]
The cmel-http4 component has been renamed to camel-http in camel 3.x, see https://camel.apache.org/manual/latest/camel-3-migration-guide.html#_renamed_components

**Comment by lburgazzoli** [comment]
@lmorandini can we close this one ?

**Comment by lmorandini** [comment]
Sure.
