### ISSUE TITLE
Camel Cron trait page is rendered incorrectly

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1401]
It says a valid cron is: `cron:tab?schedule=0/2++++?`, but it should be `cron:tab?schedule=0/2+*+*+*+?`.

Page here: https://camel.apache.org/camel-k/latest/traits/cron.html

**Comment by nicolaferraro** [comment]
Replacement of + with {plus} needs to be done in the code generator, otherwise it's replaced when we regenerate the doc.

**Comment by oscerd** [comment]
ok. Need to check code-generator then.

**Comment by oscerd** [comment]
Btw I see the page rendered correctly
