### ISSUE TITLE
re-organize e2e tests

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#1404]
We do execute e2e tests against a number of platform with different container image publishers but for most of the tests, the way the image is published does not matter at all so I think we should re-organize the e2e to:

- define the tests beseline as vanilla k8s + knative with spectrum
- specific test for OpenShift
- specific test for OpenShift + knative (if possible)
- specific test for buildah
- specific test for buildah + knative

@nicolaferraro @astefanutti WDYT ?

**Comment by astefanutti** [comment]
I think that makes sense to improve tests execution time and resources optimisation. For the baseline tests, we may want to choose the builder that's the most supported, to cover most of its surface.

**Comment by nicolaferraro** [comment]
This is done, except that for common test we had to choose the builder that doesn't fail randomly in the CI environment.
