### ISSUE TITLE
support for jitpack dependencies

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#1407]
we should add a special support for [jitpack](https://jitpack.io/) dependencies like:

    kamel run --dependency jitpack:$owner/$repo/$version

where:

1. the `$owner` is prefixed with `com.github` if not provided
2. the `$version` is replaced with `master-SNAPSHOT` if not provided

The repository will automatically be added to the maven project by the build step if at least one dependency is of type `jitpack`

**Comment by oscerd** [comment]
I'll try to work on it if it's ok for all

**Comment by lburgazzoli** [comment]
As jitpack by default [supports also other git hosts]( https://jitpack.io/docs/#other-git-hosts), we should probably take them into account when checking for the prefix

**Comment by lburgazzoli** [comment]
Thinking a little bit about it, we could differentiate the git provider via a dedicated scheme so if using `jitpack` as scheme, then the artifact id should be fully qualified, i.e. 

    jitpack:com.github.user/repo/version

but we can provide some alternative syntax like

    github:user/repo/version

which get translated to
    
    jitpack:com.github.user/repo/version
