### ISSUE TITLE
kamel run that can auto discover/guess what to include and run

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#1409]
I wonder if we could make the kamel CLI somewhat smart for development purposes and allow to to try to auto discover/guess what you have to make it run.

Then it can output on the CLI what it have discovered and what the arguments on the CLI would be if typed manually.

Inspired by nicolas little demo, see screenshot

So it will look in the current folder the files and look inside to see what they are
*.java are java source code and included
*.jar are JAR as dependencies and included
*.properties are properties files and included
openapi*.yaml are openapi contracts and enables this trait
*.xml are looked inside to see if they are camel routes / rests

This can really help new users to get going. Just add a source java, and drop your extra JARs to include, and set some configuration in the properties file.

**Comment by davsclaus** [comment]
![Screenshot 2020-04-17 at 14 44 58](https://user-images.githubusercontent.com/477100/79570960-a5abe600-80ba-11ea-92b8-67715b08932c.png)

**Comment by nicolaferraro** [comment]
That would work for the API scenario, but there are cases where it will make bad assumptions. E.g. in https://github.com/openshift-integration/camel-k-example-event-streaming you have multiple Java files, but most of them are to be run independently.

I think that after Luca fixes https://github.com/apache/camel-k/pull/1400, we have a good format for the `kamel-config.yaml` file and we can sponsor its usage more than we do today.

That way the workflow would be:
```
kamel init API.java
kamel run API.java --open-api openapi.yaml --property-file application.properties --save
# Then from now on
kamel run API.java
```

But I'm also ok with e.g. a `--auto` flag, like:
```
kamel init API.java
kamel run API.java --auto --save
# And it recognizes what you've indicated, prints it to the console, and the --save flag will also save the options to the config
```

**Comment by lburgazzoli** [comment]
#1400 should be working now, please retest :)

**Comment by nicolaferraro** [comment]
> #1400 should be working now, please retest :)

You said that also yesterday ;)
