### ISSUE TITLE
Allow to use dash syntax in configuring component properties

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#142]
The new support for configuring components properties is nice.
https://github.com/apache/camel-k#configure-integration-components

It would be good if we can use the dash syntax as well, as it looks nicer when in lower-case and also what Spring Boot uses

So we support both styles with

    camel.component.seda.queueSize = 10
    camel.component.seda.queue-size = 10

**Comment by davsclaus** [comment]
I logged a ticket at Camel
https://issues.apache.org/jira/browse/CAMEL-12847

**Comment by davsclaus** [comment]
Okay so this is coming in Camel 2.23 onwards.

**Comment by lburgazzoli** [comment]
We are now on camel 2.23
