### ISSUE TITLE
Switchting to quarkus fails to build because of missing versions

### ISSUE THREAD

**Issue by ctron** [apache/camel-k#1423]
Having a working example, which I can run with:

    kamel run --name "influxdb-bridge"  --secret influx-bridge -d camel-influxdb -d camel-base64 -d mvn:de.dentrassi.iot:cayenne-lpp:0.1.1 InfluxBridge.java

fails, when I switch to quarkus:

    kamel run --trait quarkus.enabled=true --trait quarkus.native=true --name "influxdb-bridge"  --secret influx-bridge -d camel-influxdb -d camel-base64 -d mvn:de.dentrassi.iot:cayenne-lpp:0.1.1 InfluxBridge.java

The error in the log is:

~~~
{"level":"info","ts":1587636368.869163,"logger":"camel-k.maven","msg":"executing: mvn --batch-mode -Dmaven.repo.local=/tmp/artifacts/m2 --settings /tmp/builder-582033646/maven/settings.xml package","timeout":"3m45s"}
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.apache.camel:camel-influxdb:jar is missing. @ line 51, column 17
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.apache.camel.k.integration:camel-k-integration:1.0.0-RC2 (/tmp/builder-582033646/maven/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.apache.camel:camel-influxdb:jar is missing. @ line 51, column 17
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
{"level":"info","ts":1587636369.6771228,"logger":"camel-k.builder","msg":"step failed with error: failure while building project: exit status 1","step":"github.com/apache/camel-k/pkg/builder/runtime/BuildQuarkusRunner","phase":20,"name":"kit-bqgmg15iaumb7akhncdg","task":"builder"}
~~~

**Comment by lburgazzoli** [comment]
not all the component are available from
camel-quarkus, the list of the supported components along with the camel-quarkus version from which they are supported is here: https://camel.apache.org/camel-quarkus/latest/list-of-camel-quarkus-extensions.html

**Comment by ctron** [comment]
> not all the component are available from
> camel-quarkus, the list of the supported components along with the camel-quarkus version from which they are supported is here: https://camel.apache.org/camel-quarkus/latest/list-of-camel-quarkus-extensions.html

I think there should be some explanation of this in the documentation, and definitely some kind of improvement when using `kamel`, because you don'get any proper feedback.

**Comment by oscerd** [comment]
We love contributions.
