### ISSUE TITLE
Allow overriding of buildah image with "kamel install" switches

### ISSUE THREAD

**Issue by dtremblay** [apache/camel-k#1424]
Add a new kamel install switch to allow overriding the buildah image, e.g. "--buildah-image"

This switch would work in a similar fashion to "-base-image" and "-operator-image".

Whenever a new "kamel run" command gets used, the overriden buildah image would get used.

**Comment by orthoxerox** [comment]
any comment

**Comment by essobedo** [comment]
Unless I misunderstood the need, this should be fixed by https://github.com/apache/camel-k/pull/3558

**Comment by dtremblay** [comment]
I agree with you. I'll have to try this again to confirm. I'm closing the issue now.
