### ISSUE TITLE
Kotlin Autocomplete in Intellij?

### ISSUE THREAD

**Issue by dylanenabled** [apache/camel-k#1425]
Sorry if this is not the appropriate place to ask this, please direct me to somewhere better if not.

I'm looking to get autocomplete, go to source, etc working in intellij for Kotlin script camelk integrations.

I've manually set up intellij to find the camel libraries etc for now by adding them to the module as Provided libraries using the maven repo, and it works, but only if I create a RouteBuilder class. It doesn't understand the global `from` function and other DSL things and I have to do `context.addRoutes` for the routes to be found in the integration.

``` kotlin
import org.apache.camel.builder.RouteBuilder

@Suppress("unused") // Used by camelk
class MyRoutes: RouteBuilder() {
    override fun configure() {
        //Autocomplete works here!
        from("timer:start?repeatCount=1")
            .log("started!!!!")
            .end()
    }
}

//This is an error :(
context.addRoutes(MyRoutes())
```

However `intellij` thinks this is an error because `context` is not defined globally.

Is there a way to get Intellij to understand the global context and from (and so on) functions for kotlin script?

I found this https://discuss.kotlinlang.org/t/make-auto-completion-work-in-kotlin-scripts-with-context/10185/11 but couldn't get it to work.

Also,
This is a bit of a feature request, but it'd be nice if `kamel` generated the necessary intellij iml files etc to add the camel-core, etc libraries (including detected ones based on the source) to intellij for autocomplete.

**Comment by lburgazzoli** [comment]
If you add `camel-k-loader-kotlin` to the dependencies list, it should work

**Comment by dylanenabled** [comment]
I have added that with version 1.0.9, does it need to be a specific version?

**Comment by dylanenabled** [comment]
It works after updating the dependency to `org.apache.camel.k:camel-k-loader-kotlin:1.2.1`, thanks!

**Comment by dylanenabled** [comment]
For what it is worth (for others who might be looking for this, or maybe you have a better way to set it up @lburgazzoli), my iml file looks like:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<module type="JAVA_MODULE" version="4">
  <component name="FacetManager">
    <facet type="kotlin-language" name="Kotlin">
      <configuration version="3" platform="JVM 1.8" allPlatforms="JVM [1.8]">
        <compilerSettings />
        <compilerArguments>
          <option name="jvmTarget" value="1.8" />
        </compilerArguments>
      </configuration>
    </facet>
  </component>
  <component name="NewModuleRootManager" inherit-compiler-output="true">
    <exclude-output />
    <content url="file://$MODULE_DIR$">
      <sourceFolder url="file://$MODULE_DIR$/src" isTestSource="false" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
    <orderEntry type="library" scope="PROVIDED" name="org.apache.camel:camel-core:3.0.0" level="project" />
    <orderEntry type="library" scope="PROVIDED" name="org.apache.camel:camel-csv:3.0.0" level="project" />
    <orderEntry type="library" scope="PROVIDED" name="org.apache.camel:camel-jackson:3.0.0" level="project" />
    <orderEntry type="library" scope="PROVIDED" name="KotlinJavaRuntime" level="project" />
    <orderEntry type="library" scope="PROVIDED" name="org.apache.camel:camel-aws-s3:3.0.0" level="project" />
    <orderEntry type="library" scope="PROVIDED" name="org.apache.camel:camel-aws-sqs:3.0.0" level="project" />
    <orderEntry type="library" scope="PROVIDED" name="org.apache.camel.k:camel-k-loader-kotlin:1.2.1" level="project" />
  </component>
</module>
```

Note I'm on a slightly older version for camel-k that uses camel 3.0.0 currently, probably those need to be updated.

It might be worth adding something on how to set this up to the kotlin documentation.
