### ISSUE TITLE
Move languages documentation to camel-k-runtime

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#1427]
The support for languages camel-k users can use to implement integrations is done in the [camel-k-runtime](https://github.com/apache/camel-k-runtime) repository and it would be nice to have the related documentation also hosted on that repo: @zregvart do you think it is possible ?

**Comment by zregvart** [comment]
Not an issue, we build the documentation from several repositories already:

https://github.com/apache/camel-website/blob/a8a56f97db6e76679c3386e830d0fca842e4896c/antora-playbook.yml#L6-L56

You need to watch out for any links that are already pointing to this components/modules and make sure that they remain valid. Easiest way is not to change the component or module names.

**Comment by djencks** [comment]
Could one of you point out an example of the source code and a documentation page for what you are referring to?

**Comment by lburgazzoli** [comment]
The languages section is here: https://github.com/apache/camel-k/tree/master/docs/modules/ROOT/pages/languages
Target repo is https://github.com/apache/camel-k-runtime/ (which lacks any document structure)

**Comment by djencks** [comment]
Thanks, makes sense!
If you have any problems getting this to work let me know, I’m happy to help or provide hints or even PRs.

**Comment by lburgazzoli** [comment]
If you have any time and want to take it, go ahead. 
I don't have time this week

**Comment by djencks** [comment]
Done, see https://issues.apache.org/jira/browse/CAMEL-14975 <https://issues.apache.org/jira/browse/CAMEL-14975>

I have some suggestions for simplifying the camel-k docs, that I made in the issue.

Also it looks like the “traits” index page (traits.adoc) could perhaps be generated by my indexer extension rather than go code.  Does this seem interesting?

Thanks
David Jencks

**Comment by oscerd** [comment]
This has been done.
