### ISSUE TITLE
Use /openapi.json as default location for OpenAPI data

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1428]
This applies to the 3scale trait, which currently uses `/api-doc` by default.

**Comment by rajatdiptabiswas** [comment]
Would you kindly let me know what exactly needs to be done so that I can try working on it?

**Comment by nicolaferraro** [comment]
Hi @rajatdiptabiswas, I think it's sufficient to change the default value in the threescale addon trait from "/api-doc" to "/openapi.json". Can you do it?

**Comment by rajatdiptabiswas** [comment]
From what I understood, I believe I should change `ThreeScaleDescriptionPathDefaultValue = "/api-doc"` to `ThreeScaleDescriptionPathDefaultValue = "/openapi.json"` in line 67 of `/addons/threescale/3scale.go`

There are a few more mentions of `/api-doc` in `3scale_test.go`, `traits.yaml`, and `3scale.adoc`.  One more in line 44 of `3scale.go` as well. 
Do I need to make any changes to those?

I am hopeful I shall be able to make the required changes. 
Kindly confirm if I have understood your instructions correctly.

Thanks in advance!

**Comment by nicolaferraro** [comment]
Yes, changing that variable plus the mention is ok.

traits.yaml, and 3scale.adoc can be manually changed or auto-updated running `make generate-doc`.
