### ISSUE TITLE
Does any company use Camel K in production environment?

### ISSUE THREAD

**Issue by TeslaCN** [apache/camel-k#1436]

**Comment by nicolaferraro** [comment]
In terms of community releases, we'll publish version 1.0.0 in the next weeks, so I don't expect someone being in production with the current pre-releases.

For going in production, you also usually want support. As far as I know, Red Hat is going to provide support for Camel K, so you may ask to them. I'm not aware of other companies providing it.

**Comment by mgenereu** [comment]
@TeslaCN , I think this is an interesting question because while Camel K works for development, there doesn't seem to be documentation for production environments using Terraform or other programatic environments.
