### ISSUE TITLE
Take a look at service binding

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1445]
https://application-stacks.github.io/service-binding-specification/

It provides a clean way by which we can connect to services in the same cluster without the users having to provide credentials and all that stuff.

We can e.g.
```
kamel run Api.java --connect mypostgresdb
```

(did I already write a similar issue in the past?)

And have your Camel K operator resolve the connection details for the database and inject them into the integration pod, e.g. making a JDBC connection available in the registry.

The same for other brokers or Kafka.

**Comment by michaelwjoyner** [comment]
Thats hot!

**Comment by lburgazzoli** [comment]
New home: https://github.com/k8s-service-bindings/spec

**Comment by johnpoth** [comment]
I can take a look at this

**Comment by lburgazzoli** [comment]
@johnpoth would be nice to have sort of proposal, like https://github.com/apache/camel-k/blob/master/proposals/monitoring-security.adoc so it can be turned into a documentation soon or later.

**Comment by johnpoth** [comment]
Sounds good! I'll create one once I have more visibility on this. Creating a small MVP at the moment

**Comment by johnpoth** [comment]
Do you have any graph visualization tools you recommend for the camel-k proposals/docs ?

**Comment by astefanutti** [comment]
I've used http://lucidchart.com for the diagrams in the _secured monitoring_ proposal. I recommend it, though you may have to request a corporate license. Other tools can be used, and you can even try tools like https://github.com/ivanceras/svgbob 😄.

**Comment by johnpoth** [comment]
Closed with #1952 , thanks !
