### ISSUE TITLE
Support setting parameters as modeline options

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1449]
This should be the "supported" way of setting options for running files.

On an integration file:

```
// camel-k: dependency=camel-hl7 trait=quarkus.enabled=true

from("...")...
```

This way:
- information about how to run a file are self-contained in the file
- we don't forget about an external config file that overrides our settings
- the semantics is well defined: it's like those options are passed to the command line together with other options that you pass

It should also work:
- with multiple lines (each one starting with comment and "camel-k: "
- in multiple files (e.g. linked with "--source" or via args)

**Comment by lburgazzoli** [comment]
@nicolaferraro once done, I would remove the `kamel/run/integrations/$name` support from the config file
