### ISSUE TITLE
sanitized integration name on Windows contains whole path

### ISSUE THREAD

**Issue by rrayst** [apache/camel-k#1462]
**Version**: 1.0.0-nightly.202005130003

**Problem**: On Windows, the whole file path passed to ``kamel run`` is used as the integration name.
```
C:\ > kamel run git\camel-k\examples\Sample.java
integration "gitcamel-kexamplessample" created
```

On Linux, this is not the case.

**Workaround**: Using a / instead of a \ works around the issue.
```
C:\ > kamel run git\camel-k\examples/Sample.java
integration "sample" created
```

**Possible solution**: Use ``filepath.Base(..)`` instead of ``path.Base(..)`` in https://github.com/apache/camel-k/blob/1.0.0-nightly.202005130003/pkg/util/kubernetes/sanitize.go#L33 .

**Comment by nicolaferraro** [comment]
Yeah, we should try to fix it before next release.
