### ISSUE TITLE
Kamel uninstall leftovers

### ISSUE THREAD

**Issue by ipolyzos** [apache/camel-k#1465]
On a clean namespace i.e

	  $ kubectl get all,pvc,configmap,rolebindings,clusterrolebindings,secrets,sa,roles,clusterroles,crd -l 'app=camel-k'
	  No resources found in default namespace.

When I try to uninstall a new clean installation of Camel-k not all resources removed. The _crd_ and _clusterrole_ remain installed i.e

	  $ kamel install 
	  Camel K installed in namespace default 
	  $ kamel uninstal
	  Camel K Integration Platform removed from namespace default
	  Camel K Config Maps removed from namespace default
	  Camel K Operator removed from namespace default
	  Camel K Role Bindings removed from namespace default
	  Camel K Roles removed from namespace default
	  Camel K Service Accounts removed from namespace default
	  $ kubectl get all,pvc,configmap,rolebindings,clusterrolebindings,secrets,sa,roles,clusterroles,crd -l 'app=camel-k'   
	  NAME                                                 CREATED AT
	  clusterrole.rbac.authorization.k8s.io/camel-k:edit   2020-05-26T15:26:52Z

	  NAME                                                                                  CREATED AT
	  customresourcedefinition.apiextensions.k8s.io/builds.camel.apache.org                 2020-05-26T15:26:52Z
	  customresourcedefinition.apiextensions.k8s.io/camelcatalogs.camel.apache.org          2020-05-26T15:26:52Z
	  customresourcedefinition.apiextensions.k8s.io/integrationkits.camel.apache.org        2020-05-26T15:26:52Z
	  customresourcedefinition.apiextensions.k8s.io/integrationplatforms.camel.apache.org   2020-05-26T15:26:52Z
	  customresourcedefinition.apiextensions.k8s.io/integrations.camel.apache.org           2020-05-26T15:26:52Z

**Comment by ipolyzos** [comment]
Fix submitted. I can confirm now that on a clean namespace i.e

    $ kubectl get all,pvc,configmap,rolebindings,clusterrolebindings,secrets,sa,roles,clusterroles,crd -l 'app=camel-k'                                                                     git:(master|✚2 
	No resources found in default namespace.

When I try to uninstall a clean installation of Camel-k the CRD and ClusterRole are also removed i.e

    $ kamel install 
    Camel K installed in namespace default 
    $ kubectl get all,pvc,configmap,rolebindings,clusterrolebindings,secrets,sa,roles,clusterroles,crd -l 'app=camel-k'     git:(kamel-uninstall-remove-crd-clusterrole|✚2 
    NAME                                   READY   STATUS              RESTARTS   AGE
    pod/camel-k-operator-89fb65586-npmb6   0/1     ContainerCreating   0          6s

    NAME                               READY   UP-TO-DATE   AVAILABLE   AGE
    deployment.apps/camel-k-operator   0/1     1            0           6s

    NAME                                         DESIRED   CURRENT   READY   AGE
    replicaset.apps/camel-k-operator-89fb65586   1         1         0       6s

    NAME                                                                     ROLE                                    AGE
    rolebinding.rbac.authorization.k8s.io/camel-k-operator                   Role/camel-k-operator                   6s
    rolebinding.rbac.authorization.k8s.io/camel-k-operator-events            Role/camel-k-operator-events            6s
    rolebinding.rbac.authorization.k8s.io/camel-k-operator-servicemonitors   Role/camel-k-operator-servicemonitors   6s

    NAME                              SECRETS   AGE
    serviceaccount/camel-k-operator   1         6s

    NAME                                                              CREATED AT
    role.rbac.authorization.k8s.io/camel-k-operator                   2020-05-26T15:59:13Z
    role.rbac.authorization.k8s.io/camel-k-operator-events            2020-05-26T15:59:13Z
    role.rbac.authorization.k8s.io/camel-k-operator-servicemonitors   2020-05-26T15:59:13Z
  
    NAME                                                 CREATED AT
    clusterrole.rbac.authorization.k8s.io/camel-k:edit   2020-05-26T15:26:52Z

    NAME                                                                                  CREATED AT
    customresourcedefinition.apiextensions.k8s.io/builds.camel.apache.org                 2020-05-26T15:26:52Z
    customresourcedefinition.apiextensions.k8s.io/camelcatalogs.camel.apache.org          2020-05-26T15:26:52Z
    customresourcedefinition.apiextensions.k8s.io/integrationkits.camel.apache.org        2020-05-26T15:26:52Z
    customresourcedefinition.apiextensions.k8s.io/integrationplatforms.camel.apache.org   2020-05-26T15:26:52Z
    customresourcedefinition.apiextensions.k8s.io/integrations.camel.apache.org           2020-05-26T15:26:52Z
    $ kamel uninstall   
    Camel K Integration Platform removed from namespace default
    Camel K Config Maps removed from namespace default
    Camel K Operator removed from namespace default
    Camel K Role Bindings removed from namespace default
    Camel K Roles removed from namespace default
    Camel K Service Accounts removed from namespace default
    $ kubectl get all,pvc,configmap,rolebindings,clusterrolebindings,secrets,sa,roles,clusterroles,crd -l 'app=camel-k'     git:(kamel-uninstall-remove-crd-clusterrole|✚3 
    No resources found in default namespace.

**Comment by nicolaferraro** [comment]
See comment on https://github.com/apache/camel-k/pull/1466#issuecomment-634513928

Maybe we can document that for a complete uninstall you should pass some additional flags, but I wouldn't do it by default.

**Comment by ipolyzos** [comment]
@nicolaferraro  a provisional change in the docs issued with PR #1475, if you could please review it would be great

**Comment by nicolaferraro** [comment]
This has been implemented
