### ISSUE TITLE
Converting ProcessorDefinition to DSL and interfacing with camel k

### ISSUE THREAD

**Issue by contactreji** [apache/camel-k#1469]
I just posted a question on camel forum [here](https://camel.465427.n5.nabble.com/Converting-ProcessorDefinition-to-DSL-and-interfacing-with-camel-k-td5868664.html) 

I felt it might be relevant to ask the same question with camel-k community.

**Comment by davsclaus** [comment]
The issue tracker is not primary for questions - the mainling list you posted on is for all Camel projects.
