### ISSUE TITLE
OLM: enable support for OperatorGroup

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#1471]
/cc @nicolaferraro

**Comment by nicolaferraro** [comment]
Let's defer this a bit.
Apart from enabling support for multiple namespaces, there are multiple places where we use the `NAMESPACE` env variable as if it contains "" or a single namespace, while it should be parsed to check if it contains multiple namespaces.

I think it's not mandatory to have it in 1.0.0.
