### ISSUE TITLE
Delegate installation to external tools

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1503]
Long term, the plan for Camel K installation should be:

- To install Camel K on Openshift: use **Operator Hub**
- To install Camel K on Kubernetes: use **Helm**

Remove everything else, like `kamel install`.

**Comment by astefanutti** [comment]
Installation Camel K without OLM will be provided with #1979, relying on Kustomize.

**Comment by squakez** [comment]
Duplicated in other issues. Closing in favor of them.
