### ISSUE TITLE
Modeline and file-based options on http/github endpoints

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1522]
This https://github.com/apache/camel-k/pull/1515 introduces new ways to run integrations from the cloud directly.

What about modeline options that can be declared in the remote file?

E.g. the file declares something like:

```
// camel-k: property-file=application.properties

from("").to("")
```

Currently file-based options are ignored on remote URLs. But can we do better? ("possibly" avoiding infinite recursion).

**Comment by lburgazzoli** [comment]
should they follow the same path? i.e.

    // camel-k: property-file=github:user/repo/application.properties

**Comment by nicolaferraro** [comment]
I'd better allow relative paths, so they work both when checking out the repo or running integrations remotely.

**Comment by lburgazzoli** [comment]
It is a little complex as you don't know what is the relative path, assuming that you can run an integration with multiple sources

**Comment by lburgazzoli** [comment]
mh, wonder if we should add a `working-dir` option like:

    kamel run --working-dir github:user/repo MyRoute.java --property-file=application.property

would be translated to:
   
    kamel run github:user/repo/MyRoute.java --property-file=github:user/repo/application.property

**Comment by nicolaferraro** [comment]
The current approach, also for local files, is to ignore the current CWD dir in the shell. All file-based modeline options are always relative to the file that contains them, so it will be for remote files.

So the `--working-dir github:user/repo` is implicit if you run `kamel run github:user/repo/MyRoute.java`.

**Comment by lburgazzoli** [comment]
Yep but my point is that there's a different behaviour for the same option used inside a source and outside the source so property-file=application.properties may related to two different locations depending where the option is used, if that's acceptable I can work on it

**Comment by nicolaferraro** [comment]
> Yep but my point is that there's a different behaviour for the same option used inside a source and outside the source so property-file=application.properties may related to two different locations depending where the option is used, if that's acceptable I can work on it

Oh, yes. I think this difference is already there.

Take a file like `./path/It.java` and a property file `./application.properties`.

To run the file and link it to the properties, you should run:

```
kamel run ./path/It.java --property-file application.properties
```

Because CLI options are not related to the file but to the current location.

But if you want to link it using modeline, you should write this line in the file:

```
// camel-k: property-file=../application.properties
```

I don't see it as a big problem, we just need to document it ;)

**Comment by lburgazzoli** [comment]
I guess we can do both so:

1. if the working-dir is set, all the non absolute paths are relative to the working dir
2. if not set, the non absolute paths are relative to the context (to the file for modeline, to the current cwd for the CLI)
