### ISSUE TITLE
kamel run directory (self contained)

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#1523]
It would also in the future be nice to be able to run by just specifying a directory, then the CLI figures out what files are in the directory and what kind they are

```
myrepo/foo
- MyRoute.java
- application.properties
- myawesomelib.jar
```

```
kamel run github:user/myrepo/foo
```

And it gets translated into that example above from Luca in #1522 (incl adding the -d for the JAR).

In fact this is "anti modeline", as you dont use the //came-k: comments but I love when end users can just keep all their stuff in the same folder, and also seperated a bit. properties goes into real properties files. And extra JARs are just downloaded JARs (no funky long maven dependencies).

**Comment by nicolaferraro** [comment]
I think this can be made compatible with modeline.
Thinking to a local directory, the CLI can look for all compatible files with a `// camel-k: language=x` (or another flag that marks it as runnable) and run each runnable file using existing modeline options.

It's common e.g. to write different .properties files that should be picked by some integrations, but not all. Modeline now also contain dependencies that should be read by the CLI.

The only problem that I see in a remote (github.com/user/repo/) is that the CLI would require to list the files or check them out, which is not a lightweight operation.

**Comment by davsclaus** [comment]
Ah yeah the github is not as important (just cool for demos and new users to Camel K). 

Good point about shared properties files etc or allowing to specify which properties file are to be used by which runnable file.

So you could have
```
myrepo/foo
- MyRoute.java
- application.properties
- Funky.groovy
- func.properties
- myawesomelib.jar
```

Then in `MyRoute.java` and `Funky.groovy` you can use the modeline to specify which properties files and JARs to include. 

And then you can run it as 2 integrations by 

```
kamel run foo
```
