### ISSUE TITLE
kamel install uses the wrong channel in OLM

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1524]
It's using `alpha`, meaning it will install 1.0.0-RC2: https://github.com/apache/camel-k/blob/ba2603da84ce40b61cdf7e1d05ca04ad19ec60c2/pkg/util/olm/operator.go#L43

We should fix it in a minor.

**Comment by ipolyzos** [comment]
I have created a PR to set this to stable, pointing to the 1.0.0 (Current).
