### ISSUE TITLE
No way to configure Ingress Trait with annotations

### ISSUE THREAD

**Issue by xytis** [apache/camel-k#1535]
In many kubernetes deployments, machinery is in place that reacts to Ingress object annotations.

What would be the prefered way to implement passing down these annotations to Ingress Trait object?

Extra: Would it be possible to configure TLS on Ingress Trait object?

**Comment by nicolaferraro** [comment]
There's currently an easy way to pass labels as:

```
kamel run ... --label mylabel=avalue -t owner.target-labels=mylabel
```

The `--label` flag labels the integration, while the trait `owner.target-labels` allows to forward them to all sub resources (including the ingress).

Although there's no corresponding `--annotation` flag (we should add it), if you manually annotate the integration with your annotations, there's a trait option `owner.target-annotations` to select the annotations to forward to sub resources.

Btw, @xytis can you provide some more references about the way the ingress can be configured via annotations, so we may find a better way to configure it, including TLS support.

**Comment by xytis** [comment]
In my experience, Ingress objects generally require at least one annotation: `kubernetes.io/ingress.class: <ingress-class-name>`. Depending on ingress provider, there could be more annotations, that configure the provider. (Examples: [Traefik](https://docs.traefik.io/v1.7/configuration/backends/kubernetes/#annotations), [Nginx](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/), [AWS](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/))
Annotations can be complex JSON objects or multiline strings, so passing them through command line is not always viable.

Regarding TLS support, it is a part of current standard [Ingress API](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls), but I usually use it in conjunction with certificate manager, which requires even more [annotation based configuration](https://cert-manager.io/docs/usage/ingress/#supported-annotations).

Overall, for now it seems that the best way to handle these kinds of scenarios would be to create the ingress object externally and use `service` trait to expose the integration.
