### ISSUE TITLE
In dev mode, changes to modeline are not taken into account

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#1536]
Assuming you add some dependencies using modeline, then if you amend them in dev mode, the integration does not reflect the new set of dependencies

**Comment by nicolaferraro** [comment]
> Assuming you add some dependencies using modeline, then if you amend them in dev mode, the integration does not reflect the new set of dependencies

That's bad, considering that dev mode was one of the target use cases for using modeline.

**Comment by johnpoth** [comment]
I can take a look at this if it's ok
