### ISSUE TITLE
Provide yaml schema of design definition

### ISSUE THREAD

**Issue by apupier** [apache/camel-k#1537]
providing a yaml schema for Camel K yaml file will allow:
- to leverage built-in yaml support in most IDEs
- to allow versioning?
- to allow migration of versions?

**Comment by apupier** [comment]
@nicolaferraro I have not found an existing issue for it. Lars mentioned that you planned to have a look to generate it.

**Comment by nicolaferraro** [comment]
@apupier there's an issue in runtime https://github.com/apache/camel-k-runtime/issues/358.
Can you provide more information there?

Let's keep this open also here. Since also the Integration CR is in the end a YAML file, we can provide also a composite YAML schema for the CR.

**Comment by lburgazzoli** [comment]
https://github.com/apache/camel-k-runtime/issues/358 has been merged
