### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by doru1004** [apache/camel-k#1541]
When trying to run kamel (RC2) on a Java file containing came code I get:

```
RuntimeSupport - Found loader org.apache.camel.k.loader.java.JavaSourceLoader@39529185 for language java from service definition
Exception in thread "main" org.apache.camel.RuntimeCamelException: org.joor.ReflectException: Compilation error: /org/apache/camel/kamel/KafkaProducer.java:6: error: package org.apache.camel.builder.component does not exist
```

Any ideas what's going wrong?

**Comment by lburgazzoli** [comment]
Can you post the full content of the java file ?

**Comment by doru1004** [comment]
Thanks for the reply, sure:

```
package org.apache.camel.kamel;

import org.apache.camel.CamelContext;
import org.apache.camel.Exchange;
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.builder.component.ComponentsBuilderFactory;
import org.apache.camel.impl.DefaultCamelContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public final class KafkaProducer {
    private KafkaProducer() { }

    public static void main(String[] args) throws Exception {
        LOG.info("Starting Kafka-Camel integration...");
        CamelContext camelContext = new DefaultCamelContext();

        // Add route to send messages to Kafka.
        camelContext.addRoutes(new RouteBuilder() {
            public void configure() {
                // Setup kafka component with the brokers.
                ComponentsBuilderFactory.kafka()
                    .brokers("X.X.X.X:9092")
                    .register(camelContext, "kafka");
              [...]
            }
        });
    }
}
```

**Comment by lburgazzoli** [comment]
camel-k does not require you to write your own main but you should focus on the integration logic, see as example https://github.com/apache/camel-k/tree/master/examples/kafka

**Comment by doru1004** [comment]
I was trying to write a client for the consumer example.

Even if I don't include a main, the error seems to occur because of the code I have in my configure method.

What's the rule for what to include and not to include in the code passed to kamel run?

**Comment by lburgazzoli** [comment]
You need to add a dependency on the camel-componentdsl as it is not included by default, something like:

    camel run -d camel-componentdsl KafkaProducer.java

**Comment by doru1004** [comment]
I guess that should have been my question from the start, a way to actually add dependencies if they are not  included in the default setup! :) Thanks for giving an example of how to add some.

In case anyone else runs into this problem, I actually avoided the use of the component factory by adding the broker details in the client code similarly to how they are used by the consumer:

```
from(...)
   .to("kafka:topic?brokers=X.X.X.X:9092")
   .log("${body}");
```

**Comment by doru1004** [comment]
> camel-k does not require you to write your own main but you should focus on the integration logic, see as example https://github.com/apache/camel-k/tree/master/examples/kafka

If I really want to, can I add runnable code though? Or do I have to restrict myself to route building?

**Comment by lburgazzoli** [comment]
it depends what you mean by runnable code as you can provide some processors or other bits but in general you should focus on routes and other code can be provided through dependencies

**Comment by doru1004** [comment]
What I had in mind was the usage of the routes, the code that performs a sendBody or requestBody. Can I include that in the code to kamel run?

Also if I have route which contains a reactive stream, such as:

```
from("timer:clock").
  .setBody().header(Exchange.TIMER_COUNTER)
  .to("some:consumer")
  .log("${body}")
```

can I expect that to run?

**Comment by lburgazzoli** [comment]
> What I had in mind was the usage of the routes, the code that performs a sendBody or requestBody. Can I include that in the code to kamel run?
> 

can you scketch an example of what you want to achieve ?

> Also if I have route which contains a reactive stream, such as:
> 
> ```
> from("timer:clock").
>   .setBody().header(Exchange.TIMER_COUNTER)
>   .to("some:consumer")
>   .log("${body}")
> ```
> 
> can I expect that to run?

It is a route so as long as you have all the dependencies it should work, if not get back to us :)

**Comment by doru1004** [comment]
I just checked the saga example on here and it looks like it's using the pattern you mention above. I can use that as a blueprint.

In regards to creating a CamelContext, adding the route builder to it and then invoking requestBody or sendBody using the routes in the builder, that's not possible?

**Comment by lburgazzoli** [comment]
camel-k creates a CamelContext for you and then it will load your routes so no, you can't create your own context and even if it could be possible to use requestBody/sendBody (by adding a listener that reacts to events), it is definitively not what we recommend and what we want to support.

**Comment by doru1004** [comment]
Thanks a lot for the clarification. This is very helpful!

**Comment by doru1004** [comment]
I put together a reactive streams example and it works great!! :)

**Comment by doru1004** [comment]
Thanks for all the help! Closing since my initial issue is resolved.
