### ISSUE TITLE
Adding dependencies on external packages

### ISSUE THREAD

**Issue by doru1004** [apache/camel-k#1546]
Let's say I have a GitHub repo with the third party Java code and I want to add is a dependency since kamel run is complaining that it can't find the package.

Without kamel, what I do is clone the repo then call mvn install and then add the dependency in the pom.xml in the usual way. How would I proceed in the kamel run case?

**Comment by lburgazzoli** [comment]
you can use a special syntax that allow to leverage jitpack:

    kamel run -d github:$user/$repo

**Comment by doru1004** [comment]
I see that this works only with version 1.0.0 and I'm using RC2. I have another issue opened of what happens when I use version 1.0.0: https://github.com/apache/camel-k/issues/1542

**Comment by lburgazzoli** [comment]
you can do the same without the special syntax, you should follow the instructions on the jitpack site so:
- add a maven repo
- use the jitpack syntax

**Comment by doru1004** [comment]
As an example, let's assume that the repo I want to install is this one:

```
https://github.com/apache/camel
```

What would be the command you have in mind? I'm not sure I understand the steps you suggested.

**Comment by doru1004** [comment]
Looks like I have managed to get the latest version of Kamel to work (build from source with latest master). I might be able to actually use your initial suggestion:

```
kamel run -d github:$user/$repo
```

The project Github repo path is similar to this: `https://github.com/apache/camel`

What is the precise `-d` parameter I need to construct for that? Is it this:

```
kamel run -d github:apache/camel <path to my java file>
```

?

**Comment by lburgazzoli** [comment]
>
> kamel run -d github:apache/camel <path to my java file>
>

yes

**Comment by doru1004** [comment]
I tried this:

```
kamel run -d github:$user/$repo path/to/KafkaProducer.java
```

And the builder errored:

```
camel-k-kit-brlt2h4evfv6ukf4201g-builder   0/1     Init:Error   0          9s
```

```
> kubectl logs camel-k-kit-brlt2h4evfv6ukf4201g-builder
Error from server (BadRequest): container "buildah" in pod "camel-k-kit-brlt2h4evfv6ukf4201g-builder" is waiting to start: PodInitializing
```

Is there a way to get more information about the failure?

**Comment by doru1004** [comment]
Any way to get more feedback as to what goes on during the building process?

**Comment by doru1004** [comment]
Can you give me an example of a GitHub dependency that you have personally tried and it worked for you? I'm trying to pass dependencies via -d that are unrelated to my example and all I am getting is the error above in the builder.

**Comment by doru1004** [comment]
I have managed to get my example to work so I'm closing this.
