### ISSUE TITLE
kamel install not working on vanilla k8 cluster 

### ISSUE THREAD

**Issue by rahgadda** [apache/camel-k#1552]
Hi Team,

I am not able to install Camel-K on the vanilla k8 cluster. 
Details are provided below.

**Environment Details**
-  K8 Cluster Details
![image](https://user-images.githubusercontent.com/13075415/85410768-1c66d300-b585-11ea-8000-03b6656e0486.png)
- Kamel K version
![image](https://user-images.githubusercontent.com/13075415/85410836-33a5c080-b585-11ea-9cad-1bf06671f22b.png)
- Logs from operator [I am not able to view operator in cluster mode]
![image](https://user-images.githubusercontent.com/13075415/85412858-ad3eae00-b587-11ea-81c9-94b82924a9ee.png)

```bash
kamel install --cluster-setup --registry-insecure 10.40.65.121:5000
kamel init hello.java
kamel run .\hello.java --dev
```
![image](https://user-images.githubusercontent.com/13075415/85367343-b0fe1080-b546-11ea-85d9-a059248acb59.png)

Nothings updated in the registry as well
![image](https://user-images.githubusercontent.com/13075415/85367024-14d40980-b546-11ea-8fcd-95094b256eb0.png)

Nothings is getting displayed in logs
![image](https://user-images.githubusercontent.com/13075415/85367463-e9055380-b546-11ea-9ae8-0ecc398c653f.png)

No Pod is created
![image](https://user-images.githubusercontent.com/13075415/85366809-b1e27280-b545-11ea-87a6-d24da86fd80e.png)

`kamel get` is displaying below
![image](https://user-images.githubusercontent.com/13075415/85366867-ce7eaa80-b545-11ea-9b38-4d38f7f44bbd.png)

Please suggest.

**Comment by nicolaferraro** [comment]
@rahgadda I think what you intended to do with `kamel install --cluster-setup ...` was to install it globally, but the right command is `kamel install --global ...`. The `cluster-setup` flag installs only the CRDs and roles to access them in the cluster, but not the operator.

Can you try with that?

**Comment by rahgadda** [comment]
@nicolaferraro,

Based on your suggestion in have used the below command. 
I am unable to run any Kamel files. Below are the detail log details. Let me know if anything else is required.
I am running my server under HTTP and HTTPS proxy, let me know if anything else has to be done.

`kamel install --global --registry-insecure --registry 10.40.65.121:5000`

`kubectl get pods`
![image](https://user-images.githubusercontent.com/13075415/86228014-7c73ff80-bbab-11ea-91ec-3140bf73c273.png)

`kamel run --property logging.level.org.apache.camel=DEBUG .\Hello.java --dev`
![image](https://user-images.githubusercontent.com/13075415/86228246-c5c44f00-bbab-11ea-869b-275ac96abd05.png)

` kubectl logs camel-k-operator-7fd78d9ffc-62m58`
{"level":"info","ts":1593594897.7412403,"logger":"cmd","msg":"Go Version: go1.13.9"}
{"level":"info","ts":1593594897.7414746,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1593594897.741599,"logger":"cmd","msg":"Operator SDK Version: v0.17.1"}
{"level":"info","ts":1593594897.7417154,"logger":"cmd","msg":"Buildah Version: 1.14.0"}
{"level":"info","ts":1593594897.7418222,"logger":"cmd","msg":"Kaniko Version: 0.17.1"}
{"level":"info","ts":1593594897.7419643,"logger":"cmd","msg":"Camel K Operator Version: 1.0.0"}
{"level":"info","ts":1593594897.742066,"logger":"cmd","msg":"Camel K Default Runtime Version: 1.3.0"}
{"level":"info","ts":1593594897.7421567,"logger":"cmd","msg":"Camel K Git Commit: e99707333b1838dc1bb217b7aec4e09c70928816"}
{"level":"info","ts":1593594897.7423863,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1593594897.856899,"logger":"leader","msg":"No pre-existing lock was found."}
{"level":"info","ts":1593594897.8608463,"logger":"leader","msg":"Became the leader."}
{"level":"info","ts":1593594898.0708477,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1593594898.071938,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1593594898.075683,"logger":"cmd","msg":"Cannot detect user cluster role: skipping."}
{"level":"info","ts":1593594898.0788667,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1593594898.0791123,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1593594898.0792158,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"build-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1593594898.0794506,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"integrationplatform-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1593594898.0797725,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"integration-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1593594898.0798006,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"integrationkit-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1593594898.1798763,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"integrationplatform-controller"}
{"level":"info","ts":1593594898.179927,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"integrationplatform-controller","worker count":1}
{"level":"info","ts":1593594898.1801393,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"integration-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1593594898.180223,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"integration-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1593594898.1802523,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"integration-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1593594898.180352,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"integrationkit-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1593594898.1804798,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"build-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1593594898.1808562,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"integrationkit-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1593594898.1808922,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"integrationkit-controller"}
{"level":"info","ts":1593594898.2807739,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"integration-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1593594898.2812517,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"build-controller"}
{"level":"info","ts":1593594898.2812874,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"integrationkit-controller","worker count":1}
{"level":"info","ts":1593594898.3810813,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"integration-controller"}
{"level":"info","ts":1593594898.3811111,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"integration-controller","worker count":1}
{"level":"info","ts":1593594898.3812163,"logger":"camel-k.controller.integration","msg":"Reconciling Integration","request-namespace":"default","request-name":"hello"}
{"level":"info","ts":1593594898.381264,"logger":"camel-k.controller.integration","msg":"Invoking action platform-setup","request-namespace":"default","request-name":"hello","api-version":"camel.apache.org/v1","kind":"Integration","ns":"default","name":"hello"}
{"level":"info","ts":1593594898.3820438,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"build-controller","worker count":1}
{"level":"info","ts":1593594898.3831995,"logger":"camel-k.trait","msg":"Apply trait: platform"}
{"level":"info","ts":1593594898.3832777,"logger":"camel-k.trait","msg":"Apply trait: deployer"}
{"level":"info","ts":1593594898.399458,"logger":"camel-k.controller.integration","msg":"state transition","request-namespace":"default","request-name":"hello","api-version":"camel.apache.org/v1","kind":"Integration","ns":"default","name":"hello","phase-from":"","phase-to":"Waiting For Platform"}
{"level":"info","ts":1593594898.3995361,"logger":"camel-k.controller.integration","msg":"Reconciling Integration","request-namespace":"default","request-name":"hello"}
{"level":"info","ts":1593594898.3995566,"logger":"camel-k.controller.integration","msg":"Invoking action platform-setup","request-namespace":"default","request-name":"hello","api-version":"camel.apache.org/v1","kind":"Integration","ns":"default","name":"hello"}
{"level":"info","ts":1593594898.4008665,"logger":"camel-k.trait","msg":"Apply trait: platform"}
{"level":"info","ts":1593594898.4009237,"logger":"camel-k.trait","msg":"Apply trait: deployer"}
{"level":"info","ts":1593595016.4694045,"logger":"camel-k.controller.integration","msg":"Reconciling Integration","request-namespace":"default","request-name":"hello"}
{"level":"info","ts":1593595016.4694574,"logger":"camel-k.controller.integration","msg":"Invoking action noop","request-namespace":"default","request-name":"hello","api-version":"camel.apache.org/v1","kind":"Integration","ns":"default","name":"hello"}
{"level":"info","ts":1593595016.5567236,"logger":"camel-k.controller.integration","msg":"Reconciling Integration","request-namespace":"default","request-name":"hello"}
{"level":"info","ts":1593595016.5569417,"logger":"camel-k.controller.integration","msg":"Invoking action noop","request-namespace":"default","request-name":"hello","api-version":"camel.apache.org/v1","kind":"Integration","ns":"default","name":"hello"}
{"level":"info","ts":1593595016.6434119,"logger":"camel-k.controller.integration","msg":"Reconciling Integration","request-namespace":"default","request-name":"hello"}
{"level":"info","ts":1593595016.6435506,"logger":"camel-k.controller.integration","msg":"Invoking action platform-setup","request-namespace":"default","request-name":"hello","api-version":"camel.apache.org/v1","kind":"Integration","ns":"default","name":"hello"}
{"level":"info","ts":1593595016.6497185,"logger":"camel-k.trait","msg":"Apply trait: platform"}
{"level":"info","ts":1593595016.6497798,"logger":"camel-k.trait","msg":"Apply trait: deployer"}
{"level":"info","ts":1593595016.6550486,"logger":"camel-k.controller.integration","msg":"state transition","request-namespace":"default","request-name":"hello","api-version":"camel.apache.org/v1","kind":"Integration","ns":"default","name":"hello","phase-from":"","phase-to":"Waiting For Platform"}
{"level":"info","ts":1593595016.655274,"logger":"camel-k.controller.integration","msg":"Reconciling Integration","request-namespace":"default","request-name":"hello"}
{"level":"info","ts":1593595016.6553886,"logger":"camel-k.controller.integration","msg":"Invoking action platform-setup","request-namespace":"default","request-name":"hello","api-version":"camel.apache.org/v1","kind":"Integration","ns":"default","name":"hello"}
{"level":"info","ts":1593595016.6568086,"logger":"camel-k.trait","msg":"Apply trait: platform"}
{"level":"info","ts":1593595016.6569502,"logger":"camel-k.trait","msg":"Apply trait: deployer"}
