### ISSUE TITLE
Migrate from ServiceMonitor to PodMonitor in Prometheus trait

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#1555]
The Prometheus creates a `ServiceMonitor` resource, so that a Prometheus operator instance can discover the integration metrics endpoints. In newer versions of the Prometheus operator, the `PodMonitor` resource has been introduced that seems more appropriate, as it would prevent the creation of an ah-hoc service for the sole monitoring purpose.

RBAC resources and documentation will have to be updated accordingly.

**Comment by heiko-braun** [comment]
Is a composite resource that contains servicemonitor, alerts, etc?
