### ISSUE TITLE
Add the camel category to Camel K CRDs

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#1556]
So that users can run `kubectl get camel` as a shorthand for `kubectl get ip,ik,it,ikb`.

See https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#categories.

**Comment by heiko-braun** [comment]
Shouldnt it be ‘get kamel’?

**Comment by astefanutti** [comment]
> Shouldn't it be ‘get kamel’?

It's for us to decide. It could also be both `camel` and `kamel` categories.

**Comment by astefanutti** [comment]
Fixed with #1615.
