### ISSUE TITLE
dependencies trait - Camel shorthand camel:dns vs camel-dns

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#1583]
Spotted this in an example
https://github.com/apache/camel-k/blob/master/examples/dns.js#L20

I assume its a mistake with the colon, eg `camel:dns` should be `camel-dns` ?

**Comment by lburgazzoli** [comment]
yes, the original idea was to use an uri like syntax but it turned out to be an issue so camel-${id} is the right one

**Comment by davsclaus** [comment]
Ok so the example should be updated
