### ISSUE TITLE
Fix generation of traits.yaml file

### ISSUE THREAD

**Issue by apupier** [apache/camel-k#1599]
typo like this one https://github.com/apache/camel-k/pull/1598 occured during generation

@astefanutti Can you provide more details please?
Where is the algorithm used for generation?
Where is the root text?

**Comment by astefanutti** [comment]
> @astefanutti Can you provide more details please?

Sure

> Where is the algorithm used for generation?

The code path starts from `script/gen_doc.sh` all the way done to https://github.com/apache/camel-k/blob/ff29575de82a5dc05b4b68512b6da2348c8453d8/cmd/util/doc-gen/generators/traitmetadatagen.go#L127

> Where is the root text?

The metadata are taken directly from the traits source code.
