### ISSUE TITLE
Traits configuration schema

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#1614]
The traits configuration is stored in the `Integration`, `IntegrationKit` and `IntegrationPlatform` resources. While this makes trait configuration part of the Camel K public API, it is not defined in any schema, and is loosely validated.

Following #1600, the traits structs are used directly for serialisation. Instead of declaring `map[string]TraitSpec` fields in the API, we could make the traits structs part of the Camel K API, and refer to them from the `Integration`, `IntegrationKit` and `IntegrationPlatform` types.

With #1582, the traits configuration schema will automatically be generated and included in the CRDs structural schemas.

**Comment by apupier** [comment]
see also https://issues.redhat.com/browse/ENTESB-16272

**Comment by tadayosi** [comment]
Done with #3235
