### ISSUE TITLE
Release Camel K 1.1.0

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1618]
Let's collect the good things we're doing to do a release early next week

**Comment by nicolaferraro** [comment]
## New Features

- Upgraded Camel K Runtime to 1.4.1 (Camel 3.4.0, Camel-Quarkus 1.0.0-CR3, Quarkus 1.6.0.Final) ([#1620](https://github.com/apache/camel-k/pull/1620), [@nicolaferraro](https://github.com/nicolaferraro))
- When subscribing to a Knative channel or broker, replies are ignored unless explicitly enabled ([#1619](https://github.com/apache/camel-k/pull/1619), [@nicolaferraro](https://github.com/nicolaferraro))


## Other Notable Changes

- fix(api): Declare integration Flow as json.RawMessage ([#1591](https://github.com/apache/camel-k/pull/1591), [@astefanutti](https://github.com/astefanutti))
- Added flag to the install command to allow setting the operator image pull policy ([#1612](https://github.com/apache/camel-k/pull/1612), [@johnpoth](https://github.com/johnpoth))
- Fixed issue missing help details as reported on &#35;1585 ([#1596](https://github.com/apache/camel-k/pull/1596), [@orpiske](https://github.com/orpiske))
- feat: Structured traits configuration serialization ([#1600](https://github.com/apache/camel-k/pull/1600), [@astefanutti](https://github.com/astefanutti))
- feat: Integration scale sub-resource works with HPA ([#1587](https://github.com/apache/camel-k/pull/1587), [@astefanutti](https://github.com/astefanutti))
- feat(crd): Generate CRDs from APIs ([#1582](https://github.com/apache/camel-k/pull/1582), [@astefanutti](https://github.com/astefanutti))
- doc: Add monitoring documentation ([#1569](https://github.com/apache/camel-k/pull/1569), [@astefanutti](https://github.com/astefanutti))

**Comment by SeekingMeaning** [comment]
Is 1.1.0 officially released? Just making sure before merging Homebrew/homebrew-core#58346

**Comment by nicolaferraro** [comment]
@SeekingMeaning, vote is still ongoing. It will close tomorrow at 16:00 CET and then released if everything is ok (so far, it is).

**Comment by nicolaferraro** [comment]
Camel K 1.1.0 is now released.
