### ISSUE TITLE
Add command completion for kamel

### ISSUE THREAD

**Issue by johnpoth** [apache/camel-k#1635]
I can take a look at this if it's ok

**Comment by lburgazzoli** [comment]
we already have support for bash completion, do you mean something else ?

**Comment by johnpoth** [comment]
Hi @lburgazzoli,

We are talking about the same thing:
`kamel get integrat` press tab should get `kamel get integrations` sort of thing
If this is already implemented, I'll look into why it's not working for me. Thanks !

**Comment by lburgazzoli** [comment]
To make it working you need to activate it as example:

    $ . <(kamel completion bash)

or save the result and load it with bash completion

**Comment by johnpoth** [comment]
thanks @lburgazzoli ! It's not working for me but I'll look into it and respond here or open a PR ASAP

**Comment by johnpoth** [comment]
@lburgazzoli after typing the command correctly, it works! Sorry for the noise, let's close this
