### ISSUE TITLE
No matches for kind "Subscription" in version "messaging.knative.dev/v1alpha1"

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1636]
We should upgrade the eventing resources to v1beta1 at least.

E.g. Subscription is no longer present at version v1alpha1.

**Comment by pjcubero** [comment]
Which is the solution to solve this issue? I have one channel consumer, and I have this error, I can't deploy the integration properly...

**Comment by nicolaferraro** [comment]
This will be fixed in next patch release.

Until then, a simple workaround is this one. Instead of:

```
from("knative:channel/xxx")
```

Use:

```
from("knative:endpoint/default")
```

This will create a Knative service. Then you can create a subscription resource by hand to bind the channel to the service: https://knative.dev/docs/eventing/event-delivery/

**Comment by pjcubero** [comment]
> This will be fixed in next patch release.
> 
> Until then, a simple workaround is this one. Instead of:
> 
> ```
> from("knative:channel/xxx")
> ```
> 
> Use:
> 
> ```
> from("knative:endpoint/default")
> ```
> 
> This will create a Knative service. Then you can create a subscription resource by hand to bind the channel to the service: https://knative.dev/docs/eventing/event-delivery/

But one question, I have in the producer this:

.to("knative:channel/creacionpac")

and in the consumer, I have this:

from("knative:channel/creacionpac")

I have to change both of them, or only the consumer?

Which is the workaround solution?

**Comment by nicolaferraro** [comment]
> > This will be fixed in next patch release.
> > Until then, a simple workaround is this one. Instead of:
> > ```
> > from("knative:channel/xxx")
> > ```
> > 
> > 
> > Use:
> > ```
> > from("knative:endpoint/default")
> > ```
> > 
> > 
> > This will create a Knative service. Then you can create a subscription resource by hand to bind the channel to the service: https://knative.dev/docs/eventing/event-delivery/
> 
> But one question, I have in the producer this:
> 
> .to("knative:channel/creacionpac")
> 
> and in the consumer, I have this:
> 
> from("knative:channel/creacionpac")
> 
> I have to change both of them, or only the consumer?
> 
> Which is the workaround solution?

Only the consumer

**Comment by pjcubero** [comment]
> > > This will be fixed in next patch release.
> > > Until then, a simple workaround is this one. Instead of:
> > > ```
> > > from("knative:channel/xxx")
> > > ```
> > > 
> > > 
> > > Use:
> > > ```
> > > from("knative:endpoint/default")
> > > ```
> > > 
> > > 
> > > This will create a Knative service. Then you can create a subscription resource by hand to bind the channel to the service: https://knative.dev/docs/eventing/event-delivery/
> > 
> > 
> > But one question, I have in the producer this:
> > .to("knative:channel/creacionpac")
> > and in the consumer, I have this:
> > from("knative:channel/creacionpac")
> > I have to change both of them, or only the consumer?
> > Which is the workaround solution?
> 
> Only the consumer

But where must I to indicate the name of the channel, creacionpac?

apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: with-dead-letter-sink
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
    name: default
  delivery:
    deadLetterSink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: error-handler
  subscriber:
    uri: http://doesnotexist.default.svc.cluster.local

**Comment by nicolaferraro** [comment]
Like:


```yaml
apiVersion: messaging.knative.dev/v1beta1
kind: Subscription
metadata:
  name: mysubscription
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
    name: your-source-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: the-name-of-your-integration
```

**Comment by pjcubero** [comment]
> Like:
> 
> ```yaml
> apiVersion: messaging.knative.dev/v1beta1
> kind: Subscription
> metadata:
>   name: mysubscription
> spec:
>   channel:
>     apiVersion: messaging.knative.dev/v1
>     kind: InMemoryChannel
>     name: your-source-channel
>   subscriber:
>     ref:
>       apiVersion: serving.knative.dev/v1
>       kind: Service
>       name: the-name-of-your-integration
> ```

Which is the relation with the from in the consumer?

from("knative:endpoint/default")

This default, what must be?

**Comment by nicolaferraro** [comment]
> > Like:
> > ```yaml
> > apiVersion: messaging.knative.dev/v1beta1
> > kind: Subscription
> > metadata:
> >   name: mysubscription
> > spec:
> >   channel:
> >     apiVersion: messaging.knative.dev/v1
> >     kind: InMemoryChannel
> >     name: your-source-channel
> >   subscriber:
> >     ref:
> >       apiVersion: serving.knative.dev/v1
> >       kind: Service
> >       name: the-name-of-your-integration
> > ```
> 
> Which is the relation with the from in the consumer?
> 
> from("knative:endpoint/default")
> 
> This default, what must be?

Just "default", you don't have to change it. That uri exposes a knative endpoint, the name is irrelevant so we conventionally set it to "default".

**Comment by pjcubero** [comment]
Ok, thanks a lot Nicola... I think I need to follow learning all of this technology... Thanks for your continuous support...

**Comment by pjcubero** [comment]
Other question, how can i invoke to an external url, because if i try to call to an external url in a knative integration, gives me one error, endpoint not found. I invoke the external url using recipientslist.

**Comment by nicolaferraro** [comment]
> Other question, how can i invoke to an external url, because if i try to call to an external url in a knative integration, gives me one error, endpoint not found. I invoke the external url using recipientslist.

It shouldn't matter what kind of integration you're running, to call an external URL you should use the `http` component, like `.to("http://theurl/thepath")`.

Btw, you can ask questions in the Gitter channel, to avoid polluting issues.

**Comment by pjcubero** [comment]
> > Other question, how can i invoke to an external url, because if i try to call to an external url in a knative integration, gives me one error, endpoint not found. I invoke the external url using recipientslist.
> 
> It shouldn't matter what kind of integration you're running, to call an external URL you should use the `http` component, like `.to("http://theurl/thepath")`.
> 
> Btw, you can ask questions in the Gitter channel, to avoid polluting issues.

Sorry, I know that this issue is not related with the last two questions that I have asked you. But I have asked in the Gitter channel, and I don't have reply. The question is:

I have one question, I have some integrations in camel-k and knative, and I want to know how can I propagate the body from the first knative service to the last one? Because I need to have available in all the integrations.

**Comment by MaciekLeks** [comment]
@nicolaferraro Thanks for the update, but in case of Kafka channel it would not work correctly for v1beta1. `kamel run <integration>` creates subscription like this:
```yaml
channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
    name: salesforce
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: camel-k-kafa-consumer
```
So the channel must be declared for v1alpha1, like so:

```yaml
apiVersion: messaging.knative.dev/v1alpha1
kind: KafkaChannel
metadata:
  name: salesforce
```



I've not checked out what about InMemoryChannel but I may assume it's the same.

**Comment by nicolaferraro** [comment]
Hi @MaciekLeks, we're adding auto-discovery for KafkaChannel v1beta1 in next 1.2.0 release.
Running with 1.1.1, if you want to use v1beta1 in the subscription you need to write an URL like: 

```
from('knative:channel/salesforce?kind=KafkaChannel&apiVersion=v1beta1')
```

And it should do what you expect.
You won't need to specify kind & api in 1.2.0.
