### ISSUE TITLE
Caffeine with Knative doesn't work

### ISSUE THREAD

**Issue by pjcubero** [apache/camel-k#1649]
I have two integrations, one with knative and other without. In the second one, if I add caffeine cache, it's working fine, but in the first one, if I add it, the integration is not deployed, and finish with error... Do you know if there is some issue if I want to use camel-caffeine with knative?

Thanks.

**Comment by oscerd** [comment]
To be able to understand and eventually reproduce, please add a reproducer on github so we can try.

**Comment by pjcubero** [comment]
Ok, this example is not working for me:

public class getTokenextends RouteBuilder {

  @BindToRegistry
  public static Cache<String, String> cache() {
    return Caffeine.newBuilder()
    .expireAfterWrite(10, TimeUnit.SECONDS)
    .maximumSize(100)
    .build();
  }	
  
  @Override
  public void configure() throws Exception {

    from("knative:endpoint/get-token")
		.to("caffeine-cache://ejemplo?cache=#cache&action=GET&key=token")
		.log("Result of Action ${header.CamelCaffeineAction} with key ${header.CamelCaffeineKey} is: ${body}")


But this is working fine for me:

public class EjemploCache extends RouteBuilder {
	@Override
	public void configure() throws Exception {
		from("timer:tick")
			.setBody(constant("Hello"))
			.setHeader("CamelCaffeineAction", constant("PUT"))
			.setHeader("CamelCaffeineKey", constant("1"))
			.toF("caffeine-cache://%s", "test")
			.log("Result of Action ${header.CamelCaffeineAction} with key ${header.CamelCaffeineKey} is: ${body}")

**Comment by pjcubero** [comment]
For example, If I run this integration:

import org.apache.camel.builder.RouteBuilder;

public class EjemploCache extends RouteBuilder {
	@Override
	public void configure() throws Exception {
		from("timer:tick")
			.setBody(constant("Hello"))
			.setHeader("CamelCaffeineAction", constant("PUT"))
			.setHeader("CamelCaffeineKey", constant("1"))
			.toF("caffeine-cache://%s", "test")
			.log("Result of Action ${header.CamelCaffeineAction} with key ${header.CamelCaffeineKey} is: ${body}")
			.setBody(constant(null))
			.setHeader("CamelCaffeineAction", constant("GET"))
			.setHeader("CamelCaffeineKey", constant("1"))
			.toF("caffeine-cache://%s", "test")
			.log("Result of Action ${header.CamelCaffeineAction} with key ${header.CamelCaffeineKey} is: ${body}")
			.setBody(constant(null))
			.setHeader("CamelCaffeineAction", constant("INVALIDATE"))
			.setHeader("CamelCaffeineKey", constant("1"))
			.log("Invalidating entry with key ${header.CamelCaffeineKey}")
			.toF("caffeine-cache://%s", "test")
			.setHeader("CamelCaffeineAction", constant("GET"))
			.setHeader("CamelCaffeineKey", constant("1"))
			.toF("caffeine-cache://%s", "test")
			.log("The Action ${header.CamelCaffeineAction} with key ${header.CamelCaffeineKey} has result? ${header.CamelCaffeineActionHasResult}");
  }
}

it's working fine. But If I try to run this:

import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.BindToRegistry;

import com.github.benmanes.caffeine.cache.Cache;
import com.github.benmanes.caffeine.cache.Caffeine;

import java.util.concurrent.TimeUnit;

public class ConsumidorCambios extends RouteBuilder {

  @Override
  public void configure() throws Exception {    

      // Write your routes here, for example:
      from("knative:endpoint/consumidor-cambios")
        .to("caffeine-cache://ejemplo?cache=#cache&action=PUT&key=token")
        .setBody().simple("Hola Mundo")
        .log("Before Read Cache! ${body}")
        .to("caffeine-cache://ejemplo?cache=#cache&action=GET&key=token") // Puedes añadir o no el parámetro cache pero claro primero debe estar vinculado, es decir haber echo una acción previamente
        .log("Test! ${body}")
        .setBody()
          .simple("Respuesta desde el endpoint de cambios ${date:now}")
        .to("log:info");

  }
}

this is not deployed properly, and at the end I see the error: 

**integration deployment failed**

**Comment by oscerd** [comment]
I think you need to explicitly pass the caffeine dependency. Why did you close this?

**Comment by pjcubero** [comment]
I don't know why I closed this. I have this two examples, attached.

[examples.zip](https://github.com/apache/camel-k/files/5014954/examples.zip)

ConsumidorCambios.java is a integration with cache and knative, and when I try to deploy with my local minikube, it's not working fine. But, the second, EjemploCache.java, it's one integration with cache and timer, and it's deployed fine and works fine. 

Is there any way to know why the first it's not working fine? where can I see the error?

**Comment by oscerd** [comment]
Do you have knative running on minikube?

**Comment by pjcubero** [comment]
> Do you have knative running on minikube?

I installed minikube, and I executed this related with knative:

./kubectl apply --filename https://github.com/knative/serving/releases/download/v0.14.2/serving-crds.yaml 
./kubectl apply --filename https://github.com/knative/serving/releases/download/v0.14.2/serving-core.yaml 
./kubectl apply --filename https://github.com/knative/eventing/releases/download/v0.14.2/eventing-crds.yaml
./kubectl apply --filename https://github.com/knative/eventing/releases/download/v0.14.2/eventing-core.yaml

**Comment by oscerd** [comment]
Have a look at the camel-k example related to knative. I believe you're missing some bits.

https://github.com/apache/camel-k-examples

**Comment by pjcubero** [comment]
> Have a look at the camel-k example related to knative. I believe you're missing some bits.
> 
> https://github.com/apache/camel-k-examples

But the only thing that I have no installed is the kamel commands, the rest are ok. And if I execute this:

./kubectl get integrationplatform

Tells me that camel-k is ready

**Comment by pjcubero** [comment]
> > Have a look at the camel-k example related to knative. I believe you're missing some bits.
> > https://github.com/apache/camel-k-examples
> 
> But the only thing that I have no installed is the kamel commands, the rest are ok. And if I execute this:
> 
> ./kubectl get integrationplatform
> 
> Tells me that camel-k is ready

Other question, my laptop has 16 gb from RAM memory, it's one i5. Can be problem of memory?

**Comment by oscerd** [comment]
In your example I don't see a files like this for example:
https://github.com/apache/camel-k-examples/blob/master/07-aws-sqs-source-basic/aws-sqs-source.yaml
https://github.com/apache/camel-k-examples/blob/master/07-aws-sqs-source-basic/aws-sqs-channel.yaml
https://github.com/apache/camel-k-examples/blob/master/07-aws-sqs-source-basic/aws-sqs-consumer.groovy

If you don't add the channel and source, knative won't work. Also I believe you're missing this file too.

kubectl apply --filename https://github.com/knative/eventing-contrib/releases/download/v0.14.2/camel.yaml

**Comment by oscerd** [comment]
Without logs or information we cannot answer questions about memory.

**Comment by pjcubero** [comment]
Ok, I have seen my problem, I had in a different namespace knative and camel, and now it's working.

I have other question, if you can reply me... I want to create channels to communicate integrations itself, how can I create, because I create like Channel, and the status is unknown, must I to create like inMemoryChannel? Which is the right format?

Thanks

**Comment by lburgazzoli** [comment]
@pjcubero please open a new issue for the channel stuff (if it is still an issue)
