### ISSUE TITLE
Add the option to deploy a CamelSource Integration from the CLI

### ISSUE THREAD

**Issue by hguerrero** [apache/camel-k#1650]
The Kamel CLI should be able to manage and deploy CamelSource knative sources.

**Comment by nicolaferraro** [comment]
They are currently part of knative, that's the reason why they are not here. Also `kubectl` can deploy them just fine..

But we can consider it when we decide the long-term strategy for CamelSources.

**Comment by hguerrero** [comment]
how is that working? I was envisioning more take a camel k integration and conver that into a camelsource and deploy as it instead of as an integration

**Comment by nicolaferraro** [comment]
> how is that working? I was envisioning more take a camel k integration and conver that into a camelsource and deploy as it instead of as an integration

What you describe is (almost) the approach taken in the experimental PR #1637, where we take an integration and create a child sinkbinding, which is interpreted by Knative as a source.

The current approach instead is that a (knative) CamelSource is created via kubectl and it creates a child Integration that runs the code.
