### ISSUE TITLE
Add a warning when operating from a CLI with a different installed Operator version

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#1652]
As experienced in #1648 there may be certain incompatibilities when a `kamel` CLI with a version is operating against an operator with another version. It would be nice to add a simple log warning the user about this incompatibility, either on CLI or on operator log.

**Comment by nicolaferraro** [comment]
We should also add some options to `kamel version` (e.g. `kamel version --operator`) to return also the operator version when asked.

Note that the operator may be installed also globally, in which case we can try some common namespaces to find it or we may not be able to determine its version.

**Comment by squakez** [comment]
I can work on this
