### ISSUE TITLE
Add support for podtemplatespec / container in the Integration CRD

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#1657]
Sometime you need to add very specific configurations to the PODs created by camel-k so instead of trying to cover all the aspect through the cli and custom config, wonder if our source should have some options to configure the containers, like using podtemplatespec as for the deployment resource

**Comment by nicolaferraro** [comment]
That would simplify also https://github.com/apache/camel-k/issues/1122. And in general cover non-standard cases.

**Comment by mmelko** [comment]
I can look at this.
