### ISSUE TITLE
IntegrationKit stuck in 'Build Submitted' phase due to validation error 'type in spec.tasks.image.volumes.secret is required' on GKE

### ISSUE THREAD

**Issue by anandkane** [apache/camel-k#1663]
Hello

I followed the instruction to install Camel K on GKE given at https://camel.apache.org/camel-k/latest/installation/gke.html and https://camel.apache.org/camel-k/latest/installation/registry/gcr.html. After that I tried to run hello.groovy, but faced the problem outlined in https://github.com/apache/camel-k/issues/1370. I was able to get past the problem by setting flag --build-publish-strategy=Kaniko.

However, the IntegrationKit is still stuck in 'Build Submitted' phase and the cause this time is 
validation failure list:
type in spec.tasks.image.volumes.secret is required

Full output of 'k describe integrationkits.camel.apache.org kit-bsqdepf9gf15pade1u5g' can be found in the attached file.

Any help in fixing this problem will be highly appreciated.

Thanks

[describe-kit.txt](https://github.com/apache/camel-k/files/5067547/describe-kit.txt)

**Comment by anandkane** [comment]
Updates:

The same example runs successfully on Minikube.

Kubernetes versions on Minikube
{
  "clientVersion": {
    "major": "1",
    "minor": "18",
    "gitVersion": "v1.18.6",
    "gitCommit": "dff82dc0de47299ab66c83c626e08b245ab19037",
    "gitTreeState": "clean",
    "buildDate": "2020-07-15T16:58:53Z",
    "goVersion": "go1.13.9",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  **"serverVersion"**: {
    "major": "1",
    **"minor": "18",**
    "gitVersion": "v1.18.3",
    "gitCommit": "2e7996e3e2712684bc73f0dec0200d64eec7fe40",
    "gitTreeState": "clean",
    "buildDate": "2020-05-20T12:43:34Z",
    "goVersion": "go1.13.9",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}

Kubernetes versions on GKE

{
  "clientVersion": {
    "major": "1",
    "minor": "18",
    "gitVersion": "v1.18.6",
    "gitCommit": "dff82dc0de47299ab66c83c626e08b245ab19037",
    "gitTreeState": "clean",
    "buildDate": "2020-07-15T16:58:53Z",
    "goVersion": "go1.13.9",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  **"serverVersion":** {
    "major": "1",
    **"minor": "15+",**
    "gitVersion": "v1.15.12-gke.2",
    "gitCommit": "fb7add51f767aae42655d39972210dc1c5dbd4b3",
    "gitTreeState": "clean",
    "buildDate": "2020-06-01T22:20:10Z",
    "goVersion": "go1.12.17b4",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}

**Comment by anandkane** [comment]
Uopdate 2: When GKE is updated to use the 'latest' kubernetes version, the error changes to "camel-k-integration-kit-controller  Cannot reconcile Integration Kit kit-bsqgln23se6vbbiof2d0: cannot create build: Build.camel.apache.org "kit-bsqgln23se6vbbiof2d0" is invalid: type: Required value"

kubernetes version after update:

  "clientVersion": {
    "major": "1",
    "minor": "18",
    "gitVersion": "v1.18.6",
    "gitCommit": "dff82dc0de47299ab66c83c626e08b245ab19037",
    "gitTreeState": "clean",
    "buildDate": "2020-07-15T16:58:53Z",
    "goVersion": "go1.13.9",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  **"serverVersion"**: {
    "major": "1",
    **"minor": "16+",**
    "gitVersion": "v1.16.13-gke.1",
    "gitCommit": "688c6543aa4b285355723f100302d80431e411cc",
    "gitTreeState": "clean",
    "buildDate": "2020-07-21T02:37:26Z",
    "goVersion": "go1.13.9b4",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}

[describe-kit-latest-k8s.txt](https://github.com/apache/camel-k/files/5068633/describe-kit-latest-k8s.txt)

**Comment by senthilkrajagopal** [comment]
--build-publish-strategy Spectrum worked for me. Looking at the code, it appears like kaniko was removed after 1.0.0-RC1.

Use spectrum along with .dockerconfigjson. Follow the steps here.. https://medium.com/hackernoon/today-i-learned-pull-docker-image-from-gcr-google-container-registry-in-any-non-gcp-kubernetes-5f8298f28969
