### ISSUE TITLE
camel-K installation failed with Helm on GKE

### ISSUE THREAD

**Issue by jeremie-H** [apache/camel-k#1664]
Hello,

I try to install camel-K with helm on a gke environment. I've followed this current guide : https://hub.helm.sh/charts/camel-k/camel-k

First step : 
```
helm repo add camel-k https://apache.github.io/camel-k/charts
```

then i 've tried
```
helm install \
  --generate-name \
  --set platform.cluster=Kubernetes \
  camel-k/camel-k
```
but i've got the following error :
```
Error: template: camel-k/templates/NOTES.txt:4:7: executing "camel-k/templates/NOTES.txt" at <(not .Values.platform.cluster) or (.Values.platform.cluster ne "OpenShift")>: can't give argument to non-function not .Values.platform.cluster
```

kubernetes version :
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.11-gke.5", GitCommit:"baccd25d44f1a0d06ad3190eb508784efbb990a5", GitTreeState:"clean", BuildDate:"2020-06-25T22:55:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```
i would be grateful if you could find a solution or a workaround :kissing:

**Comment by marzelwidmer** [comment]
Same issue with Kubernetes version : ``` k version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by marko999** [comment]
Similar problem, I have tried with kamel cli, same error
