### ISSUE TITLE
List of supported versions combinations for running Camel-K with Knative

### ISSUE THREAD

**Issue by aslom** [apache/camel-k#1665]
Is there online doc (link?) with that information?

In particular what versions of Knative are suported by  Camel K 1.0 GA? Knative Eventing APIs are changing fast? Supported 0.14+?

**Comment by aslom** [comment]
Related to https://github.com/apache/camel-k/issues/1336

**Comment by ricardozanini** [comment]
Glad that you bring this up. Current Camel-K version is not compatible with Knative Eventing v1 CRDs. When we try to deploy one of the knative examples, camel-k stuck on deployment phase:

```
Warning  IntegrationError             2m34s (x18 over 14m)  camel-k-integration-controller      Cannot reconcile Integration notifier: error executing post actions: error during replace resource: could not create or replace resource notifications-notifier: no matches for kind "Subscription" in version "messaging.knative.dev/v1alpha1"
```

**Comment by ricardozanini** [comment]
Hi @nicolaferraro, while this compatibility issue is not fixed, how do we integrate with knative?

**Comment by squakez** [comment]
Relates #3306
