### ISSUE TITLE
Package installation artifacts with Helm

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#167]
The `kamel` binary is useful for development purposes, but we need also to be compatible with CI/CD platforms to support automated deployments.

First target is to support Helm (https://github.com/helm/helm) as deployment model for the operator, integration platform, contexts and integrations.

Supporting Helm will enable integration with various CI/CD platforms, including Jenkins X (https://github.com/jenkins-x).

**Comment by whyman** [comment]
Hello,

Do you have a high level plan of what is needed to get this done, my team and I are willing to do the work if you can provide some guidance.

Cheers!

**Comment by alexeyshockov** [comment]
Help support is really a must IMO, because it's a default app manager for k8s, at least that's what I see around me.

Do you still have any plans for the future about it?

**Comment by nicolaferraro** [comment]
Definitely. Assigned to next milestone.
