### ISSUE TITLE
document how to create knative camel sources using Java

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#1674]

**Comment by arthurdm** [comment]
That would be great!   I also really like how `kamel run <java>` puts my source code into an Integration CR - are there plans on augmenting `kamel` to have similar capability, put wrapping in a CamelSource?  Perhaps `kamel run <java> --camelsource`?

**Comment by lburgazzoli** [comment]
We are actively working to make the experience of creating sources easier so in the future it will be possible nut we are still working on some of the low level bits (https://github.com/apache/camel-k/issues/1654, https://github.com/apache/camel-k/issues/1567)

**Comment by astefanutti** [comment]
I think this can be closed as the work as shifted in favour of Kamelets.
