### ISSUE TITLE
Failed to install Camel-K in IKS

### ISSUE THREAD

**Issue by JackJiaJJ** [apache/camel-k#1687]
I launched a k8s env in **IBM Cloud (IKS)**, and I failed to install Camel-K, it prompted below error:

Error: cannot get command client: no Auth Provider found for name "oidc"

**Below are the commands I executed:**

 [root@bamfvt3master1 ~]# kubectl get nodes
NAME            STATUS   ROLES    AGE    VERSION
10.38.109.116   Ready    <none>   3d2h   v1.17.11+IKS
10.38.109.117   Ready    <none>   3d2h   v1.17.11+IKS
10.38.109.126   Ready    <none>   3d2h   v1.17.11+IKS

 [root@bamfvt3master1 ~]#  wget https://github.com/apache/camel-k/releases/download/v1.1.0/camel-k-client-1.1.0-linux-64bit.tar.gz

 [root@bamfvt3master1 ~]#  tar xvf camel-k-client-1.1.0-linux-64bit.tar.gz

 [root@bamfvt3master1 ~]#  cp kamel /usr/bin

 [root@bamfvt3master1 ~]#  kamel install
Error: cannot get command client: no Auth Provider found for name "oidc"

**Comment by nicolaferraro** [comment]
Seems similar to the issue happened with Azure https://github.com/apache/camel-k/issues/1138

**Comment by JackJiaJJ** [comment]
@nicolaferraro if there is any workaround ? thanks a lot !

**Comment by nicolaferraro** [comment]
Technically support for `oidc` should be there (https://github.com/apache/camel-k/blob/25a6a74aca4c8ad4adcc78cca8ebbfc626a20316/cmd/kamel/main.go#L33). We need to investigate.

**Comment by nicolaferraro** [comment]
It was added recently, we can backport the change to v1.1.1 which will be available next week.

**Comment by JackJiaJJ** [comment]
That's so great !  thanks a lot ! @nicolaferraro

**Comment by nicolaferraro** [comment]
Fixed by https://github.com/apache/camel-k/pull/1694
