### ISSUE TITLE
Integration controller issue

### ISSUE THREAD

**Issue by shanisma** [apache/camel-k#1691]
Hello,

I deployed kamel on kubernetes with this command:

`kamel install --cluster-setup `

`kamel install --registry-insecure --registry <registry url> --registry-auth-password <password> --registry-auth-username <username> --maven-repository http://repository.apache.org/content/groups/snapshots-group@id\=apache@snapshots@noreleases`

Operator is up and running
![pod](https://user-images.githubusercontent.com/23318335/92406935-93017e80-f139-11ea-954f-1ef540a7f62c.png)

Integration kit is stuck ...
![ik](https://user-images.githubusercontent.com/23318335/92407042-d78d1a00-f139-11ea-98b9-7af540e2a4ff.png)

On operator logs  I get: 

` {
   "level":"error",
   "ts":1599496483.1858208,
   "logger":"controller-runtime.controller",
   "msg":"Reconciler error","controller":"integrationkit-controller","request":"kamel/kit-btb5nh8mjidspgqc3csg",
   "error":"cannot create build: Build.camel.apache.org \"kit-btb5nh8mjidspgqc3csg\" is invalid:  ││ type: Required value","errorVerbose":"Build.camel.apache.org \"kit-btb5nh8mjidspgqc3csg\" is invalid: type: Required value\ncannot create build\ngithub.com/apache/camel-k/pkg/controller/integrationkit.(*buildAction).handleBuildSubmitted\n\tgithub.com/apache/camel-k@/pkg/controller/int ││ egrationkit/build.go:112\ngithub.com/apache/camel-k/pkg/controller/integrationkit.(*buildAction).Handle\n\tgithub.com/apache/camel-k@/pkg/controller/integrationkit/build.go:57\ngithub.com/apache/camel-k/pkg/controller/integrationkit.(*ReconcileIntegrationKit).Reconcile\n\tgithub.com/a ││ pache/camel-k@/pkg/controller/integrationkit/integrationkit_controller.go:228\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/i ││ nternal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/control ││ ler.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tk8s.io/apimachin ││ ery@v0.18.2/pkg/util/wait/wait.go:88\nruntime.goexit\n\truntime/asm_amd64.s:1357","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.i ││ o/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/intern ││ al/controller.(*Controller).worker\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/ ││ apimachinery@v0.18.2/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:88"
   }`

'Build.camel.apache.org "kit-btb5nh8mjidspgqc3csg" is invalid: type: Required value
cannot create build
github.com/apache/camel-k/pkg/controller/integrationkit.(*buildAction).handleBuildSubmitted
        github.com/apache/camel-k@/pkg/controller/integrationkit/build.go:112
github.com/apache/camel-k/pkg/controller/integrationkit.(*buildAction).Handle
        github.com/apache/camel-k@/pkg/controller/integrationkit/build.go:57
github.com/apache/camel-k/pkg/controller/integrationkit.(*ReconcileIntegrationKit).Reconcile
        github.com/apache/camel-k@/pkg/controller/integrationkit/integrationkit_controller.go:228
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
        k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
        k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:88
runtime.goexit
        runtime/asm_amd64.s:1357

github.com/go-logr/zapr.(*zapLogger).Error
        github.com/go-logr/zapr@v0.1.1/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
        k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
        k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:88'

**Comment by nicolaferraro** [comment]
Hi, there are some inconsistencies in the command you've provided and probably in the resources that are installed in the cluster.

`kamel install --cluster-setup` does not install the operator, but only the "cluster-wide" resources, such as CRDs, roles and bindings. So the operator has been installed by other means and probably the version does not match the version of the CRDs installed on the cluster.

Can you try to delete all `camel.apache.org` CRDs and install them + the operator at the same version?

**Comment by shanisma** [comment]
Hello, 

In order I did:

❯ k delete crd builds.camel.apache.org
❯ k delete crd camelcatalogs.camel.apache.org
❯ k delete crd integrationkits.camel.apache.org
❯ k delete crd integrationplatforms.camel.apache.org
❯ k delete crd integrations.camel.apache.org
❯ k delete ns kamel
❯ k create ns kamel

❯ kamel install --cluster-setup
❯ kamel install --registry-insecure --registry <registry url> --registry-auth-password <password> --registry-auth-username <username> --maven-repository http://repository.apache.org/content/groups/snapshots-group@id\=apache@snapshots@noreleases

❯ kn kamel
Context "<context>" modified.
Active namespace is "kamel".

❯ k get po
NAME                                READY   STATUS    RESTARTS   AGE
camel-k-operator-5985c6f7fd-cf5h9   1/1     Running   0          6s

❯ echo "from('timer:tick?period=3000')
dquote>   .setBody().constant('Hello world from Camel K')
dquote>   .to('log:info')"> hello.groovy

# stuck in this phase
❯ kamel run hello.groovy --dev
integration "hello" created
Condition "IntegrationPlatformAvailable" is "True" for Integration hello: camel-k
Integration hello in phase "Initialization"
Condition "IntegrationKitAvailable" is "False" for Integration hello: creating a new integration kit
Integration hello in phase "Building Kit"
Integration hello subresource kit-btcvo67a6dohuhq8oi80 (Integration Kit) changed phase to "Build Submitted"
Progress: integration "hello" in phase Initialization
Progress: integration "hello" in phase Building Kit

❯ k get ik
NAME                       PHASE             TYPE       IMAGE
kit-btcvo67a6dohuhq8oi80   Build Submitted   platform  

❯ k describe ik/kit-btcvo67a6dohuhq8oi80
Name:         kit-btcvo67a6dohuhq8oi80
Namespace:    kamel
Labels:       camel.apache.org/created.by.kind=Integration
              camel.apache.org/created.by.name=hello
              camel.apache.org/created.by.version=313604762
              camel.apache.org/kit.type=platform
              camel.apache.org/runtime.provider=main
              camel.apache.org/runtime.version=1.4.1
Annotations:  <none>
API Version:  camel.apache.org/v1
Kind:         IntegrationKit
Metadata:
  Creation Timestamp:  2020-09-10T10:12:40Z
  Generation:          1
  Resource Version:    313604769
  Self Link:           /apis/camel.apache.org/v1/namespaces/kamel/integrationkits/kit-btcvo67a6dohuhq8oi80
  UID:                 035ba4fd-8064-4d79-8de1-0b790f67ee93
Spec:
  Dependencies:
    camel:log
    camel:timer
    mvn:org.apache.camel.k/camel-k-loader-groovy
    mvn:org.apache.camel.k/camel-k-runtime-main
Status:
  Conditions:
    Last Transition Time:  2020-09-10T10:12:40Z
    Last Update Time:      2020-09-10T10:12:40Z
    Message:               IntegrationPlatform (camel-k)
    Reason:                IntegrationPlatformAvailable
    Status:                True
    Type:                  IntegrationPlatformAvailable
  Digest:                  vAD6Yapbidv510tlxOx4l9Z5z3WkFcymcy95KEKNLyxc
  Phase:                   Build Submitted
  Platform:                camel-k
  Runtime Provider:        main
  Runtime Version:         1.4.1
  Version:                 1.1.0
Events:
  Type     Reason                      Age                From                                Message
  ----     ------                      ----               ----                                -------
  Normal   IntegrationKitPhaseUpdated  54s                camel-k-integration-kit-controller  Integration Kit kit-btcvo67a6dohuhq8oi80 in phase "Build Submitted"
  Warning  IntegrationKitError         7s (x14 over 54s)  camel-k-integration-kit-controller  Cannot reconcile Integration Kit kit-btcvo67a6dohuhq8oi80: cannot create build: Build.camel.apache.org "kit-btcvo67a6dohuhq8oi80" is invalid: type: Required value



❯ k logs po/camel-k-operator-5985c6f7fd-cf5h9 

{"level":"info","ts":1599732808.8930442,"logger":"camel-k.trait","msg":"Apply trait: init"}
{"level":"info","ts":1599732808.8930545,"logger":"camel-k.trait","msg":"Apply trait: camel"}
{"level":"info","ts":1599732808.893602,"logger":"camel-k.trait","msg":"Apply trait: builder"}
{"level":"error","ts":1599732808.9012918,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"integrationkit-controller","request":"kamel/kit-btcvo67a6dohuhq8oi80","error":"cannot create build: Build.camel.apache.org \"kit-btcvo67a6dohuhq8oi80\" is invalid: type: Required value","errorVerbose":"Build.camel.apache.org \"kit-btcvo67a6dohuhq8oi80\" is invalid: type: Required value\ncannot create build\ngithub.com/apache/camel-k/pkg/controller/integrationkit.(*buildAction).handleBuildSubmitted\n\tgithub.com/apache/camel-k@/pkg/controller/integrationkit/build.go:112\ngithub.com/apache/camel-k/pkg/controller/integrationkit.(*buildAction).Handle\n\tgithub.com/apache/camel-k@/pkg/controller/integrationkit/build.go:57\ngithub.com/apache/camel-k/pkg/controller/integrationkit.(*ReconcileIntegrationKit).Reconcile\n\tgithub.com/apache/camel-k@/pkg/controller/integrationkit/integrationkit_controller.go:228\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:88\nruntime.goexit\n\truntime/asm_amd64.s:1357","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1599732849.861622,"logger":"camel-k.controller.integrationkit","msg":"Reconciling IntegrationKit","request-namespace":"kamel","request-name":"kit-btcvo67a6dohuhq8oi80"}
{"level":"info","ts":1599732849.8617609,"logger":"camel-k.controller.integrationkit","msg":"Invoking action build-submitted","request-namespace":"kamel","request-name":"kit-btcvo67a6dohuhq8oi80","api-version":"camel.apache.org/v1","kind":"IntegrationKit","ns":"kamel","name":"kit-btcvo67a6dohuhq8oi80"}
{"level":"info","ts":1599732849.8621068,"logger":"camel-k.trait","msg":"Apply trait: init"}
{"level":"info","ts":1599732849.8621185,"logger":"camel-k.trait","msg":"Apply trait: camel"}
{"level":"info","ts":1599732849.8628836,"logger":"camel-k.trait","msg":"Apply trait: builder"}
{"level":"error","ts":1599732849.8708012,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"integrationkit-controller","request":"kamel/kit-btcvo67a6dohuhq8oi80","error":"cannot create build: Build.camel.apache.org \"kit-btcvo67a6dohuhq8oi80\" is invalid: type: Required value","errorVerbose":"Build.camel.apache.org \"kit-btcvo67a6dohuhq8oi80\" is invalid: type: Required value\ncannot create build\ngithub.com/apache/camel-k/pkg/controller/integrationkit.(*buildAction).handleBuildSubmitted\n\tgithub.com/apache/camel-k@/pkg/controller/integrationkit/build.go:112\ngithub.com/apache/camel-k/pkg/controller/integrationkit.(*buildAction).Handle\n\tgithub.com/apache/camel-k@/pkg/controller/integrationkit/build.go:57\ngithub.com/apache/camel-k/pkg/controller/integrationkit.(*ReconcileIntegrationKit).Reconcile\n\tgithub.com/apache/camel-k@/pkg/controller/integrationkit/integrationkit_controller.go:228\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:88\nruntime.goexit\n\truntime/asm_amd64.s:1357","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:88"}


error : 'cannot create build: Build.camel.apache.org "kit-btcvo67a6dohuhq8oi80" is invalid: type: Required value'

errorVerbose:
Build.camel.apache.org "kit-btcvo67a6dohuhq8oi80" is invalid: type: Required value
cannot create build
github.com/apache/camel-k/pkg/controller/integrationkit.(*buildAction).handleBuildSubmitted
        github.com/apache/camel-k@/pkg/controller/integrationkit/build.go:112
github.com/apache/camel-k/pkg/controller/integrationkit.(*buildAction).Handle
        github.com/apache/camel-k@/pkg/controller/integrationkit/build.go:57
github.com/apache/camel-k/pkg/controller/integrationkit.(*ReconcileIntegrationKit).Reconcile
        github.com/apache/camel-k@/pkg/controller/integrationkit/integrationkit_controller.go:228
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
        k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
        k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:88
runtime.goexit
        runtime/asm_amd64.s:1357

stacktrace:
github.com/go-logr/zapr.(*zapLogger).Error
        github.com/go-logr/zapr@v0.1.1/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
        k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
        k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:88

**Comment by nicolaferraro** [comment]
Can you also provide some more info about your Kube platform?

**Comment by shanisma** [comment]
Hello I tested new  crd ... not working :( same issue.

Here kubernetes version : K8s Rev: v1.16.6  

A RKE cluster...

**Comment by squakez** [comment]
Please retest with latest Camel K version, and reopen if it is still an error.
