### ISSUE TITLE
Camel K installed globally by default

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1693]
We should move towards a vision where Camel K Integrations are resources that anyone can use in a cluster, just like Deployments.
A cluster admin installs Camel K in a cluster and anybody can use it. 

This can be achieved by:

1) Changing the installation mode

- Helm: install the operator in the "camel-system" namespace by default
- OLM: use global installation by default and the "operatorframework.io/suggested-namespace" annotation to install operator in "camel-system"
- kamel install: default it to global in the "camel-system" namespace

2) Improving builds

One of the major drawbacks of global installation is that builds don't use maven caches and they are much slower.
We need to work on that strategy to build globally and reuse integration kits across namespaces.

3) Troubleshooting

Improve events to make sure that people who can't access "camel-system" can get notified about what's actually going wrong and how to fix it.
This include signalling issues with configuration, especially on Kubernetes.

Wdyt?
@lburgazzoli , @astefanutti

**Comment by lburgazzoli** [comment]
I think we also need to have some segregation policies so admins can control who can see what

**Comment by astefanutti** [comment]
I think we can close this and follow-up the discussion in #1799.
