### ISSUE TITLE
Kamel init - Do not include license header

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#1696]
The `kamel init Foo.java` command generates source code that has an ASF license header.

But since this is for end users and they may use other licenses or none at all, then we should generally not include a header out of the box. This also makes the code smaller and leaner and quicker to overview and understand.

This applies also to the other languages it can generate for like groovy, kotlin, xml etc.

**Comment by nicolaferraro** [comment]
Already fixed.
