### ISSUE TITLE
can't run hello.java,maybe somethings wrong with registry

### ISSUE THREAD

**Issue by w-j-d** [apache/camel-k#1699]
Camel-k Install command-line:

./kamel install --registry docker.io --organization XXXXXXorg --registry-auth-username XXXXX --registry-auth-password XXXX -n camel-k --maven-settings=configmap:maven-settings/settings.xml --build-timeout 12h   --cluster-type kubernetes

./kamel init Hello.java
./kamel run Hello.java -n camel-k --dev

then:

```
integration "hello" created
Progress: integration "hello" in phase Initialization
Condition "IntegrationPlatformAvailable" is "True" for Integration hello: camel-k
Integration hello in phase "Initialization"
Progress: integration "hello" in phase Building Kit
Integration hello in phase "Building Kit"
Condition "IntegrationKitAvailable" is "False" for Integration hello: creating a new integration kit
Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Integration Kit) changed phase to "Build Submitted"
Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Scheduling"
Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Pending"
Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Running"
Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Integration Kit) changed phase to "Build Running"
Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Failed"
Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Initialization" (recovery 1 of 5)
Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Scheduling" (recovery 1 of 5)
Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Pending" (recovery 1 of 5)
Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Running" (recovery 1 of 5)
Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Failed" (recovery 1 of 5)
(combined from similar events): Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Initialization" (recovery 2 of 5)
(combined from similar events): Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Scheduling" (recovery 2 of 5)
Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Scheduling" (recovery 2 of 5)
(combined from similar events): Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Pending" (recovery 2 of 5)
(combined from similar events): Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Running" (recovery 2 of 5)
(combined from similar events): Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Failed" (recovery 2 of 5)
(combined from similar events): Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Initialization" (recovery 3 of 5)
(combined from similar events): Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Scheduling" (recovery 3 of 5)
(combined from similar events): Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Pending" (recovery 3 of 5)
(combined from similar events): Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Running" (recovery 3 of 5)
(combined from similar events): Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Failed" (recovery 3 of 5)
(combined from similar events): Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Initialization" (recovery 4 of 5)
(combined from similar events): Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Scheduling" (recovery 4 of 5)
(combined from similar events): Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Pending" (recovery 4 of 5)
(combined from similar events): Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Running" (recovery 4 of 5)
(combined from similar events): Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Failed" (recovery 4 of 5)
(combined from similar events): Integration hello subresource kit-btdjjqfugpq87eqj57t0 (Build) changed phase to "Initialization" (recovery 5 of 5)
Progress: integration "hello" in phase Error
Error: integration "hello" deployment failed
```

**Comment by w-j-d** [comment]
pod logs:

[INFO] Downloaded from alimaven: http://maven.aliyun.com/nexus/content/groups/public/com/vdurmont/semver4j/3.1.0/semver4j-3.1.0.jar (27 kB at 6.3 kB/s)

[INFO] Downloaded from alimaven: http://maven.aliyun.com/nexus/content/groups/public/com/google/guava/guava/20.0/guava-20.0.jar (2.4 MB at 551 kB/s)

[INFO] Downloaded from alimaven: http://maven.aliyun.com/nexus/content/groups/public/org/jboss/jandex/2.2.1.Final/jandex-2.2.1.Final.jar (201 kB at 45 kB/s)

[INFO] Downloaded from alimaven: http://maven.aliyun.com/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar (169 kB at 38 kB/s)

[INFO] Downloaded from alimaven: http://maven.aliyun.com/nexus/content/groups/public/com/squareup/javapoet/1.11.1/javapoet-1.11.1.jar (99 kB at 22 kB/s)

[INFO] ------------------------------------------------------------------------

[INFO] BUILD SUCCESS

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 01:10 min

[INFO] Finished at: 2020-09-11T08:56:13Z

[INFO] ------------------------------------------------------------------------

{"level":"info","ts":1599814573.4560225,"logger":"camel-k.builder","msg":"step done in 71.726598 seconds","step":"github.com/apache/camel-k/pkg/builder/runtime/ComputeDependencies","phase":20,"name":"kit-btdjjqfugpq87eqj57t0","task":"builder"}

{"level":"info","ts":1599814573.4560711,"logger":"camel-k.builder","msg":"executing step","step":"github.com/apache/camel-k/pkg/builder/IncrementalImageContext","phase":30,"name":"kit-btdjjqfugpq87eqj57t0","task":"builder"}

{"level":"info","ts":1599814573.4709873,"logger":"camel-k.builder","msg":"step done in 0.014901 seconds","step":"github.com/apache/camel-k/pkg/builder/IncrementalImageContext","phase":30,"name":"kit-btdjjqfugpq87eqj57t0","task":"builder"}

{"level":"info","ts":1599814573.4710214,"logger":"camel-k.builder","msg":"dependencies: [camel:log camel:timer mvn:org.apache.camel.k/camel-k-loader-java mvn:org.apache.camel.k/camel-k-runtime-main]"}

{"level":"info","ts":1599814573.4710348,"logger":"camel-k.builder","msg":"artifacts: [org.apache.camel:camel-log:jar:3.4.0 org.apache.camel:camel-support:jar:3.4.0 org.apache.camel:camel-api:jar:3.4.0 org.apache.camel:camel-management-api:jar:3.4.0 org.apache.camel:camel-util:jar:3.4.0 org.slf4j:slf4j-api:jar:1.7.30 org.apache.camel:camel-timer:jar:3.4.0 org.apache.camel.k:camel-k-loader-java:jar:1.4.1 org.apache.camel.k:camel-k-runtime-core:jar:1.4.1 org.apache.camel:camel-core-languages:jar:3.4.0 org.apache.camel:camel-endpointdsl:jar:3.4.0 org.apache.camel:camel-core-engine:jar:3.4.0 org.apache.camel:camel-base:jar:3.4.0 org.jooq:joor:jar:0.9.13 org.apache.camel.k:camel-k-runtime-main:jar:1.4.1 org.apache.camel:camel-main:jar:3.4.0 org.apache.camel:camel-bean:jar:3.4.0 org.apache.logging.log4j:log4j-core:jar:2.13.3 org.apache.logging.log4j:log4j-api:jar:2.13.3 org.apache.logging.log4j:log4j-slf4j-impl:jar:2.13.3]"}

{"level":"info","ts":1599814573.4710484,"logger":"camel-k.builder","msg":"artifacts selected: [org.apache.camel:camel-log:jar:3.4.0 org.apache.camel:camel-support:jar:3.4.0 org.apache.camel:camel-api:jar:3.4.0 org.apache.camel:camel-management-api:jar:3.4.0 org.apache.camel:camel-util:jar:3.4.0 org.slf4j:slf4j-api:jar:1.7.30 org.apache.camel:camel-timer:jar:3.4.0 org.apache.camel.k:camel-k-loader-java:jar:1.4.1 org.apache.camel.k:camel-k-runtime-core:jar:1.4.1 org.apache.camel:camel-core-languages:jar:3.4.0 org.apache.camel:camel-endpointdsl:jar:3.4.0 org.apache.camel:camel-core-engine:jar:3.4.0 org.apache.camel:camel-base:jar:3.4.0 org.jooq:joor:jar:0.9.13 org.apache.camel.k:camel-k-runtime-main:jar:1.4.1 org.apache.camel:camel-main:jar:3.4.0 org.apache.camel:camel-bean:jar:3.4.0 org.apache.logging.log4j:log4j-core:jar:2.13.3 org.apache.logging.log4j:log4j-api:jar:2.13.3 org.apache.logging.log4j:log4j-slf4j-impl:jar:2.13.3]"}

{"level":"info","ts":1599814573.47107,"logger":"camel-k.builder","msg":"base image: adoptopenjdk/openjdk11:slim"}

{"level":"info","ts":1599814573.4710739,"logger":"camel-k.builder","msg":"resolved base image: adoptopenjdk/openjdk11:slim"}

{"level":"info","ts":1599814573.4710774,"logger":"camel-k.builder","msg":"resolved image: "}

{"level":"info","ts":1599814573.473236,"logger":"camel-k.builder","msg":"Patch not applied (no difference)"}

**Comment by nicolaferraro** [comment]
Can you try adding `--build-publish-strategy=Spectrum` to `kamel install`, it usually solves a lot of issues.

Then `kamel reset` and retry.
With "Spectrum", you'll find logs about what's happening directly in the operator pod.

**Comment by w-j-d** [comment]
thank you,I will try it!

**Comment by w-j-d** [comment]
spectrum - 2020/09/11 10:48:41 Composing layers...

spectrum - 2020/09/11 10:48:41 Pushing image docker.io/office602org/camel-k-kit-btdl9p3r4smi8mn5l4l0:2174943 (insecure=true)...

{"level":"info","ts":1599821329.5719368,"logger":"camel-k.builder","msg":"step failed with error: Head https://index.docker.io/v2/office602org/camel-k-kit-btdl9p3r4smi8mn5l4l0/blobs/sha256:6de1a9cecd4603db2034d7a4779017912e9638454a4ea499e8257f4176bfd0b2: stopped after 10 redirects","step":"github.com/apache/camel-k/pkg/builder/spectrum/Publisher","phase":40,"name":"kit-btdl9p3r4smi8mn5l4l0","task":"builder"}

**Comment by w-j-d** [comment]
docker.io after create user,have need to do something else?

**Comment by nicolaferraro** [comment]
I see docker hub is doing something strange: `stopped after 10 redirects`

Ideas @astefanutti , @lburgazzoli ?

**Comment by w-j-d** [comment]
./kamel install --registry docker.io --organization office602org --registry-auth-username office602 --registry-auth-password ****** -n camel-k --maven-settings=configmap:maven-settings/settings.xml --build-timeout 12h   --cluster-type kubernetes  --registry-insecure  true --force  --build-publish-strategy=Spectrum

**Comment by nicolaferraro** [comment]
> docker.io after create user,have need to do something else?

Are you using your own user ID as `--organization` parameter? or also an organization for which you have write access should be ok. Nothing else should be needed.

Which kubernetes env are you using?

**Comment by nicolaferraro** [comment]
> ./kamel install --registry docker.io --organization office602org --registry-auth-username office602 --registry-auth-password ****** -n camel-k --maven-settings=configmap:maven-settings/settings.xml --build-timeout 12h --cluster-type kubernetes --registry-insecure true --force --build-publish-strategy=Spectrum

Probably you should not set `--registry-insecure true`, docker is secure. That's why you may get the redirects.

**Comment by w-j-d** [comment]
![image](https://user-images.githubusercontent.com/52056489/92918108-b726cd80-f461-11ea-8f68-41656ffb0cf4.png)

**Comment by w-j-d** [comment]
only kubenetes,not minikube

**Comment by w-j-d** [comment]
I use kubesphere,it is like minikube

**Comment by w-j-d** [comment]
https://kubesphere.io/

**Comment by w-j-d** [comment]
./kamel install --registry docker.io  --registry-auth-username office602 --registry-auth-password epri@1025 -n camel-k --maven-settings=configmap:maven-settings/settings.xml --build-timeout 12h   --cluster-type kubernetes    --build-publish-strategy=Spectrum

**Comment by w-j-d** [comment]
./kamel install --registry docker.io  --registry-auth-username office602 --registry-auth-password ***** -n camel-k --maven-settings=configmap:maven-settings/settings.xml --build-timeout 12h   --cluster-type kubernetes    --build-publish-strategy=Spectrum

**Comment by w-j-d** [comment]
spectrum - 2020/09/11 11:13:18 Pulling base image adoptopenjdk/openjdk11:slim (insecure=false)...

spectrum - 2020/09/11 11:13:18 No matching credentials were found, falling back on anonymous

spectrum - 2020/09/11 11:13:23 Composing layers...

spectrum - 2020/09/11 11:13:23 Pushing image docker.io/camel-k/camel-k-kit-btdln38c8068mibhvbjg:2182394 (insecure=false)...

{"level":"info","ts":1599822811.2376115,"logger":"camel-k.builder","msg":"step failed with error: HEAD https://index.docker.io/v2/camel-k/camel-k-kit-btdln38c8068mibhvbjg/blobs/sha256:f08d8e2a3ba11bea23cf5c17e8e1c620057412ed05c32d1114640e18d6dd0a43: unsupported status code 401","step":"github.com/apache/camel-k/pkg/builder/spectrum/Publisher","phase":40,"name":"kit-btdln38c8068mibhvbjg","task":"builder"}

**Comment by w-j-d** [comment]
{"level":"info","ts":1599826868.3883812,"logger":"camel-k","msg":"could not find any knative type in namespace camel-k, last error was: services.serving.knative.dev is forbidden: User \"system:serviceaccount:camel-k:camel-k-operator\" cannot list resource \"services\" in API group \"serving.knative.dev\" in the namespace \"camel-k\""}
{

**Comment by nicolaferraro** [comment]
> ./kamel install --registry docker.io --registry-auth-username office602 --registry-auth-password ***** -n camel-k --maven-settings=configmap:maven-settings/settings.xml --build-timeout 12h --cluster-type kubernetes --build-publish-strategy=Spectrum

I think you forgot the `--organization` option. By default Camel K uses the kube namespace as organization (works with local registries).

**Comment by w-j-d** [comment]
knative need installed?

**Comment by nicolaferraro** [comment]
> knative need installed?

No, it's just an info message. Knative is optional.

**Comment by w-j-d** [comment]
thks,it's ok,because I am from china can't direct to visit docker.io, I need modify /etc/hosts

**Comment by abogatov** [comment]
Hi @w-j-d,
did you manage to solve it problem?
