### ISSUE TITLE
Does camel-k plan to provide Java SDK client Calls?

### ISSUE THREAD

**Issue by w-j-d** [apache/camel-k#1708]
If it can be called through the SDK mode, it is more convenient to integrate than the command line mode.

**Comment by lburgazzoli** [comment]
what do you mean ?

**Comment by w-j-d** [comment]
It will  be replace the ServiceMIx

**Comment by lburgazzoli** [comment]
btw, we have https://camel.zulipchat.com for general discussions

**Comment by w-j-d** [comment]
OK
