### ISSUE TITLE
Ability to set labels on knative service (for things like "cluster-local")

### ISSUE THREAD

**Issue by makandre** [apache/camel-k#1712]
For `from("knative:type/name")` routes, we need ability to configure it so that the knative service that it creates would have certain labels. Particularly, need a way to apply `serving.knative.dev/visibility=cluster-local` label so my service would not be exposed publicly.

**Comment by makandre** [comment]
Workaround suggested by @nicolaferraro is to run with `--label serving.knative.dev/visibility=cluster-local -t owner.target-labels=serving.knative.dev/visibility`

**Comment by vassilvk** [comment]
@makandre, as a workaround you can create a [KubeMod](https://github.com/kubemod/kubemod) `ModRule` to intercept the service as is being created by the operator and inject the necessary labels.

**Comment by halmakidon** [comment]
This feature was released in v1.10.0.
https://camel.apache.org/releases/k-1.10.0/
> [#3546](https://github.com/apache/camel-k/pull/3546) Feat(trait): Knative service visibility support

Can someone please close this issue if possible?

**Comment by squakez** [comment]
Sure, thanks for reporting!
