### ISSUE TITLE
Document installation on air-gapped clusters

### ISSUE THREAD

**Issue by orthoxerox** [apache/camel-k#1721]
Probably blocked by #1424 

The documentation would benefit from enumerating installation options that are required to make Camel K work on a cluster that has no access to the internet and can only reach custom Maven and Docker repositories with certificates signed by an enterprise CA (or self-signed).

**Comment by arthurdm** [comment]
+1 to this item.  It would be very helpful to have this doc.  Is air gap possible today, just not documented?

**Comment by arthurdm** [comment]
hi @nicolaferraro - do you know if this is already possible today, or are there changes required to achieve this?

**Comment by nicolaferraro** [comment]
> hi @nicolaferraro - do you know if this is already possible today, or are there changes required to achieve this?

It's technically possible to achieve this. The CA part is a bit more complex because it requires a custom operator image to inject the custom company certificates, everything else should be configurable upon installation

**Comment by orthoxerox** [comment]
any comment

**Comment by squakez** [comment]
I wonder if it would be enough to use `kamel install --registry ... --maven ... -o yaml > offline-installer.yaml`, export the output and apply on any other cluster via `kubect apply -f offline-installer.yaml`. We'd need to let `kamel install -o yaml` work in offline mode, but that is certainly feasible to do.

**Comment by orthoxerox** [comment]
any comment

**Comment by squakez** [comment]
Same as #4118, closing.
