### ISSUE TITLE
Property placeholder conflict in groovy

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#173]
Looks like simple language e.g. `.transform().simple("aaa ${body}")` conflicts with property resolution when using groovy.

**Comment by lburgazzoli** [comment]
You should use plain strings ```''``` as ```""``` is a GString and every value with ${} or $ is interpolated:

    .transform().simple('aaa ${body}')

**Comment by nicolaferraro** [comment]
Yes, I figured out it later.. but better to have this explanation here for the future..

**Comment by davsclaus** [comment]
Also you can use `$simple{body}` style in Camel

**Comment by nicolaferraro** [comment]
I think it's not working.. that was one of my tests, it complains on the `simple` variable missing..

**Comment by davsclaus** [comment]
Ah darn - bad James for creating both groovy and camel with that same syntax ;)
