### ISSUE TITLE
Add a cli subcommand to inspect dependencies required by an Integration

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#1738]
Something like:

    kamel inspect MyIntegration.java

That could ouput a json document listing the dependencies an integration requries

**Comment by doru1004** [comment]
Sounds great! This would be a very useful feature to have.
Would this command be able to support an option that would print all transitive dependencies also? Something like:

```
kamel inspect -transitive-dependencies Integration.java
```

**Comment by doru1004** [comment]
The patch for outputting all the transitive dependencies is now available: https://github.com/apache/camel-k/pull/1777

**Comment by astefanutti** [comment]
I think it's been fixed with #1777 and #2048.
