### ISSUE TITLE
Generate OLM Bundle

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#1743]
OLM has introduced a new _bundle_ format, deprecating the previous _package manifests_.

Following up #1741, the Operator SDK CLI exposes a new `generate bundle` command that generates the OLM bundle for an operator project. The convention is to use the `kustomize` CLI to assemble the resources, instead of relying on a configuration file, as it used to be for generating package manifests.

**Comment by phantomjinx** [comment]
- https://v1-0-x.sdk.operatorframework.io/docs/olm-integration/quickstart-bundle/
- https://v1-0-x.sdk.operatorframework.io/docs/olm-integration/quickstart-package-manifests/
- https://v1-0-x.sdk.operatorframework.io/docs/olm-integration/quickstart-bundle/

**Comment by astefanutti** [comment]
Let's close this one and track further work in #1820.
