### ISSUE TITLE
Binary resources such as keystores are being corrupted

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1750]
Doing:

```
kamel run TLS.java --resource trust.jks
```

The sha256sum of the `trust.jsk` file in the container is different from the original one, which means something has corrupted it.

Workaround is:

```
kubectl create secret generic trust --from-file trust.jks
kamel run TLS.java --secret trust
```

Which is also a best practice for such data, but this problem may cause other issues.

Tested on: https://self-signed.badssl.com/

**Comment by rampraveen83** [comment]
Tried with v 1.2, and jks files are still getting corrupted. Compared the file size and its different when bundled with camel 
e.g kamel run kafka.java --resource keystore.jks --resource truststore.jks

Caused by: java.io.IOException: Invalid keystore format

**Comment by nicolaferraro** [comment]
This is strange, as binary resources are base64 encoded.

@rampraveen83 can you try with:

```shell
kamel run kafka.java --resource keystore.jks --resource truststore.jks --compression=true
```

Compression is the mechanism that we tried to auto-enable on 1.2 to avoid corruption.
Also, can you double check the version with `kamel version`?
