### ISSUE TITLE
Ability to configure PodDisruptionBudget for integrations

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#1760]
To improve high-availability of integrations, the Camel K operator should provide the ability to create PodDisruptionBudget resources for integration pods:

https://kubernetes.io/docs/tasks/run-application/configure-pdb/

Open points:

- [ ] Where should the PodDisruptionBudget configuration be exposed? Should it be exposed by a dedicated trait, or grouped into a more general _scheduling_ or _pod_ trait?
- [ ] Make sure it is compatible with all the deployment strategies: Deployment, Knative Service and CronJob?

**Comment by mmelko** [comment]
I will look at this.

**Comment by mmelko** [comment]
#1787 This is what I have so far. PDB is created for every integration and deleted with integration. I decided to go with new trait for the PDB but I can refactor if necessary.

I still need to create test for the trait and also I'm not sure if `IntegrationRunning` phase is the best here.
