### ISSUE TITLE
Camel K on GKE doesn't seem to work

### ISSUE THREAD

**Issue by nicolasduminil** [apache/camel-k#1770]
Hello,
I've installed by following this guide: https://camel.apache.org/camel-k/latest/installation/gke.html.
Then, I tried to run the basic, as follows:

    kamel run Basic.java --dev
    integration "basic" created
    Progress: integration "basic" in phase Initialization
    Integration basic in phase "Initialization"
    Progress: integration "basic" in phase Building Kit
    Condition "IntegrationPlatformAvailable" is "True" for Integration basic: camel-k
    Integration basic in phase "Building Kit"
    Condition "IntegrationKitAvailable" is "False" for Integration basic: creating a new integration kit

And here I'm stuck as nothing happens. Not sure what I'm supposed to do with that. Please help.
Many thanks in advance.
Kind regards,
Nicolas

**Comment by nicolasduminil** [comment]
Anyone please ?

**Comment by nicolaferraro** [comment]
> Hello,
> I've installed by following this guide: https://camel.apache.org/camel-k/latest/installation/gke.html.
> Then, I tried to run the basic, as follows:
> 
> ```
> kamel run Basic.java --dev
> integration "basic" created
> Progress: integration "basic" in phase Initialization
> Integration basic in phase "Initialization"
> Progress: integration "basic" in phase Building Kit
> Condition "IntegrationPlatformAvailable" is "True" for Integration basic: camel-k
> Integration basic in phase "Building Kit"
> Condition "IntegrationKitAvailable" is "False" for Integration basic: creating a new integration kit
> ```
> 
> And here I'm stuck as nothing happens. Not sure what I'm supposed to do with that. Please help.
> Many thanks in advance.
> Kind regards,
> Nicolas

Did you follow specific instructions also for the registry?  https://camel.apache.org/camel-k/latest/installation/registry/gcr.html

**Comment by nicolasduminil** [comment]
Yes, I did

    kubectl get integrationplatform
    NAME      PHASE
    camel-k   Ready

    kubectl get secret
    NAME                           TYPE                                  DATA   AGE
    camel-k-builder-token-cphxm    kubernetes.io/service-account-token   3      26m
    camel-k-operator-token-ccbdj   kubernetes.io/service-account-token   3      26m
    camel-k-operator-token-tvknm   kubernetes.io/service-account-token   3      30m
    default-token-r8p5b            kubernetes.io/service-account-token   3      30m

    kubectl get pod
    NAME                                READY   STATUS    RESTARTS   AGE
    camel-k-operator-5c64758759-8x86x   1/1     Running   0          35m

**Comment by nicolaferraro** [comment]
> Yes, I did
> 
> ```
> kubectl get integrationplatform
> NAME      PHASE
> camel-k   Ready
> 
> kubectl get secret
> NAME                           TYPE                                  DATA   AGE
> camel-k-builder-token-cphxm    kubernetes.io/service-account-token   3      26m
> camel-k-operator-token-ccbdj   kubernetes.io/service-account-token   3      26m
> camel-k-operator-token-tvknm   kubernetes.io/service-account-token   3      30m
> default-token-r8p5b            kubernetes.io/service-account-token   3      30m
> 
> kubectl get pod
> NAME                                READY   STATUS    RESTARTS   AGE
> camel-k-operator-5c64758759-8x86x   1/1     Running   0          35m
> ```

Can you provide output of:

```
kubectl get integrationplatform -o yaml
```

and:

```
kubectl logs camel-k-operator-5c64758759-8x86x
```

**Comment by nicolasduminil** [comment]
Sure:

    nicolas@nicolas-XPS-15-9570:~/camel-k-examples/01-basic$ kubectl get integrationplatform -o yaml
    apiVersion: v1
    items:
    - apiVersion: camel.apache.org/v1
      kind: IntegrationPlatform
      metadata:
        creationTimestamp: "2020-10-15T16:29:26Z"
        generation: 1
        labels:
          app: camel-k
        name: camel-k
        namespace: camel-basic
        resourceVersion: "1286986"
        selfLink: /apis/camel.apache.org/v1/namespaces/camel-basic/integrationplatforms/camel-k
        uid: b7aaec12-fb86-420e-a3e9-eec14f5b3256
      spec:
        build:
          maven:
            settings: {}
          registry:
            address: gcr.io
            organization: marko-luksa-book
            secret: kaniko-secret
        resources: {}
      status:
        build:
          baseImage: adoptopenjdk/openjdk11:slim
          buildStrategy: pod
          maven:
            localRepository: /tmp/artifacts/m2
            settings:
              configMapKeyRef:
                key: settings.xml
                name: camel-k-maven-settings
            timeout: 3m45s
          persistentVolumeClaim: camel-k
          publishStrategy: Buildah
          registry:
            address: gcr.io
            organization: marko-luksa-book
            secret: kaniko-secret
          runtimeVersion: 1.4.1
          timeout: 5m0s
        cluster: Kubernetes
        phase: Ready
        version: 1.1.1
    kind: List
    metadata:
      resourceVersion: ""
      selfLink: ""

    kubectl logs camel-k-operator-5c64758759-8x86x | more
    {"level":"info","ts":1602779122.7708209,"logger":"cmd","msg":"Go Version: go1.14.7"}
    {"level":"info","ts":1602779122.771104,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
    {"level":"info","ts":1602779122.7711782,"logger":"cmd","msg":"Operator SDK Version: v0.17.1"}
    {"level":"info","ts":1602779122.7712398,"logger":"cmd","msg":"Buildah Version: 1.14.0"}
    {"level":"info","ts":1602779122.7712998,"logger":"cmd","msg":"Kaniko Version: 0.17.1"}
    {"level":"info","ts":1602779122.7713506,"logger":"cmd","msg":"Camel K Operator Version: 1.1.1"}
    {"level":"info","ts":1602779122.771417,"logger":"cmd","msg":"Camel K Default Runtime Version: 1.4.1"}
    {"level":"info","ts":1602779122.7714822,"logger":"cmd","msg":"Camel K Git Commit: 75cdfa0c4d71fe3022fdaff7d39585875509beb7"}
    {"level":"info","ts":1602779122.7717433,"logger":"leader","msg":"Trying to become the leader."}
    {"level":"info","ts":1602779123.402134,"logger":"leader","msg":"No pre-existing lock was found."}
    {"level":"info","ts":1602779123.4140332,"logger":"leader","msg":"Became the leader."}
    {"level":"info","ts":1602779124.700966,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
    {"level":"info","ts":1602779124.7014265,"logger":"cmd","msg":"Registering Components."}
    {"level":"info","ts":1602779124.7098584,"logger":"cmd","msg":"Cannot detect user cluster role: skipping."}
    {"level":"info","ts":1602779124.7140436,"logger":"cmd","msg":"Starting the Cmd."}
    {"level":"info","ts":1602779124.714422,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
    {"level":"info","ts":1602779124.7148936,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"build-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1602779124.7152061,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"integration-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1602779124.715461,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"integrationkit-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1602779124.7156723,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"integrationplatform-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1602779124.8155446,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"integration-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1602779124.8162408,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"integrationplatform-controller"}
    {"level":"info","ts":1602779125.0152614,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"build-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1602779125.0160916,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"integration-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1602779125.016125,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"integration-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1602779125.0162377,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"integrationkit-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1602779125.0162742,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"integrationkit-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1602779125.0162866,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"integrationkit-controller"}
    {"level":"info","ts":1602779125.0163245,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"integrationplatform-controller","worker count":1}
    {"level":"info","ts":1602779125.115765,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"build-controller"}
    {"level":"info","ts":1602779125.1160297,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"build-controller","worker count":1}
    {"level":"info","ts":1602779125.1162815,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"integration-controller","source":"kind source: /, Kind="}
    {"level":"info","ts":1602779125.1166108,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"integrationkit-controller","worker count":1}
    {"level":"info","ts":1602779125.2175317,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"integration-controller"}
    {"level":"info","ts":1602779125.2178118,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"integration-controller","worker count":1}
    "level":"info","ts":1602779366.9630513,"logger":"camel-k.controller.integrationplatform","msg":"Reconciling IntegrationPlatform","request-namespace":"camel-basic","request-name":"camel-k"}
    {"level":"info","ts":1602779366.9631183,"logger":"camel-k.controller.integrationplatform","msg":"Invoking action initialize","request-namespace":"camel-basic","request-name":"camel-k","api-version":"camel.apache.org/v1","kind":"IntegrationPlatform","ns":"camel-basic","name":"camel-k"}
    {"level":"info","ts":1602779366.9744282,"logger":"camel-k","msg":"RuntimeVersion set to 1.4.1"}
    {"level":"info","ts":1602779366.9746928,"logger":"camel-k","msg":"BaseImage set to adoptopenjdk/openjdk11:slim"}
    {"level":"info","ts":1602779366.9747736,"logger":"camel-k","msg":"LocalRepository set to /tmp/artifacts/m2"}
    {"level":"info","ts":1602779366.9748497,"logger":"camel-k","msg":"Timeout set to {5m0s}"}
    {"level":"info","ts":1602779366.9749281,"logger":"camel-k","msg":"Maven Timeout set to 3m45s"}
    {"level":"info","ts":1602779367.1636393,"logger":"camel-k","msg":"Maven Timeout set to 3m45s"}
    {"level":"info","ts":1602779367.1804066,"logger":"camel-k.controller.integrationplatform","msg":"state transition","request-namespace":"camel-basic","request-name":"camel-k","api-version":"camel.apache.org/v1","kind":"IntegrationPlatform","ns":"camel-basic","name":"camel-k","phase-from":"","phas
e-to":"Creating"}
    {"level":"info","ts":1602779367.1807163,"logger":"camel-k.controller.integrationplatform","msg":"Reconciling IntegrationPlatform","request-namespace":"camel-basic","request-name":"camel-k"}
    {"level":"info","ts":1602779367.180847,"logger":"camel-k.controller.integrationplatform","msg":"Invoking action create","request-namespace":"camel-basic","request-name":"camel-k","api-version":"camel.apache.org/v1","kind":"IntegrationPlatform","ns":"camel-basic","name":"camel-k"}
    {"level":"info","ts":1602779367.180941,"logger":"camel-k.controller.integrationplatform","msg":"Installing camel catalog: camel-catalog-1.4.1-main.yaml","request-namespace":"camel-basic","request-name":"camel-k","api-version":"camel.apache.org/v1","kind":"IntegrationPlatform","ns":"camel-basic",
"name":"camel-k"}
    {"level":"info","ts":1602779367.3352988,"logger":"camel-k.controller.integrationplatform","msg":"Installing camel catalog: camel-catalog-1.4.1-quarkus.yaml","request-namespace":"camel-basic","request-name":"camel-k","api-version":"camel.apache.org/v1","kind":"IntegrationPlatform","ns":"camel-bas
ic","name":"camel-k"}
    {"level":"info","ts":1602779367.4122064,"logger":"camel-k.controller.integrationplatform","msg":"state transition","request-namespace":"camel-basic"
,"request-name":"camel-k","api-version":"camel.apache.org/v1","kind":"IntegrationPlatform","ns":"camel-basic","name":"camel-k","phase-from":"Creating","phase-to":"Ready"}
    {"level":"info","ts":1602779367.4125063,"logger":"camel-k.controller.integrationplatform","msg":"Reconciling IntegrationPlatform","request-namespace":"camel-basic","request-name":"camel-k"}
    {"level":"info","ts":1602779367.41267,"logger":"camel-k.controller.integrationplatform","msg":"Invoking action monitor","request-namespace":"camel-basic","request-name":"camel-k","api-version":"camel.apache.org/v1","kind":"IntegrationPlatform","ns":"camel-basic","name":"camel-k"}
    {"level":"info","ts":1602779372.180863,"logger":"camel-k.controller.integrationplatform","msg":"Reconciling IntegrationPlatform","request-namespace":"camel-basic","request-name":"camel-k"}
    {"level":"info","ts":1602779372.1809328,"logger":"camel-k.controller.integrationplatform","msg":"Invoking action monitor","request-namespace":"camel-basic","request-name":"camel-k","api-version":"camel.apache.org/v1","kind":"IntegrationPlatform","ns":"camel-basic","name":"camel-k"}
    {"level":"info","ts":1602779437.300872,"logger":"camel-k.controller.integration","msg":"Reconciling Integration","request-namespace":"camel-basic","request-name":"basic"}
    {"level":"info","ts":1602779437.3009295,"logger":"camel-k.controller.integration","msg":"Invoking action platform-setup","request-namespace":"camel-basic","request-name":"basic","api-version":"camel.apache.org/v1","kind":"Integration","ns":"camel-basic","name":"basic"}
    {"level":"info","ts":1602779437.3011146,"logger":"camel-k.trait","msg":"Apply trait: init"}
    {"level":"info","ts":1602779437.3011205,"logger":"camel-k.trait","msg":"Apply trait: platform"}
    {"level":"info","ts":1602779437.3011353,"logger":"camel-k.trait","msg":"Apply trait: camel"}
    {"level":"info","ts":1602779437.4021022,"logger":"camel-k.trait","msg":"Apply trait: dependencies"}
    {"level":"info","ts":1602779437.4052267,"logger":"camel-k.trait","msg":"Apply trait: deployer"}
    {"level":"info","ts":1602779437.4105144,"logger":"camel-k.trait","msg":"Apply trait: gc"}
    {"level":"info","ts":1602779437.4107096,"logger":"camel-k.trait","msg":"Apply trait: container"}
    {"level":"info","ts":1602779437.4107974,"logger":"camel-k.trait","msg":"Apply trait: owner"}
    {"level":"info","ts":1602779437.4170864,"logger":"camel-k","msg":"could not find any knative type in namespace camel-basic, last error was: services
.serving.knative.dev is forbidden: User \"system:serviceaccount:camel-basic:camel-k-operator\" cannot list resource \"services\" in API group \"serving.knative.dev\" in the namespace \"camel-basic\""}
    {"level":"info","ts":1602779437.4334302,"logger":"camel-k.controller.integration","msg":"state transition","request-namespace":"camel-basic","request-name":"basic","api-version":"camel.apache.org/v1","kind":"Integration","ns":"camel-basic","name":"basic","phase-from":"","phase-to":"Initialization"}
    ...
    {"level":"error","ts":1602779437.60473,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"integrationkit-controller","r
equest":"camel-basic/kit-bu47iba8981ueqfuf2k0","error":"error during trait customization: Secret \"kaniko-secret\" not found","errorVerbose":"Secret
 \"kaniko-secret\" not found\nerror during trait customization\ngithub.com/apache/camel-k/pkg/trait.Apply\n\tgithub.com/apache/camel-k/pkg/trait/tra
it.go:47\ngithub.com/apache/camel-k/pkg/controller/integrationkit.(*buildAction).handleBuildSubmitted\n\tgithub.com/apache/camel-k/pkg/controller/in
tegrationkit/build.go:76\ngithub.com/apache/camel-k/pkg/controller/integrationkit.(*buildAction).Handle\n\tgithub.com/apache/camel-k/pkg/controller/
integrationkit/build.go:57\ngithub.com/apache/camel-k/pkg/controller/integrationkit.(*ReconcileIntegrationKit).Reconcile\n\tgithub.com/apache/camel-
k/pkg/controller/integrationkit/integrationkit_controller.go:228\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHand
ler\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Con
troller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/
internal/controller.(*Controller).worker\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg
/util/wait.JitterUntil.func1\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apima
chinery@v0.18.2/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:88\nruntime.
goexit\n\truntime/asm_amd64.s:1373","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s
.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/cont

**Comment by nicolaferraro** [comment]
Can you try adding the flag `--build-publish-strategy=Kaniko` to `kamel install ...`?

The kaniko secret is not expected to work with Buildah (which is now the default). We should update the doc to mention this (if it works).

**Comment by nicolasduminil** [comment]
I'm reinstalling again Camel K following the instructions here: https://camel.apache.org/camel-k/latest/installation/gke.html and here: https://camel.apache.org/camel-k/latest/installation/registry/gcr.html.

    nicolas@nicolas-XPS-15-9570:~$ kubectl get pod
    No resources found in default namespace.
    nicolas@nicolas-XPS-15-9570:~$ kubectl get deployment
    No resources found in default namespace.

    nicolas@nicolas-XPS-15-9570:~$ kubectl create clusterrolebinding user-cluster-admin-binding --clusterrole=cluster-admin --user=...
    clusterrolebinding.rbac.authorization.k8s.io/user-cluster-admin-binding created

    nicolas@nicolas-XPS-15-9570:~$ kubectl create secret generic kaniko-secret --from-file=kaniko-secret.json
    secret/kaniko-secret created

    nicolas@nicolas-XPS-15-9570:~$ kamel install --registry gcr.io --organization marko-luksa-book --registry-secret kaniko-secret --force
    Camel K installed in namespace default 

Now Camel K is installed. I go then to the tutorials, examples.

    nicolas@nicolas-XPS-15-9570:~$ cd camel-k-examples/01-basic/
    nicolas@nicolas-XPS-15-9570:~/camel-k-examples/01-basic$

Here I'm following the guide and I'm doing:

    nicolas@nicolas-XPS-15-9570:~/camel-k-examples/01-basic$ kubectl create namespace camel-basic
    namespace/camel-basic created

    nicolas@nicolas-XPS-15-9570:~/camel-k-examples/01-basic$ kubectl config set-context --current --namespace=camel-basic
    Context "gke_marko-luksa-book_europe-west1_kubia" modified.

    kamel install
    Error: cannot find automatically a registry where to push images

So, here I get an error. However, I've created the registry. I try again:

    nicolas@nicolas-XPS-15-9570:~/camel-k-examples/01-basic$ kamel install --registry gcr.io --organization marko-luksa-book --registry-secret ../../kaniko-secret
    Error: Camel K seems already installed (use the --force option to overwrite existing resources): serviceaccounts "camel-k-operator" already exists

Okay, I'm trying to force it:

    nicolas@nicolas-XPS-15-9570:~/camel-k-examples/01-basic$ kamel install --registry gcr.io --organization marko-luksa-book --registry-secret ../../kaniko-secret --force
    Camel K installed in namespace camel-basic 

It worked. So, here is the integration platform:

    nicolas@nicolas-XPS-15-9570:~/camel-k-examples/01-basic$ kubectl get integrationplatform -o yaml
    apiVersion: v1
    items:
    - apiVersion: camel.apache.org/v1
      kind: IntegrationPlatform
      metadata:
        creationTimestamp: "2020-10-19T13:11:46Z"
        generation: 1
        labels:
          app: camel-k
        name: camel-k
        namespace: camel-basic
        resourceVersion: "2952401"
        selfLink: /apis/camel.apache.org/v1/namespaces/camel-basic/integrationplatforms/camel-k
        uid: b1e09325-7cf7-46b4-b52e-045f0a98a202
      spec:
        build:
          maven:
            settings: {}
          registry:
            address: gcr.io
            organization: marko-luksa-book
            secret: ../../kaniko-secret
        resources: {}
      status:
        build:
          baseImage: adoptopenjdk/openjdk11:slim
          buildStrategy: pod
          maven:
            localRepository: /tmp/artifacts/m2
            settings:
              configMapKeyRef:
                key: settings.xml
                name: camel-k-maven-settings
            timeout: 3m45s
          persistentVolumeClaim: camel-k
          publishStrategy: Buildah
          registry:
            address: gcr.io
            organization: marko-luksa-book
            secret: ../../kaniko-secret
          runtimeVersion: 1.4.1
          timeout: 5m0s
        cluster: Kubernetes
        phase: Ready
        version: 1.1.1
    kind: List
    metadata:
      resourceVersion: ""
      selfLink: ""

Now, I'm trying to run:

    nicolas@nicolas-XPS-15-9570:~/camel-k-examples/01-basic$ kamel run Basic.java --dev
    integration "basic" created
    Progress: integration "basic" in phase Initialization
    Integration basic in phase "Initialization"
    Condition "IntegrationPlatformAvailable" is "True" for Integration basic: camel-k
    Progress: integration "basic" in phase Building Kit
    Condition "IntegrationKitAvailable" is "False" for Integration basic: creating a new integration kit
    Integration basic in phase "Building Kit"

And after that I got stuck. This is what the log file is saying:

    {"level":"error","ts":1603112902.8573582,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"integrationkit-controller", "request":"camel-basic/kit-bu47iba8981ueqfuf2k0","error":"undefined camel catalog","errorVerbose":"undefined camel catalog\ngithub.com/apache/camel-k/pkg/controller integrationkit.*buildAction).handleBuildSubmitted\n\tgithub.com/apache/camel-k/pkg/controller/integrationkit/build.go:82\ngithub.c
om/apache/camel-k/pkg/controller/integrationkit.(*buildAction).Handle\n\tgithub.com/apache/camel-k/pkg/controller/integrationkit/build.go:57\ngithub.com/apache/camel-k/pkg/controller/integrationkit.(*ReconcileIntegrationKit).Reconcile\n\tgithub.com/apache/camel-k/pkg/controller/integrationkit/integrationkit_controller.go:228\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tk8
s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:88\nruntime.goexit\n\truntime/asm_amd64.s:1373","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:
232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tsigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tk8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:88"}

**Comment by nicolasduminil** [comment]
Running with --build-publish-strategy=Kaniko as suggested:

    nicolas@nicolas-XPS-15-9570:~/camel-k-examples/01-basic$ kamel install --registry gcr.io --organization marko-luksa-book --registry-secret ../../kaniko-secret --force --build-publish-strategy=Kaniko
    Camel K installed in namespace camel-basic 
    nicolas@nicolas-XPS-15-9570:~/camel-k-examples/01-basic$ kamel run Basic.java --dev
    integration "basic" created
    Progress: integration "basic" in phase Initialization
    Condition "IntegrationPlatformAvailable" is "True" for Integration basic: camel-k
    Progress: integration "basic" in phase Building Kit
    Integration basic in phase "Initialization"
    Condition "IntegrationKitAvailable" is "False" for Integration basic: creating a new integration kit
    Integration basic in phase "Building Kit"

And here I get stuck. Nothing has changed. I don't know what Buildah is and whether it is supposed to work or not with it but I reckon that it's supposed to work by following the guide. Did I miss anything ? Is there something I can do such that to get things working ? Or should I just consider that it simply doesn't work ?

**Comment by nicolasduminil** [comment]
On minikube it doesn't work neither:

    $ kubectl get integrationplatform
    NAME      PHASE
    camel-k   

    $ kubectl get po -A
    NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE 
    kube-system   coredns-f9fd979d6-gqbhb            1/1     Running   0          8m29s
    kube-system   etcd-minikube                      1/1     Running   0          8m28s
    kube-system   kube-apiserver-minikube            1/1     Running   0          8m28s
    kube-system   kube-controller-manager-minikube   1/1     Running   0          8m28s
    kube-system   kube-proxy-mqnmp                   1/1     Running   0          8m29s
    kube-system   kube-scheduler-minikube            1/1     Running   0          8m28s
    kube-system   registry-8t8jg                     1/1     Running   0          7m51s
    kube-system   registry-proxy-b4cpb               1/1     Running   0          7m51s
    kube-system   storage-provisioner                1/1     Running   1          8m34s

    $ kamel run Basic.java --dev
    integration "basic" created

and this is it, nothing happens.
