### ISSUE TITLE
Default to using Micrometer for integration monitoring

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#1773]
Quarkus recommends using Micrometer over MicroProfile Metrics starting Quarkus version 1.9:

https://quarkus.io/blog/micrometer-metrics/

The Prometheus trait should default to using Micrometer instead of MP metrics with Quarkus.

This requires the Camel Quarkus Micrometer extension to be available.

**Comment by haanhvu** [comment]
I'm working on this. Sending a PR soon.

**Comment by gansheer** [comment]
@squakez It might be good idea to add this issue to the 2.0.0 milestone.

**Comment by gansheer** [comment]
I would like to work on this. @squakez
