### ISSUE TITLE
Document Jitpack usage

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1789]
We should document which options are available and how they map to Jitpack.

Examples:

```
dependency=jitpack:com.github.user/repo/version
dependency=github:user/repo/version
dependency=jitpack:com.gitlab.user/repo/version
dependency=gitlab:user/repo/version
dependency=jitpack:com.bitbucket.user/repo/version
dependency=bitbucket:user/repo/version
dependency=jitpack:com.gitee.user/repo/version
dependency=gitee/repo/version
dependency=jitpack:com.azure.user/repo/version
dependency=azure:user/repo/version
```

**Comment by davsclaus** [comment]
It would be good with a new page in the docs that focus on jitpack, and shows how you can have a camel-k java route use a few other .java files that are build via jitpack into a JAR that camel-k then includes as dependency.

Its a bit unclear how to do this today.

**Comment by apupier** [comment]
I think i tis still a useful enhancement

**Comment by squakez** [comment]
There is some mention in [dependencies documentation](https://camel.apache.org/camel-k/1.7.x/configuration/dependencies.html#dependencies-kind). I've also done an example recently about [jitpack usage](https://github.com/apache/camel-k/tree/main/examples/jitpack). Do you think is that enough or something is missing before closing this issue?

**Comment by apupier** [comment]
I think it is not enough. The dependencies documentation is mentioning a single syntax.
