### ISSUE TITLE
Scalability of integration components in a non knative environment

### ISSUE THREAD

**Issue by arijitmazumdar** [apache/camel-k#1798]
Hi
We are testing camel-k capabilities on a minikube environment, we haven't installed knative.
We have observed when we create an integration, by default the replica is 1. 
Curious to know can we create an integration component with multiple pods in the beginning ?
Also as we are in a non knative environment, how can we scale the number of pods. I have tried to change the number of replica in the deployment to 2 from 1, however it's not creating 2 pods.

**Comment by astefanutti** [comment]
Hi, one option is to set the `.spec.replicas` field of the Integration resource.

Also the `kubectl scale` sub-command can be used to scale the Integration, e.g.:

    $ kubectl scale it my-integration --replicas N

**Comment by arijitmazumdar** [comment]
Hi
How to pass .spec.replicas in the `kamel run` command?
The other option did work by using `kubectl scale integration`... Thanks for that.

**Comment by astefanutti** [comment]
There is currently no option to the `kamel run` subcommand to set the replicas count. That would make a good enhancement. Feel free to create an issue for that.

it is possible to edit the Integration resource with `kubectl edit` or `kubectl patch`, e.g.:

    $ kubectl patch it my-integration -p '{"spec":{"replicas":2}}'
