### ISSUE TITLE
scaling out camel-k integrations are not working correctly

### ISSUE THREAD

**Issue by arijitmazumdar** [apache/camel-k#1806]
Hi
I have written a simple camel-k component which exposes a rest endpoint, which responds back.

```
import org.apache.camel.builder.RouteBuilder;

public class BasicRest extends RouteBuilder {
  @Override
  public void configure() throws Exception {

      from("rest:get:hello/{name}")
        .transform().simple("Bye World, ${header.name} from --> ${hostname}!!")
        .log("Got 1 hello");
  }
}
```

I have deployed the component using `kamel run BasicRest.java --dev`
I have scaled the integration using `kubectl scale it basic-rest --replicas=2`
This created 2 instances
```
$ kubectl  get it
NAME         PHASE     KIT                        REPLICAS
basic-rest   Running   kit-buekus3365fim0fprqeg   2

$ kubectl get po
NAME                               READY   STATUS    RESTARTS   AGE
basic-rest-65cb866cd7-g9lpv        1/1     Running   0          12m
basic-rest-65cb866cd7-tvl77        1/1     Running   0          12m
camel-k-operator-8bd669468-sbpv2   1/1     Running   3          7d2h

```
I have port-forwarded the service using `kubectl port-forward svc/basic-rest 8080:80`
But when I am doing a curl to the endpoint I can only see same response.

```
$curl localhost:8080/hello/arijit 
Bye World, arijit from --> basic-rest-65cb866cd7-g9lpv!!
$ curl localhost:8080/hello/arijit 
Bye World, arijit from --> basic-rest-65cb866cd7-g9lpv!!
$ curl localhost:8080/hello/arijit 
Bye World, arijit from --> basic-rest-65cb866cd7-g9lpv!!
```
Ideally hostname should be altered for some requests. Am I making any mistakes

**Comment by astefanutti** [comment]
The `kubectl port-forward svc` command is just a convenient wrapper around pod port-forwarding and does not enable to balance traffic on the service endpoints. The Kubernetes API only enables port forwarding for pods. The `kubectl port-forward svc` command picks a pod from the Service endpoints once, and forwards traffic to that pod.

This is being discussed at the end of https://github.com/kubernetes/kubernetes/issues/15180. To leverage the default round-robin load balancing, standard application traffic must be used, like with Ingress or Route.

**Comment by astefanutti** [comment]
Let me close this as it's been answered.

**Comment by arijitmazumdar** [comment]
Hi
Sorry for being late. I've tried with exposing the service as node-port, but I am still seeing the same behavior.
```
$kamel run BasicRest.java -t service.node-port=true --dev

$k get nodes -o wide
NAME       STATUS   ROLES    AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE           KERNEL-VERSION     CONTAINER-RUNTIME
minikube   Ready    master   16d   v1.19.2   192.168.49.2   <none>        Ubuntu 20.04 LTS   5.4.0-53-generic   docker://19.3.8

$ k get svc
NAME         TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
basic-rest   NodePort   10.99.128.250   <none>        80:30802/TCP   41s
 curl 192.168.49.2:30802/hello/arijit
Bye World, arijit from --> basic-rest-75b5458f9-p5bf7!!
$ curl 192.168.49.2:30802/hello/arijit
Bye World, arijit from --> basic-rest-75b5458f9-p5bf7!!
$ curl 192.168.49.2:30802/hello/arijit
Bye World, arijit from --> basic-rest-75b5458f9-p5bf7!!
$ curl 192.168.49.2:30802/hello/arijit
Bye World, arijit from --> basic-rest-75b5458f9-p5bf7!!
```

**Comment by astefanutti** [comment]
Could you please try with:

    $ kubectl get --raw "/api/v1/namespaces/<NAMESPACE>/services/basic-rest:http/proxy/hello/arijit

This reaches the service through the API server proxy.

**Comment by arijitmazumdar** [comment]
I retested again. I am getting the right result. In the last step I probably missed to scale up the integration component to 2. Thanks a lot for patiently supporting me.
```
arijit@arijit-HP-ProBook-440-G5:~$ curl 192.168.49.2:30256/hello/arijit 
Bye World, arijit from --> basic-rest-75b5458f9-p5bf7!!
arijit@arijit-HP-ProBook-440-G5:~$ curl 192.168.49.2:30256/hello/arijit 
Bye World, arijit from --> basic-rest-75b5458f9-7pvg7!!
arijit@arijit-HP-ProBook-440-G5:~$ curl 192.168.49.2:30256/hello/arijit 
Bye World, arijit from --> basic-rest-75b5458f9-p5bf7!!
arijit@arijit-HP-ProBook-440-G5:~$ curl 192.168.49.2:30256/hello/arijit 
Bye World, arijit from --> basic-rest-75b5458f9-7pvg7!!
arijit@arijit-HP-ProBook-440-G5:~$ curl 192.168.49.2:30256/hello/arijit 
Bye World, arijit from --> basic-rest-75b5458f9-7pvg7!!
arijit@arijit-HP-ProBook-440-G5:~$ curl 192.168.49.2:30256/hello/arijit 
Bye World, arijit from --> basic-rest-75b5458f9-p5bf7!!
```

**Comment by astefanutti** [comment]
Great! Thanks for the feedback.

**Comment by haifzhan** [comment]
@arijitmazumdar  Hi there, I am facing the same issue my replicas are not able to receive any traffic. Is trait `-t service.node-port=true` the only configuration required(I already have my service template and the port forwarding has been applied)?  Thanks!
