### ISSUE TITLE
Camel sslContextParameter not working

### ISSUE THREAD

**Issue by starafdar-git** [apache/camel-k#1815]
Hi Team,
I am trying to use ssl certificate to make rest call , but seems its not working as expected however its working on spring boot with camel:

#Code snippet for updating ssl context parameter
CamelContext camelContext = getContext();
KeyStoreParameters ksp = new KeyStoreParameters();
ksp.setResource("/etc/camel/conf.d/_secrets/****/*****.p12");
ksp.setPassword("*****");

KeyManagersParameters kmp = new KeyManagersParameters();
kmp.setKeyStore(ksp);
kmp.setKeyPassword("*****");
SSLContextParameters scp = new SSLContextParameters();
scp.setKeyManagers(kmp); 
camelContext.setSSLContextParameters(scp);

#command :
 kamel run --secret=*** --dependency=camel-http --dependency=camel-undertow  ***Proxy.java --dev

**Comment by lburgazzoli** [comment]
If you are using the latest version of camel-k (1.2.0), the default runtime has been switched to quarkus so best is to follow this guide: https://quarkus.io/guides/http-reference#ssl

**Comment by starafdar-git** [comment]
@lburgazzoli 
Thanks for your reply 
 Created a config map for application.properties and added below content:
 quarkus.http.ssl.certificate.key-store-file="/etc/camel/conf.d/_secrets/****/***certificate.p12"
 quarkus.http.ssl.certificate.key-store-file-type="P12"
 quarkus.http.ssl.certificate.key-store-password="****"

then used below command to run but still same 
 kamel run --configmap=configmap --secret=**-cert --dependency=camel-http --dependency=camel-undertow  ***Proxy.java --dev

**Comment by squakez** [comment]
In latest version 1.5 we're introducing a different way to manage `secret` and `properties`. You may have a look at the examples here to see how we're setting `SSLContextParameter` with the new configuration: https://github.com/apache/camel-k/tree/main/examples/http
