### ISSUE TITLE
Enable services to be associated with a version

### ISSUE THREAD

**Issue by objectiser** [apache/camel-k#182]
When using camel-k in an Istio environment, it would be good if a service for a HTTP route could have an optional version, to enable support for routing rules to manage traffic across versions.

Hopefully eventually the same would be relevant for messaging endpoints.

**Comment by nicolaferraro** [comment]
This is really a nice thing to have. Do you have any pointers to the Istio version management strategies?

**Comment by objectiser** [comment]
Some relevant docs are here:
https://istio.io/docs/tasks/traffic-management/request-routing/
https://istio.io/docs/concepts/traffic-management/

Using the bookinfo example to illustrate, you just need to add a version label to the deployments, as defined in the [three versions of the review service](https://github.com/istio/istio/blob/45692c579c6d755194421540149a99ac4cb59528/samples/bookinfo/platform/kube/bookinfo.yaml#L101-L156).

Then a virtual service can be defined to manage traffic across the different versions. For example, [this rule](https://github.com/istio/istio/blob/45692c579c6d755194421540149a99ac4cb59528/samples/bookinfo/networking/virtual-service-reviews-50-v3.yaml) splits traffic to the reviews service 50/50 between v1 and v3.

**Comment by squakez** [comment]
Stale. Please, reopen if relevant again.
