### ISSUE TITLE
Refactor artifacts of deploy directory and continue alignment towards operator-sdk & kustomize

### ISSUE THREAD

**Issue by phantomjinx** [apache/camel-k#1820]
Following on from #1743 ....

* Refactor and remove any duplication between the `deploy` and `config` directories;
* The `config` directory should now become the source of truth for the artifacts, where applicable, retargetting the kamel CLI accordingly;
* Make clear in README that the bundle directory should be generated on an as-needed basis rather than being checked-in (the CSV manifest resources are checked-in);

***UPDATE: splitting below off to #1979***
* Start to offer camel-k as an install with kustomize rather than needing to download the `kamel cli`, allowing install with standard tools;
  - This will require consideration of different production setups, tailoring the `config` directory to support patches for different use-cases, eg. including addons, installing on different types of cluster;
  - Need to gauge any comparable loss of flexibility as compared to the kamel cli;

**Comment by phantomjinx** [comment]
Due to large change required for initial part of this issue, am splitting off kustomize effort into separate issue #1979.

**Comment by astefanutti** [comment]
This's been fixed by #1978.
