### ISSUE TITLE
Document secrets for using secrets (and config maps)

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1838]
There are some undocumented features that need to find some place in the doc, e.g. in: https://camel.apache.org/camel-k/latest/configuration/configmap-secret.html#_reference_a_secret_in_properties

E.g. 

1. The `{{secret:<mysecret>/<myentry>}}` property function that can be used in routes or injection points directly (not only in property files
2. The equivalent `{{configmap:<mycm>/<myentry>}}` for ConfigMaps
3. The `CAMEL_K_MOUNT_PATH_CONFIGMAPS` and `CAMEL_K_MOUNT_PATH_SECRETS` to access cm/secret entries as files

**Comment by heiko-braun** [comment]
The price for the best issue title in 2020 goes to @nicolaferraro !

**Comment by squakez** [comment]
The link referred in this issue was deleted after #2003. I can work on this issue in order to find the right place for documenting this feature.
