### ISSUE TITLE
Lower priority of modeline options

### ISSUE THREAD

**Issue by doru1004** [apache/camel-k#1843]
In the current implementation modeline options take precedence over the same user-provided options. It feels like this should be the other way around i.e. if a user mentions an option on the command line, that option should overwrite any modeline option with the same name.

Modeline options are currently inserted at the end of the original command line which means that they overwrite any identical options that appear earlier in the command line.

User wrote:
```
kamel run -p prop1=val1 file.yaml
```

file.yaml:
```
# camel-k: property prop1=val2
```

After modeline options are extracted:
```
kamel run -p prop1=val1 file.yaml --property prop1=val2
```

prop1 will have val2. Instead, prop1 should have val1 and the modeline prop1 should not have been extracted at all. The command line after modeline should be:
```
kamel run -p prop1=val1 file.yaml
```

Thoughts?

**Comment by nicolaferraro** [comment]
Yes, I think what you're suggesting is the right way to handle those params

**Comment by doru1004** [comment]
Opened a PR about this: https://github.com/apache/camel-k/pull/1857

**Comment by squakez** [comment]
I think this was already fixed
