### ISSUE TITLE
kamel run - compile errors should be more visible

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#185]
I made a mistake in the runtime/example/Sample.java file where the `\n` new line escape was changed to `\C` which would cause the java code to compile error. But I could not really see that too well. 

This is just a ticket to remember to look into this and see if its really the case and if so make it report it better to the log output.

**Comment by orpiske** [comment]
The features added with the new logging trait for 1.5 (and backported to 1.4) along w/ the `kamel dump` should alleviate this problem (if not resolving it altogether) ... . As such, I'm closing this one.
