### ISSUE TITLE
Installation hangs on GKE 

### ISSUE THREAD

**Issue by kasun04** [apache/camel-k#188]
Hi @nicolaferraro , 

I'm trying to run a simple REST DSL on GKE. 

- Install Kamel on GKE - 
- kubectl  get pods
NAME                                READY     STATUS    RESTARTS   AGE
camel-k-operator-7fb9dc6fb4-88shs   0/1       Pending   0          4m

- Looks like the camel-k-operator hangs here. 

Any thoughts?

**Comment by kasun04** [comment]
More logs: 

Events:
  Type     Reason            Age               From               Message
  ----     ------            ----              ----               -------
  Warning  FailedScheduling  2m (x26 over 8m)  default-scheduler  PersistentVolumeClaim is not bound: "camel-k-builder" (repeated 2 times)

**Comment by nicolaferraro** [comment]
Thanks @kasun04 for reporting this issue. Camel K has not been tried on GKE yet and such problems were expected to happen.

Currently the binary data is "passed" to Kaniko through a shared PV (RWM) that is not available in all Kubernetes implementations (including GKE, I think).
We can solve this issue e.g. by co-locating the kaniko builder and the maven builder pods.

Another issue that we need to solve for GKE is supporting image push secrets (that are not needed on Minikube).

Current support for Kubernetes is limited to Minikube at the moment.
We need to fix this issue to support also GKE oob.

**Comment by kasun04** [comment]
thanks @nicolaferraro . 
Does it work with Docker for mac at least?

**Comment by kasun04** [comment]
It works with Docker for mac (not on minikube). 
I've deployed a sample integration examples/routes-rest.js and was expecting it to create svc, ingress etc so that I can invoke my RESTful service. 
Do I have to manually create ingress, service etc for that? Here are the pod and svc information. 

kubectl get pods
NAME                                READY     STATUS    RESTARTS   AGE
camel-k-operator-64c5686848-4zkzt   1/1       Running   0          2h

./kamel get
NAME		CONTEXT	STATUS
routes
routes-rest

kubectl get svc
NAME               TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)     AGE
camel-k-operator   ClusterIP   10.97.6.139   <none>        60000/TCP   2h
kubernetes         ClusterIP   10.96.0.1     <none>        443/TCP     3h
