### ISSUE TITLE
Default catalog is ignored and the operator creates a duplicate

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1897]
With 1.3.0, doing:

```
kamel install
````

Creates a default catalog:

```
kubectl get camelcatalog
NAME                          RUNTIME VERSION   RUNTIME PROVIDER
camel-catalog-1.6.0           1.6.0             quarkus
```

But when an integration is run:

```
kamel run examples/Sample.java -w
```

Then another catalog is created.

```
kubectl get camelcatalog
NAME                          RUNTIME VERSION   RUNTIME PROVIDER
camel-catalog-1.6.0           1.6.0             quarkus
camel-catalog-1.6.0-quarkus   1.6.0             quarkus
```

The `-quarkus` catalog is created because a mechanism exists that creates a catalog when one is not available for the platform runtime. We have only 1 runtime now, but anyway a new catalog is created and the default one ignored.

At a first glance, the reason seems to be that the default catalog is missing the `camel.apache.org/runtime.provider: quarkus` annotation.

**Comment by lburgazzoli** [comment]
@nicolaferraro do we need to bring the `camel.apache.org/runtime.provider` annotation back in camel-k-runtime ?

**Comment by astefanutti** [comment]
I think we can just remove the lookup by annotation and also get rid of `camel.apache.org/runtime.provider` altogether.
