### ISSUE TITLE
hotrod-client.properties not picked up

### ISSUE THREAD

**Issue by edeandrea** [apache/camel-k#1898]
The `hotrod-client.properties` file does not seem to be getting picked up when running under quarkus. 

In my sample (https://gist.github.com/edeandrea/770c84be9da204ff0b13f2340975904e) I would assume that the properties I have defined in the [`hotrod-client.properties`](https://gist.github.com/edeandrea/770c84be9da204ff0b13f2340975904e#file-camelk-client-yml-L34-L45) and are [mounted into the `Integration`](https://gist.github.com/edeandrea/770c84be9da204ff0b13f2340975904e#file-camelk-client-yml-L56-L57) would be picked up by the `camel:infinispan` component, but they are not.

I know this because my `hotrod-client.properties` file defines `infinispan.client.hotrod.marshaller=org.infinispan.commons.marshall.UTF8StringMarshaller`. When I run my integration and look into the Infinispan cache, the keys/values that are there aren't simple strings.

**Comment by lburgazzoli** [comment]
the `hotrod-client.properties` is not automatically loaded by camel-k, you should configure quarkus/camel about where to find it, similar to what you do with `quarkus.infinispan-client.trust-store` but it does not look like there is such option in quarkus-infinispan.

For camel it should be something like:

   camel.component.infinispan.condifuration.configuration-uri = ${env:CAMEL_K_MOUNT_PATH_CONFIGMAPS}/camelk-rhdg-client-confi/hotrod-client.properties

**Comment by edeandrea** [comment]
Thanks I'll give this a try. I assume you also have to do whats in #1870, otherwise camel-quarkus does not respect the `camel.component.*` properties.

**Comment by edeandrea** [comment]
> the `hotrod-client.properties` is not automatically loaded by camel-k as the config maps are not in the classpath

Actually in my case the configmap is mounted as a file and is on the classpath.

Would that still not be picked up by camel-k?

**Comment by edeandrea** [comment]
The problem here is that the Quarkus runtime expects `hotrod-client.properties` to be in `META-INF` (see https://github.com/quarkusio/quarkus/blob/master/extensions/infinispan-client/deployment/src/main/java/io/quarkus/infinispan/client/deployment/InfinispanClientProcessor.java#L62). With camel-k, the build is performed by the operator so the user has no way to put `hotrod-client.properties` inside `META-INF`. Quarkus should allow configuration of where `hotrod-client.properties` lives.

**Comment by edeandrea** [comment]
@lburgazzoli I filed quarkusio/quarkus#14368
