### ISSUE TITLE
Kamel CLI - Add command to run integration in Java debug mode

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#190]
... so we can do remote debugging in the running container, like the fabric8 f-m-p maven plugin can do.

    Kamel run Foo.java --dev --debug

Then it does the tunneling on localhost:5005 into the k8s cluster to the running pod. So the developer can just do Java remote debugging on localhost:5005 from his Java editor.

**Comment by davsclaus** [comment]
Yeah or your custom business logic if you have java beans etc.

**Comment by zregvart** [comment]
I'll work on a PR over the weekend.
