### ISSUE TITLE
kamel inspect is not providing dependencies specified in modeline

### ISSUE THREAD

**Issue by apupier** [apache/camel-k#1921]
call `kamel inspect MyRouteBuilderWithAdditionalDependencies.java` with the specified file having this content:
```
// camel-k: dependency=mvn:com.github.camel-tooling/camel-lsp-server:1.1.0

import org.apache.camel.builder.RouteBuilder;

public class MyRouteBuilderWithAdditionalDependencies extends RouteBuilder{
	public void configure() {
    }
}
```

it returns:
`mvn:org.apache.camel.k/camel-k-loader-java`

the declared depdency in modeline is missing

**Comment by doru1004** [comment]
Thanks for reporting this.

Solved by: https://github.com/apache/camel-k/pull/1924/files
