### ISSUE TITLE
SinkBinding produces errored pods on 0.18+ / OpenShift Serverless 1.12

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1945]
Testing on OpenShift serverless.

When a pod that uses sink-binding is run, the webhook on deployments seems not to be applied immediately, so this results into two deployments, one of which does not contain the injected parameters and ends in an error state.

We should investigate why the Knative webhook does not change the deployment immediately and if we can put some countermeasures to avoid the double deployment.

Making the integration itself sink-bindable is a possible strategy.

**Comment by astefanutti** [comment]
I think it's been fixed with #2190.
