### ISSUE TITLE
Usage of binary data in ConfigMaps

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#1946]
As a follow up of #1881 I am wondering if there is any reason why we are not using binary `ConfigMap`s. I was thinking to find some way and generate a binary `ConfigMap`s when we detect any resource that is binary (and default to text if not). That would simplify the usage of a binary resource directly from `Integration`s as we delegate kube cluster to mount a volume with the binary content.

**Comment by lburgazzoli** [comment]
I think the main reason was that configmap were supposed to hold configurations whereas to add arbitrary binary data there were a `--resource` and maybe we should improve `--resource` to be able to support arbitrary configmap and secrets

**Comment by squakez** [comment]
I've made some test in order to enhance `--resource`. It would leverage `ConfigMap` `BinaryData` when we detect the resource as binary and the user is not asking for base64 `--compression`. I'm thinking to add also the `content-type` to the resource, so we always know what type is expected.
