### ISSUE TITLE
Expose operator information

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#1947]
When we start an operator we see the following log traces:
```
{"level":"info","ts":1611586026.069271,"logger":"cmd","msg":"Go Version: go1.15.2"}
{"level":"info","ts":1611586026.0692925,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1611586026.0692983,"logger":"cmd","msg":"Buildah Version: 1.14.0"}
{"level":"info","ts":1611586026.0693028,"logger":"cmd","msg":"Kaniko Version: 0.17.1"}
{"level":"info","ts":1611586026.0693076,"logger":"cmd","msg":"Camel K Operator Version: 1.4.0-SNAPSHOT"}
{"level":"info","ts":1611586026.0693126,"logger":"cmd","msg":"Camel K Default Runtime Version: 1.6.0"}
{"level":"info","ts":1611586026.0693188,"logger":"cmd","msg":"Camel K Git Commit: 098e835a161112a52b64f811f9af94845cd7ca9d"}
```
I think it would be nice to expose publicly an endpoint with those information so that the CLI (or any other tool) can easily query the operator and return those configuration.

**Comment by lburgazzoli** [comment]
Maybe such info should be stored somewhere in `IntegrationPlatform.Status` ? 
Ideally everything should be possible through kubectl.

**Comment by astefanutti** [comment]
It may be preferable to expose these into an unstructured map rather than typed fields as this may not be something that we want to consider as a stable public API.
