### ISSUE TITLE
Persist trait status

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2024]
As today when traits are applied, they may perform some ato configuration magics that leaves no trace in the integration status or kubernetes events. It is of course possible to determine what happened by reverse engineering what resources the operator generates but it is not an easy task.

For troubleshooting and monitoring purpose we should have a way to track what traits have been applied and the related set-up. 

An option would be to store phase transitions as part of the conditions list as marshaled json trait

**Comment by squakez** [comment]
Same as #4811
