### ISSUE TITLE
Local build implementation

### ISSUE THREAD

**Issue by doru1004** [apache/camel-k#2038]
Opened the issue to track the proposed changes from PR https://github.com/apache/camel-k/pull/1816 discussion:

- transform current inspect command to: `kamel local inspect`
- rename `kamel local create` to `kamel local build`
- enable `kamel local build` to construct a local directory hierarchy, at a custom location specified by the user, containing all the elements required by the integration.
- enable `kamel local run` to pick up integration directory and just run the integration locally.
- enable `kamel local build` to save just the dependencies in a custom location specified by the user.

**Comment by astefanutti** [comment]
I think it's been fixed with #2048.
