### ISSUE TITLE
Provide option to get the Json/Yaml of a integration

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#207]
Something like `kamel run int.groovy -o yaml` (to mimic `oc` and `kubectl`).

**Comment by chirino** [comment]
how about `kamel eject`

**Comment by chirino** [comment]
already working on this btw.

**Comment by chirino** [comment]
also working on setting up my asf account so I can self assign.

**Comment by oscerd** [comment]
Sorry for this. Removed myself :-)

**Comment by oscerd** [comment]
I didn't know you can't self assign actually
