### ISSUE TITLE
Provide automated tests for "kamel local run --integration-directory <dir-name>" command

### ISSUE THREAD

**Issue by apupier** [apache/camel-k#2075]
The new feature has been added via #2048 but it doesn't seem to have any tests for the `kamel local run --integration-directory <dir-name>` options.

might be an extra step in the `kamel local build` tests https://github.com/apache/camel-k/issues/2074

**Comment by jamesnetherton** [comment]
Isn't that `make test-local`?

https://github.com/apache/camel-k/tree/master/e2e/local

**Comment by apupier** [comment]
I wasn't precise enough in the description. it is not this one. it is for the added use using the --integration-directory option

**Comment by apupier** [comment]
still relevant

**Comment by apupier** [comment]
still relevant
