### ISSUE TITLE
Upgrade to Service Binding operator to v0.5.0

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#2077]
v0.5.0 has just been released. #2076 prepares the ground by upgrading to an intermediate version, but v0.5.0 introduces breaking changes in the ServiceBinding API that should be integrated. See:

https://github.com/redhat-developer/service-binding-operator/releases/tag/v0.5.0

**Comment by johnpoth** [comment]
That was fast! I can take a look

**Comment by arthurdm** [comment]
I am interested in learning more about the connection and usage between Camel K and Service Binding, as I work on the [Service Binding Spec](https://k8s-service-bindings.github.io/spec/).   Any details that could be shared?

**Comment by astefanutti** [comment]
@arthurdm you can find some details in https://github.com/apache/camel-k/blob/master/proposals/service-binding/service-binding.adoc.

**Comment by johnpoth** [comment]
There is also a [meeting](https://github.com/redhat-developer/service-binding-operator#community-discussion-contribution-and-support)  where use cases can be discussed. Next one is today at 1:00 PM UTC I think

**Comment by johnpoth** [comment]
@arthurdm I think one relevant part of the specification that is relevant here is the use of [custom service projection](https://github.com/k8s-service-bindings/spec#custom-projection) where camel-k handles the mounting of the binding information (in the form of a `secret`) into the `Deployment`.  I am mentioning this as it's scheduled to be [removed](https://github.com/k8s-service-bindings/spec/pull/143) if my understanding is correct.

One of the benefit of using this approach was that the `Deployment` did not have to be created in an incomplete state: waiting for the binding information and the resulting `Pods` failing.

**Comment by arthurdm** [comment]
Thanks for link @astefanutti / @johnpoth!

Yes - are you noted, we're about to remove the `CustomServiceProjection` from the spec.  In order to leverage the new `ClusterApplicationResourceMapping` artifact my recommendation would be to expose the needed elements (volumeMount, env, etc) in the `.spec` of `Integration` - so that we don't get into a reconciler loop between the Service Binding Operator changing the generated `Deployment` that is owned by the Camel K Operator.

**Comment by astefanutti** [comment]
I've created #2096, as an umbrella issue to make Integration _PodSpecable_.

**Comment by johnpoth** [comment]
In the case of ServiceBinding, the integration [isn't needed](https://github.com/k8s-service-bindings/spec/commit/20daf4e312ca502a301cb552624680152d4fe319) to be PodSpecable

**Comment by astefanutti** [comment]
> In the case of ServiceBinding, the integration [isn't needed](https://github.com/k8s-service-bindings/spec/commit/20daf4e312ca502a301cb552624680152d4fe319) to be PodSpecable

It seems that was the case an hour ago 😉.

**Comment by astefanutti** [comment]
Fixes with #2094.
