### ISSUE TITLE
Kamelet - Possible to pre configure component options

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#2081]
I the Kamelet docs at
https://camel.apache.org/camel-k/latest/kamelets/kamelets.html

I cannot see a way how I can pre configure the Camel components that the Kamelet may be using.

In regular Camel K I can specify a properties file where I have

```
camel.component.xxxx.yyyy = 123
```

Likewise you can also configure data formats, and languages (more rare to do this) so we may want to make available to do this for those kind too.

**Comment by lburgazzoli** [comment]
I think the main issue here is that, if in your route you instantiate the same kamelets/templates twice, the you have issues when configuring components as the same component is shared among the kamelets/templates  (that's the reason we have the kamelet-reifier component in camel-k). 

A solution would be to have a route context where the kamelet can bind its own beans but that would complicate a little the camel context.

**Comment by davsclaus** [comment]
Ah yeah that is correct. So we may consider making components private per template, by adding a unique prefix on the component name, and register it in the component registry.

But the idea of `RouteContext` where we can then bind it as a bean that also works for other clashes, where we do a registry lookup first.
