### ISSUE TITLE
Add support for `@mirrorOf=xxx` for --maven-repository option

### ISSUE THREAD

**Issue by bouskaJ** [apache/camel-k#2088]
I would like to use `kamel install -maven-repository=https://repository.apache.org/content/repositories/snapshots@mirrorOf=*` for setting mirrors in the Camel-K settings.xml

Currently, we support only the following attributes. https://github.com/apache/camel-k/blob/master/pkg/util/maven/maven_project.go#L183-L194

**Comment by astefanutti** [comment]
Fixed with #2089. Thanks!
