### ISSUE TITLE
OLM installation may fail with default values

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#2113]
Installing the default camel-k operator via `kamel install` may not work on minikube or other k8s distribution where OLM is installed outside openshift (ie https://olm.operatorframework.io/docs/getting-started/#install-released-olm). It produces the following error:
```
message: targeted catalogsource openshift-marketplace/community-operators missing
```
To workaround it you can override the default `catalogsource` with the expected default by OLM installation `kamel install --olm-source-namespace=olm --olm-source=operatorhubio-catalog`.

However I think it could be convenient to change the default values to the ones expected by the default OLM installation in order to be consistent.

**Comment by squakez** [comment]
They seems to be also the values used from operatorHub.io procedure: https://operatorhub.io/install/camel-k.yaml

**Comment by squakez** [comment]
The fix for this issue would be the following one: https://github.com/apache/camel-k/compare/master...squakez:fix/2113_olm_default

However I am not sure if we introduce any problem when dealing with Openshift operators and the like. @astefanutti, @nicolaferraro should I proceed or do you think this may trigger other problems?

**Comment by astefanutti** [comment]
@squakez yes the current default values match the community catalog that comes in OpenShift 4. Changing these would break people using the upstream CLI version with OpenShift 4.

Another option would be to have _dynamic_ default values, as the `kamel install` command is capable of detecting the environment it's installing onto.

If we were to keep _static_ default values, then we would have to assess what is the dominant usage to make a decision. I haven't seen any evidence that OLM on Kubernetes is taking off? Are there any major Kubernetes distribution, aside OpenShift, that comes with OLM OOTB? I'd be inclined to think the dominant OLM use case is on OpenShift, and that the upstream CLI install command should default to the community catalog, which is the case. 

For the product catalog in OpenShift 4, these variables are set as Go build-time variables in downstream builds, whose CLI binaries can be downloaded from the OpenShift Web console, which is the dominant use case for product versions.

**Comment by squakez** [comment]
I imagined that. I think the best experience would be to have dynamic values based on our capability to discover what kind of OLM is installed in the cluster. I will have a look and we can keep this open in the while.

**Comment by astefanutti** [comment]
Sounds good to me 👍🏼.
