### ISSUE TITLE
Add sample using Flink

### ISSUE THREAD

**Issue by arthurdm** [apache/camel-k#2116]
Looking around the web I could not find anywhere a sample that used Flink directly from a Camel K integration, e.g. using the `to(flink:..)` component.

In the Flink Component page there's [partial example](https://camel.apache.org/components/3.7.x/flink-component.html#_camel_flink_producer_call) but it doesn't show how to implement the referenced DataSet and dataSetCallback properties.

**Comment by oscerd** [comment]
If you are not looking at this, I'll have a look

**Comment by arthurdm** [comment]
Thanks @oscerd!   I think a very useful sample would show how to create a `DataSet` that took into consideration the incoming payload.  Here's the snippet I was trying to get to work [1].  I couldn't get my `DataSet` to be registered.  Keep getting this error [2].

**[1]**
```java
public class FlinkSample extends RouteBuilder implements Processor {

    @Override
    public void configure() throws Exception {

        // Receive a msg from the configured Kafka topic
        from("timer:foo")
            .log("Received body: ${body}")
            .split(body().tokenize("\n"))
            .process(this)
        .to("flink:dataSet?dataSet=#myDataSet&dataSetCallback=#myDataSetCallback")
            .log("Response body: ${body}");

    }

    @BindToRegistry
    public  DataSetCallback<String> myDataSetCallback () {
        return new DataSetCallback<String>() {
            @Override
            public String onDataSet(DataSet ds, Object... payloads) {
                return "this is the result";
            }
         };
    }

    @Override
    public void process(Exchange exchange) throws Exception {
        final ExecutionEnvironment env = ExecutionEnvironment.getExecutionEnvironment();
        DataSet<String> myDataSet = env.fromElements(exchange.getIn().toString());
        exchange.getContext().getRegistry().bind("myDataSet", DataSet.class, myDataSet);
    }

}
```

**[2]**
```
Failed to start application (with profile prod): org.apache.camel.NoSuchBeanException: No bean could be found in the registry for: myDataSet of type: org.apache.flink.api.java.DataSet
	at org.apache.camel.support.CamelContextHelper.mandatoryLookupAndConvert(CamelContextHelper.java:253)
	at org.apache.camel.support.EndpointHelper.resolveReferenceParameter(EndpointHelper.java:290)
	at org.apache.camel.support.EndpointHelper.resolveReferenceParameter(EndpointHelper.java:250)
	at org.apache.camel.support.component.PropertyConfigurerSupport.property(PropertyConfigurerSupport.java:53)
	at org.apache.camel.component.flink.FlinkEndpointConfigurer.configure(FlinkEndpointConfigurer.java:26)
	at org.apache.camel.support.PropertyBindingSupport.setSimplePropertyViaConfigurer(PropertyBindingSupport.java:703)
```

**Comment by oscerd** [comment]
I think the problem is you're trying to bind the myDataSet to the registry in the process step, but it must done before, like you do for the callback

**Comment by arthurdm** [comment]
ya - indeed if I move the registration as the first lines of `configure` things work, but then I don't have the `{body}` information available to populate the `DataSet`.  Is there another way to access the incoming data for the processing?

**Comment by lburgazzoli** [comment]
I don't think this could ever work as the flink endpoint is resolved when the route is reified, which means that even if you change the dataSet instance in the registry, it won't be noticed by the endpoint. 

I think the only solution would be to amend the flink component and i.e. accept the dataSet to be set on an header.

**Comment by arthurdm** [comment]
that's good to know @lburgazzoli - I was going a bit crazy trying to get that to work. 😅 

Is there a way to programatically call the Flink component from a Camel K Integration as an alternative to `to(flink:..)`?   The Flink Component claims that  we can `use incoming message as input data for the task`.

**Comment by lburgazzoli** [comment]
I think the easier option would really be to improve the component

**Comment by arthurdm** [comment]
I was able to get further along by changing `to(flink:..)` to `toD(flink:..)`.    That seemed to have allowed my DataSet to be registered dynamically, but now getting `Caused by: java.lang.ClassNotFoundException: scala.Product$class`.   Is there a particular scala version / dependency I need to set for the flink component?

**Comment by arthurdm** [comment]
hi @oscerd - just wondering if you're also hitting the same roadblock I hit above.  Is our only option to improve the core Flink component?

**Comment by oscerd** [comment]
I think it is worth to amend the component. I still didn't find time to look at the sample.
