### ISSUE TITLE
Push to insecure registry fails when using Kaniko build strategy

### ISSUE THREAD

**Issue by orpiske** [apache/camel-k#2127]
This is similar to the issue I reported on #2122, but involves one more item. 

In addition to the items reported on the aforementioned issue, the push also fails because Kaniko itself assumes https. A simple work-around for this is setting the flags `--skip-tls-verify` and `--skip-tls-verify-pull`. They force Kaniko to use the HTTP protocol when talking to the registry.

```
DEBU[0000] Copying file /builder/kit-c17mger67bimpfkia980/context/Dockerfile to /kaniko/Dockerfile 
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "my-insecure-registry-with-no-https.com/opiske/camel-k-kit-c17mger67bimpfkia980:380084": creating push check transport for k3s-node-master.usersys.redhat.com failed: Get https://my-insecure-registry-with-no-https.com/v2/: x509: certificate has expired or is not yet valid
```

I have a fix in place and will open a PR with a proposed fix soon.

**Comment by astefanutti** [comment]
Fixes with #2130. Thanks!
