### ISSUE TITLE
Maven build extensions

### ISSUE THREAD

**Issue by viacheslav-fomin-main** [apache/camel-k#2132]
Hello! 

I need to get dependencies from AWS s3 bucket serving as a maven repository. To do this I need to add this extension https://github.com/Yleisradio/aws-maven but I could not find a way how it is done in camel K. Is this currently possible? or is there another way to access AWS s3 maven repo?

Thank you in advance!

**Comment by lburgazzoli** [comment]
We don't have direct support for this but it would be very welcome (relates to https://github.com/apache/camel-k/issues/1227).

If the extension can be configured via maven' settings.xml, then you can follow the instruction there https://github.com/apache/camel-k#configure-maven-settings

**Comment by viacheslav-fomin-main** [comment]
Thanks! I think we will contribute this.
