### ISSUE TITLE
Camel K doesn't automatically create an endpoint to view the Openapi doc that it was built with.

### ISSUE THREAD

**Issue by pprosser-redhat** [apache/camel-k#2135]
I created an API with Camel K by defining an Openapi specification. Including the openapi doc with the open-api parameter means that I only need to write my integration by using a "from("direct:....") and Camel K takes care of the rest. Great stuff. 

I expected the Integration to automatically expose an endpoint e.g. /api-doc that allows a developer to see the documentation for the API. Turns out that this isn't the case. 

I needed to include an application property

camel.context.rest-configuration.api-context-path=/api-doc

to make this happen.

Is it possible to automate this in the operator or at least have better documentation to make this clear.

**Comment by JeSuisAlrick** [comment]
Excellent bug report.
