### ISSUE TITLE
Secret type not supported with buildah on K3S

### ISSUE THREAD

**Issue by orpiske** [apache/camel-k#2136]
When using buildah along with k3s, it fails with the reason: _"error during trait customization: unsupported secret type for registry authentication"_. A full stack trace is provided below. The offending line is [here](https://github.com/apache/camel-k/blob/55f74d3e44ad059219ec3d1fb00fb85ab2e60cd1/pkg/trait/builder.go#L260).

Stack trace:
```{"level":"error","ts":1615895993.1570735,"logger":"controller-runtime.manager.controller.integrationkit-controller","msg":"Reconciler error","name":"kit-c189rdl2uobonj4b77g0","namespace":"camel-basic-dev","error":"error during trait customization: unsupported secret type for registry authentication","errorVerbose":"unsupported secret type for registry authentication\ngithub.com/apache/camel-k/pkg/trait.getRegistrySecretFor\n\tgithub.com/apache/camel-k/pkg/trait/builder.go:485\ngithub.com/apache/camel-k/pkg/trait.(*builderTrait).buildahTask\n\tgithub.com/apache/camel-k/pkg/trait/builder.go:264\ngithub.com/apache/camel-k/pkg/trait.(*builderTrait).Apply\n\tgithub.com/apache/camel-k/pkg/trait/builder.go:85\ngithub.com/apache/camel-k/pkg/trait.(*Catalog).apply\n\tgithub.com/apache/camel-k/pkg/trait/trait_catalog.go:117\ngithub.com/apache/camel-k/pkg/trait.Apply\n\tgithub.com/apache/camel-k/pkg/trait/trait.go:46\ngithub.com/apache/camel-k/pkg/controller/integrationkit.(*buildAction).handleBuildSubmitted\n\tgithub.com/apache/camel-k/pkg/controller/integrationkit/build.go:76\ngithub.com/apache/camel-k/pkg/controller/integrationkit.(*buildAction).Handle\n\tgithub.com/apache/camel-k/pkg/controller/integrationkit/build.go:57\ngithub.com/apache/camel-k/pkg/controller/integrationkit.(*reconcileIntegrationKit).Reconcile\n\tgithub.com/apache/camel-k/pkg/controller/integrationkit/integrationkit_controller.go:250\ngithub.com/apache/camel-k/pkg/util/monitoring.(*instrumentedReconciler).Reconcile\n\tgithub.com/apache/camel-k/pkg/util/monitoring/controller.go:71\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\tsigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\tk8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tk8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tk8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\tk8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\tk8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:99\nruntime.goexit\n\truntime/asm_amd64.s:1374\nerror during trait customization\ngithub.com/apache/camel-k/pkg/trait.Apply\n\tgithub.com/apache/camel-k/pkg/trait/trait.go:47\ngithub.com/apache/camel-k/pkg/controller/integrationkit.(*buildAction).handleBuildSubmitted\n\tgithub.com/apache/camel-k/pkg/controller/integrationkit/build.go:76\ngithub.com/apache/camel-k/pkg/controller/integrationkit.(*buildAction).Handle\n\tgithub.com/apache/camel-k/pkg/controller/integrationkit/build.go:57\ngithub.com/apache/camel-k/pkg/controller/integrationkit.(*reconcileIntegrationKit).Reconcile\n\tgithub.com/apache/camel-k/pkg/controller/integrationkit/integrationkit_controller.go:250\ngithub.com/apache/camel-k/pkg/util/monitoring.(*instrumentedReconciler).Reconcile\n\tgithub.com/apache/camel-k/pkg/util/monitoring/controller.go:71\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\tsigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\tk8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tk8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tk8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\tk8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\tk8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:99\nruntime.goexit\n\truntime/asm_amd64.s:1374","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\tsigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\tk8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tk8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tk8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\tk8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\tk8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:99"}```

**Comment by astefanutti** [comment]
IIRC, when we added Buildah support, the supported file format were `.dockercfg` and `.dockerconfigjson`. That explains the error. We should check whether the `config.json` format is now supported, or possibly improve the error message.
