### ISSUE TITLE
build camel-k on windows linux subsystem (ubuntu)

### ISSUE THREAD

**Issue by onderson** [apache/camel-k#214]
:/mnt/c/dev/go-workspace/src/github.com/apache/camel-k$ go version
go version go1.10.4 linux/amd64

:/mnt/c/dev/go-workspace/src/github.com/apache/camel-k$ dep version
dep:
 version     : devel
 build date  :
 git hash    :
 go version  : go1.8.3
 go compiler : gc
 platform    : linux/amd64

:/mnt/c/dev/go-workspace/src/github.com/apache/camel-k$ make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Fails  in the same as mentioned #213

**Comment by onderson** [comment]
@nicolaferraro ,

successful in wsl

`:/mnt/c/dev/go-workspace/src/github.com/apache/camel-k$ go build -o camel-k ./cmd/camel-k/*.go`

`:/mnt/c/dev/go-workspace/src/github.com/apache/camel-k$ ls -lh camel-k
-rwxrwxrwx 1 root root 44M Nov 13 13:38 camel-k`

**Comment by nicolaferraro** [comment]
Great @onderson! I think this is the way to go..

**Comment by onderson** [comment]
@nicolaferraro , yes it is a way but the whole build chain will be like Linux. I guess I would not be able to get an ".exe" file. I will try to see where it will go. Still wondering how CI handles this. Closing. I will keep the other issue open.

**Comment by nicolaferraro** [comment]
@onderson the Windows binary file is generated using cross-compilation, also from a Linux machine. This is what we've put in the release page.. although I've not tested it..

**Comment by onderson** [comment]
thanks @nicolaferraro , looking through the codebase now i know cross compilation. Now using an ubuntu vm. it is all good. i can build. but on windows i can not. 
Windows Subsystem Linux (again it is an ubuntu), make halts 

`sezgin@local:/mnt/c/dev/go-workspace/src/github.com/apache/camel-k$ make
Makefile:1: *** missing separator.  Stop`

So for anyone who want to build on windows, the issue is still there.
