### ISSUE TITLE
CGO and linking woes when building with newer Fedora versions

### ISSUE THREAD

**Issue by orpiske** [apache/camel-k#2140]
When building on Fedora 33, trying to run the operator image on a k3s cluster running CentOS Stream, the operator fails with:

```
kamel: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by kamel)
```

This seems to be fixed by disabling CGO for the build-kamel target on the Makefile. 

I'll send a PR with a proposed fix for this.

**Comment by astefanutti** [comment]
Fixed with #2141.
