### ISSUE TITLE
`extensions/v1beta1` Ingress is deprecated

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2157]
Running operator against OpenShift 4.6 and noticed:

    W0322 15:58:35.370055   10528 warnings.go:67] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

**Comment by astefanutti** [comment]
A draft PR is open: #2084. It must be adapted, to pass on OpenShift 3, where the newer API is not present.

**Comment by lburgazzoli** [comment]
@astefanutti missed it

**Comment by astefanutti** [comment]
@lburgazzoli no worries, I'm actually glad somebody else cares 😉.

With the recent controller-runtime upgrade (#2087), the deprecation warning are logged, which is useful to anticipate compatibility issues: https://kubernetes.io/blog/2020/09/03/warnings/.

**Comment by apupier** [comment]
Kubernetes 1.22 is planned for the 4th August: https://github.com/kubernetes/sig-release/tree/master/releases/release-1.22#tldr

**Comment by apupier** [comment]
some information to potentially help the migration https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/138#discussioncomment-1245759

**Comment by astefanutti** [comment]
The migration is rather straightforward #2084. The challenge is to handle our e2e tests execution on OpenShift 3.
