### ISSUE TITLE
Global vs local operator 

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2177]
My understanding is that global and local scoped operators can co exists and the global operator won't try to handle any camel-k resource that is created in a namespace where a Lease resource (created by the local operator) exists.

This should be ok for most of the case but assuming a local operator is installed but not started, then the Lease is not created and the global operator may start taking ownership of namespace local resources.

To avoid such problem, would it be possible to also support namespace labels ? (something similar to what knative does)

**Comment by abkieling** [comment]
Is the Lease resource created in the namespace where the local operator is running? In case, it would not work for operators that manage camel-k resources in a separate namespace.
