### ISSUE TITLE
Resource selector

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2178]
In case of a "rolling upgrade" of camel-k, where you have multiple version of the camel-k operator running and you want to move integrations from one operator to the another by steps, it may be useful to have an option to configure what resources an operator is suppose to watch by providing a label selector.

i.e. by having a selector resource on the integration platform:

```yaml
selector:
    camel.apache.com/operator.version: 1.2.3
```

**Comment by astefanutti** [comment]
It seems highly correlated to #1943, if not a duplicate.

**Comment by lburgazzoli** [comment]
yep,  I'm getting old ...
