### ISSUE TITLE
Migrate the PodDisruptionBudget trait to `policy/v1` API

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#2206]
The PodDisruptionBudget API has been promoted to `policy/v1` in Kubernetes 1.21,  with no schema changes.

The PodDisruptionBudget trait currently uses the `policy/v1beta1` PodDisruptionBudget API, that's deprecated, and will no longer be served in 1.25+. Once we upgrade to Kubernetes API v1.21, the PodDisruptionBudget trait should be migrated to using `policy/v1`.

**Comment by squakez** [comment]
dde63261f6004697e7c81dc4e50a6d56740251ea
