### ISSUE TITLE
camel-k make resulting in test failures while building runtime kotlin 

### ISSUE THREAD

**Issue by onderson** [apache/camel-k#222]
Here is the log detail;

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 16.308 s <<< FAILURE! - in org.apache.camel.k.kotlin.LoaderTest
[ERROR] load route from classpath  Time elapsed: 16.258 s  <<< FAILURE!
java.lang.AssertionError: 

Expected size:<1> but was:<0> in:
<[]>
	at org.apache.camel.k.kotlin.LoaderTest.load route from classpath(LoaderTest.kt:40)

[INFO] Running org.apache.camel.k.kotlin.dsl.IntegrationTest
[ERROR] Tests run: 3, Failures: 2, Errors: 1, Skipped: 0, Time elapsed: 8.731 s <<< FAILURE! - in org.apache.camel.k.kotlin.dsl.IntegrationTest
[ERROR] load integration with binding  Time elapsed: 5.239 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting:
 <null>
to be equal to:
 <"myRegistryEntry1">
but was not.
	at org.apache.camel.k.kotlin.dsl.IntegrationTest.load integration with binding(IntegrationTest.kt:49)

[ERROR] load integration with rest  Time elapsed: 2.026 s  <<< ERROR!
java.lang.IllegalStateException: runtime.camelContext.restConfiguration must not be null
	at org.apache.camel.k.kotlin.dsl.IntegrationTest.load integration with rest(IntegrationTest.kt:28)

[ERROR] load integration with component configuration  Time elapsed: 1.449 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting:
 <0>
to be equal to:
 <1234>
but was not.
	at org.apache.camel.k.kotlin.dsl.IntegrationTest.load integration with component configuration(IntegrationTest.kt:82)

[INFO] Running org.apache.camel.k.kotlin.extension.LogExtensionTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.084 s - in org.apache.camel.k.kotlin.extension.LogExtensionTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   LoaderTest.load route from classpath:40 
Expected size:<1> but was:<0> in:
<[]>
[ERROR]   IntegrationTest.load integration with binding:49 
Expecting:
 <null>
to be equal to:
 <"myRegistryEntry1">
but was not.
[ERROR]   IntegrationTest.load integration with component configuration:82 
Expecting:
 <0>
to be equal to:
 <1234>
but was not.
[ERROR] Errors: 
[ERROR]   IntegrationTest.load integration with rest:28 IllegalState runtime.camelContex...
[INFO] 
[ERROR] Tests run: 5, Failures: 3, Errors: 1, Skipped: 0

**Comment by lburgazzoli** [comment]
Which env ?

**Comment by lburgazzoli** [comment]
I think the problem can be fixed by setting the env var KOTLIN_JDK_HOME to point to your jdk installation.

**Comment by onderson** [comment]
It was ubuntu. Yes it helps. Thanks @lburgazzoli
