### ISSUE TITLE
Update run-from-github page to correct github example path

### ISSUE THREAD

**Issue by bfitzpat** [apache/camel-k#2230]
Found a glitch with the camel k docs up at the apache site on https://camel.apache.org/camel-k/latest/running/run-from-github.html

The path is listed as `github:apache/camel-k/examples/Sample.java` but should be `github:apache/camel-k/examples/languages/Sample.java` -- so it corresponds to https://raw.githubusercontent.com/apache/camel-k/master/examples/languages/Sample.java

Tested locally and that seems to be correct.

**Comment by bfitzpat** [comment]
Created https://github.com/apache/camel-k/pull/2231

**Comment by astefanutti** [comment]
Fixed with #2231.
