### ISSUE TITLE
Kaniko build failing on Minikube

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#226]
```
time="2018-11-16T11:11:15Z" level=info msg="step failed with error: error while evaluating condition: build failed" logger=builder phase=40 request="context-jvm:652316" step=publisher
```

Same for the other contexts. Any idea @lburgazzoli ?

**Comment by nicolaferraro** [comment]
Going to debug..

**Comment by lburgazzoli** [comment]
no idea.

btw, we need to add better logging ...

**Comment by nicolaferraro** [comment]
I think the issue is that packaging should be done into the `/workspace` path for Kaniko, that needs to share the volume with the operator.

While currently the builder uses a path like `--context=/tmp/builder-475625899/package/context`

**Comment by nicolaferraro** [comment]
Ok, as long as the build cycle include the kaniko step it's ok
