### ISSUE TITLE
Leverage KinD multi-nodes cluster setup for CI

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#2302]
Currently, all e2e tests run on single-node clusters. To closer match real clusters with multiple nodes, it would be useful to leverage KinD multi-nodes setup. Also, a couple of e2e tests would specifically benefit from being executed on a multi-nodes cluster.

This requires to setup a local container image registry. With the great work by @orpiske, it should be possible to achieve this:
https://www.orpiske.net/2021/05/camel-k-kind-and-a-local-registry/.

/cc @orpiske

**Comment by johnpoth** [comment]
[k3d](https://github.com/rancher/k3d) is also pretty handy if resource consumption is an issue. A registry can be created automatically `k3d cluster create my-cluster --registry-create`
