### ISSUE TITLE
Timeout when debugging the operator locally

### ISSUE THREAD

**Issue by johnpoth** [apache/camel-k#2315]
Operator exits with message `Failed to update lock: rate: Wait(n=1) would exceed context deadline` and stopping on a breakpoint for too long

**Comment by astefanutti** [comment]
Out of curiosity, what IDE do you use?

I've been facing that issue as well with Goland, though my understanding is that rather an issue with it not running other Go routines while one is being stepped. In my case, I step into the reconcile loop routine, and the routine that refresh the Lease used for leader election is also blocked.

**Comment by johnpoth** [comment]
I use VSCode for Go. 

From the logs, it seems the issue arrise when debugging for more than 15 seconds which is the default [LeaseDuration](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/manager/manager.go#L180). I think this [issue](https://github.com/go-delve/delve/issues/777) describes the problem in the Go debugger. From the comment section, it seems like a difficult fix

**Comment by astefanutti** [comment]
Thanks, that looks like the issue. It's likely Goland uses Delve as well.
