### ISSUE TITLE
Json marshalling is needed for Rest route and uncommented code seems to be executed

### ISSUE THREAD

**Issue by bzdgn** [apache/camel-k#2341]
I've applied the camel [rest dsl example here](https://camel.apache.org/manual/latest/rest-dsl.html#_rest_dsl_with_java) for the Camel K, the simple integration file is as follows, which fails;

```java
import org.apache.camel.builder.RouteBuilder;

public class RestRoute extends RouteBuilder {

    @Override
    public void configure() throws Exception {
        
        // rest endpoints
        rest("/status")
            .get("/hello").to("direct:hello");
        
        // routes
        from("direct:hello")
            .transform().constant("Hello World");
        
    }

}
```

However, if I add ```marshal().json()``` line to the route, it works;

```java
import org.apache.camel.builder.RouteBuilder;

public class RestRoute extends RouteBuilder {

    @Override
    public void configure() throws Exception {
        
        // rest endpoints
        rest("/status")
            .get("/hello").to("direct:hello");
        
        // routes
        from("direct:hello")
            .transform().constant("Hello World")
            .marshal().json();
        
    }

}
```

And even if I comment out the ```marshal().json()``` line, it continues to work;

```java
import org.apache.camel.builder.RouteBuilder;

public class RestRoute extends RouteBuilder {

    @Override
    public void configure() throws Exception {
        
        // rest endpoints
        rest("/status")
            .get("/hello").to("direct:hello");
        
        // routes
        from("direct:hello")
            .transform().constant("Hello World")
            //.marshal().json();
        
    }

}
```

Is there a problem with this example, or the code I've shared, or is this a bug?

I've also asked this on stackoverflow but I suspect that it may be a bug;

https://stackoverflow.com/questions/67731034/camel-k-rest-route-needs-json-marshalling-and-commented-code-executed

**Comment by bzdgn** [comment]
I'm attaching the terminal output and the operator logs here.

**Terminal output** that includes the output of the kamel ```--dev``` mode;

[Terminal Output](https://github.com/apache/camel-k/files/6558999/camel-k-terminal-on-dev-mode.txt)

**Camel K Operator logs** taken from the MiniKube;

[Camel K Operator logs](https://github.com/apache/camel-k/files/6559002/logs-from-camel-k-operator-in-camel-k-operator-784d84fdc9-vnq96.txt)

**Comment by lburgazzoli** [comment]
I tried to run the same example but it is working for me. 
I suspect there is an issue with pulling the base image for the kit, can you try to delete all the kits ?

    kubectl delete integrationkits --all
