### ISSUE TITLE
Camel K seems to fail with Knative 0.23

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-k#2343]
Probably it's because for example `messaging.knative.dev/v1beta1` is dropped and now Knative supports only `messaging.knative.dev/v1`: 
https://knative.dev/docs/reference/api/eventing/

All the examples that still use `messaging.knative.dev/v1beta1` `InMemoryChannel` are not deployable with Knative 0.23.

**Comment by astefanutti** [comment]
Yes, we have to do a round of upgrade to the latest Knative API versions, and drop the ones that have been deprecated / removed from recent Knative versions.

I've been holding it back because of #2195. We need to make sure Knative test suite runs on newest versions.

**Comment by tadayosi** [comment]
@astefanutti Is there anything we should consider for OpenShift 3 support when upgrading Knative like Ingress #2084?  Or can we simply jump into the latest version if the test suite passes?

**Comment by astefanutti** [comment]
@tadayosi we should not concern with OpenShift 3. As soon as the test suite passes with the latest version, it's good to go.

**Comment by astefanutti** [comment]
Fixed with #2424. Thanks!
