### ISSUE TITLE
Cannot update integration using kamel run

### ISSUE THREAD

**Issue by sdirbach** [apache/camel-k#2379]
Hi,

when I try to update an Integration using `kamel run` I get this error:

```
$ kamel run SimpleRestDSL.java
No IntegrationPlatform resource in <namespace> namespace
Error: integrations.camel.apache.org "simple-rest-dsl" is forbidden: User "<user>" cannot update resource "integrations/status" in API group "camel.apache.org" in the namespace "<namespace>"
```

I think this may be, because an empty status element is created for the Integration object (which may be observed using `-o yaml`)

Strange enough, but using the yaml output and piping it to the oc command works:

`kamel run SimpleRestDSL.java -oyaml|oc apply -f -`

Any idea where this may come from?

The Camel K Operator / kamel version is 1.4.0

Kind regards,
Sascha

**Comment by sdirbach** [comment]
Hi,

I did some debugging and found that the _Status.Phase_ field is set to _v1.IntegrationPhaseUpdating_ before actually updating the integration:
https://github.com/apache/camel-k/blob/release-1.4.x/pkg/cmd/run.go#L604

The status subresource of the CRD seems to be restricted to cluster admins and operators only. Shouldn't that also be allowed to users which have a namespaced admin role and/or any of these roles?:

integrations.camel.apache.org-v1-admin
integrations.camel.apache.org-v1-edit

Kind regards,
Sascha

**Comment by astefanutti** [comment]
Thanks a lot for the analysis. How exactly did you install Camel K, with the CLI or OLM?

With the CLI, that is with `kamel install`, the following roles are supposed to be aggregated to the `admin` role:

https://github.com/apache/camel-k/blob/df0216f28bb461e1b1aea77d8991ab0815690db5/config/rbac/user-cluster-role.yaml#L29

I would expect the _wildcard_ syntax to include the sub-resources, as it's used also to grant permission to the operator service account. So I would expect the operator to be unable to update the `status` sub-resource as well if it wasn't the case.

**Comment by astefanutti** [comment]
Could you provide the output of:

```
$ kubectl auth can-i update integration --subresource=status --v=9
```

**Comment by sdirbach** [comment]
Camel K was installed throgh OLM

I attached two executions of the can-i command. The first [can-i-default.log](https://github.com/apache/camel-k/files/6648040/can-i-default.log) is the default installation. The second 
[can-i-with-role.log](https://github.com/apache/camel-k/files/6648043/can-i-with-role.log)
 is after creating a custom role named foo [role-foo.yaml.txt](https://github.com/apache/camel-k/files/6648045/role-foo.yaml.txt)

**Comment by astefanutti** [comment]
Thanks. OLM is responsible for creating the aggregated roles for API resources it installs from CRDs:

https://github.com/operator-framework/olm-docs/blob/15cf01d3550e3ffc6861f9ade373081809276822/content/en/docs/Concepts/crds/operatorgroup.md#rbac

I haven't double checked it, but from the understanding that I have of the following section:

> A `<kind.group-version-edit>` ClusterRole is generated with the `create, update, patch, release` verbs on `<group> <kind>` with aggregation labels rbac.authorization.k8s.io/aggregate-to-edit: true`

is that the generated aggregating roles do not grant permission on sub-resources.

Logically, permissions on sub-resources should be granted by OLM as well. I don't see any reason to prevent operations on a sub-resource, of a resource that the user can delete.

**Comment by sdirbach** [comment]
Yes looks like OLM ignores the /status subresource while creating these roles. 

Maybe status should only be updated by the operator and not by any tooling?

**Comment by astefanutti** [comment]
> Maybe status should only be updated by the operator and not by any tooling?

That's a very good question! From a theoretical standpoint, I agree the `status` sub-resource should only be updated by the operator. In your use case, the CLI sets the Integration in a specific phase, to make the operator aware it should not perform any operation on the Integration, in order to avoid conflicting changes.

I would rather propose to use patching with optimistic locking if needed, instead of an update operation in combination with a home-made concurrency control mechanism. That would simplify Integration update from the CLI, in addition to removing the scale sub-resource RBAC requirement.
