### ISSUE TITLE
Delete knative warning when Knative is not installed

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#2397]
The operator prints periodically this info:

```
{"level":"info","ts":1623416979.434832,"logger":"camel-k","msg":"could not find any knative type in namespace camel, last error was: services.serving.knative.dev is forbidden: User \"system:serviceaccount:camel:camel-k-operator\" cannot list resource \"services\" in API group \"serving.knative.dev\" in the namespace \"camel\""}
```

It looks like an error, while it's not. That log should be suppressed.

**Comment by dimitraz** [comment]
I'm happy to take a look at this if no one else already is!

**Comment by astefanutti** [comment]
@dimitraz great, feel free to go ahead. I think we use that opportunity to revisit the `IsEnabledInNamespace` method entirely, as I doubt the current implementation is relevant.

**Comment by k0pper** [comment]
Getting this error when trying to deploy a KameletBinding onto a minikube cluster with the Camel K Operator running in the same namespace. The creation of the integrations fails and periodically prints out this message. 

> {"level":"info","ts":1633961666.2383604,"logger":"camel-k.controller.kameletbinding","msg":"Reconciling KameletBinding","request-namespace":"default","request-name":"chuck-norris-telegram-binding"}
> {"level":"info","ts":1633961666.2408755,"logger":"camel-k.controller.kameletbinding","msg":"Invoking action monitor","request-namespace":"default","request-name":"chuck-norris-telegram-binding","api-version":"camel.apache.org/v1alpha1","kind":"KameletBinding","ns":"default","name":"chuck-norris-telegram-binding"}
> {"level":"info","ts":1633961666.2700589,"logger":"camel-k","msg":"could not find any knative type in namespace default, last error was: services.serving.knative.dev is forbidden: User \"system:serviceaccount:default:camel-k-operator\" cannot list resource \"services\" in API group \"serving.knative.dev\" in the namespace \"default\""}

Any possible fixes for this one?

**Comment by claudio4j** [comment]
@astefanutti about your suggestion to revisit the `knative.IsEnabledInNamespace` function, it is my understanding this function is used in `pkg/controller/integration/platform_setup.go` to set the knative profile if knative is enabled in the ns, so in this context it looks to be doing correctly. 
WDYT to remove the log from `knative.IsEnabledInNamespace` function and print it if the user explicitly enables the knative trait but there is no knative in the namespace ?

**Comment by KuthumiPepple** [comment]
I'd like to work on this

**Comment by KuthumiPepple** [comment]
How do I reproduce this bug

**Comment by claudio4j** [comment]
@KuthumiPepple When you run the camel-k-operator in a namespace with no knative resources,it will print the mentioned output in the camel-k-operator pod log.

**Comment by KuthumiPepple** [comment]
@claudio4j So I built the operator with `make` and then followed this [guide](https://camel.apache.org/camel-k/next/contributing/local-development.html) for running the operator locally. However, when I run `kamel operator`, I do not see the error message in the logs. It seems I may be missing something or doing something wrongly.

**Comment by claudio4j** [comment]
You should just install camel-k-operator in the kubernetes cluster and watch the camel-k-operator log. The `kamel operator` is for development purposes to run the camel-k-operator locally.

**Comment by tadayosi** [comment]
@KuthumiPepple Since it's been inactive for long time, let me unassign it from you.

**Comment by KuthumiPepple** [comment]
That's OK.

**Comment by nchudasmasumo** [comment]
i am trying to create kamlet for kafka source as below 

`kamel bind kafka-source -p "source.bootstrapServers=my-cluster-kafka-brokers.kafka.svc.cluster.local:9092" -p "source.topic=kafka-push-logs" kafka.strimzi.io/v1beta1:KafkaTopic:kafka-push-logs -p "source.user=" -p "source.password="`

Getting below error logs in camel-k-operator. Is there any step am I missing here? Do I need to provide some other configuration besides?

`{"level":"info","ts":1670544567.7943175,"logger":"camel-k.controller.kameletbinding","msg":"Reconciling KameletBinding","request-namespace":"default","request-name":"kafka-source-to-kafka-push-logs"}
{"level":"info","ts":1670544567.7944477,"logger":"camel-k.controller.kameletbinding","msg":"Invoking action initialize","request-namespace":"default","request-name":"kafka-source-to-kafka-push-logs","api-version":"camel.apache.org/v1alpha1","kind":"KameletBinding","ns":"default","name":"kafka-source-to-kafka-push-logs"}
{"level":"info","ts":1670544567.7976258,"logger":"camel-k","msg":"could not find any knative type in namespace default, last error was: the server could not find the requested resource"}
{"level":"error","ts":1670544567.8029149,"logger":"controller.kamelet-binding-controller","msg":"Reconciler error","name":"kafka-source-to-kafka-push-logs","namespace":"default","error":"could not determine sink URI: kafkatopics.kafka.strimzi.io \"kafka-push-logs\" not found","errorVerbose":"kafkatopics.kafka.strimzi.io \"kafka-push-logs\" not found\ncould not determine sink URI\ngithub.com/apache/camel-k/pkg/controller/kameletbinding.CreateIntegrationFor\n\tgithub.com/apache/camel-k/pkg/controller/kameletbinding/integration.go:109\ngithub.com/apache/camel-k/pkg/controller/kameletbinding.(*initializeAction).Handle\n\tgithub.com/apache/camel-k/pkg/controller/kameletbinding/initialize.go:53\ngithub.com/apache/camel-k/pkg/controller/kameletbinding.(*ReconcileKameletBinding).Reconcile\n\tgithub.com/apache/camel-k/pkg/controller/kameletbinding/kamelet_binding_controller.go:203\ngithub.com/apache/camel-k/pkg/util/monitoring.(*instrumentedReconciler).Reconcile\n\tgithub.com/apache/camel-k/pkg/util/monitoring/controller.go:70\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227\nruntime.goexit\n\truntime/asm_amd64.s:1581","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
{"level":"info","ts":1670544608.7631521,"logger":"camel-k.controller.kameletbinding","msg":"Reconciling KameletBinding","request-namespace":"default","request-name":"kafka-source-to-kafka-push-logs"}
{"level":"info","ts":1670544608.7632976,"logger":"camel-k.controller.kameletbinding","msg":"Invoking action initialize","request-namespace":"default","request-name":"kafka-source-to-kafka-push-logs","api-version":"camel.apache.org/v1alpha1","kind":"KameletBinding","ns":"default","name":"kafka-source-to-kafka-push-logs"}
{"level":"info","ts":1670544608.7716732,"logger":"camel-k","msg":"could not find any knative type in namespace default, last error was: the server could not find the requested resource"}
{"level":"error","ts":1670544608.777633,"logger":"controller.kamelet-binding-controller","msg":"Reconciler error","name":"kafka-source-to-kafka-push-logs","namespace":"default","error":"could not determine sink URI: kafkatopics.kafka.strimzi.io \"kafka-push-logs\" not found","errorVerbose":"kafkatopics.kafka.strimzi.io \"kafka-push-logs\" not found\ncould not determine sink URI\ngithub.com/apache/camel-k/pkg/controller/kameletbinding.CreateIntegrationFor\n\tgithub.com/apache/camel-k/pkg/controller/kameletbinding/integration.go:109\ngithub.com/apache/camel-k/pkg/controller/kameletbinding.(*initializeAction).Handle\n\tgithub.com/apache/camel-k/pkg/controller/kameletbinding/initialize.go:53\ngithub.com/apache/camel-k/pkg/controller/kameletbinding.(*ReconcileKameletBinding).Reconcile\n\tgithub.com/apache/camel-k/pkg/controller/kameletbinding/kamelet_binding_controller.go:203\ngithub.com/apache/camel-k/pkg/util/monitoring.(*instrumentedReconciler).Reconcile\n\tgithub.com/apache/camel-k/pkg/util/monitoring/controller.go:70\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227\nruntime.goexit\n\truntime/asm_amd64.s:1581","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
`

**Comment by tadayosi** [comment]
This issue should be already fixed with https://github.com/apache/camel-k/commit/3652ee74813567f255e7f353a5045301e3d08ed4
