### ISSUE TITLE
Update Camel K Serverless api examples to not use --property-file

### ISSUE THREAD

**Issue by apupier** [apache/camel-k#2463]
The example https://github.com/apache/camel-k-examples/blob/main/02-serverless-api/ is using property-file deprecated option in 2 files:

https://github.com/apache/camel-k-examples/blob/b50a18ccc8ee3fcf677e99ca33ef347fede86707/02-serverless-api/test/yaks-config.yaml#L14

https://github.com/apache/camel-k-examples/blob/main/02-serverless-api/readme.didact.md

**Comment by apupier** [comment]
https://github.com/apache/camel-k-examples/pull/32

**Comment by squakez** [comment]
I think it can be closed now. @apupier?
