### ISSUE TITLE
Make sure Camel K runs on Microshift

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-k#2473]
One of the possible migration paths after dropping OCP 3.11 on CI (#1550) is [Microshift](https://github.com/redhat-et/microshift). Let's kick the tires and make sure Camel K runs on Microshift.

**Comment by tadayosi** [comment]
At this moment, Microshift lacks the internal image registry:
- https://github.com/redhat-et/microshift/issues/138
- https://github.com/redhat-et/microshift/issues/144

Camel K assumes the image registry is always available at `image-registry.openshift-image-registry.svc:5000` whenever it's a OpenShift cluster, so it doens't work on Microshift.

The Microshift team is working on the optional component loader which should provide a way to enable the image registry for the cluster. For now, let's wait for the feature to be implemented.
- https://github.com/redhat-et/microshift/pull/158

**Comment by astefanutti** [comment]
> Camel K assumes the image registry is always available at `image-registry.openshift-image-registry.svc:5000` whenever it's a OpenShift cluster, so it doesn't work on Microshift.

One idea to explore it further as a possible alternative for #1550 in the meantime it's worked out by Microshift team would be to deploy the internal registry ourselves using https://hub.docker.com/_/registry.

**Comment by tadayosi** [comment]
@astefanutti Ah nice idea!  I was rather thinking to customise the code of Microshift to directly add support for cluster-image-registry-operator, but using the same local registry used in KinD and exposing it as `image-registry.openshift-image-registry.svc:5000` sounds easier. Let me explore the idea a bit more.

**Comment by astefanutti** [comment]
> @astefanutti Ah nice idea! I was rather thinking to customise the code of Microshift to directly add support for cluster-image-registry-operator, but using the same local registry used in KinD and exposing it as `image-registry.openshift-image-registry.svc:5000` sounds easier. Let me explore the idea a bit more.

Exactly. Also the `image-registry.openshift-image-registry.svc:5000` URL is just a default that's set during installation, it can be changed in the IntegrationPlatform if that makes things easier.

**Comment by tadayosi** [comment]
With the custom docker registry and using `Spectrum` build push strategy I could build a kit into the registry. However, the integration pod creation fails with `ErrImagePull` error.

```
$ k describe po simple-5646fbd95c-7ql5x
...
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  3m2s                default-scheduler  Successfully assigned test/simple-5646fbd95c-7ql5x to racine
  Normal   Pulling    91s (x4 over 3m2s)  kubelet            Pulling image "image-registry.test.svc:5000/test/camel-k-kit-c45mm4poholli5rraht0@sha256:e5b426fea3eb53b1f210efd7e0ba924c7e3950fd9a6c5736ec9b73fcc1abcbae"
  Warning  Failed     91s (x4 over 3m2s)  kubelet            Failed to pull image "image-registry.test.svc:5000/test/camel-k-kit-c45mm4poholli5rraht0@sha256:e5b426fea3eb53b1f210efd7e0ba924c7e3950fd9a6c5736ec9b73fcc1abcbae": rpc error: code = Unknown desc = error pinging docker registry image-registry.test.svc:5000: Get "http://image-registry.test.svc:5000/v2/": dial tcp: lookup image-registry.test.svc on 127.0.0.1:53: no such host
  Warning  Failed     91s (x4 over 3m2s)  kubelet            Error: ErrImagePull
  Warning  Failed     80s (x6 over 3m2s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    66s (x7 over 3m2s)  kubelet            Back-off pulling image "image-registry.test.svc:5000/test/camel-k-kit-c45mm4poholli5rraht0@sha256:e5b426fea3eb53b1f210efd7e0ba924c7e3950fd9a6c5736ec9b73fcc1abcbae"
```

The error:

> Failed to pull image "image-registry.test.svc:5000/test/camel-k-kit-c45mm4poholli5rraht0@sha256:e5b426fea3eb53b1f210efd7e0ba924c7e3950fd9a6c5736ec9b73fcc1abcbae": rpc error: code = Unknown desc = error pinging docker registry image-registry.test.svc:5000: Get "http://image-registry.test.svc:5000/v2/": dial tcp: lookup image-registry.test.svc on 127.0.0.1:53: no such host

It must be related to the cluster's CoreDNS, but I haven't found a way to fix it. From a pod inside the same cluster the hostname resolves successfully:
```
$ k exec ubi8 -- nslookup image-registry.test.svc
Server:		10.43.0.10
Address:	10.43.0.10#53

Name:	image-registry.test.svc.cluster.local
Address: 10.43.25.142
```

**Comment by tadayosi** [comment]
OK, changing the service name of the custom registry to `image-registry.openshift-image-registry.svc` an integration starts to deploy!  It appears some extra configuration is required for CoreDNS to recognise if you want to use a different registry. For now, using the default name should be fine.

Note also we need to add `image-registry.openshift-image-registry.svc` to the insecure registries in `/etc/containers/registries.conf` to make sure crio uses http for pulling images from the registry:
```
[registries.insecure]
registries = ['image-registry.openshift-image-registry.svc:5000']
```

**Comment by astefanutti** [comment]
Awesome! I'd be curious to see how it behaves in GitHub Actions hosted runners!

Also, out of curiosity, does the monitoring stack come out of the box (in the `openshift-monitoring` namespace)?

**Comment by tadayosi** [comment]
Yes, my goal is to adapt it as a GH action and run it in a CI workflow.

> Also, out of curiosity, does the monitoring stack come out of the box (in the openshift-monitoring namespace)?

In reality, the out of the box configuration is quite austere like this:
```
$ k get po -A
NAMESPACE                                   NAME                                  READY   STATUS             RESTARTS   AGE
kube-system                                 kube-flannel-ds-m6d8g                 1/1     Running            0          6d21h
kubevirt-hostpath-provisioner               kubevirt-hostpath-provisioner-5jf7c   1/1     Running            0          6d21h
openshift-dns                               dns-default-qtpk2                     3/3     Running            0          145m
openshift-ingress                           router-default-78d9fc46bb-nz8tk       1/1     Running            0          6d21h
openshift-service-ca                        service-ca-66bcdfc59-wbtg2            1/1     Running            3          6d21h
```
By default it's far from fully functional OCP environment. That's another reason why we might need to wait for https://github.com/redhat-et/microshift/issues/144 to be done from Microshift side.

**Comment by tadayosi** [comment]
Just returned from PTO and since then I've been still distracted by other tasks. But let me update with the current status on the tasks.

- I ran e2e tests on a local microshift instance, and not surprisingly there are many test failures including `cron_test.go`.
    - That should be because there are not API resources which are necessary to pass the tests in microshift out of the box.
- I'm now in the process of finding required API resources for the e2e tests stepy by step.
