### ISSUE TITLE
V1.5.0 release without assets

### ISSUE THREAD

**Issue by drano** [apache/camel-k#2481]
I can see release 1.5.0 in https://github.com/apache/camel-k/releases but no assets related to this version. Is it normal?

**Comment by oscerd** [comment]
It is still on vote

**Comment by drano** [comment]
Where could I see votes about a release ?

**Comment by oscerd** [comment]
On the dev or users mailing list
https://camel.apache.org/community/mailing-list/

**Comment by nicolaferraro** [comment]
Released!
