### ISSUE TITLE
kamel 1.4.1 build failure

### ISSUE THREAD

**Issue by chenrui333** [apache/camel-k#2484]
```
--- FAIL: TestIsLocalFileAndExists (0.00s)
run_test.go:520:
Error Trace: run_test.go:520
Error: Expected value not to be nil.
Test: TestIsLocalFileAndExists
```

relates to Homebrew/homebrew-core#80613

**Comment by chenrui333** [comment]
Gonna try out kamel 1.5.0 build now

**Comment by squakez** [comment]
I guess it depends on the operating system and the level of permissions of the account which is executing the build. Basically the [test](https://github.com/apache/camel-k/blob/main/pkg/cmd/util_test.go#L37) is assuming that there is a permission denied on accessing the `/root/` directory. I guess we may even remove it if we're not able to reproduce the same behavior on any system, or find a way to skip it when running on non-linux OS.

**Comment by chenrui333** [comment]
This [build patch](https://github.com/apache/camel-k/pull/2561) works for me, and I restart [the 1.5.0 release update PR](https://github.com/Homebrew/homebrew-core/pull/81904)

**Comment by chenrui333** [comment]
Close the issue as my build is green now. Thanks for the help!
