### ISSUE TITLE
Documentation for `kamel local run`

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-k#2490]
I'm interested to know how we can use `kamel local run` but other than the command help there is very little documentation available for the subcommand. Can someone knowledgeable to the subcommand write documentation for it?

I'm mainly interested in:
* the main purpose,
* the prerequisites/preconditions, and
* the scope (limitations)

of the subcommand.

I once just tried `kamel local run examples/languages/Sample.java` without any connected clusters and apparently it failed.

**Comment by oscerd** [comment]
@doru1004 could give explanations and write some better documentation.

**Comment by tadayosi** [comment]
Related: #2737
