### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by 2020testuser** [apache/camel-k#2498]
Hi,
Could anyone please help me? When I install camel-k in the Kubernetes command, I'm getting this msg. How can I resolve this error? Thanks advance!!

`
kamel install --cluster-setup --registry=https://docker.repo1.uhc.com/ --wait

`
Output:
`
OLM is not available in the cluster. Fallback to regular installation.
Camel K cluster setup completed successfully
`

**Comment by tadayosi** [comment]
Looks like you are successful. `OLM is not available in the cluster. Fallback to regular installation.` just says OLM is not available in your cluster. As a next step, run `kamel install` and you'll see the camel-k operator up and running.

**Comment by tadayosi** [comment]
Can we close this?
