### ISSUE TITLE
`Kamel local` chokes on traits

### ISSUE THREAD

**Issue by pilhuhn** [apache/camel-k#2499]
`Kamel run` supports traits via modline or `-t` flag.
The local build/run fails with them.

Local option should not fail -- especially if the trait is needed for in-cluster execution and given via modline

```
% kamel version
Camel K Client 1.5.0
hrupp@snert cdi % kamel local build c-tower.yml
Modeline options have been loaded from source files
Full command: kamel local build c-tower.yml --trait=knative.channel-sinks=return-channel --dependency=mvn:com.github.pilhuhn:camel-ansible-tower:95bd0a70da --dependency=mvn:org.apache.camel.k:camel-k-knative-producer
Error: unknown flag: --trait
```

Same for `kamel local run`

**Comment by tadayosi** [comment]
It's related to #2490. At this moment it's not clear what we can expect from `kamel local run`.

My feeling with this issue, however, is that it doesn't make sense to support traits with local run, as traits are mainly for adapting _remote_ platform differences, not _local_.

**Comment by pilhuhn** [comment]
My issue is that I have the traits in the modline. Removing them from there means I will later forget to add them in remote mode.
If they make no sense locally, a warning could be printed, but `kamel local build` should not abort.

**Comment by scodeman** [comment]
This issue should not be closed, as mentionned by @pilhuhn, the local build could print a warning but not abort
