### ISSUE TITLE
CloudEvent header mapping is confusing

### ISSUE THREAD

**Issue by pilhuhn** [apache/camel-k#2501]
I am using Camel-K with knative.

Standard CloudEvent-headers show up in the header map with a `CamelCloudEvent` prefix, which is pretty unexpected.
Retrieving them as "normal" ( e.g. `ce-source`) fails.
Custom CE-headers show up without that prefix though (e.g. `ce-rhrouting`) :

`Headers: {Accept-Encoding=gzip, CamelCloudEventID=d1bd2700-a251-4dca-bce7-4cbb395bc281, CamelCloudEventSource=notifications-gw, CamelCloudEventType=com.redhat.cloud.notification.toCamel, CamelCloudEventVersion=1.0, CamelHttpMethod=POST, CamelHttpPath=, CamelHttpQuery=null, CamelHttpUri=/, Ce-Knativearrivaltime=2021-07-13T09:25:17.733927213Z, Ce-Rhaccount=54321, Ce-Rhrouting=ansible, content-length=393, Content-Type=application/json,  K-Proxy-Request=activator, User-Agent=Go-http-client/1.1,  X-Request-Id=0d28e4fb-0dcd-4db1-b27b-1c3edfa3a027}`

**Comment by lburgazzoli** [comment]
The reason is that - as far as I remember - depending on the cloud event spec version that is used, some headers have different names so at least those from the spec are mapped to `CamelCloudEvent*`, others are untouched.

We could add an option to also include the raw values
