### ISSUE TITLE
Liveness and Readiness Probes not Supported When Using HTTPS

### ISSUE THREAD

**Issue by Kyle-Cooley** [apache/camel-k#2513]
When using https to secure internal communications, it is not possible to enable health and readiness probes.

https://github.com/apache/camel-k/blob/main/pkg/trait/container.go#L267
```
		if util.IsTrue(t.ProbesEnabled) && portName == defaultContainerPortName {
			// don't set the port on Knative service as it is not allowed.
			t.configureProbes(&container, 0, defaultProbePath)
		}
```

Note that `defaultContainerPortName` is set to `http` and in this scenario it has been set to `https` (does the name matter?).

**Comment by squakez** [comment]
Closed by #2527
