### ISSUE TITLE
Reduce time for first Integration start

### ISSUE THREAD

**Issue by apupier** [apache/camel-k#2520]
During first integration deployment a lot of bom dependencies are downloaded. See https://gist.github.com/apupier/6a9fed422bba9b5fde85164055df89a8 With a simple timer example it can take 20 minutes on a not so fast network.

Maybe the container might be can be prepoluated with common ones?

**Comment by squakez** [comment]
I think it could be interesting to have a simple timer-2-log integration used to imprint the operator container. We would reduce the very first startup time. In any case I can expect 20 minutes in a local developer environment, not on a public cloud :)

**Comment by tadayosi** [comment]
While it doesn't improve the very first run, using Maven repository mirror in a cluster is a way to make subsequent runs faster.
I introduced this technique for local e2e testing:
https://camel.apache.org/camel-k/latest/contributing/e2e.html#using-nexus

**Comment by tadayosi** [comment]
Perhaps we can make Maven mirroring as the default option and preload a common set of camel jars into the mirror during kamel installation.

**Comment by squakez** [comment]
I am working on something related to the build, and we may think to find an easy way to bundle the known basic set of dependencies. We can use a similar approach on what we do with local `make images-dev`, where we copy development artifacts. As an example, we can see the following list of dependencies downloaded from a fresh 1.8.2 installation:

[1.8.2.log](https://github.com/apache/camel-k/files/8390214/1.8.2.log)

against the list of dependencies downloaded in 1.9.0-SNAPSHOT (which I created via `make images-dev`):

[1.9.0-SNAPSHOT.log](https://github.com/apache/camel-k/files/8390223/1.9.0-SNAPSHOT.log)

There is half the number of dependencies needed to download. We may even go further by finding a way to calculate automatically the rest of needed dependencies (ie, the catalog and the related boms).

**Comment by squakez** [comment]
Best practices provided in https://camel.apache.org/camel-k/next/installation/advanced/maven.html#maven-proxy and https://camel.apache.org/camel-k/next/installation/advanced/offline.html
