### ISSUE TITLE
camel-k-integration override provided groupId name in Kafka component

### ISSUE THREAD

**Issue by pcg76** [apache/camel-k#2523]
When using the Kafka component and provide a groupId, the Kafka component does not use the provided groupId. It default to using "camel-k-integration" as the groupId for Kafka instead.

**Comment by oscerd** [comment]
This is coming from https://github.com/apache/camel-quarkus/issues/2901
It's fixed in camel-quarkus, so it will be once we update the camel-k-runtime.

**Comment by orpiske** [comment]
I've just confirmed this one as fixed with the Camel K runtime 1.9. It will be fixed w/ Camel K 1.6.0 release.

**Comment by pcg76** [comment]
> I've just confirmed this one as fixed with the Camel K runtime 1.9. It will be fixed w/ Camel K 1.6.0 release.

Thank you for the confirmation 🙂

**Comment by nicolaferraro** [comment]
Fixed in 1.6.0
