### ISSUE TITLE
Multiple of the examples fail on Minikube

### ISSUE THREAD

**Issue by jeffgbradley2** [apache/camel-k#2537]
After pulling down the 1.5.0 examples and kamel program from [here](https://github.com/apache/camel-k/releases/tag/v1.5.0), and opening the polyglot folder, and running the kamel command according to the readme, the deployment fails. 

➜  polyglot ./kamel run --name polyglot routes.xml beans.groovy JavaRoute.java --dev
Integration "polyglot" created
Condition "IntegrationPlatformAvailable" is "True" for Integration polyglot: camel-basic/camel-k
Progress: integration "polyglot" in phase Initialization
Integration polyglot in phase "Initialization"
Progress: integration "polyglot" in phase Building Kit
Integration polyglot in phase "Building Kit"
Condition "IntegrationKitAvailable" is "False" for Integration polyglot: creating a new integration kit
Integration polyglot subresource kit-c41c2sgssbjmb883fs3g (Integration Kit) changed phase to "Build Submitted"
Integration polyglot subresource kit-c41c2sgssbjmb883fs3g (Build) changed phase to "Scheduling"
Integration polyglot subresource kit-c41c2sgssbjmb883fs3g (Build) changed phase to "Pending"
Integration polyglot subresource kit-c41c2sgssbjmb883fs3g (Build) changed phase to "Running"
Integration polyglot subresource kit-c41c2sgssbjmb883fs3g (Integration Kit) changed phase to "Build Running"
Integration polyglot subresource kit-c41c2sgssbjmb883fs3g (Build) changed phase to "Failed"
Integration polyglot subresource kit-c41c2sgssbjmb883fs3g (Build) changed phase to "Initialization" (recovery 1 of 5)
Integration polyglot subresource kit-c41c2sgssbjmb883fs3g (Build) changed phase to "Scheduling" (recovery 1 of 5)
Integration polyglot subresource kit-c41c2sgssbjmb883fs3g (Build) changed phase to "Pending" (recovery 1 of 5)
Integration polyglot subresource kit-c41c2sgssbjmb883fs3g (Build) changed phase to "Running" (recovery 1 of 5)
Integration polyglot subresource kit-c41c2sgssbjmb883fs3g (Build) changed phase to "Failed" (recovery 1 of 5)

**Comment by jeffgbradley2** [comment]
Still trying to get simple examples to run and failing. Only single java files seem to work, although I _can_ add a property file. XML files, Groovy files, do not work. For example:

After following the instructions for installation on Minikube found [here](https://camel.apache.org/camel-k/latest/installation/minikube.html) and [here](https://camel.apache.org/camel-k/latest/installation/installation.html#procedure) I have Minikube running and configured, and Camel K installed:

```text
➜  01-basic git:(main) ✗ k get integrationplatform
NAME      PHASE
camel-k   Ready
➜  01-basic git:(main) ✗ k get pods
NAME                                READY   STATUS    RESTARTS   AGE
camel-k-operator-784d84fdc9-9gz2c   1/1     Running   0          25m
```

Created a basic XML route below.

```xml
<routes xmlns="http://camel.apache.org/schema/spring">
    <route id="simple-xml-route">
        <from uri="timer:tick" />
        <to uri="log:info"/>
    </route>
</routes>
```

Ran the integration with `kamel`.

```text
➜  01-basic git:(main) ✗ kamel run basic.xml --dev
integration "basic" created
Condition "IntegrationPlatformAvailable" is "True" for Integration basic: camel-basic/camel-k
Progress: integration "basic" in phase Initialization
Progress: integration "basic" in phase Building Kit
Integration basic in phase "Initialization"
Integration basic in phase "Building Kit"
Condition "IntegrationKitAvailable" is "False" for Integration basic: creating a new integration kit
Integration basic subresource kit-c45csbab3g2ddljd8njg (Integration Kit) changed phase to "Build Submitted"
Integration basic subresource kit-c45csbab3g2ddljd8njg (Build) changed phase to "Scheduling"
Integration basic subresource kit-c45csbab3g2ddljd8njg (Build) changed phase to "Pending"
Integration basic subresource kit-c45csbab3g2ddljd8njg (Build) changed phase to "Running"
Integration basic subresource kit-c45csbab3g2ddljd8njg (Integration Kit) changed phase to "Build Running"
Integration basic subresource kit-c45csbab3g2ddljd8njg (Build) changed phase to "Failed"
```

**Comment by squakez** [comment]
I've tested against `1.5.0` and it works on my environment:
```
$ kamel run --name polyglot routes.xml beans.groovy JavaRoute.java --dev
....
[1] 2021-08-18 08:26:49,953 INFO  [io.quarkus] (main) camel-k-integration 1.5.0 on JVM (powered by Quarkus 2.0.0.Final) started in 5.318s. 
...
[1] 2021-08-18 08:26:51,012 INFO  [info] (Camel (camel-1) thread #0 - timer://hello) Exchange[
[1]   Id: 530D63FA65026E1-0000000000000000
[1]   ExchangePattern: InOnly
[1]   Properties: {CamelTimerCounter=1, CamelTimerFiredTime=Wed Aug 18 08:26:50 UTC 2021, CamelTimerName=hello, CamelTimerPeriod=3000}
[1]   Headers: {CamelMessageTimestamp=1629275210949, firedTime=Wed Aug 18 08:26:50 UTC 2021, MyHeader=HelloFromJava}
[1]   BodyType: String
[1]   Body: Hello from Groovy
[1] ]
```

**Comment by squakez** [comment]
I think you may have some problem in during the `Build` phase. Can you report the result of the build and the log of the `camel-k-operator`?
