### ISSUE TITLE
KAMEL_INSTALL_DEFAULT_KAMELETS behavior

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2560]
This commit https://github.com/apache/camel-k/commit/a84667ae86051ebfa757038ea8293ed6d0283962 introduce the KAMEL_INSTALL_DEFAULT_KAMELETS option but it looks like this is a build time option, is there any chance to add this flag to the install command

**Comment by tadayosi** [comment]
Looks like a good enhancement to me. Let me work on it.
