### ISSUE TITLE
Read certificates from secrets to setup TLS config for route trait

### ISSUE THREAD

**Issue by claudio4j** [apache/camel-k#2574]
Currently route trait parameters `tls-certificate`, `tls-key`, `tls-ca-certificate`, `tls-destination-ca-certificate` expects certificates to set as string parameters, but that is a difficult to set as command line parameters, example:
```
-t route.tls-key="-----BEGIN RSA PRIVATE KEY-----MIIEowIBAA..."
```

This is a proposal to read certificates from secrets to setup TLS configuration for route trait.

**Comment by squakez** [comment]
With this approach, the certificates may be provided with different means (ie, volumes mounted) as well.
