### ISSUE TITLE
Should we move to go 1.16 / 1.17 ?

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2579]

**Comment by astefanutti** [comment]
Based on my experience, I think it's safer to transitively follow the Golang version that is used by the current k8s version Camel K depends on.

**Comment by lburgazzoli** [comment]
Seems to be 1.16 from 1.21 right ?

**Comment by astefanutti** [comment]
Right, however we still depend on k8s 1.20, as we are held back by Knative that still depends on it, and cannot upgrade to 1.21 due to breaking changes. The path of least resistance would be to wait until Knative upgrade to 1.21, then we can upgrade to it, and to Golang 1.16 along with it.
