### ISSUE TITLE
Kamel `bind` step index unclear

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#2586]
I was playing with `kamel bind` command and I realized that we use 0 index start when we play with `step` properties. Ie `kamel bind ... --step my-step -p step-0.my-key=value`. For usability I think we should improve this and let the user start with 1 index instead.

**Comment by heiko-braun** [comment]
+1

**Comment by SaumyaSachdev** [comment]
Hi, I'm an Outreachy applicant and I'd like to be assigned this issue

**Comment by squakez** [comment]
Thanks for the interest. Please, reach out to me if you need any help.

**Comment by SaumyaSachdev** [comment]
Hi @squakez, I tried reaching out to you on Zulip with a few questions. Could you please help with them?

**Comment by squakez** [comment]
Hello, I've already answered in the chat, though, it's easier for me following up here asynchronously. As a reference you can used the output produced by the following statement:
```
$ kamel bind timer:foo log:bar --step first --step second -p step-0.var1=1 -p step-0.var2=2 -p step-1.vara=a -o yaml
```
We must convert that index starting with 0 to start with 1 and having the very same output. Likely a unit test as the one available at https://github.com/apache/camel-k/blob/main/pkg/cmd/bind_test.go#L61 will help you making some good TDD approach.

**Comment by SaumyaSachdev** [comment]
![makeError](https://user-images.githubusercontent.com/15673508/164042107-289b0da3-b1d9-404a-b2fd-7af5fa2ef995.png)
I'm trying to test my changes locally by building the repository and replacing the binary in my /usr/bin, however, I get this error. I was successfully able to build this project earlier. Could you please help resolve this error? I'm not sure what is wrong here

**Comment by essobedo** [comment]
@SaumyaSachdev are you still working on this issue?
