### ISSUE TITLE
Provide a way to specify exclusions for a dependency

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-k#2598]
Related #2594.
At this moment, there is no way to exclude some sub-dependencies from a dependency with Dependencies trait. There should be a case when you want to use some lib but it doesn't work well with the rest of the libs without excluding some dependents.

**Comment by squakez** [comment]
Maybe we can add a `exclusions` parameter in the trait which looks for the dependencies and remove them from the dependency list.

**Comment by lburgazzoli** [comment]
We need to be really careful about exposing such advanced feature as we did it already in the past but it ended up being hard to maintain, the ux was very bad and breaking the build was quite easy so IMHO, better to solve the issue in our catalog (especially with libraries like jolokia where the user is not even aware of what we are doing)

An alternative option could be to have the user provide a bom with an explicit dependency management section in which he can tweak every depedency however.

**Comment by tadayosi** [comment]
I agree with @lburgazzoli. The solution wouldn't have to be easy. At least if there is a way to resolve it for the users who encounter such an issue, that's fine. I like the idea of allowing the users to provide a custom bom as an advanced option.
