### ISSUE TITLE
How to define custom container specs ?

### ISSUE THREAD

**Issue by mmacphail** [apache/camel-k#2606]
Hello,

I was wondering how to define custom container specs. I followed the doc and some issues, I'm not certain how it's done in version `1.5.0`.

I want to specify the kubernetes service account used to run the pod. I tried the following syntax:
```
kamel run --trait pod.spec.serviceAccountName=test helloworld.groovy
``` 

But clearly my syntax is wrong.

**Comment by astefanutti** [comment]
You can set the service account name directly on the `.spec.serviceAccountName` field of the Integration resource.

The _pod_ trait enables to customise the container specs by passing a template from file. However it is currently a subset of the `PodSpec` struct. We'll add the ability to set the service account name from there soon.

**Comment by mmacphail** [comment]
Thank you, for now I use the following command `k edit integration helloworld` and add the service account here, which is working but a bit inconvenient.
