### ISSUE TITLE
A better name for KameletBinding

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2625]
When the KameletBinding concept was introduced in camel-k, if was meant to bind two Kamelets and nothing more, but over time we have added more capabilities, like:

- support for processing steps to transform exchanges/messages
- support to address/source from different systems so the source/sink does not need be a kamelet anymore

So I think the term KameletBinding is not more appropriate and to reduce confusion, following the discussion on the [dev mailing list](https://lists.apache.org/thread.html/rd4c2305e0a6569a633873bfe8e27483f6436e34a729e9ce1329c6816%40%3Cdev.camel.apache.org%3E), we should rename `KameletBinding` to `Binding`

**Comment by squakez** [comment]
I've just realized the the CRD type "Binding" may not be a good name. When we try to get the CR from Kube we got some error:
```
squake:~/workspace/camel-k [feat/2625]$ k get bindings
Error from server (MethodNotAllowed): the server does not allow this method on the requested resource
squake:~/workspace/camel-k [feat/2625]$ k get bindings.camel.apache.org
No resources found in default namespace.
squake:~/workspace/camel-k [feat/2625]$ k get bd
No resources found in default namespace.
```
@lburgazzoli @astefanutti wdyt? IMO we are safe to use it, but it may create some problem in the future. Since we're still in time, maybe we can call it `CamelBinding` instead.

**Comment by christophd** [comment]
What about `IntegrationBinding`?

**Comment by christophd** [comment]
I think we should avoid the name clash with the reserved K8s resource

**Comment by lburgazzoli** [comment]
Maybe Pipe ?

**Comment by squakez** [comment]
I'm thinking on `Bond`
- a connection between two surfaces or objects that have been joined together, especially by means of an adhesive substance, heat, or pressure.
- (in construction) a pattern in which bricks are laid in order to ensure the strength of the resulting structure.

**Comment by squakez** [comment]
Finally, `Pipe` seems to be more appropriate and intuitive, let's go for it. Any objection, please feel free to add a comment.
