### ISSUE TITLE
Provide a way to inject annotations/labels into child resources

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#263]
I'd like to set the labels/annotations that are put into resources (e.g. `Deployment`) created from a `Integration`.
A trait may handle this task. We need to choose if we want to propagate labels/annotations set on the `Integration` or provide a field in the spec (I tend for the first one).

**Comment by rhuss** [comment]
Looks like that Prometheus operator does something similar. Might be worth to check how they are doing it.
