### ISSUE TITLE
Remove maven wrapper and any leftover pom.xml

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#2659]

**Comment by davsclaus** [comment]
Is there actually any java or maven left here? If not we can remove this instead

**Comment by apupier** [comment]
there are java files: https://github.com/apache/camel-k/search?l=java

and it remains one pom.xml file https://github.com/apache/camel-k/blob/main/e2e/yaks/openshift/monitoring/app/pom.xml

but it does not seem at first sight that the Maven wrapper is used

**Comment by squakez** [comment]
We're still using it to generate the catalog, altough, it is also generated in Camel K runtime. I'm going to figure it out how to solve.
