### ISSUE TITLE
Flaky TestKameletBindingScale test?

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#2660]
I've noticed since a while that we may have some flaky E2E test. I'm trying to pass the checks for a PR and I am observing this behavior. Sometimes the test fails as:
```
--- FAIL: TestKameletBindingScale (153.57s)
    --- FAIL: TestKameletBindingScale/Update_binding_scale_spec (60.04s)
    --- PASS: TestKameletBindingScale/Scale_kamelet_binding_with_polymorphic_client (10.75s)
    --- PASS: TestKameletBindingScale/Scale_kamelet_binding_with_Camel_K_client (2.38s)
```
Other times it fails as (ie, https://github.com/apache/camel-k/pull/2650/checks?check_run_id=3697376158)
```
--- FAIL: TestKameletBindingScale (98.51s)
    --- PASS: TestKameletBindingScale/Update_binding_scale_spec (11.10s)
    --- PASS: TestKameletBindingScale/Scale_kamelet_binding_with_polymorphic_client (6.81s)
    --- FAIL: TestKameletBindingScale/Scale_kamelet_binding_with_Camel_K_client (0.02s)
```
I have the feeling something is not entirely working with the test itself. @nicolaferraro any idea?

**Comment by nicolaferraro** [comment]
It's not very clear what's happening from the logs. My best guess is that the only error present there is caused by a non-atomic operation in client-side apply, since that runs on a very old OpenShift.

I'll follow-up with @tadayosi on #2643 to create an OpenShift 4 action.
