### ISSUE TITLE
Enable secondary integration platforms

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#2687]
We've always considered the integration platform as a singleton resource in a namespace, indeed we set all additional platforms in phase "Duplicate", in order to just have one and easily look it up.

There are advanced cases, e.g. when you plan to do step-by-step upgrades (with optional rollback) of the integrations to newer versions of the operator, where you need to keep both operators running (each one comes with its related integration platform default properties), and move integrations one by one to the new configuration, check state and continue/rollback. That would work with #2683, but since the integration platform is singleton, the two operators need to be in different namespaces, complicating the automation of such solutions.

I'd like to add a marker label to an integration platform to specify it as `secondary`. A secondary platform is always reconciled, even in the presence of other platforms, and never gets looked up as `default` for the namespace: it needs to be requested explicitly by the integration/klb resources (I'd prefer via label/annotation, to avoid injecting new fields into spec and status of all resources from klb down to build).
Other standard platforms (without the `secondary` marker) will continue to behave as of today (i.e. only one allowed).

Wdyt @lburgazzoli , @astefanutti ?

**Comment by joes** [comment]
@nicolaferraro

Does `kamel run` have any options wrt secondary platforms? Or does the operator support traits that will make an integration run in a secondary platform?
