### ISSUE TITLE
Compact/flatten integrationkit (container image) hierarchy?

### ISSUE THREAD

**Issue by joes** [apache/camel-k#2736]
After working on one integration with some custom kamelets I have this image/integrationkit hierarchy for the running integration (the box at the bottom represents the integration).

![digraph_gc1](https://user-images.githubusercontent.com/32820/140758870-ba6fa75e-a6c8-41a5-812c-f32baf0641d6.png)

Is it fair to say that I will have a lot of integrationkits representing each stage of development/experimenting? Kits that are the result of experimenting/development will not see a lot of reuse I suspect.

Is there any way to compact multiple kits to one single integrationkit/image? For instance, if I was to take all of the integrationkit resources in k8s and merge them automatically somehow, would it then be possible to make `kamel run` use that specific integrationkit to build a container image when the integration is built?

**Comment by squakez** [comment]
Thanks for the feedback, I think it's a very valid input for us to think how to improve the overall process. As you mentioned, each layer can be seen as a further approximation to the final production stage. Indeed, the interim layers don't seem to add too much value.

I wonder if it makes sense to think about a `kamel kit compact` command which would take care to identify that chain of relationship, merging all the layers into a final image. However, I fail to see the advantage of that operation, apart of a tidier organization of the registry.

**Comment by joes** [comment]
One thing I forgot to mention is that the screenshot above shows the hierarchy right after I did a cleanup using a garbage collection script. Actually there will be even more integrationkits/images created in different branches that represent dead-ends in the development process in the container registry. 

Here's a image hierarchy/graph screenshot showing how things may end up looking in your container registry unless some basic housekeeping is attempted after developing an integration:

![image](https://user-images.githubusercontent.com/32820/142624376-7e11c639-2064-47a1-bee0-6a02d4def422.png)

**Comment by astefanutti** [comment]
@joes thanks a lot for raising this. Providing container image garbage collection / compaction is something we plan to provide.

**Comment by joes** [comment]
This should be adressed in order to make Camel K truly ready for production use.

**Comment by oscerd** [comment]
Removed stale label

**Comment by johnpoth** [comment]
> This should be adressed in order to make Camel K truly ready for production use.

I agree this is important +1. I often have to clean up my local image registry regularly.

That being said, it's hard/impossible for camel-k to know whether an integrationkit is going to be used or not in the future. We could try adding versions/tags to the integration that would help identify integrations in development so only the latest integrationkit needs to be saved.
