### ISSUE TITLE
Adding mavens settings-security.xml to the spec.build.maven is not possible

### ISSUE THREAD

**Issue by BramDeCneudt** [apache/camel-k#2747]
I'm trying to add our private nexus repository to the caml-k spec.build. I'm following the steps here: https://camel.apache.org/camel-k/latest/configuration/maven.html

Problem is that our nexus repository also requires a settings-security.xml (https://maven.apache.org/guides/mini/guide-encryption.html) which is not explained in the previous mentioned documentation page. I also tried to create a new config map from the security-settings.xml and add it to the spec.build.maven.settings but it seems that it only accepts one key/name pair.

**Comment by haanhvu** [comment]
@squakez I think I can fix this. Assign to me please
