### ISSUE TITLE
Add official documentation on Quarkus Native introduced in 1.7

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#2752]
@astefanutti I guess you may have already worked on something. As we're about to publish the blog, I think soon we will have questions and basic doubts where we will benefit from an official documentation page. Thanks!

**Comment by astefanutti** [comment]
There is a bit of documentation in the [_quarkus_ trait page](https://camel.apache.org/camel-k/next/traits/quarkus.html), and an example about [automatic rollout deployment to native integration](https://camel.apache.org/camel-k/next/traits/quarkus.html#_automatic_rollout_deployment_to_native_integration). That being said, a dedicated page focusing on the native build details would definitely be a valuable addition.

**Comment by squakez** [comment]
https://camel.apache.org/camel-k/next/running/quarkus-native.html
