### ISSUE TITLE
Document dependency on camel-quarkus (and camel)

### ISSUE THREAD

**Issue by djencks** [apache/camel-k#2759]
In the discussion around https://github.com/apache/camel-k/pull/2757 it turned out that camel-k uses in some way camel-quarkus. I believe this means that the camel-k and camel-quarkus versions are tied together in some way.

I suggest:

- adding a `camel-quarkus-version` attribute to the camel-k antora.yml component descriptor
- Adding a prominent sentence on the component landing page something like:

Camel-k version {page-component-version} depends on xref:{camel-quarkus-version}@camel-quarkus::index.adoc[] at version {camel-quarkus-version} and xref:{camel-version}@components::index.adoc[] at version {camel-version}.

Aside from answering a question I keep having :-) this will keep us from removing a version of the documentation for a subproject that is still used in some way by another subproject, even if it's not otherwise documented.

**Comment by djencks** [comment]
According to https://github.com/apache/camel-k/pull/2757#issuecomment-973903736 there's also a relationship to camel-kamelets:
```
camel-k/script/Makefile
Lines 59 to 62 in 119c1e0
 # Define here the repo containing the default Kamelet catalog (if any) 
 KAMELET_CATALOG_REPO := https://github.com/apache/camel-kamelets.git 
 # Optional branch for the default Kamelet catalog (change this to a tag before release) 
 KAMELET_CATALOG_REPO_BRANCH := v0.5.0 
```

I think this indicates a policy problem that needs to be solved by releasing camel-kamelets: I emailed the dev list about this.  Then we can have versioned documentation for camel-kamelets and link to them.

**Comment by oscerd** [comment]
Camel-kamelets is part of the vote of Camel-k, like camel-k-runtime. There is no need to have a separated vote, it doesn't make sense and having 15 days of vote + release, just for aligning documentation versions, doesn't make sense too.

**Comment by oscerd** [comment]
I think this is already solved.

**Comment by djencks** [comment]
This is complete as part of the https://github.com/apache/camel-website/issues/701 work.
