### ISSUE TITLE
How can I find the log file location in the integration pod? 

### ISSUE THREAD

**Issue by haifzhan** [apache/camel-k#2762]
I have asked a question on StackOverflow(https://stackoverflow.com/questions/70042082/where-is-the-logs-in-camel-k-integration-pod) about camel k logging and paste it here for getting help:

I have an integration pod running with kamel:

    kamel run MyRoute.java

I have log in the route

    from("...")
    .log("my log message")
I am able to check the log lines with command:

    kubectl logs my-route-85d7f65c96-rmb4z --tail=10

Then I am able to access to the pod using:

    kubectl exec -it -c integration my-route-85d7f65c96-rmb4z /bin/sh

I tried to check folder `/var/log`, unfortunately there's no related log files.

I have 2 questions on this:
- Where is the log file location in the integration pod?
- How can I specify log file location If I want to log certain lines into a separated log file?

Thanks

**Comment by squakez** [comment]
I've just answered to the the post in SO, I see also @nicolaferraro provided the same information.

**Comment by astefanutti** [comment]
> Where is the log file location in the integration pod?

Generally, containers write to `stdout` or `stderr`. That is the case for integration Pods, that rely on the [Quarkus console log handler](https://quarkus.io/guides/logging#console-log-handler) by default.

Then it depends on the container runtime that's setup for your cluster. With CRI-O, the log files are written in the `/var/log/pods` directory of the host node by default. It's `/var/lib/docker/containers` for the Docker container runtime. You can access this directory by accessing the node where the Pod is schedule, but it's also possible to mount the directory into a Pod.

> How can I specify log file location If I want to log certain lines into a separated log file?

You can configure the [Quarkus file log handler](https://quarkus.io/guides/logging#quarkus-log-logging-log-config_quarkus.log.file-file-logging), e.g.:

```
$ kamel run -p quarkus.log.file.enable=true -p quarkus.log.file.path=/tmp/trace.log
```

Some examples of Quarkus logging configuration are available at https://quarkus.io/guides/logging#examples.
