### ISSUE TITLE
Implement gosec to inspect source code for security problems

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2763]
We should add [gosec](https://github.com/securego/gosec)  to inspect source code for security problems

**Comment by lburgazzoli** [comment]
We should probably also pay a little bit more attention to golangci-lint results

**Comment by lburgazzoli** [comment]
Or maybe enable gosec linter in golangci-lint

**Comment by squakez** [comment]
I think this was resolved by #2766
