### ISSUE TITLE
Is there any resources requirements for camel-k operator Deployment?

### ISSUE THREAD

**Issue by shuhua-wang** [apache/camel-k#2768]
I am deploying the camel-k operator using helm charts provided in this repo. However I didn't find any resources requirements for the Pod of camel-k operator in the values.yaml file. Such as:

    resources:
      limits:
        cpu: 
        memory: 
      requests:
        cpu: 
        memory: 

Is there any recommendation for those requirements when using camel-k operator?

**Comment by astefanutti** [comment]
The main contributor to compute resources consumption is likely to be the Maven builds that are performed in the operator Pod (assuming you use the default build strategy). So the resource requirements should be defined accordingly. The following requirements are sensible defaults that should work in most cases:

```yaml
resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
```

Note that if you plan to perform native builds, then the memory requirements must be increased significantly. Also the CPU requirements are rather "soft", in the sense that it won't break the operator, but it'll perform slower in general.

**Comment by davsclaus** [comment]
@astefanutti that is good advice, I think its worth to add this in the documentation

There seems to be some advanced docs here about scheduling
https://camel.apache.org/camel-k/next/installation/scheduling.html
