### ISSUE TITLE
Update documentation about monitoring metrics using Prometheus Operator 0.38.0

### ISSUE THREAD

**Issue by betonetotbo** [apache/camel-k#2794]
Recently I was facing problems about monitoring metrics of my camel-k integrations.

Prometheus was not scraping metrics from new PODs. After a while, I found the source of the problem.

I was using Prometheus Operator 0.38.1, and this version (so as the version 0.38.0) has a bug, it doesn't updates Prometheus configuration when new PodMonitors come on, so Prometheus doesn't scrape metrics. The only way was restarting the Prometheus Operator (at boot it force the configuration updates always).

Here is the complete history: https://github.com/prometheus-operator/prometheus-operator/issues/4428

So, I recomending to update the Camel-K documentation at https://camel.apache.org/camel-k/1.7.x/observability/monitoring.html#kubernetes , because it says to use the version 0.38.0.

The minimum version with this fixed is: 0.39.0.

**Comment by astefanutti** [comment]
Thanks a lot for the heads-up, and sorry for all the hiccups. I think we can directly update to the latest version.
