### ISSUE TITLE
CXF Support

### ISSUE THREAD

**Issue by Nyquest** [apache/camel-k#2799]
Hi!
Will the _CXF_ be supported in new versions of Camel K? 
Now i am getting error:
`org.apache.camel.FailedToCreateRouteException: Failed to create route cxf: cxf://http://...please check your classpath contains the needed Camel component jar`
I tried on versions _1.3_ and _1.6_ and there was this problem

**Comment by oscerd** [comment]
There is no quarkus extension for cxf. I don't think so.

**Comment by Nyquest** [comment]
Thank you for your quick reply!
Sorry, I'm not very familiar with Quarkus, but what do you think of this extension: 
https://github.com/quarkiverse/quarkus-cxf.
Is it possible to someway use this solution together with Camel-K?

**Comment by oscerd** [comment]
Quarkus-cxf is an extension from quarkiverse and from the quarkus organization. I'm talking about the camel-quarkus extensions. 

https://camel.apache.org/camel-quarkus/2.5.x/reference/components.html

At the moment there is no plan of having an extension for it and I don't think the quarkiverse extension will be taken into consideration.
