### ISSUE TITLE
Use build-tags to configure what feature are included in a camel-k build

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#2801]
To make it easy to create custom build of camel-k (i.e. to remove some features) we should add appropriate build tags to the code.
As example, we could add specific build tags to strip out specific builders: 

_kaniko.go_
```go
// +build builder
// +build kaniko

// kaniko builder logic here
```

_buildah.go_
```go
// +build builder
// +build buildah

// buildah builder logic here
```

**Comment by squakez** [comment]
@lburgazzoli as we've deprecated Buildah and Kaniko and planning to remove from the code base, do you think this is still a useful issue for any other scope? if not, I think we can close it.

**Comment by lburgazzoli** [comment]
let's close it and reopen if/when needed
