### ISSUE TITLE
SEDA low performance issue

### ISSUE THREAD

**Issue by haifzhan** [apache/camel-k#2808]
Hi Camel-K team,

I have used SEDA in my route for processing high PPS(Packets per second) streaming.  Below is my code snippet, I use 5 consumers to consume events from in-memory queue. I tested PPS to 10,000 and my pod crashes 30 minutes later and complains the JVM heap space out of memory.

```
from("netty:udp://" + HOST + ":" + PORT + "?sync=false&receiveBufferSize=16777216")
  // .log("in: ${body}")
  .to("seda:next?size=5000&timeout=0&blockWhenFull=true");


  from("seda:next?concurrentConsumers=5")
  .unmarshal(myDataFormat)
  .routePolicy(myPolicy)
  .process(myProcessor)
  .choice()
  .when(body().contains(MISSING_REQUIRED_FIELDS)).to("log:warning").otherwise()
  .log("log:${body}");
```

Is there any way to tune performance? What I am planning to try is replace in-memory queue with Kafka, unfortunately I haven't found any resources to demo how to connect with Kafka for SEDA component.

Same question had asked on [StackOverflow](https://stackoverflow.com/questions/70189210/camel-k-seda-component-get-out-of-memory-error) 
Can you please have a look and help? Thanks!

**Comment by oscerd** [comment]
What do you mean with Kafka for SEDA component? Camel provides the JVM trait, with it you could set a bigger heap and at least try to fine tuning the configuration.

**Comment by haifzhan** [comment]
@oscerd Thanks for your reply. SEDA uses in-memory queue by default, I am trying to replace the in memory queue with Kafaka, is it possible?

**Comment by oscerd** [comment]
Sure, it's possible.

**Comment by haifzhan** [comment]
I don't know how to do that. My understanding is the 2nd chunk's ` from("seda:next?concurrentConsumers=5")` would contains both kafka and seda. Is there any tutorial or where I can find some sample code? Thanks

**Comment by oscerd** [comment]
Do you want to substitute seda with Kafka on the consumer side or you want to do something else? It's not really clear.

**Comment by haifzhan** [comment]
I want to substitute SEDA with Kafka on the consumer side here's the pseudo code
```
from("Netty listening on UDP")
.to("Kafa Topic");

from("SEDA taking events from Kafka Topic with multiple Consumers")
.process("My procssor")
.log();
```

**Comment by oscerd** [comment]
Well you can do something like

from(netty).to(kafka)

from(kafka).to(seda)

from(seda).process().log()
