### ISSUE TITLE
Use deprecated field of yaml schema specification instead of only modifying description

### ISSUE THREAD

**Issue by apupier** [apache/camel-k#2817]
There is a deprecated field in specification  http://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.3
it would be nice to use it instead of mentioning the deprecation only in description field like here https://github.com/apache/camel-k/blob/48422c08bc20295d09cb31694adc177726806d6b/helm/camel-k/crds/crd-kamelet.yaml#L217

it will allow various tooling to make it more visible.

**Comment by squakez** [comment]
Yeah, it would be good to have. We are generating the CRDs with some tooling and I haven't found an immediate way to declare the value is deprecated, ie `Resources []ResourceSpec `json:"resources,omitempty,deprecated"``. Not sure if it exists some struct label that is taken in consideration when we generate the CRDs.

**Comment by squakez** [comment]
Maybe we're lucky if we bump the gen-tool version: https://github.com/kubernetes-sigs/controller-tools/pull/541

Going to have a look later.

**Comment by astefanutti** [comment]
While CRD structural schemas rely on OpenAPI v3 schemas, there are some limitations. The `deprecated` field cannot be set, as documented in:

https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation

The `+kubebuilder:deprecatedversion` marker applies at the CRD level, not the field level.

**Comment by apupier** [comment]
still an important feature even if upstream doesn't provide an out of the box solution currently
