### ISSUE TITLE
Best practice to manage multiple routes in Camel-K

### ISSUE THREAD

**Issue by haifzhan** [apache/camel-k#2824]
Hi Camel-K team, 

I have a question about managing routes. As far as I know each camel-k route is written in a single file(java/groovy/...), what would be the best structure for a camel-k project?

```
my-project
    |___route_one
              |___RouteOne.java
              |___pod_template.yaml
              |___logging.properties
    |___route_two
              |___RouteTwo.yaml
              |___service_template.yaml
    |___route_three
              |___RouteThree.other_language
```
For instance, here's the commands for the 3 routes:
1. ` kamel run RouteOne.java --pod-template pod_template.yaml --property-file routing.properties`
2. For route two I need to apply the service template and then run kamel run
3. Similarly for route three, it is written by other language

Here's my question:
- What would be the best way to manage the routes status(start, stop and so on)?
- What would be the best way if I am using API to mange the routes?
- How to add test cases for each route?

Thanks so much.

**Comment by squakez** [comment]
>     * What would be the best way to manage the routes status(start, stop and so on)?
>     * What would be the best way if I am using API to mange the routes?

I guess that in both case, you can play with `Integration` CRD and the related status.

>     * How to add test cases for each route?

[YAKS](https://github.com/citrusframework/yaks) seems to be a perfect fit.

**Comment by haifzhan** [comment]
> > ```
> > * What would be the best way to manage the routes status(start, stop and so on)?
> > * What would be the best way if I am using API to mange the routes?
> > ```
> 
> I guess that in both case, you can play with `Integration` CRD and the related status.
> 
> > ```
> > * How to add test cases for each route?
> > ```
> 
> [YAKS](https://github.com/citrusframework/yaks) seems to be a perfect fit.

Thanks for reply. What is Integration CRD? Would you mind share with me a link ? Thanks!

**Comment by squakez** [comment]
Sure!
An [Integration](https://camel.apache.org/camel-k/1.7.x/architecture/cr/integration.html
) is the specification of the route and all it needs to run on a K8S cluster. The CLI will turn a route into it automatically, and you can create one on your own and play with APIs directly. As an example you can make a [dry-run](https://camel.apache.org/camel-k/next/running/running.html#no-cli-integration) and use the outcome to ingest the K8S API.

Have a look at the [definition of the CRD](https://camel.apache.org/camel-k/1.7.x/apis/camel.html#camel.apache.org/v1.Integration) if you need to tune it accordingly.
