### ISSUE TITLE
Kafka component propagating headers is supported?

### ISSUE THREAD

**Issue by doru1004** [apache/camel-k#2825]
Which version of Camel-K actually supports Kafka components that can propagate headers?

It seems that Camel added the propagate headers method here roughly 3 months ago according to GitHub:

https://github.com/apache/camel/blob/main/components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaRecordProcessor.java

It's not certain how to tell when this change will be visible to Camel-K or if it already is.

Thanks in advance for the help!

**Comment by oscerd** [comment]
It will be available when we'll switch to 3.13.0/3.14.0 of Camel, which should be in 1.8.0

**Comment by doru1004** [comment]
Sounds great thanks a lot! :)
