### ISSUE TITLE
Choose a single location for examples

### ISSUE THREAD

**Issue by oscerd** [apache/camel-k#2826]
We had some discussion here: https://github.com/apache/camel-k/pull/2731

I think it's important to have a single location for examples, because it would be much easier to maintain and also we could be able to tag them without having the camel-k release enriched with examples.

My vote is to move all the examples in the https://github.com/apache/camel-k-examples repository

But I'd like to get more feedback and votes.

**Comment by squakez** [comment]
Yes, it was something I planned to do in the past, but went out of my radar (#2462). As mentioned in that discussion, I am good with moving everything in the dedicated repository. In that case, I suggest we apply the same branching strategy of the main project.

**Comment by oscerd** [comment]
Ok, I'm going to work on this.

**Comment by astefanutti** [comment]
It sounds good to me. Having the examples promoted into their own repository will certainly make them more visible. Possibly, it'll even make things easier to setup automated testing and foster test coverage in this new repository.

**Comment by oscerd** [comment]
Do we still want to move everything in a different repository?

**Comment by squakez** [comment]
+1 for me. We can link the example folder in the new location.

**Comment by squakez** [comment]
Great, thanks @oscerd ! I wonder if we should also remove the CamelSource examples.

**Comment by oscerd** [comment]
Where are them?

**Comment by squakez** [comment]
> Where are them?

This one for instance: https://github.com/apache/camel-k-examples/tree/main/04-aws-kinesis-source-basic

**Comment by oscerd** [comment]
Yeah, I think we need to focus on kamelets and generic-examples.
