### ISSUE TITLE
Platform options

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#284]
We do not yet have a way to store platform level / global options so i.e:

- we hard-coded bits such as the camel version to use
- we can configure maven repositories at integration level only

We should be able to set such options at platform level i.e.

    kamel install --maven-repo=... --camel-version=...

We should also be able to  set such version later on

    kamel set --maven-repo=... --camel-version=...

**Comment by nicolaferraro** [comment]
I think the spec field of the integrationplatform resource is the place where we should store that options.
We already have the cluster type (Openshift/Kubernetes) and the profile to use (O/K/Knative), we can continue with info like that such as the global maven settings.
