### ISSUE TITLE
How to specify the BaseImage when creating an integration?

### ISSUE THREAD

**Issue by S96EA** [apache/camel-k#2844]
I want to use a different BaseImage(for example, a private image) instead of the default BaseImage.
I found that we can specify the platform when creating an integration ([link](https://github.com/apache/camel-k/blob/fc8aa4636ff3a95dee401d258b5e8ddf3c597020/pkg/apis/camel/v1/integration_types.go#L56)), And the platform is bound to a BaseImage ([link](https://github.com/apache/camel-k/blob/fc8aa4636ff3a95dee401d258b5e8ddf3c597020/pkg/apis/camel/v1/integrationplatform_types.go#L114)), but the BaseImage is not used because [IncrementalImageContext](https://github.com/apache/camel-k/blob/7efe4ffbfd82050acf89821846db1137c231d554/pkg/builder/image.go#L122)，this step will find the integrationKit that already exists, these integrationKits do not use the new BaseImage.
So is there any other way we can change the default BaseImage?

**Comment by squakez** [comment]
If the `IntegrationKit` was created before updating the `baseImage` for the platform, then, yes, the algorithm will choose the best matching kit in between the existing ones, whichever was the `baseImage` from which it derived from. If you need to update all the `Integration` and the related kits, the best thing you can do is to `kamel reset` which will clean all the namespace. Of course, this is a disruptive action that will wipe all your running stuff.

**Comment by S96EA** [comment]
How about adding a label to the integrationKit, which is used in the IncrementalImageContext step to filter IntegrationKits that use a certain baseImage?

**Comment by squakez** [comment]
Could be an idea in the context of the work requested for #2736
