### ISSUE TITLE
Make knative broker name configurable

### ISSUE THREAD

**Issue by claudio4j** [apache/camel-k#2864]
Make knative broker name configurable, follow on https://github.com/apache/camel-k-runtime/issues/535

**Comment by squakez** [comment]
Relates https://github.com/apache/camel-k-runtime/issues/764

**Comment by Delawen** [comment]
Can someone please open this again? @squakez

**Comment by lucamolteni** [comment]
Any news on this?

**Comment by claudio4j** [comment]
It is fixed, see [an example on how to set the custom broker name](https://github.com/apache/camel-k/blob/main/e2e/global/knative/files/knative_broker_receiver.groovy#L21).
I am closing this issue, thanks for reminding.

**Comment by lucamolteni** [comment]
@claudio4j that test seems to be present in the 1.10.2 so might I assume it's working properly in 1.10.2 or should I use another version?

**Comment by squakez** [comment]
Yes, it should be present since version 1.10 of Camel K.
