### ISSUE TITLE
Trait to override integration image name and version generated

### ISSUE THREAD

**Issue by alagusundarams** [apache/camel-k#2872]
https://github.com/apache/camel-k/blob/main/pkg/trait/builder.go#L182 it would be a great if we are provided with an option  to override the version and the image name generated by the operator. 
IntegrationKit.Name
IntegrationKit.ResourceVersion
As this will help the organizations to control the image name and version which is generated by operator.

**Comment by squakez** [comment]
This was more recently discussed in https://github.com/apache/camel-k/issues/4205 - as a result we introduced the concept of `alias` in the IntegrationKit, which can be used freely by the user.
