### ISSUE TITLE
IntegrationPlatform camel-k hardcoded name causes wrong assumptions

### ISSUE THREAD

**Issue by claudio4j** [apache/camel-k#2883]
If user creates an `IntegrationPlatform` with a name different from `camel-k` and run any integration, the kamel output shows 
`No IntegrationPlatform resource in <current ns> namespace`

kamel CLI [version.go](https://github.com/apache/camel-k/blob/main/pkg/cmd/version.go#L136) try to get the `IntegrationPlatform/camel-k`, but it should query the active/primary object in the current namespace.

**Comment by KuthumiPepple** [comment]
I would like to work on this. Can you assign it to me

**Comment by christophd** [comment]
This one has been solved with #3358
