### ISSUE TITLE
Update readiness condition based on new Camel health check format

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#2886]
The parsing of the health check results from the integration Pod(s) readiness endpoint(s) should be adapted once apache/camel#6779 is pulled.

**Comment by tadayosi** [comment]
OK, now I'm investigating why `health_test.go` always fails on CI. Is this the reason why it always does?  If so, I'm taking care of it.

**Comment by squakez** [comment]
Very very probably :)
