### ISSUE TITLE
Enabling prometheus causes KameletBindings to be stuck in status "Creating"

### ISSUE THREAD

**Issue by k0pper** [apache/camel-k#2896]
Hello,

I tried enabling Prometheus metrics with the Prometheus Trait and installing the helm prometheus release 
 

`echo '{"spec": {"traits": {"prometheus": { "configuration": {"enabled": true } } }}}' > monitoring-patch.json`
`kubectl patch integrationplatform camel-k --patch "$(cat monitoring-patch.json)" --namespace camel-k --type='merge'`
`helm install prometheus prometheus-community/prometheus --namespace camel-k`

Everything works kind of, but all the KameletBindings I try to create afterwards are stuck in the "Creating" phase. They **do** get deployed and they work as they should, but they never exit the "Creating" status. 

Without the Prometheus Trait, everything works again, why?

The Operator logs out this error:

> {"level":"error","ts":1642695960.005641,"logger":"controller-runtime.manager.controller.integration-controller","msg":"Reconciler error","name":"chucknorris-to-log","namespace":"camel-k","error":"error executing post actions: error during apply resource: &{{PodMonitor monitoring.coreos.com/v1} {chucknorris-to-log  camel-k    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[camel.apache.org/generation:1 camel.apache.org/integration:chucknorris-to-log] map[] [{camel.apache.org/v1 Integration chucknorris-to-log 5a918a18-271f-48ca-9a31-78e17a1b23f8 0xc0008d29e0 0xc0008d29e1}] []  []} { [] [{http <nil> /q/metrics  map[]   false <nil> [] [] <nil>}] {map[camel.apache.org/integration:chucknorris-to-log] []} {false []} 0}}: no matches for kind \"PodMonitor\" in version \"monitoring.coreos.com/v1\"","errorVerbose":"no matches for kind \"PodMonitor\" in version \"monitoring.coreos.com/v1\"\nerror during apply resource: &{{PodMonitor monitoring.coreos.com/v1} {chucknorris-to-log  camel-k    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[camel.apache.org/generation:1 camel.apache.org/integration:chucknorris-to-log] map[] [{camel.apache.org/v1 Integration chucknorris-to-log 5a918a18-271f-48ca-9a31-78e17a1b23f8 0xc0008d29e0 0xc0008d29e1}] []  []} { [] [{http <nil> /q/metrics  map[]   false <nil> [] [] <nil>}] {map[camel.apache.org/integration:chucknorris-to-log] []} {false []} 0}}\ngithub.com/apache/camel-k/pkg/trait.(*deployerTrait).serverSideApply\n\tgithub.com/apache/camel-k/pkg/trait/deployer.go:98\ngithub.com/apache/camel-k/pkg/trait.(*deployerTrait).Apply.func1\n\tgithub.com/apache/camel-k/pkg/trait/deployer.go:71\ngithub.com/apache/camel-k/pkg/trait.Apply\n\tgithub.com/apache/camel-k/pkg/trait/trait.go:52\ngithub.com/apache/camel-k/pkg/controller/integration.(*monitorAction).Handle\n\tgithub.com/apache/camel-k/pkg/controller/integration/monitor.go:77\ngithub.com/apache/camel-k/pkg/controller/integration.(*reconcileIntegration).Reconcile\n\tgithub.com/apache/camel-k/pkg/controller/integration/integration_controller.go:322\ngithub.com/apache/camel-k/pkg/util/monitoring.(*instrumentedReconciler).Reconcile\n\tgithub.com/apache/camel-k/pkg/util/monitoring/controller.go:71\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99\nruntime.goexit\n\truntime/asm_amd64.s:1371\nerror executing post actions\ngithub.com/apache/camel-k/pkg/trait.Apply\n\tgithub.com/apache/camel-k/pkg/trait/trait.go:54\ngithub.com/apache/camel-k/pkg/controller/integration.(*monitorAction).Handle\n\tgithub.com/apache/camel-k/pkg/controller/integration/monitor.go:77\ngithub.com/apache/camel-k/pkg/controller/integration.(*reconcileIntegration).Reconcile\n\tgithub.com/apache/camel-k/pkg/controller/integration/integration_controller.go:322\ngithub.com/apache/camel-k/pkg/util/monitoring.(*instrumentedReconciler).Reconcile\n\tgithub.com/apache/camel-k/pkg/util/monitoring/controller.go:71\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99\nruntime.goexit\n\truntime/asm_amd64.s:1371","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99"}

Alex

**Comment by astefanutti** [comment]
You need to have the Prometheus operator installed in your cluster by default, specifically the `PodMonitor` CRD.

In case, you don't want the auto-configuration of the Prometheus operator, and only need the metrics exposed, you can disable it with the `pod-monitor` option of the _prometheus_ trait, e.g. when patching the IntegrationPlatform:

```
$ echo '{"spec": {"traits": {"prometheus": { "configuration": {"enabled": true, "podMonitor": false } } }}}' > monitoring-patch.json
```

See https://camel.apache.org/camel-k/1.7.x/traits/prometheus.html#_configuration.

**Comment by k0pper** [comment]
Suggested fix works, thank you for now :)
