### ISSUE TITLE
[Docs/Website] Generate API documentation as AsciiDoc rather than html

### ISSUE THREAD

**Issue by djencks** [apache/camel-k#2898]
Currently the API documentation (e.g. https://camel.apache.org/camel-k/next/apis/camel.html) has no styling, is hard to understand for this reason, and doesn't fit in with the rest of the Antora docs.

It turns out to be moderately easy to extend the generator to generate plain text compatible with AsciiDoc and to rewrite the templates to generate AsciiDoc, with much better results.

**Comment by squakez** [comment]
Same as #2289

**Comment by djencks** [comment]
This is done on next/main: I'm planning to look into porting it to earlier versions.

**Comment by djencks** [comment]
The upstream maintainer of the generator doesn't seem to be responding to my PR, so I think we're done with this for now.
