### ISSUE TITLE
SEDA multiple threads not working

### ISSUE THREAD

**Issue by starafdar-git** [apache/camel-k#3001]
Hi Team/All,

I am using SEDA with concurrentConsumer=100 but in logs i can see only on thread , 
I wanted understand why it is showing 1 thread only in logs ? Does that means threading is not working ?
Any help would be appreciated .

**Comment by davsclaus** [comment]
You can ask for such help on the user mailing list or the zulip chat room - its a general Camel questions and not really Camel K specific.

https://camel.apache.org/community/support/

Also mind that 100 threads is very much - dont set it so high that is more threads than you have CPU cores. Also you need a lot of pending messages for more than 1 thread to be active.
