### ISSUE TITLE
Builder/Camel trait configmap/secret beside properties

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3002]
The builder trait allow you to define plain text properties that will be provided at build time. This is also available via 
```
kamel run --build-property a=1
```
It would be nice to provide the possibility to use configmap and secret as well in order to have something like:
```
kamel run --build-properties secret:my-build-props
```
The same may be applied to `camel` trait which exposes runtime `properties`

**Comment by mmelko** [comment]
I can look at this

**Comment by essobedo** [comment]
@mmelko are you still working on this issue?

**Comment by essobedo** [comment]
Should be fixed by https://github.com/apache/camel-k/pull/3626
