### ISSUE TITLE
kamel log tail option

### ISSUE THREAD

**Issue by R-Lam** [apache/camel-k#3004]
We're currently developing multiple integrations in dev environment so we need to watch logs very often, but the amount of logs retrieve from the container everytime we issue the command has started to annoy some of us.

Will be nice to have a `--tail` option just like kubectl/oc commands.

**Comment by astefanutti** [comment]
@parul5sahoo that's great! I've assigned it to you. It'd be a very useful enhancement 👍🏼.

**Comment by parul5sahoo** [comment]
@astefanutti can you share some resources that can help understand the codebase better?

**Comment by squakez** [comment]
> @astefanutti can you share some resources that can help understand the codebase better?

You can have a look here: https://github.com/apache/camel-k/blob/main/pkg/cmd/log.go#L132 likely we should introduce a `--tail` option and keep waiting for the incoming log until an interrupt signal (CTRL-C) is sent.

**Comment by parul5sahoo** [comment]
@squakez so I was looking at the codebase, was pondering whether I need to create a new flag [like this](https://github.com/apache/camel-k/blob/cb9b886f964f398e14a02965896267f07190eec2/pkg/cmd/run.go#L116) and try to incorporate that in the usage of log command ?

**Comment by squakez** [comment]
@parul5sahoo are you still working on this? If not, I will remove the assignment, so that anybody else interested can work on it.

**Comment by parul5sahoo** [comment]
Hey @squakez, I haven't got a chance to look at it.  Won't be able to work on it currently.

**Comment by squakez** [comment]
No problem, thanks for letting me know.

**Comment by essobedo** [comment]
The corresponding PR https://github.com/apache/camel-k/pull/3589
