### ISSUE TITLE
kamel client for macOS from release 1.8.0 is really 1.0.0-M4

### ISSUE THREAD

**Issue by GeraldLoeffler** [apache/camel-k#3006]
Downloading https://github.com/apache/camel-k/releases/download/v1.8.0/camel-k-client-1.8.0-mac-64bit.tar.gz and running `kamel version` returns `Camel K Client 1.0.0-M4`.

**Comment by davsclaus** [comment]
Are you sure, I just downloaded the mac client from Apache and its 1.8.0
https://www.apache.org/dyn/closer.lua/camel/camel-k/1.8.0/camel-k-client-1.8.0-mac-64bit.tar.gz

```
~/Downloads/camel-k-client-1.8.0-mac-64bit ❯ ./kamel version
Camel K Client 1.8.0
```

And its the downloads from ASF that we official support

**Comment by oscerd** [comment]
I don't have a mac available, but can you try with the github file in the release?

**Comment by davsclaus** [comment]
Also the github downloads works for me - both the regular mac and the arm mac are all 1.8.0 versions
