### ISSUE TITLE
Access channel in different namespace

### ISSUE THREAD

**Issue by himanshumps** [apache/camel-k#3009]
How do I access the channel in different namespace?

knative:channel/channel-name???

**Comment by himanshumps** [comment]
Even the knative endpoint is not working if I give the service url

**Comment by astefanutti** [comment]
Cross-namespace references to Knative channels has been added in Knative 0.22 and has yet to be supported in Camel K: #2201.

**Comment by himanshumps** [comment]
But why the endpoint reference to different namespace channel(Inmemory chanel) with svc.cluster.local does not work. If it is a post over http, it should be supported

**Comment by himanshumps** [comment]
I tried creating a kamelet binding with uri option from source channel in one workspace to destination channel in another workspace with uri option as well but that also did not work.
