### ISSUE TITLE
kamel uninstall seems to remain some resources in the cluster

### ISSUE THREAD

**Issue by catshout** [apache/camel-k#3013]
We do have 2 namespaces

camel-k for the global Camel-K Operator
integration for integrations

The Camel-K Operator has been installed in global mode in the namespace camel-k.

I did perform the following commands on our k8s cluster to cleanup the Camel-K installation ..

```
kamel reset -n camel-k
kamel reset -n integration
kamel uninstall --global --all
kubectl delete ns camel-k
kubectl delete ns integration

```

After that I did run ..

```
kubectl create ns camel-k
kubectl config set-context $(kubectl config current-context) --namespace camel-k
kubectl create secret generic kaniko-secret --from-file=/home/cas-dev-gke/kaniko-secret.json -n camel-k
kamel install --global --build-publish-strategy=Kaniko --registry gcr.io --organization cas-dev-gke --registry-secret kaniko-secret -n camel-k
```

I got a message so far ..

```
Error: Camel K seems already installed (use the --force option to overwrite existing resources): integrationplatforms.camel.apache.org "camel-k" already exists
```

It seems that something remains even after the Operator uninstall and namespace deletion.

**Comment by squakez** [comment]
I've tried the scenario a few times and sometimes it works correctly, but sometimes it fails (for me it failed with a pending service-account resource). In theory, the removal procedure is taking care of all resources:
```
$ kamel uninstall --global --all
Camel K Integration Platform removed from namespace default
Camel K Config Maps removed from namespace default
Camel K Registry Secret removed from namespace default
Camel K platform Kamelets removed from namespace default
Camel K Operator removed from namespace default
Camel K Role Bindings removed from namespace default
Camel K Roles removed from namespace default
Camel K Service Accounts removed from namespace default
Camel K Custom Resource Definitions removed from cluster
Camel K Cluster Role Bindings removed from cluster
Camel K Cluster Roles removed from cluster
```
For the time being, you please use the `--force` option to overcome the problem.

**Comment by squakez** [comment]
Tested this again and it seems the problem is a missing removal of the operator. Ideally we should have a `kamel uninstall --global --all -n camel-k` before deleting the namespace. It seems that certain clusterrole otherwise are kept in the cluster. Always perform the `uninstall` in the same namespace where it was installed and don't rely on deleting the namespace as a way of removing the operator.
