### ISSUE TITLE
Migrate to recommended OLM channel naming best practices

### ISSUE THREAD

**Issue by phantomjinx** [apache/camel-k#3017]
The OLM documentation has [recommendations](https://olm.operatorframework.io/docs/best-practices/channel-naming/) for naming of metadata bundle channels. Currently, camel-k uses a single version-named channel, eg. [stable-1.8.0](https://github.com/k8s-operatorhub/community-operators/blob/main/operators/camel-k/camel-k.package.yaml#L11). This requires users to change channel explicitly in order to upgrade.

OLM best practices recommend the following alternative approach:
- 3 channels of the form: candidate, fast (or latest) and stable where bundles would be published according to how production-ready and tested they might be. This would allow for unsupported snapshot bundles to be created for the `candidate` channel while only fully-tested releases would be available on `stable`. The `latest` channel would become the default channel where new releases are published with those releases only being added to the `stable` channel at a point when they have been sufficiently available.

**Comment by squakez** [comment]
Done in https://github.com/apache/camel-k/pull/4635 following https://olm.operatorframework.io/docs/best-practices/channel-naming/#example-2 approach (we only use stable channel).
