### ISSUE TITLE
cron.concurrency-policy does not work correctly

### ISSUE THREAD

**Issue by crosscode-nl** [apache/camel-k#3019]
When using cron.concurrency-policy with a long running route it does functionally not matter which value is chosen: 

For example, when running:

```console
kamel run timer-schedule.xml -n camel-k --trait cron.concurrency-policy=Allow
```

with route: 

```xml
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://camel.apache.org/schema/spring"
        xsi:schemaLocation="http://camel.apache.org/schema/spring http://camel.apache.org/schema/spring/camel-spring.xsd">

    <route>
        <from uri="timer:tick?period=60000"/>
        <log message="Work started"/>
        <loop>
            <constant>120</constant>
            <log message="start delay for loop: ${exchangeProperty.CamelLoopIndex}"/>
            <delay>
                <constant>60000</constant>
            </delay>
        </loop>
        <log message="Work completed"/>
    </route>
</routes>
```

It will create the cron job with concurrency policy: Allow , but the route will be restarted every minute anyway. Same goes for Forbid. CronJob contains Forbid as concurrency policy, so that works but the route still stops every minute instead of going on. 

What is the purpose of this trait if for any value this route gets stopped? Do I understand this feature correctly if I expect when Replace is set that the route is stopped and replaced with the new route, but when forbid is chosen nothing should happen to the route and no new route is started, and when allow is chosen that each time 1 minute is reached?

**Comment by squakez** [comment]
I think you're missing to provide some scheduler, ie `-t cron.schedule="0/1 * * * *"`. In theory the `cron.auto` option (which default to true) should however have calculated that on the `timer` component. I think it can be some sort of bug, in the while you can specify the `schedule` option.

**Comment by crosscode-nl** [comment]
I don't think the bug is related to timer calculation. The bug is related to how the concurrency policy works. The Camel route seems to behave like it always is configured Replace. It is dissonant with what is configured in Kubernetes. It does not understand Forbid and Allow. The route will always be aborted and restarted.

**Comment by squakez** [comment]
I think the problem with that route is the default value of `cron.active-deadline-seconds` property which is set to 60 seconds. That value will shutdown the route even if the workload is not complete. In order to prevent that, you need to set it to higher value. I've tested and it worked successfully in Camel K > 1.9 versions.

**Comment by pai911** [comment]
@squakez Hi!  is it possible to remove this trait completely? Sometimes it's hard to predict how long a job will run,

**Comment by squakez** [comment]
> @squakez Hi! is it possible to remove this trait completely? Sometimes it's hard to predict how long a job will run,

Sure. Run with the cron trait `enabled` property as `false`.
