### ISSUE TITLE
More user-friendly error messages for `kamel local` subcommands

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-k#3028]
For example:
```sh
$ kamel local build hello.groovy 
base directory that holds the base image Dockerfile has not been set correctly
```
what it really needs here is to pass `--image` option.

**Comment by cornelia247** [comment]
hello! please can this be assigned to me?

**Comment by bjethwan** [comment]
% kamel local build --image=docker.io/bjethwan/hello hello.groovy
failure while building project: exit status 1

**Comment by tadayosi** [comment]
See https://github.com/apache/camel-k/issues/3307 for capturing an use case to be improved.

**Comment by tadayosi** [comment]
@cornelia247 Do you still plan to work on this?  Since it's been inactive for long time, if you don't plan to work on any longer I'll clear the assignment.
