### ISSUE TITLE
Camel Pluggable Properties Source Feature: How to provide credentials for different cloud providers 

### ISSUE THREAD

**Issue by oscerd** [apache/camel-k#3031]
In Camel 3.16.0, we'll bring the ability of retrieving secrets directly from cloud providers secret manager/vault services (AWS Secrets Manager/GCP Secrets Manager/Azure Key Vault and Hashicorp Vault).

As reported by @astefanutti:

> In the case where AWS Secrets Manager in used in EKS, which I assume would be most of the cases for Camel K (is it really?), it seems there is a mechanism to auto-inject the credentials into Pods using AWS Secrets and Configuration Provider (ASCP):
> 
> https://docs.aws.amazon.com/secretsmanager/latest/userguide/integrating_csi_driver.html
> 
> Generally, it seems that for any of the supported vault providers, the solution would be based on the Secrets Store CSI driver: 
> 
> https://secrets-store-csi-driver.sigs.k8s.io/

This issue is a placeholder, to discuss how to provide the credentials and what would be the best strategy.

**Comment by oscerd** [comment]
AWS Secrets Manager Vault merged - for 1.11.0 and 1.10.1
GCP Secret Manager - To be done
Azure Key Vault - To be done

**Comment by squakez** [comment]
I think this is now complete, is it so @oscerd?
