### ISSUE TITLE
wrong XSD url generated with XML initialiser

### ISSUE THREAD

**Issue by brunoNetId** [apache/camel-k#3093]
Running the command:

`kamel init sample.xml`

generates the following XML root node:

```
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://camel.apache.org/schema/spring"
        xsi:schemaLocation="
            http://camel.apache.org/schema/spring
            http://camel.apache.org/schema/spring/camel-spring.xsd">
```

According to the Camel K team, the scheme generated should be HTTPS (instead of HTTP)

**Comment by rnetuka** [comment]
PR (main): https://github.com/apache/camel-k/pull/3102
PR (release-1.8.x): https://github.com/apache/camel-k/pull/3101

**Comment by squakez** [comment]
Thanks @rnetuka!! FYI, you can just create a PR on main and tag with the backport label to have it backported automatically.

**Comment by oscerd** [comment]
It won't work. It will only work if the branch has been pushed on this repository, if it's from a fork it won't.

**Comment by squakez** [comment]
> It won't work. It will only work if the branch has been pushed on this repository, if it's from a fork it won't.

Ah, okey, now I understand why it failed for me once! Thanks!
