### ISSUE TITLE
Nightly builds in test docker repo

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3106]
I'm recovering the nightly builds and I've noticed we're publishing them into some `testcamelk/camel-k` repository (see https://hub.docker.com/r/testcamelk/camel-k/tags). I wonder if we should instead use the official repo (apache/camel-k). I don't know if there is any policy limitation though from the foundation.

Then, another thing I noticed is that we are not using `latest` tag at all. I think we should label the latest stable release with this tag as well.

@astefanutti @oscerd @lburgazzoli any thought?

**Comment by squakez** [comment]
Thanks @oscerd. I've managed to setup a single nightly release which is pushing to `testcamelk` repo. That configuration is taken from some organization secret (see https://github.com/apache/camel-k/blob/main/.github/workflows/release.yml#L52-L53). Can you please tell me if we have the equivalent for `camelk/camelk` staging as you were suggesting? replacing that should be enough to publish the nightly in the staging repo.

**Comment by oscerd** [comment]
I don't think we have something like that for camelk/camelk. We need @nicolaferraro for this purpose, because he set up the original account.

**Comment by astefanutti** [comment]
@oscerd Now that we have a single rolling tag, would that be acceptable to push it in `apache/camel-k`? That may not be obvious for users that `camelk/camelk` is legit, and requires the prudent ones to do their own research to assess whether it's fishy or not.

**Comment by oscerd** [comment]
Yes, it makes sense totally sense now.

**Comment by squakez** [comment]
Do we already have the secret configured for that account?

**Comment by squakez** [comment]
@oscerd is it something already present in the setting of the project as it happens for `TEST_DOCKER_HUB_USERNAME`? Thanks.

**Comment by oscerd** [comment]
As far as I know no. The only case when we push on docker is when we release.. so it is done with personal accounts. We ask Infra to enable some accounts of the PMC.

**Comment by squakez** [comment]
Great, thanks. Let me know when we have any news so we I can do the needed changes. In the while we can use the testing docker hub. I've just checked and it replaces correctly the image.

**Comment by squakez** [comment]
Hi @oscerd can I ask you if you have any update on this one? Thanks in advance.

**Comment by oscerd** [comment]
I didn't ask to Infra. I would probably first ask to @zregvart because he's the expert about Infra and credentials.

**Comment by zregvart** [comment]
There are some notes on this towards the bottom of [this document](https://infra.apache.org/github-actions-secrets.html).
The ASF policy [allows](https://www.apache.org/legal/release-policy.html#compiled-packages) distribution of compiled binaries, for end user convenience. For snapshot builds we need to carefully [steer end users away](https://www.apache.org/legal/release-policy.html#publication) as they are not official voted-upon releases, so make sure to indicate that these are only for development/testing.

**Comment by squakez** [comment]
> There are some notes on this towards the bottom of [this document](https://infra.apache.org/github-actions-secrets.html). The ASF policy [allows](https://www.apache.org/legal/release-policy.html#compiled-packages) distribution of compiled binaries, for end user convenience. For snapshot builds we need to carefully [steer end users away](https://www.apache.org/legal/release-policy.html#publication) as they are not official voted-upon releases, so make sure to indicate that these are only for development/testing.

Thanks @zregvart . I see in the example it mentions the usage of certain secrets (`DOCKERHUB_USER` and token `DOCKERHUB_TOKEN`), but they must be provided in the configuration setting. As I understand from a previous comment from @oscerd, we don't have them set. The official release process is done with personal user accounts, so, if we want to proceed ahead we will need to ask those credentials.

**Comment by squakez** [comment]
I've provided some detail in the release notes to let people know the test account is the one we use. We can keep it as it is I guess.
