### ISSUE TITLE
Nightly tag failure

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3107]
I'm trying to setup a nightly job to add a tag on our repo (which would trigger the nightly release process). [It is failing](https://github.com/apache/camel-k/actions/runs/1966158447) because of the following failure:
```
rickstaa/action-create-tag@v1 is not allowed to be used in apache/camel-k. Actions in this workflow must be: within a repository owned by apache, created by GitHub, verified in the GitHub Marketplace or match the following: */*@[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]+, AdoptOpenJDK/install-jdk@*, JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92, TobKed/label-when-approved-action@*
```
@oscerd or anybody else with admin privileges, do you know if we can include such an action in GH settings? or alternatively if there is any similar action we can use to tag the project in GH actions.

**Comment by oscerd** [comment]
I don't think it is possible to allow gh action with write access to an Apache repository. We can try to ask to ASF Infra.

**Comment by astefanutti** [comment]
What's the strategy to maintain the nightly tags? While I see the value of having a single / updated nightly tag, I don't think polluting the repository with unbounded nightly tags would have neither value from the end users standpoint, nor the project developers.

**Comment by squakez** [comment]
Yeah, I was thinking that maybe we can just do that manually on demand, whenever we think it has some value? At the moment it is as simple as pushing a tag on the `main` branch.

**Comment by astefanutti** [comment]
I think the real need for users is to have a single "rolling" `latest` and/or `nightly` tags. Ideally this would be done in CI automatically.
