### ISSUE TITLE
E2E failing in release-1.8.x

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3120]
Several fails are happening in `release-1.8.x` branch e2e testing:

https://github.com/apache/camel-k/runs/5542672234?check_suite_focus=true
https://github.com/apache/camel-k/runs/5542672426?check_suite_focus=true
https://github.com/apache/camel-k/runs/5542672190?check_suite_focus=true

**Comment by tadayosi** [comment]
Since it's become stable in release-1.9.x and main let's close this.
