### ISSUE TITLE
Support operator hub bundle format in `make bundle`

### ISSUE THREAD

**Issue by valdar** [apache/camel-k#3128]
Would be nice to support operator hub bundle format (i.e.  https://github.com/k8s-operatorhub/community-operators/tree/main/operators/camel-k/1.8.2/manifests) with `make bundle` target.

**Comment by phantomjinx** [comment]
This has been done. All versions have been converted to bundle format.
Outstanding Items to be included in new releases:
1. Rename the CRDs and manifest to conform to what's generated by `make bundle` to make copying easier.
2. Add the tests directory containing OLM scorecard tests generated by `make bundle`.

**Comment by phantomjinx** [comment]
This has been completed. Please close.
cc @squakez @christophd
