### ISSUE TITLE
Camel K operator scaling documentation

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3133]
Scaling the Camel K operator should be easily performed via:
```
kubectl scale deployments camel-k-operator --replicas 2
```
However, we may provide some insightful documentation on the basics (ie, how the builds are performed, the resource reconciled, etc...)

**Comment by parul5sahoo** [comment]
Hey @squakez, I would like to work on this issue. But I am a bit new to the community so would require some time and useful resources to draft the docs.

**Comment by squakez** [comment]
Thanks for your interest! In this case we only have the source code which can let use understand better how the scaling is performed. If you're looking for an entry level issue, I'd sugges to look at "[good first issue](https://github.com/apache/camel-k/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)" label instead.

**Comment by Arshita-CHD** [comment]
Hey @squakez, could you assign this issue to me, I would love to work on it.

**Comment by squakez** [comment]
Sure, although as commented previously, this issue may require some expertise or deep code digging in order to reverse engineer the behavior of the feature. Do you still want to give it a try @Arshita-CHD ?

**Comment by Arshita-CHD** [comment]
I would love to give it a try

**Comment by squakez** [comment]
Issue no longer needed after recent multi operator refactoring.
