### ISSUE TITLE
`make build-resources` does not work on Windows

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#3134]
The build on Windows fails because the `build-resources` target fails. The package name computed in the following location is not correct:

https://github.com/apache/camel-k/blob/8fcf47c258c00ae3671929ba018ba8aeee79772d/cmd/util/vfs-gen/main.go#L117

**Comment by SubhasmitaSw** [comment]
I was experiencing the same issue and looking for solutions; I'd want to address this because my primary development environment is on a Windows PC. 
@astefanutti, could you kindly offer a brief description of the prospective solution you want, as well as any references?

**Comment by astefanutti** [comment]
@SubhasmitaSw I can see two possible work-around that I'd like to be confirmed:
* Copy the `script/Makefile` into the project root directory and try to run from there
* Overwrite the Makefile symlink at the project root directory with one created by `mklink`: https://docs.microsoft.com/fr-fr/windows-server/administration/windows-commands/mklink

Another option would be to run the commands from the `script` directory, but that requires to make all the paths relative to the location of the Makefile, which may not be straightfoward: https://stackoverflow.com/questions/18136918/how-to-get-current-relative-directory-of-your-makefile

**Comment by SubhasmitaSw** [comment]
@astefanutti could you please assign this to me, I'd start working on it.

**Comment by astefanutti** [comment]
@SubhasmitaSw great, assigned :)

**Comment by SubhasmitaSw** [comment]
@astefanutti this issue description should now be changed to address the major problem, isn't it?

**Comment by astefanutti** [comment]
@SubhasmitaSw I've updated the issue title and description. Let me know if that's correct.

**Comment by SubhasmitaSw** [comment]
@astefanutti  Yes, It looks good now. One things, is this still to be considered a `good-first-issue`?

**Comment by astefanutti** [comment]
> @astefanutti Yes, It looks good now. One things, is this still to be considered a `good-first-issue`?

@SubhasmitaSw I was inclined to be optimistic, but I infer from your comment that you suggest it may not qualify :) I trust your feedback and let's remove the label 👍🏼.

**Comment by tadayosi** [comment]
@SubhasmitaSw Do you mean `status/never-stale`?

**Comment by SubhasmitaSw** [comment]
@tadayosi yes

**Comment by phantomjinx** [comment]
Fixing this issue while looking into #3364

**Comment by phantomjinx** [comment]
https://github.com/apache/camel-k/pull/3823

**Comment by squakez** [comment]
According to the last comment, this is solved. Closing.
