### ISSUE TITLE
Use Kubernetes recommended labels 

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#3137]
We set a number of labels on the Camel K operator manifest itself, but also on the resources created by the operator.

We should aim at conforming to the Kubernetes recommended labels and deprecated the redundant ones: 

https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

**Comment by desirekaleba** [comment]
Hi @astefanutti,

I am an Outreachy applicant expressing my interest in this project.

Would you please assign me this task?

**Comment by astefanutti** [comment]
@desirekaleba Great! assigned to you 👍🏼.

**Comment by desirekaleba** [comment]
Thanks, @astefanutti,

Would you provide more light on how to go about the issue, please?

**Comment by Gre8t** [comment]
hi @astefanutti can I and @desirekaleba work together on this. I am  Also an applicant.

**Comment by astefanutti** [comment]
> hi @astefanutti can I and @desirekaleba work together on this. I am Also an applicant.

@Gre8t that's better to have one applicant per issue so we can track contributions more easily. There are other issues labelled "good first issue" that you may want to work on. Thanks for your understanding.

**Comment by Gre8t** [comment]
ok, I understand.
