### ISSUE TITLE
Prepare for releasing Camel-K with Camel 3.16.0

### ISSUE THREAD

**Issue by oscerd** [apache/camel-k#3138]
First we'll need a new Camel Quarkus release I suppose. 

But it's better to check, we moved some components from camel-k-runtime to Camel and we need to double check.

@astefanutti @lburgazzoli @squakez

**Comment by squakez** [comment]
Yes, likely we need camel->camel-quarkus->camel-k-runtime train released before applying the changes to camel-k.

**Comment by oscerd** [comment]
First PR on camel-k-runtime: https://github.com/apache/camel-k-runtime/issues/805

Using the staging 2.8.0 camel-quarkus.
