### ISSUE TITLE
Prometheus trait usage example

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3144]
Provide some example to show how to use the trait. See other examples in https://github.com/apache/camel-k/tree/main/examples/traits as a reference.

**Comment by Deepthi562** [comment]
I'm interested in solving this...can I be assigned with this?

**Comment by squakez** [comment]
> I'm interested in solving this...can I be assigned with this?

It is already solved. Thanks for you interesest. Feel free to look at any other issue though.
