### ISSUE TITLE
Update the DSL yaml doc about the extension section

### ISSUE THREAD

**Issue by claudio4j** [apache/camel-k#3151]
It mentions class `org.apache.camel.k.loader.yaml.parser.ProcessorStepParser` which doesn't exist in camel-k-runtime anymore.
https://camel.apache.org/camel-k/1.6.x/languages/yaml.html#_extending_the_dsl

yaml dsl [was moved to camel ](https://camel.apache.org/components/3.11.x/others/yaml-dsl.html)

**Comment by Gre8t** [comment]
hhm, I don's seam to find where this class `ProcessorStepParser` is mentioned on the link provided. Can you please shed more light on this?

**Comment by claudio4j** [comment]
@davsclaus when the camel-knative was [migrated from camel-k-runtime to camel](https://github.com/apache/camel/pull/6749), was it intended to remove support for [extending the dsl](https://github.com/apache/camel-k-runtime/blob/main/docs/modules/languages/pages/yaml.adoc#extending-the-dsl) ?
If yes, I think we can remove that doc section.

**Comment by davsclaus** [comment]
@claudio4j yes thanks that is not supported anymore, we. should remove that doc section

cc @lburgazzoli

**Comment by claudio4j** [comment]
Thanks Claus, this is [the PR](https://github.com/apache/camel-k-runtime/pull/881).
