### ISSUE TITLE
Local dependencies examples

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3167]
We should include some example related to the local dependencies feature.

_Originally posted by @squakez in https://github.com/apache/camel-k/pull/2835#pullrequestreview-928614436_

**Comment by squakez** [comment]
cc @johnpoth

**Comment by johnpoth** [comment]
Thanks @squakez ! I was about to create some follow up stories!

So I think the example could easily be constructed from one of the IT [test](https://github.com/apache/camel-k/blob/d6660dc7a2bda3b824b24ae5f80ccf15cc6e305e/e2e/registry/registry_maven_wagon_test.go#L123). Mentioning CLI [configuration](https://github.com/apache/camel-k/blob/26423a26f5244170912df372214d60e92602c4d5/docs/modules/ROOT/pages/cli/cli.adoc#image-registry) would be useful IMO as most enterprise registries require AUTH or extra CAs, thanks!

**Comment by johnpoth** [comment]
Ideally the example should showcase both a JAR and some sort of a data [file](https://github.com/apache/camel-k/blob/d6660dc7a2bda3b824b24ae5f80ccf15cc6e305e/e2e/registry/registry_maven_wagon_test.go#L92) (maybe a CSV)

**Comment by KuthumiPepple** [comment]
I'd like to work on this

**Comment by squakez** [comment]
> I'd like to work on this

Just assigned, thanks!

**Comment by squakez** [comment]
Probably already covered in the docs: https://camel.apache.org/camel-k/next/configuration/dependencies.html#local-remote-dependencies
