### ISSUE TITLE
Split Operator binary from Kamel CLI binary

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3175]
Right now we use `kamel` binary as both the operator binary to be executed on the Pod and as the CLI we ship to final user. Although the size of the file is not yet too big (around 30 MB), I think we could benefit from having 2 separate binaries, the CLI to be shipped to the users and the operator to be bundled into the container image.

Reactions?

**Comment by oscerd** [comment]
Frankly, at this stage, I don't see a good reason for doing it.

**Comment by squakez** [comment]
Thanks @oscerd. Just to complete the quick description above, the idea would not to break the project in separate subprojects, but have the same release cycle and procedure. The only thing is that we will build 2 deliverables which serve different concerns.

**Comment by tadayosi** [comment]
Removing the stale label as it still seems to be worth exploring.

**Comment by squakez** [comment]
@tadayosi , FYI, you can also add `status/never-stale` in order to avoid it become stale again in the future.

**Comment by squakez** [comment]
Implicitly included in the will to move part of the CLI running logic into Camel JBang. Closing.
