### ISSUE TITLE
Image Registry

### ISSUE THREAD

**Issue by johnpoth** [apache/camel-k#3176]
When pushing artifacts to the Image Registry from the Kamel CLI it would be cool if we could retrieve the image push secret and CAs tied to the Image Registry that are stored in the *IntegrationPlatform* CR and pass them on to Spectrum. 

Currently the user has to set this up [manually](https://github.com/apache/camel-k/blob/26423a26f5244170912df372214d60e92602c4d5/docs/modules/ROOT/pages/cli/cli.adoc#image-registry).

Thanks !

**Comment by Gre8t** [comment]
Yeah, this should be checked during `kamel install`. If no CR is present then we can use the flags to set this up.

**Comment by tadayosi** [comment]
Let's mark this as never-stale.

**Comment by squakez** [comment]
No longer relevant. The feature has been deprecated.
