### ISSUE TITLE
OLM basic installation integration test

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3180]
We are already covering the `upgrade` procedure when providing an OLM-based installation. We should leverage that test case and provide a more basic one to cover the simple installation only. It can be later extended with further coverage on other features related to the OLM installation.

**Comment by tadayosi** [comment]
OLM test coverage is not enough, so let's mark this as never-stale.

**Comment by bouskaJ** [comment]
@squakez we already have https://github.com/apache/camel-k/blob/main/e2e/install/olm/olm_install_test.go. Maybe it solves this issue. Can you check it?

**Comment by squakez** [comment]
Yeah, a think that one also cover installation phase.
