### ISSUE TITLE
Add `.status.observedGeneration` to Camel K CRDs

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#3182]
It's considered a best practice to add a `.status.observedGeneration` field to CRDs that define a status sub-resource, and that is updated with the latest `.metadata.generation` value at each reconciliation.

**Comment by tejaswari7** [comment]
I would like to work on this issue. Please assign it to me

**Comment by SubhasmitaSw** [comment]
Currently, I'm working on this @tejaswari7

**Comment by astefanutti** [comment]
@tejaswari7 I forgot to update the issue as @SubhasmitaSw started working on this few days ago. Feel free to pick another good first issue.

**Comment by astefanutti** [comment]
Fixed with #3218.
