### ISSUE TITLE
Improve the reliability of e2e tests by installing operator globally as a pre-requisite.

### ISSUE THREAD

**Issue by phantomjinx** [apache/camel-k#3183]
Tests on the cluster can randomly fail due to a variety of issues that never get repeated (even in the same test suite), eg. the catalogsource is slow to spin up and the test timesout. Since the e2e tests are less about the installation of the operator and more about the types of resource exposed to it, it seems prudent to try and improve reliability (and even performance) by installing the operator as a global pre-requisite for most tests for which it itself is not under test, ie. those tests where it is the main test target such as `builder`.

**Comment by tadayosi** [comment]
I believe #3382 addressed the issue. Lets close it.
