### ISSUE TITLE
kamel init - Use camelCase for yaml created sample files

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#3206]
The camel DSL for yaml is aligning to use camelCase ;)

The kamelet init command outputs code that uses dash case

These 2 files
https://github.com/apache/camel-k/blob/main/resources/templates/kamelet.tmpl
https://github.com/apache/camel-k/blob/main/resources/templates/yaml.tmpl

change the following from -> to
set-body -> setBody
set-header -> setHeader

**Comment by SarveshLimaye** [comment]
Hey @davsclaus can I work on this issue ?

**Comment by davsclaus** [comment]
@SarveshLimaye yes sure you are welcome to work on this

**Comment by squakez** [comment]
We have many more places where to apply the replacement. I suggest we target a replacement in all the project.
