### ISSUE TITLE
[E2E] Split integration test suite for kubernetes and openshift CI workflows

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-k#3210]
Now that GH Actions allows partial re-runs of workflows for only failed ones, it should be beneficial to split long-running workflows such as `kubernetes` and `openshift` into smaller jobs, so that only failed set of tests can be re-run.
https://github.blog/2022-03-16-save-time-partial-re-runs-github-actions/

Currently `kubernetes` and `openshift` workflows run this set of integration tests in one job:
```
test-integration: build
	STAGING_RUNTIME_REPO="$(STAGING_RUNTIME_REPO)" \
	go test -timeout 60m -v ./e2e/common -tags=integration $(TEST_INTEGRATION_COMMON_RUN) && \
	go test -timeout 60m -v ./e2e/common/build -tags=integration $(TEST_INTEGRATION_COMMON_BUILD_RUN) && \
	go test -timeout 60m -v ./e2e/common/cli -tags=integration $(TEST_INTEGRATION_COMMON_CLI_RUN) && \
	go test -timeout 60m -v ./e2e/common/config -tags=integration $(TEST_INTEGRATION_COMMON_CONFIG_RUN) && \
	go test -timeout 60m -v ./e2e/common/languages -tags=integration $(TEST_INTEGRATION_COMMON_LANG_RUN) && \
	go test -timeout 60m -v ./e2e/common/traits -tags=integration $(TEST_INTEGRATION_COMMON_TRAITS_RUN)
```

**Comment by desirekaleba** [comment]
Hi @squakez,

Can I work on this?

**Comment by squakez** [comment]
> Hi @squakez,
> 
> Can I be assigned to this?

Sure, thanks!

**Comment by tadayosi** [comment]
It's already partially done by being split into common, install, builder, and knative. Let's close it for now.
