### ISSUE TITLE
Add e2e test for kamel run --dev in a warmed-up environment

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-k#3211]
Once an integration is built and the kit is available, `kamel run --dev` should start up really fast, in the order of seconds. E2E test should cover this scenario.

**Comment by squakez** [comment]
We already have Dev mode tests: https://github.com/apache/camel-k/blob/main/e2e/common/cli/dev_mode_test.go - or were you thinking at something different?

**Comment by tadayosi** [comment]
Yes, our QE thinks that we advertise the dev mode starts an integration really fast in the second run or later, i.e. in 1s, but there is no such e2e test that verifies the scenario.

I plan to add another test to `dev_mode_test.go` which runs an integration twice in dev mode and then verifies the second run starts in the order of seconds, say 10s.

**Comment by tadayosi** [comment]
Now I think it's a good candidate task for the internship program. If anyone has an interest to work on this, I'm willing to help you.

**Comment by haanhvu** [comment]
> Now I think it's a good candidate task for the internship program. If anyone has an interest to work on this, I'm willing to help you.

@tadayosi I'll do this!

**Comment by haanhvu** [comment]
@tadayosi hey I have 2 questions:
- We need to test on both the dev mode and the remote dev mode, or just the dev mode?
- What can I use to show the start-up time?

**Comment by tadayosi** [comment]
Hi @haanhvu,

> We need to test on both the dev mode and the remote dev mode, or just the dev mode?

You should add a test to this existing e2e test. Since it is e2e test, it should be always a remote test (i.e. a test with an remote cluster).
https://github.com/apache/camel-k/blob/main/e2e/common/cli/dev_mode_test.go

> What can I use to show the start-up time?

You can use Gomega's `Eventually` with timeout of 10s to test the start-up time. If the test can be really stable with a even shorter timeout such as 5s on CI, we can use the shorter timeout.

**Comment by tadayosi** [comment]
@haanhvu Are you still working on this?  Is there any help we can provide for you?  If you don't have time to work on it now, I can take it over.

**Comment by haanhvu** [comment]
> @haanhvu Are you still working on this? Is there any help we can provide for you? If you don't have time to work on it now, I can take it over.

yes please
