### ISSUE TITLE
Unable to access MongoDB from kamelets binding [DOCS bug]

### ISSUE THREAD

**Issue by lucamaf** [apache/camel-k#3228]
as mentioned here
https://github.com/apache/camel-k/issues/2684#issuecomment-1105686941

**Comment by oscerd** [comment]
If the log are the original one you need to have a capped collection. The one you're consuming from it's not.

**Comment by lucamaf** [comment]
works! although I coulnd't find any mention about this restriction for the collection in the documentation

**Comment by oscerd** [comment]
I think it's in the main documentation of the component. But needs to be add in the kamelet description. Let me leave this open so I'll fix it. Thanks for reporting.
