### ISSUE TITLE
kamel local build is writing on stderr with Maven dependency specified as modeline even if it is working

### ISSUE THREAD

**Issue by apupier** [apache/camel-k#3252]
When using this kind of command:
```
kamel local build --integration-directory "/home/apupier/.config/Code/User/globalStorage/redhat.vscode-camelk/java-dependencies-3.16.0" "/home/apupier/ws/test-debug-from-empty-workspace/MyCamelRoute.java"
```
with this kind of file:
```
// camel-k: language=java dependency=mvn:org.apache.commons:commons-math3:3.6.1

import org.apache.camel.builder.RouteBuilder;

public class MyCamelRoute extends RouteBuilder {
  @Override
  public void configure() throws Exception {

      // Write your routes here, for example:
      from("timer:java?period=1000")
        .routeId("java")
        .setBody()
          .simple("Hello Camel from ${routeId}")
        .to("log:info");
  }
}
```

On stderr, there is this message:
```
Modeline options have been loaded from source files
Full command: kamel local build --integration-directory /home/apupier/.config/Code/User/globalStorage/redhat.vscode-camelk/java-dependencies-3.16.0 /home/apupier/ws/test-debug-from-empty-workspace/MyCamelRoute.java --dependency=mvn:org.apache.commons:commons-math3:3.6.1
```

The dependency is correctly available in the local folder

**Comment by apupier** [comment]
I guess it comes from https://camel.apache.org/blog/2022/04/camel-k-release-1-9/#warning-cli-output-to-stderr 
it sounds like an "info" log is going to stderr now. how can we determine that there is a real error now?

**Comment by apupier** [comment]
> how can we determine that there is a real error now?

it seems that we can rely on the exit code. My manual tests so far reveals correct exit code provided.

So I think it is both strange that some info/warnign is written on stderr and that the VS Code extension for Camel K was relying on the stderr to detect errors isntead of exit code;  i think that relying on exit code is a lot cleaner on VS Code Camel K side.
On Camel K side, I think it would be nicer to not have info/warning written on stderr but this seems to be not blocking for VS Code Camel K (but unfortunately the test coverage is very low so hard to be sure)

**Comment by squakez** [comment]
Thanks for confirming that. The main problem is that the CLI is expecting to produce some output when we use `-o yaml`. In that case, if we slip any log trace, we mess up with the output, so, the natural solution would be either to remove the log trace, or to redirect to the `stderr`. Not sure if we can find any alternative. If this is no longer an issue, feel free to close.

**Comment by apupier** [comment]
What about redirecting to stderr only when using the `-o yaml`?

**Comment by squakez** [comment]
It could be a solution. Although I am not 100% sure it's a good practice to have the output sent to different stream based on some flag selection: it may confuse the user. Let's keep it open and gather some feedback from the folks out there.

**Comment by tadayosi** [comment]
To me that modeline message seems to be info, not warning or error, so it's natural to be output to stdout. When we specify `-o` with `kamel local` command, rather we should suppress any log output to stdout.
