### ISSUE TITLE
1.9.x TestHealthTrait/Readiness_condition_with_stopped_route failure

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3258]
Right now, only this test is failing:
```
    --- FAIL: TestHealthTrait/Readiness_condition_with_stopped_route (416.44s)
```

_Originally posted by @squakez in https://github.com/apache/camel-k/issues/3256#issuecomment-1119494943_

**Comment by tadayosi** [comment]
Should be fixed already.
