### ISSUE TITLE
update camel-k operator from 0.6.0

### ISSUE THREAD

**Issue by kubovdm** [apache/camel-k#3259]
After update operator to higher version from 0.6.0 every integrations was not build, on build resourse i see only 
```
  conditions:
    - lastTransitionTime: '2022-05-07T08:23:12Z'
      lastUpdateTime: '2022-05-07T08:23:12Z'
      message: camel-k
      reason: IntegrationPlatformAvailable
      status: 'True'
      type: IntegrationPlatformAvailable
  duration: 294.557985ms
  error: context deadline exceeded
  failure:
    reason: context deadline exceeded
    recovery:
      attempt: 5
      attemptMax: 5
      attemptTime: '2022-05-07T08:25:33Z'
    time: '2022-05-07T08:23:13Z'
  phase: Error
  platform: camel-k
  startedAt: '2022-05-07T08:25:33Z'
```

**Comment by squakez** [comment]
Hello. I am not sure to understand what do you mean by "update operator to higher version from 0.6.0" can you please clarify and show exactly what was changed in your configuration? Thanks.

**Comment by kubovdm** [comment]
Hello. I use offical helm chart version 0.6.0 in k8s, and developers ask me to update to higher version. When i do rollup and update camelcatalogue and integrationplatfrom crd and after that i see only one error when integraion try to build pod. I read logs of camel-k operator, and can`t find errors, only messages about retry attemption. Configuration helm chart i don't changed.

**Comment by squakez** [comment]
Thanks for the clarification. I wonder if this relates to #3261

**Comment by kubovdm** [comment]
i see that error about last version of camel-k? i try to use different versions, and no one is not work for me.

**Comment by squakez** [comment]
It does not seem relevant any longer. Please, reopen if the problem still happen in supported versions of Camel K.
