### ISSUE TITLE
Move from release nightly to Continuous Delivery

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3260]
We may think to move the actual nightly release job that build the latest bits of Camel K in an unsupported pre-release into a Continuous Delivery. Basically it means the very same procedure we already have in place, but, we move the trigger from a nightly cron to any merge we perform in `main`.

**Comment by squakez** [comment]
fyi @lburgazzoli

**Comment by lburgazzoli** [comment]
can this be done also for .x branches ? says 1.8.x, 1.9.x etc

**Comment by squakez** [comment]
Yeah, I think we should put this in place for at least actual version - 2 releases branch.

**Comment by squakez** [comment]
Nightly builds is quite stable at this stage and moving to a full CD approach on each merge can create bottlenecks with the limited resource we have in GH actions. Closing for now.
