### ISSUE TITLE
Create proper Camel event source page on Knative website

### ISSUE THREAD

**Issue by christophd** [apache/camel-k#3262]
The Knative documentation uses a very old and obsolete description of the Camel event source. We should update this to reflect Kamelet catalog and a quickstart how to use KameletBindings as event sources in Knative.

Website content: [https://knative.dev/docs/eventing/sources/apache-camel-source/](https://knative.dev/docs/eventing/sources/apache-camel-source/)

**Comment by squakez** [comment]
No longer relevant.
