### ISSUE TITLE
Integration Kit image build runs into an endless loop when a lower level image can't be pulled from Registry

### ISSUE THREAD

**Issue by catshout** [apache/camel-k#3266]
Hi all.

We're still working with Camel-K 1.8.0. We did experience that an Integration Kit build runs into an endless loop when a lower level image can't be pulled from Registry. The build will be tried again and again.

We must delete the Operator, afterwards the Integration Kit build was running properly again.

I'd expect in such a case (lower level image not found), that the Operator does have a mitigation strategy built in (e.g. build the Integration Kit based on an other one existing or from scratch).

So far the question, does the Integration Kit build process be re-worked in 1.9.x. And .. we'd expect a bit more detailed log entries in the Operator logs.

Best
Gerald

**Comment by squakez** [comment]
I'm marking this as a bug as we should detect the problem and notify somehow to the user instead of looping infinetely. Maybe a retry with exponential backoff for some time, afterwards the build should be set in error state. We may solve this in 1.9.x and maybe backport to 1.8.x, dependending on when someone will have the availability to contribute on it.

**Comment by catshout** [comment]
Tx @squakez.

We're working with named Integration Kit images and references in the Integrations to one (in such a case re-usable) Integration Kit.

Maybe it's also an approach to make the automated layering configurable. For a better control of the artefacts we'd like to have a created named Integration Kit self-contained, means not built up on any existing one. Finally we'd have up to max 20 Integration Kits for a large number of Integrations, so in our case the layering won't have an advantage.

**Comment by squakez** [comment]
I tried to reproduce this issue but did not manage to have it failing. If I deleted an intermediate image layer, the spectrum tool is able to rebuild it as far as I could see. Tested both 1.8 and 1.9. Can you please provide a step by step reproducer?
