### ISSUE TITLE
Proposal: Clarify the description for the Operator in the OLM catalog

### ISSUE THREAD

**Issue by rhuss** [apache/camel-k#3267]
The description of Camel-K operator in the OLM is a bit misleading:

![image](https://user-images.githubusercontent.com/99080/168227758-87ffed81-3fc6-4745-9cd5-66a6355fdd3c.png)

It is not clear, that an `IntegrationPlatform` gets installed lazily on first use by an `Integration` if none has been created manually (but sounds more like that it is immediately created when the operator is installed).

I propose a wording like _.... is created automatically at first use with a default configuration if not present, so you can skip this step_

**Comment by squakez** [comment]
Thanks for reporting @rhuss . However I struggle to find the documentation page where this is reported. Do you mind posting the link? thanks.

**Comment by tadayosi** [comment]
@squakez This is about the description in the CSV manifest:
https://github.com/apache/camel-k/blob/main/config/manifests/bases/camel-k.clusterserviceversion.yaml#L76

**Comment by squakez** [comment]
Okey, I was looking through website doc. Thanks @tadayosi

**Comment by rhuss** [comment]
sorry, overlooked the question. But yes, it's in the CSV ...
