### ISSUE TITLE
Local Dependencies Registry Problem

### ISSUE THREAD

**Issue by jonathan-k4** [apache/camel-k#3271]
It appears the new support for local `file://` dependencies ignores the `organization` field of the registry settings when it tries to upload the jar file to the registry.

https://camel.apache.org/camel-k/1.8.x/installation/registry/registry.html

When the integration is saved to the registry it does this:

https://github.com/apache/camel-k/blob/a79f8329361ddee26f418bc2c80f8546614fc3c8/pkg/trait/builder.go#L197

However, when the file is uploaded, it only uses `registry.address`:

https://github.com/apache/camel-k/blob/d43560bbf819a2bdf98aa3d584b587cbd5dcf5ba/pkg/cmd/run.go#L967

This is causing issues with uploads to Harbor as it returns a 400 because the organization in the path is missing.

**Comment by johnpoth** [comment]
Should be fixed in [1.9.2](https://hub.docker.com/layers/camel-k/camelk/camel-k/1.9.2/images/sha256-01113e6a19b03ce3000a36dfa42ae5e75f1e65046144837d6eb4973667042b54?context=explore) (under vote)
