### ISSUE TITLE
Dependency doc is wrong about how to add camel components

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#3291]
https://camel.apache.org/camel-k/1.9.x/configuration/dependencies.html

It says `-d camel-mina2` but the syntax for camel is to use a colon, eg `-d camel:mina2`.
Also mina2 is an old Camel 2.x component, that is removed in camel 3.

So lets use another, can be netty or http, etc.

**Comment by squakez** [comment]
I think that was the original way we supported the components, see the `kamel run --help`:
```
  -d, --dependency stringArray         A dependency that should be included, e.g., "-d camel-mail" for a Camel component, or "-d mvn:org.my:app:1.0" for a Maven dependency
```
I remind we were converting the `camel-xxx` to `camel:xxx` or viceversa, so I'm marking this as a bug as well.

**Comment by tadayosi** [comment]
@davsclaus @squakez I recently fixed the discrepancy issue between `kamel run -d` and `kamel local run -d` #2213, and now both commands support both `camel-amqp` and `camel:amqp` notations. And as Pasquale said internally `camel-xxx` is converted to `camel:xxx` on an Integration's status.

So, the question is which notation do we prefer as the standard notation for dependencies in the docs?  `camel-xxx` or `camel:xxx`?

**Comment by squakez** [comment]
I like it more `camel:xxx` as we also have `mvn:yyy` approach. I think we need to harmonize the way we reference camel components/dependencies and use always the same way. However, if we decide to drop `camel-xxx` approach, we'll need a period of deprecation.

**Comment by tadayosi** [comment]
Then we can choose `camel:xxx` as the standard, preferred notation and use them throughout the docs and examples. I'll mark `camel-xxx` as deprecated whereever appropriate and remove the usages from the docs.

**Comment by davsclaus** [comment]
I think 90% of end users would type `camel-xxx` as its the name of the JAR file, using `camel:xxx` can be hard on the eye to notice that using a colon instead of dash.

I would support both notations, but harmonize the docs as suggested here in the PR
