### ISSUE TITLE
Integration Platform issues when using the Operator 

### ISSUE THREAD

**Issue by utherp0** [apache/camel-k#3297]
This is an odd one; on OpenShift 4.10 when you install Camel-K/Integration it does not create by default an Integration Platform. When you create a default one and then create an Integration using 'kamel run' (in this case a simple Event reader - see https://github.com/utherp0/functest2/blob/main/camelk/EventReader.java) the integration fails. If you then delete the Integration Platform, and then run the Integration without a platform present the Operator will create an IP and the Integration runs.

However, if you create an Integration *before* you create a default Integration Platform the integration fails to start.

This is always repeatable on OCP4.10.

**Comment by utherp0** [comment]
So, I think the problem I am seeing is that if I create a default ip before I run the integration it fails; the default is just 'as is', taking all the defaults on the Ux for the ip. 

Creating one with no ip present does create the ip:

uther@ilawson-mac camelk % oc project camelktest
Now using project "camelktest" on server "https://api.cluster-nq5hk.nq5hk.sandbox542.opentlc.com:6443".
uther@ilawson-mac camelk % oc get ip
No resources found in camelktest namespace.
uther@ilawson-mac camelk % kamel run EventReader.java 
integration "event-reader" created
uther@ilawson-mac camelk % oc get ip 
NAME      PHASE
camel-k   Ready
uther@ilawson-mac camelk % oc get integration
NAME           PHASE          KIT                        REPLICAS
event-reader   Building Kit   kit-ca69lbu4gbef2b5j58f0

**Comment by christophd** [comment]
would be good to see the error from the logs so I can have an idea what went wrong.

Are you using a global operator? where is that operator running (maybe in namespace camelktest)?

**Comment by utherp0** [comment]
Yup - I'm installing operator namespace bound, i.e. the operator is running locally. Once the test has completed (the build is taking a while) I'll spin up another namespace and create the ip first which should cause the problem, and will get the logs

**Comment by utherp0** [comment]
The Operator is deployed into the namespace rather than across the Cluster, by local I mean namespace bound
<img width="1842" alt="Screenshot 2022-05-25 at 09 12 20" src="https://user-images.githubusercontent.com/2233236/170214330-3ebdcb7c-e7a9-4e56-8ebc-99e9826a9762.png">

**Comment by mathianasj** [comment]
i am seeing this issue as well

**Comment by christophd** [comment]
could you please do a `kubectl get integrationplatform camel-k -o yaml` for both the manual created ip and the automatically created ip. This will print the custom resource and we can see any difference that makes the one succeed while the other fails

**Comment by mathianasj** [comment]
I figured out the problem I missed in the documentation that if installed on openshift I did not create an IP once I removed it everything started working.
