### ISSUE TITLE
kamel local build:failure while building project: exit status 1

### ISSUE THREAD

**Issue by wuzhen0808** [apache/camel-k#3307]
The kamel local build command report a message without any detail. 
Is there any way to see the detail log to show the progress of building flow?
Hard to step forward with just a exit code. 
Following is the source code and command lines, thanks a lot.

S:~/study-kamel$ cat hello.java
// camel-k: language=java

import org.apache.camel.builder.RouteBuilder;

public class hello extends RouteBuilder {
  @Override
  public void configure() throws Exception {

      // Write your routes here, for example:
      from("timer:java?period=1000")
        .routeId("java")
        .setBody()
          .simple("Hello Camel K from ${routeId}")
        .to("log:info");

  }
}

S:~/study-kamel$ kamel local inspect hello.java
dependencies:
camel:timer
camel:log
mvn:org.apache.camel.quarkus:camel-quarkus-java-joor-dsl

S:~/study-kamel$ kamel local build hello.java
failure while building project: exit status 1

**Comment by squakez** [comment]
is `@OverRide` a typo?

**Comment by tadayosi** [comment]
Have a look at the doc:
https://camel.apache.org/camel-k/1.9.x/running/local.html

In short, `kamel local build` requires at least `--image` option to run. I agree the message is not user-friendly. There's an issue for it: #3028

**Comment by tadayosi** [comment]
Since it's already well documented, let's close it. Error messages can be polished at #3028.
