### ISSUE TITLE
Add a `kamel install --publish-strategy-option`

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3308]
We don't have a direct way to fill the `platform.Spec.Build.PublishStrategyOptions`. It would be nice to include it in the `kamel install` as an option.

We should also transform the `kaniko-build-cache` option to fit into the new model.

_Originally posted by @squakez in https://github.com/apache/camel-k/issues/1238#issuecomment-1139295649_

**Comment by essobedo** [comment]
@squakez `PublishStrategyOptions` is currently a map, do you want something less flexible in the model or it is good enough as it is? 

In case a map is the expected type, what about proposing a flag like the flags `property` and `build-property` of the run command (where you can either set a specific property or provide a properties file)?

**Comment by essobedo** [comment]
Should be fixed by https://github.com/apache/camel-k/pull/3631
