### ISSUE TITLE
Camel route terminates when route takes longer than 5 minutes

### ISSUE THREAD

**Issue by mydeveloperplanet** [apache/camel-k#3335]
In our project we had long running routes (at least longer than 5 minutes). When using Camel-K we noticed the following behaviour:
* Create a route which takes longer than 5 minutes, e.g. set a delay in the route longer than 5 minutes
* Start the route via a Rest call
* The route will be terminated after 5 minutes

We also tried to put the message on a seda queue after the Rest call, but then the route terminates immediately.

For our project, we moved away from Camel-K because we had to deliver a working solution. I created this issue after a request in a [tweet](https://twitter.com/freaky_styley/status/1526924847393259521).

**Comment by squakez** [comment]
Thanks for reporting the issue. It looks quite strange indeed, we never experienced such a behavior. In order to see the exact problem in action, do you mind posting a reproducer? It would be enough to have the route and the way you're calling it. Also, please specify the camel k version, knative version and kubernetes cluster you're running. Thanks!

**Comment by christophd** [comment]
A possible cause could be Knative serving shutting down the pod because of auto scale to zero due to inactivity on the REST endpoint.

Did you have Knative serving enabled in your scenario? 

We could verify this disabling auto scale functionality to see if this is the problem

**Comment by mydeveloperplanet** [comment]
We were using Camel-K 1.7.0, KNative 1.1.0. Kubernetes cluster was K3S.
Knative serving was enabled as far as I can see.
I understand the need for a reproducer, but the developers departed from Camel-K and are not eager to spend more time into it, I am sorry. But they did say that it can be easily reproduced by setting a delay of > 10 minutes in the route.
