### ISSUE TITLE
Configure Maven builds based on CPU quota

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#3339]
The CPU resources allocated to the operator can significantly impact the integration build time.

Following #2837, which makes the operator aware of the CPU quota set on the operator container, Maven should be configured according to it.

For instance, the number of threads used to download dependencies in parallel, which is a major contributor to the build time, should be defaulted based on the CPU quota, by setting the `maven.artifact.threads` option here: https://github.com/apache/camel-k/blob/87d9d7a20de55eb290fa194d3d15229a3dec9843/pkg/util/maven/maven_command.go#L77

**Comment by SubhasmitaSw** [comment]
Please assign it to me @astefanutti

**Comment by squakez** [comment]
Can this be closed?

**Comment by astefanutti** [comment]
Yes, it's been addressed by #3344.
