### ISSUE TITLE
Configure parallel container image layers push based on CPU quota

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#3340]
The CPU resources allocated to the operator can significantly impact the integration build time.

Following #2837, which makes the operator aware of the CPU quota set on the operator container, the underlying container image push implementation should be configured accordingly.

For instance, the new option introduced in google/go-containerregistry#803 should be surfaced in Spectrum<sup>[1]</sup>, defaulted according to the operator container CPU quota, and passed to go-containerregistry<sup>[2]</sup>.  

[1]: https://github.com/container-tools/spectrum/blob/8f8efa4592a2891dd9c1efa3f031f73a36862a93/pkg/builder/options.go#L5-L16
[2]: https://github.com/container-tools/spectrum/blob/8f8efa4592a2891dd9c1efa3f031f73a36862a93/pkg/builder/build.go#L55

1: https://github.com/container-tools/spectrum/blob/8f8efa4592a2891dd9c1efa3f031f73a36862a93/pkg/builder/options.go#L5-L16
2: https://github.com/container-tools/spectrum/blob/8f8efa4592a2891dd9c1efa3f031f73a36862a93/pkg/builder/build.go#L55

**Comment by squakez** [comment]
I think this can be closed. Any leftover by any chance?

**Comment by astefanutti** [comment]
Yes, it's been addressed by #3366.
