### ISSUE TITLE
Kamel install error on Minikube

### ISSUE THREAD

**Issue by chorton-coastal** [apache/camel-k#3348]
After running `kamel install` I'm getting an error on the operator.
I'm using kamel  `1.9.2` and minikube `v1.25.2`.

```
> kubectl get pods
NAME                                READY   STATUS             RESTARTS        AGE        
camel-k-operator-56f584bf94-82gff   0/1     CrashLoopBackOff   9 (3m21s ago)   24m        

> kubectl logs -p camel-k-operator-56f584bf94-82gff
{"level":"error","ts":1654870876.582687,"logger":"cmd","msg":"failed to set GOMAXPROCS from cgroups","error":"path \"/docker/8ce2a9598fa8ae5ed2c911c7b2b9022aa7a934a9170b1c8936ac9ba56dd86d71\" is not a descendant of mount point root \"/docker/8ce2a9598fa8ae5ed2c911c7b2b9022aa7a934a9170b1c8936ac9ba56dd86d71/kubelet\" and cannot be exposed from \"/sys/fs/cgroup/rdma/kubelet\"","stacktrace":"github.com/apache/camel-k/pkg/cmd.(*operatorCmdOptions).run\n\tgithub.com/apache/camel-k/pkg/cmd/operator.go:54\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.2.1/command.go:860\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.2.1/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.2.1/command.go:902\nmain.main\n\tcommand-line-arguments/main.go:47\nruntime.main\n\truntime/proc.go:225"}
```

**Comment by squakez** [comment]
It seems some error while getting information from your operating system. Are you using any virtual environment by any chance? You may try to force a GOMAXPROCS environment variable and setting 1 or 2 as a value.

**Comment by chorton-coastal** [comment]
Adding the environment variable didn't help. I was able to get it working using the hyperv driver instead of docker.

```
minikube start --driver hyperv
```

**Comment by squakez** [comment]
Yes, I've just hit the same problem. It seems a problem with the docker driver indeed. It is giving this error once I've run an update. Reopening in order to figure it out how to fix. Thanks for the workaround!

**Comment by squakez** [comment]
We're probably hitting https://github.com/uber-go/automaxprocs/issues/49

**Comment by squakez** [comment]
Some further workaround in https://github.com/elastic/cloud-on-k8s/issues/5325
