### ISSUE TITLE
Unable to get basic hello.groovy example working on local single node KIND cluster

### ISSUE THREAD

**Issue by bjethwan** [apache/camel-k#3349]
```
% kubectl version --short
Client Version: v1.23.1
Server Version: v1.21.1
```

```
% kamel version
Camel K Client 1.8.1
```

https://camel.apache.org/camel-k/1.9.x/running/running.html

`kamel run hello.groovy`

```
{"level":"info","ts":1654957525.8224964,"logger":"camel-k","msg":"spectrum - 2022/06/11 14:25:25 Pulling base image adoptopenjdk/openjdk11:slim (insecure=false)..."}
{"level":"error","ts":1654957556.1208284,"logger":"camel-k.controller.build","msg":"Build kit-caiaa4tp090c73cco220 failed: could not pull base image image adoptopenjdk/openjdk11:slim: Get \"https://auth.docker.io/token?scope=repository%3Aadoptopenjdk%2Fopenjdk11%3Apull&service=registry.docker.io\": dial tcp: i/o timeout","request-namespace":"default","request-name":"kit-caiaa4tp090c73cco220","api-version":"camel.apache.org/v1","kind":"Build","ns":"default","name":"kit-caiaa4tp090c73cco220"}
{"level":"info","ts":1654957556.1424239,"logger":"camel-k.controller.build","msg":"state transition","request-namespace":"default","request-name":"kit-caiaa4tp090c73cco220","api-version":"camel.apache.org/v1","kind":"Build","ns":"default","name":"kit-caiaa4tp090c73cco220","phase-from":"Running","phase-to":"Failed"}
```

It's such a stupid thing that every time it fails to download the base image it again enters in the complete maven build cycle.

**Comment by bjethwan** [comment]
```
% kamel local build --image=docker.io/bjethwan/hello hello.groovy
failure while building project: exit status 1
```

**Comment by bjethwan** [comment]
Does it have to build the image every time I run "kamel run hello.groovy"?

**Comment by tadayosi** [comment]
You don't need `kamel local build` at all for just deploying an integration to a K8s cluster.

Looking at the log, it appears that there is something wrong with the registry settings. Make sure you followed the steps here with the correct credentials:
https://camel.apache.org/camel-k/1.9.x/installation/platform/kind.html

**Comment by tadayosi** [comment]
@bjethwan If you've just uninstalled Camel K operator, the IntegrationKits used for the build is still there. So long as you keep the IntegrationKits Camel K won't recreate the container image with the hash. As you say, if you recreating the entire kind cluster the IntegrationKits are also gone and you'll need to rebuild the images.

**Comment by bjethwan** [comment]
@tadayosi So if I take this solution to production, camel-k will not use the tested kit-* but recreate a new one?
Can't I export and import the integrationkit? Will that skip camel-k from rebuilding in production env?

**Comment by squakez** [comment]
I think the new `kamel promote` (https://github.com/apache/camel-k/pull/3325) may be your solution. You can already use installing nightly build or waiting for 1.10 release.
