### ISSUE TITLE
kamel local run support --build-property ?

### ISSUE THREAD

**Issue by barius** [apache/camel-k#3356]
This may be a feature request :P

During fast prototyping on JDBC mysql connection, I have to try different combinations of `--property` and `--build-property`.
The `--build-property quarkus.datasource.camel.db-kind=mysql` is for quarkus to detect mysql stuff and have to be used with `-d mvn:io.quarkus:quarkus-jdbc-mysql`.
Building a kit via `kamel run` on my local k8s costs around ~2min, and `kamel local run` just takes seconds.
Also, local runs seems to be faster than k8s runs (which may be my problem because I'm just using my macbook to run docker desktop and there are other overheads such as istio etc.).

Is there any plan on adding `--build-property` to` kamel local run`?

As far as I have found out, passing `--build-property` to quarkus involves adding these properties to `src/main/resources/application.properties` file in the maven build directory.
I'm able to emulate the behavior by manually editing this file and run `mvn -q package` as a workaround.

**Comment by squakez** [comment]
The `local` command just execute a jvm locally on your machine and it is meant to be used for quick testing and local troubleshooting. I don't think it can be on parity with the cluster `run` which is in charge to arrange the project, look for dependencies, capabilities, etc... , build and store an IntegrationKit (incremental). Think of that as a very thin layer on top of a normal Camel Quarkus execution.

**Comment by tadayosi** [comment]
In many cases, building kits on a k8s cluster takes time because it downloads jars externally every time. Hosting a maven repo manager like Nexus might mitigate the building time. While there's no good documentation for the technique, you could look at this in the meantime:
https://camel.apache.org/camel-k/1.9.x/contributing/e2e.html#using-nexus

I believe you could do
```
kubectl apply -f https://raw.githubusercontent.com/apache/camel-k/main/e2e/support/files/nexus.yaml
```
then you could use the nexus with this install command:
```
kamel install --maven-repository=http://nexus.nexus/repository/maven-public/@id=nexus@mirrorOf=*
```

**Comment by barius** [comment]
@squakez Thanks for the reply!
>  I don't think it can be on parity with the cluster run which is in charge to arrange the project, look for dependencies, capabilities, etc... , build and store an IntegrationKit (incremental). Think of that as a very thin layer on top of a normal Camel Quarkus execution.

Yes, I totally agree with that. Took me a while to figure out the difference between `--build-property` and `--property` though :P
Anyway, `kamel run` is surely a better option in regards of log formatting, `--dev` mode with auto sync, .etc so I will stick with that :)

btw any ideas on the strangely slow performance on k8s? Got ~3x slower when connecting to mysql via `jdbc://` in k8s than local run.

**Comment by squakez** [comment]
> btw any ideas on the strangely slow performance on k8s? Got ~3x slower when connecting to mysql via jdbc:// in k8s than local run.
Probably it's because the different layers of virtualization. However, a fine tuned cluster should behave as any local machine. I guess you need to investigate how to improve network performances in your cluster.

**Comment by barius** [comment]
> Probably it's because the different layers of virtualization. However, a fine tuned cluster should behave as any local machine. I guess you need to investigate how to improve network performances in your cluster.

Sure, I'll work on that. Thanks!

**Comment by barius** [comment]
Closing this issue because `kamel run` is a better option.
