### ISSUE TITLE
Add E2E workflow using Windows runner for testing Camel K CLI client and local run

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-k#3364]
We release a Windows version of Camel K CLI, but there is no test coverage targeting Windows environment yet. This causes some Windows only issues with the CLI and `kamel local` commands unnoticed until users try the CLI on Windows, such as #3363.

Since GitHub provides Windows runners for workflows, it should be desirable to have an E2E workflow on Windows that runs part of our E2E suite, especially for the CLI client and the `local` testing.

**Comment by tadayosi** [comment]
cc @phantomjinx

**Comment by tadayosi** [comment]
Related issues: #213 #214 #3134

To reuse the existing e2e tests as-is, we are required to resolve those issues above first to make build work on Windows.

Another approach might be using the cross-compiled `kamel.exe` to run a separate e2e workflow with a dedicated set of Windows tests.

**Comment by phantomjinx** [comment]
Happy to take this on.

**Comment by phantomjinx** [comment]
`kind` cannot be installed on Window runners at the moment.

see https://github.com/actions/runner-images/issues/5760 and https://github.com/microsoft/WSL/issues/6301

**Comment by tadayosi** [comment]
One idea might be just run workflows that don't require a Kind cluster, such as `build` and `local-it` for the time being.

**Comment by phantomjinx** [comment]
> One idea might be just run workflows that don't require a Kind cluster, such as `build` and `local-it` for the time being.

Yes. The `build` workflow is successful but `local-it` cannot be run at the moment as the base image used for the jdk runtime for the integrations are not available on `windows` either. I did try overriding the base image using the switch but could not find an image that contained all the correct components.

**Comment by tadayosi** [comment]
Ah I see. Then maybe we can start small from only running `build` on Windows. The `build` runs unit tests so it should be still worth running on Windows.

**Comment by squakez** [comment]
Subcommand no longer supported.
