### ISSUE TITLE
VSCode extension

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#338]
Would be nice to have a VSCode extension that:

- shows available integrations
- edit integrations
- show logs

Some experimental work related to a camel-k ui from @riccardo-forina can be found here https://github.com/riccardo-forina/camel-k-ui

**Comment by lburgazzoli** [comment]
Some work in progress: https://github.com/camel-tooling/vscode-camelk

**Comment by nicolaferraro** [comment]
Done
