### ISSUE TITLE
Set log-level on Camel K operator not working

### ISSUE THREAD

**Issue by christophd** [apache/camel-k#3399]
The operator logging level should be settable with envvar `LOG_LEVEL="debug"` on the operator deployment.

Actually this does not have any effect on the log output. In particular I do not see logs other than default verbosity level `0`.

Platform: OCP 4.10
Camel K v1.9.2

**Comment by christophd** [comment]
Turns out this is due to a missing backport to 1.9.x

**Comment by squakez** [comment]
Closed by #3401
