### ISSUE TITLE
Failing integration does not report error condition

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3412]
Any failing integration, ie `kamel run -d mvn:com.example:nonexistent:1.0 Hello.java` will correctly set the error on IntegrationKit, but won't do on Integration, resulting the Integration in a `Building Kit` state even if it failed:

```
squake:~ $ kamel get
NAME	PHASE		KIT
hello	Building Kit	default/kit-cb19gvc268e9p6peapt0

squake:~ $ k get integrationkit
NAME                       PHASE   TYPE       IMAGE
kit-cb19gvc268e9p6peapt0   Error   platform 
```

**Comment by tadayosi** [comment]
Is this something like this that is relevant to the issue?
https://github.com/apache/camel-k/blob/main/pkg/controller/integration/monitor.go#L218

**Comment by squakez** [comment]
> Is this somewhere like this that is relevant to the issue? https://github.com/apache/camel-k/blob/main/pkg/controller/integration/monitor.go#L218

Thanks @tadayosi. I am not sure what is the expected behavior. I mean, I'm assuming that a failing IntegrationKit build will take care to turn the Integration which owns it as errored as well but I don't know where it used to happen. There were several refactoring in the past, so, likely we missed something. Also we need to introduce an E2E test to take care of this situation and avoid any future regression.

**Comment by astefanutti** [comment]
@squakez as you pointed it out, the integration phase is set to error when the kit fails in: https://github.com/apache/camel-k/blob/37cba2f05ee3e59db3e2b8f18f88b887f15b9ac7/pkg/controller/integration/build_kit.go#L91

I suspect this works, but the integration phase gets overwritten later with: https://github.com/apache/camel-k/blob/c3b9c9be36e219b593bb395795be817171a0b431/pkg/controller/integration/monitor.go#L230

For some reasons, the phase is not set to error while introspecting the underlying deployment / pods. That being said, it may be more robust to force the phase to error in that case, which would likely provide a better error message.

**Comment by squakez** [comment]
I've gone deep in this and found the responsible is this check here: https://github.com/apache/camel-k/blob/132dcebd1af7457f2952e14435e887061f45d720/pkg/controller/integration/kits.go#L117-L121 Basically we never found a match when the integrationkit has failed, resulting in the issue described. Unfortunately the method is used in other places, so I will need to find a way to solve it.
