### ISSUE TITLE
Example readme page 404 links

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3413]
https://github.com/apache/camel-k/blob/main/examples/README.md has some missing link due to ongoing example migration to https://github.com/apache/camel-k-examples. This page must be updated along the changes that are performed.

**Comment by squakez** [comment]
fyi @KuthumiPepple

**Comment by KuthumiPepple** [comment]
Ok I'll do that. Thanks for pointing that out

**Comment by tadayosi** [comment]
Already fixed.
