### ISSUE TITLE
Any ideas on disabling property expansion in kamel run?

### ISSUE THREAD

**Issue by barius** [apache/camel-k#3422]
The use case is that I'm trying to log to different files in each pod on environment variable HOSTNAME. In application.properties :
```
quarkus.log.file.enable=true
quarkus.log.file.path=/log/log.test-logging.${HOSTNAME}
```
Kamel does this expansion on `kamel run` and ${HOSTNAME} is resolved to my local machine rather than k8s pod name.

Since Quarkus also provides property expression/expansion, could there be any method or thoughts to differentiate the two? e.g. changing prefix and postfix of "github.com/magiconair/properties" or add a switch to disable it?

Regards :)

**Comment by squakez** [comment]
Maybe you can leverage directly Camel properties features: https://camel.apache.org/components/3.17.x/properties-component.html#_using_system_and_environment_variables_in_locations

**Comment by barius** [comment]
@squakez If I use Camel properties, should I pass the properties via `kamel run -p`? Or `--trait camel.properties=`?

**Comment by squakez** [comment]
You can both use a properties file or pass a list of properties. The `kamel run` will replace into trait for you. Ie:
```
test.properties
a=x
b=y
...
kamel run Test.java -o yaml -p file:test.properties
```
and
```
kamel run Test.java -o yaml -t camel.properties=a=x -t camel.properties=b=y
```
will produce the same output.

**Comment by barius** [comment]
yep, `-p` and `-t camel.properties` are interchangeable unless property expansion is involved, since the Go package `github.com/magiconair/properties` used in camel-k does some shallow parsing to `-p` properties.
Anyway this is no big issue and I can use some wrapper script to pass a property file as multiple `-t camel.properties` arguments :P

**Comment by squakez** [comment]
I was answering to:
> Multiple -t camel.properties= seems to not work, and -t camel.properties=[foo=bar,baz=blabla] won't work :(
the way to use multiple properties via trait is the one provided in the previous comment.

**Comment by barius** [comment]
yes, I have tried again and multiple -t camel.properties= is now OK.
Now I use a wrapper script to expand a properties file into several `-t camel.properties=` args and it's ok.
Shall we close this issue?
