### ISSUE TITLE
failed: could not pull base image image adoptopenjdk/openjdk11:slim: https://auth.docker.io/token dial tcp: i/o timeout

### ISSUE THREAD

**Issue by bjethwan** [apache/camel-k#3425]
How to get rid of this issue while working with Camel k in KIND cluster?

`failed: could not pull base image image adoptopenjdk/openjdk11:slim: Get \"https://auth.docker.io/token?scope=repository%3Aadoptopenjdk%2Fopenjdk11%3Apull&service=registry.docker.io\": dial tcp: i/o timeout`

I upgraded docker desktop on my MacBook and restarted multiple times. I have no proxy setting. This is my home wifi and that GET endpoint works fine in my browser in base machine.

Is there some work around. How can I make the IntegrationKit use my localhost docker registry to pull that base image?

**Comment by squakez** [comment]
It seems the registry points to docker. In order to change that, you can edit the IntegrationPlatform or install it from scratch to point to your local registry. The operation is described in https://camel.apache.org/camel-k/1.9.x/contributing/local-development.html#local-minikube

**Comment by claudio4j** [comment]
You can cache the openjdk11 image in podman and push it to your registry
```
podman tag adoptopenjdk/openjdk11:slim $REGISTRY/<namespace>/openjdk11:slim
podman push $REGISTRY/<namespace>/openjdk11:slim --tls-verify=false
```

Then you can install camel-k and set the base-image
```
kamel install --base-image=<internal registry address:port>/<namespace>/openjdk11:slim
```

**Comment by claudio4j** [comment]
@squakez can this be closed, since it's not an issue in the code ?
@bjethwan there is a [camel-k zulip chat](https://camel.zulipchat.com) if you would like a more interactive way to ask questions.

**Comment by squakez** [comment]
I'll let @bjethwan close if he's happy with the resolution.
