### ISSUE TITLE
Option `--maven-repository` on kamel run command has no effect

### ISSUE THREAD

**Issue by christophd** [apache/camel-k#3447]
Users are able to add a custom Maven repository URL on the `kamel run` command via `--maven-repository` option

Setting this option has no effect and the given Maven repository is not being added when building the IntegrationKit.

**Comment by squakez** [comment]
I've made a quick test and it works for me with kamel 1.9.2. We also have a test covering that feature: https://github.com/apache/camel-k/blob/main/e2e/global/common/build/maven_repository_test.go#L42

**Comment by christophd** [comment]
@squakez thanks for testing this. I'll double check on my side, too to confirm that this issue exists or not

**Comment by christophd** [comment]
ok I can confirm that `--maven-repository` option is working for the run command.

my issue was related to the initial CamelCatalog build that is done by the operator when running a first integration. the run command option is not passed to this initial build so it was failing because of the missing maven repository, too. 

the initial build needs the repository set during kamel install as a `--maven-repository` option.

so I think we can safely close this one.
