### ISSUE TITLE
Raise error when dependency could not be resolved via CamelCatalog

### ISSUE THREAD

**Issue by christophd** [apache/camel-k#3449]
The Camel K operator tries to resolve dependencies for a given integration by having a look at the source code of the integration (e.g. by looking at the used Camel route URIs `from('componentA:foo').to('componentB:bar')`). 

In this process the operator tries to resolve the dependency via the given CamelCatalog.

We should raise build errors when such a dependency is not resolvable with the given CamelCatalog. At the moment the dependency is left unresolved causing runtime errors when the integration is running (due to missing artifact in the runtime classpath).

The integration should be put to error phase as a result.

**Comment by squakez** [comment]
Relates #3127

**Comment by tadayosi** [comment]
Can we assume that every available component is really provided in the Camel catalog?  For instance, `camel-quarkus-management` is not listed in the Camel catalog 1.13.0. I'm concerned that if we throw errors and reject building it if a dependency is not listed in the catalog we might end up rejecting some projects that are in fact valid in terms of dependencies.

**Comment by squakez** [comment]
I think it should not be related to dependencies but as mentioned in #3127 to capabilities/components.

**Comment by tadayosi** [comment]
@christophd @squakez BTW, I noticed that if we implement this strict guard on components using catalog, users won't be able to use custom components or renaming of existing components unless we provide a way for the users to extend the catalog. Do we support such use cases right now?

**Comment by squakez** [comment]
I am not sure we do allow any extension, as everything should be present in Camel Quarkus as well. @astefanutti do you recall if we had any extension mechanism in place?

**Comment by claudio4j** [comment]
It seems to me there should be a parameter of `kamel run --verify-deps=<true|false>` to allow the integration to run and provide feedback to the user in the case the integrations uses a dependency not in the catalog but is a resolvable one.

**Comment by tadayosi** [comment]
@claudio4j FYI there is `kamel local inspect <integration-file>` that does similar check but locally.
