### ISSUE TITLE
`make generate-crd` error

### ISSUE THREAD

**Issue by SubhasmitaSw** [apache/camel-k#3453]
Ref [gnu-sed failing](https://github.com/apache/camel-k/pull/3427#issuecomment-1182903367)

gnu-sed is failing, causing the post processing steps to abort returning an error like:

```
go: creating new go.mod: module tmp
CONTROLLER_GEN=/Users/chikki/go/bin/controller-gen ./script/gen_crd.sh
sed: 1: "/creationTimestamp:/a\\ ...": extra characters after \ at the end of a command
make: *** [generate-crd] Error 1
```

System: Mac OSX

Probable reason: BSD/macOS sed requires an actual newline character to follow `a\`, before the text to append

**Comment by tadayosi** [comment]
I think the solution is answered, so let's close it.
