### ISSUE TITLE
Option ```--registry-insecure false``` takes no effect when using local dependencies ```-d file:///path/xxx.jar``` 

### ISSUE THREAD

**Issue by Hades-888** [apache/camel-k#3455]
Hi Community,

We are running into an issue when using local dependencies option ```-d file:///path/xxx.jar```  in ```--registry-insecure false``` mode on k8s, but it still logs ```(insecure=true)``` during pushing image and throws an error of unexpected status code 503 Service Unavailable. The same task works fine without using local dependencies.

**VERSION**

Camel K Client 1.9.2

**Command to produce the Issue**

kamel install command
```
kamel install \
--registry-insecure false \
--registry xxx.com \
--registry-auth-username xxx \
--registry-auth-password xxx \
--organization xxx \
--maven-settings=configmap:maven-settings/settings.xml \
--build-timeout 1h \
--cluster-type kubernetes \
--build-publish-strategy Spectrum \
--force \
-n xxx
```
kamel run command
```
kamel run xxx.java \
-d file:///path/xxx.jar \
-n xxx \
--dev 
```
**Error Log**

**with** local dependencies option ```-d file:///path/xxx.jar``` 
![ture](https://user-images.githubusercontent.com/97818949/179461344-c942dce6-2b5e-4e26-a797-2bf5da279759.png)

**without** local dependencies option ```-d file:///path/xxx.jar``` 
![false](https://user-images.githubusercontent.com/97818949/179461314-35169164-fafd-40e0-8cc4-bdac9fb3f2b8.png)

**Expected Behavior**

We want use local jar dependencies ```-d file:///path/xxx.jar```and the HTTPS protocol in registry config ```--registry-insecure false``` 

Thanks

**Comment by squakez** [comment]
FYI @johnpoth

**Comment by johnpoth** [comment]
Hi @Hades-888, thanks for the feedback!

The insecure option should be taken from the platform CR (default name `camel-k`) Do you mind double checking the insecure option is correctly set by running something like:

`kubectl get integrationplatform camel-k -o=jsonpath='{.spec.build.registry.insecure}' -n xxx`

Thanks !

**Comment by Hades-888** [comment]
> Hi @Hades-888, thanks for the feedback!
> 
> The insecure option should be taken from the platform CR (default name `camel-k`) Do you mind double checking the insecure option is correctly set by running something like:
> 
> `kubectl get integrationplatform camel-k -o=jsonpath='{.spec.build.registry.insecure}' -n xxx`
> 
> Thanks !


@johnpoth ，thank you very much for your reply!

I had a query as you said，```--registry-insecure false``` seems to have no effect

<img width="638" alt="always-treu" src="https://user-images.githubusercontent.com/97818949/179483528-90c92f48-542a-4715-ad98-88f5c7a3aec5.png">

**Comment by johnpoth** [comment]
Hi @Hades-888 ,

It seems the command line parsing library [viper](https://github.com/spf13/viper) we use will set boolean flags to `true` if present regardless of the value passed... so `--boolean-flag-name false` will get set to true... may worth documenting if this works as intended.

In the meantime your can just omit `--registry-insecure false` when installing camel-k. It should be set to it's default value (false) and you should be all set!

We may want to mark this as a bug though and fix this ... i.e setting `--registry-insecure false` should set insecure to `false `-- WDY @squakez  ?

Thanks !

**Comment by squakez** [comment]
I think that's the way we parse the boolean flags. Could you try `--registry-insecure=false`?

**Comment by johnpoth** [comment]
Ah yes it seems that way :+1:

**Comment by Hades-888** [comment]
> Ah yes it seems that way 👍


> I think that's the way we parse the boolean flags. Could you try `--registry-insecure=false`?

@squakez tried, it seems return null after set ```--registry-insecure=false```
<img width="551" alt="null" src="https://user-images.githubusercontent.com/97818949/179500387-caa4fe4a-168b-4396-b2a0-9a214a95951b.png">
