### ISSUE TITLE
Integration cannot be run from github with different branch

### ISSUE THREAD

**Issue by mmajerni** [apache/camel-k#3475]
Running integration from GitHub should work as:
`kamel run github:$user/$repo/$path?branch=$branch`
Command:
`kamel run github:apache/camel-k/e2e/common/files/Java.java?branch=release-1.8.x`
is not working and it returns an error:
`Error: cannot read sources: cannot process file github:apache/camel-k/e2e/common/files/Java.java?branch=release-1.8.x: unsupported file type github:apache/camel-k/e2e/common/files/Java.java?branch=release-1.8.x`

**Comment by tadayosi** [comment]
@mmajerni Running on a GH branch should rather be like this:
```
kamel run github:apache/camel-k/release-1.8.x/e2e/common/files/Java.java
```
See the e2e tests for more details:
https://github.com/apache/camel-k/blob/release-1.9.x/e2e/common/cli/run_test.go#L43

Is there anywhere that tells `?branch=release-1.8.x` should work?

**Comment by tadayosi** [comment]
OK, I tried that but doesn't work as well:
```
$ ./kamel run github:apache/camel-k/release-1.8.x/e2e/common/files/Java.java
Error: cannot read sources: cannot read sources: the provided URL https://raw.githubusercontent.com/apache/camel-k/master/release-1.8.x/e2e/common/files/Java.java is not reachable, error code is 404
```
Definitely there's something wrong with it.

**Comment by tadayosi** [comment]
Looks like that test is silently failing, that's why we haven't noticed it. Related #3465

**Comment by mmajerni** [comment]
Hi @tadayosi, I updated that test: https://github.com/apache/camel-k/pull/3438/files#diff-d618db0cd5368f9f7428e20a95fd07e6b62a1abd375a331ca74914dc10103821L43
Before, the main branch was used so it worked. I added the branch but it is not working as you mentioned. 

Docs describe that if you want to specify a branch you need to specify the branch as a query parameter:
https://camel.apache.org/camel-k/1.8.x/running/run-from-github.html#_integration_code_stored_in_a_github_repository

Also you can see in the error code which you pasted that if you add branch to the URL (`kamel run github:apache/camel-k/release-1.8.x/e2e/common/files/Java.java`) it handles it as path not the branch and automatically set branch to master: 
.../apache/camel-k/**master**/**release-1.8.x**/e2e/common/files/Java.java

There is definitely a problem. One of those commands should work:
`kamel run github:apache/camel-k/e2e/common/files/Java.java?branch=release-1.8.x`
`kamel run github:apache/camel-k/release-1.8.x/e2e/common/files/Java.java`
