### ISSUE TITLE
Camel version mismatch

### ISSUE THREAD

**Issue by MeranaTona** [apache/camel-k#3481]
Hi all,

the most recent Camel K 1.8.x release [https://github.com/apache/camel-k/releases/tag/v1.8.2](url) references Camel 3.14.1. Meanwhile, new patches were released for Camel 3.14 https://github.com/apache/camel/releases/tag/camel-3.14.4. Which should add to a more stable experience.

Is it possible to use the most recent patch version of Camel 3.14 together with Camel K 1.18.2?

Greetings

**Comment by squakez** [comment]
We're about to release 1.10. I am not sure we will dedicate attention to 1.8, unless some important critical issue arises.

**Comment by tadayosi** [comment]
Maybe we could release camel-k-runtime more frequently, at least with the camel-quarkus versions based on the Camel LTS versions. Then users could choose Camel versions with `-t camel.runtime-version=`.

**Comment by MeranaTona** [comment]
Hi all, 

thanks for your replies.

> We're about to release 1.10. I am not sure we will dedicate attention to 1.8, unless some important critical issue arises.

I think critical issues are relative, because they depend on the use case. E.g. if you want use a feature that should work but is actually bugged, in production environments you will often not be able to to upgrade the version. Thus, your use case is in danger or completely dead.

A total of 45 bug reports have been solved in the meanwhile: https://camel.apache.org/releases/release-3.14.2/#resolved https://camel.apache.org/releases/release-3.14.3/#resolved and https://camel.apache.org/releases/release-3.14.4/#resolved

In my opinion, having a Camel K LTS version would increase trust and add to the attractivity of the project for being used in production.

Greetings

**Comment by squakez** [comment]
It's a valid point. I am not sure if we've already discussed how to support Camel LTS in the past. @oscerd any input on some past discussion by any chance? I had a look at the support provided by Camel Quarkus and I wonder if we should simply align to their release cadence when anything is released on an LTS based release. Thoughts are welcome.

**Comment by tadayosi** [comment]
It makes sense to me that we follow the Camel Quarkus LTS release cadence and keep supporting its LTS versions as well as latest for Camel K runtime, so that users can choose which Camel LTS version to use by switching a Camel K runtime version.

Then, ideally we should run our entire E2E test suite against the supported matrix of Camel K runtime versions.
