### ISSUE TITLE
Add roadmap information

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#35]
We should add to the documentation a high level roadmap of the project (see https://github.com/nicolaferraro/integration-operator).

**Comment by lburgazzoli** [comment]
Can we use https://github.com/apache/camel-k/projects/16 ?

**Comment by squakez** [comment]
We can provide a blog every year, such as: https://camel.apache.org/blog/2022/03/camel-k-roadmap-2022/ In this way we don't need to maintain a documentation page up to date.
