### ISSUE TITLE
Move tracing from opentracing to opentelemetry

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3519]
As Opentracing is marked as deprecated in Camel Quarkus: https://camel.apache.org/camel-quarkus/next/reference/extensions/opentracing.html

**Comment by gansheer** [comment]
Is the subject of this issue only the task of changing the [`Tracing`](https://camel.apache.org/camel-k/next/traits/tracing.html) trait from OpenTracing to OpenTelemetry (and everything related to this change) or are there some other tasks needed ?

@squakez any detail on this issue that could be missed would be greatly appreciated :+1:

**Comment by squakez** [comment]
No, I guess it's the only thing to do. Likely we may include more test coverage as a nice to have.

**Comment by squakez** [comment]
Thanks for the detailed proposal. If the option 2 does not present any particular problem, definitely, it would be the preferred solution.
