### ISSUE TITLE
In a specific scenario a new integration pod is created every ~0.5 seconds

### ISSUE THREAD

**Issue by claudio4j** [apache/camel-k#3522]
Running the following integration in openshift 4.10 with openshift serverless 1.23, on a new namespace, many pods are quickly created and after just a few seconds the worker node is exhausted and it changes to a NotReady state, with hundreds of pods in either Running, Terminated, Pending state.
```
public class AddToChannel extends RouteBuilder {
    public void configure() throws Exception {
        rest("/")
            .put("/input")
            .to("knative:channel/messages");
    }
}
```

**Comment by squakez** [comment]
Could it be related to #1826? the behavior looks suspiciously similar...
