### ISSUE TITLE
kamel upgrade

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-k#355]
There is currently no way to upgrade comfortably and safely for the running integrations. 

The uninstall+ install sequence works, but probably harms the running integrations.

**Comment by nicolaferraro** [comment]
We should target upgrade for milestone 1.0.0.

**Comment by lburgazzoli** [comment]
I think we should evaluate using web-hook for upgrading, defaulting CRs in case of upgrades.
/cc @astefanutti @nicolaferraro

**Comment by squakez** [comment]
Process described in https://camel.apache.org/camel-k/2.0.x/contributing/upgrade.html - CR upgrade done via Webhook when necessary.
