### ISSUE TITLE
Add back beginner examples

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#3579]
We need some basic hello world type examples
https://github.com/apache/camel-k/tree/main/examples

We only have some specific today that are not basic but about features, and the first one is rather complex with user config, modeline and whatnot.

We should have some basic timer -> log that are in
- java
- yaml
- xml

And then maybe also for alternative DSLs
- groovy
- kotlin
- javascript

We used to have a languages example that demonstrated all the DSLs (but this was removed)
https://github.com/apache/camel-k/blob/main/examples/languages/routes.yaml

**Comment by tadayosi** [comment]
We are in the process of moving the examples to https://github.com/apache/camel-k-examples. Now you can find those basic examples here:
https://github.com/apache/camel-k-examples/tree/main/generic-examples/languages

If we want to run an example from the camel-k project, you can do:
```
kamel run github:apache/camel-k-examples/generic-examples/languages/routes.yaml
```

Do you think it's better to move them back to the camel-k repo?

**Comment by davsclaus** [comment]
Ah okay, well since you are moving the examples, then remove the examples from camel-k so they are all in the same repo.

**Comment by davsclaus** [comment]
I am closing this as the beginner examples are in the examples repo.
