### ISSUE TITLE
Validate failure in CI

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-k#3591]
For some reason the `validate` workflow started to fail from #3587. Let's figure out how we can restore it.
https://github.com/apache/camel-k/actions/workflows/validate.yml

**Comment by tadayosi** [comment]
cc @astefanutti

**Comment by astefanutti** [comment]
@tadayosi yes, these are new issues unrelated to @3587. Maybe we'll want to add `only-new-issues: true` to the golangci-lint action configuration.

**Comment by tadayosi** [comment]
This easy fix seems to suppress the errors #3592
