### ISSUE TITLE
`make bundle` failure

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3602]
It fails with
```
ERRO[0001] ClusterServiceVersion validation: [CSVFileNotValid] (camel-k.v1.11.1) spec.replaces "camel-k-operator.v1.11.0-SNAPSHOT" is invalid: a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') 
FATA[0001] Error generating bundle manifests: error generating ClusterServiceVersion: invalid generated ClusterServiceVersion 
make: *** [Makefile:602: bundle] Error 1
```

**Comment by tadayosi** [comment]
It doesn't fail on my env. Could it be related to versions of operator-sdk / kustomize used?
```
$ kustomize version 
{Version:kustomize/v4.1.2 GitCommit:a5914abad89e0b18129eaf1acc784f9fe7d21439 BuildDate:2021-04-15T20:38:06Z GoOs:linux GoArch:amd64}

$ operator-sdk version 
operator-sdk version: "v1.14.0", commit: "78f08b4852faf344ad3ef457c54f86087aaa0a0a", kubernetes version: "1.21", go version: "go1.16.9", GOOS: "linux", GOARCH: "amd64"
```

**Comment by squakez** [comment]
I have the following:
```
$ kustomize version
{Version:kustomize/v4.5.7 GitCommit:56d82a8378dfc8dc3b3b1085e5a6e67b82966bd7 BuildDate:2022-08-02T16:35:54Z GoOs:linux GoArch:amd64}
$ operator-sdk version
operator-sdk version: "v1.14.0", commit: "78f08b4852faf344ad3ef457c54f86087aaa0a0a", kubernetes version: "1.21", go version: "go1.16.9", GOOS: "linux", GOARCH: "amd64"
```
Not sure if it's because the `kustomize` version. @phantomjinx is it working for you?

**Comment by tadayosi** [comment]
Yes, I found that kustomize is sensitive to versions. It's always safe to use the tooling versions specified in Makefile:
https://github.com/apache/camel-k/blob/main/script/Makefile#L21-L28

FYI, I use [aqua](https://aquaproj.github.io/) to align versions for Camel K development:
https://gist.github.com/tadayosi/e1d7db2496d250bf06428a9437457119

**Comment by squakez** [comment]
No luck. With version 4.1.2 I got the same result...

**Comment by phantomjinx** [comment]
Kustomize and operator-sdk are correct and the error is valid. The `replaces` property and the `name` property of the CSV have valid syntax and these tools are checking it. The suffix `SNAPSHOT` is not valid. Ironically, these changes are not carried through to actual bundle image creation since it is possible to build the image with manual textual changes and OLM still works.

**Comment by squakez** [comment]
Not a bug.
