### ISSUE TITLE
Should `make bundle` update kustomization.yaml?

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3606]
As discussed in https://github.com/apache/camel-k/pull/3601#discussion_r963234805 the `make bundle` is adding `images` property. Is that correct?

**Comment by squakez** [comment]
Can you help @phantomjinx ?

**Comment by tadayosi** [comment]
Yes, I think so too. This is the most itchy part of kustomize for me. The kustomize developers has deliberately chosen that user-customised changes are directly applied to the `kustomization.yaml` file. And there seems to be no way to parameterise user configs other than tainting `kustomization.yaml`:
https://kubectl.docs.kubernetes.io/faq/kustomize/eschewedfeatures/#build-time-side-effects-from-cli-args-or-env-variables

**Comment by phantomjinx** [comment]
Can this be closed as asked and answered?
