### ISSUE TITLE
Allow to remap headers to cloudevents headers

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#361]
When sending messages to a knative channel, only some headers are forwarded. Custom headers are blocked. Cloudevents headers (starting with `ce-`) pass.

We may add a flag to the knative component to remap headers (which ones?) to cloudevents headers to avoid losing them.

**Comment by lburgazzoli** [comment]
It may be something to add to the CamelSource ? We could have a section in where users can define which header has to be propagate and what is the target name.
