### ISSUE TITLE
camel k 0.11.0 helm - Error: parse error at (camel-k/templates/operator.yaml:87): "-en"

### ISSUE THREAD

**Issue by joes** [apache/camel-k#3654]
To reproduce simple download the helm chart and run `helm template` on the extracted archive:

```console
$tar -xvzf camel-k-0.11.0.tgz
$helm template camel-k
Error: parse error at (camel-k/templates/operator.yaml:87): "-en"

Use --debug flag to render out invalid YAML
```

It seems there is a typo at row 87:

```
{{-end }}
```

This should be corrected to:

```
{{- end }}
```

**Comment by oscerd** [comment]
It has been fixed. Need to regen

**Comment by oscerd** [comment]
It should be fixed with https://github.com/apache/camel-k/commit/cb9f7572e2f1aec071aea28ac4f32e48be0799d0

**Comment by oscerd** [comment]
Thanks to you for reporting. I totally forget to regen when merging the fix

**Comment by oscerd** [comment]
Please check if everything works fine now.

**Comment by joes** [comment]
It works now.
