### ISSUE TITLE
Misleading message when updating an unchanged `Integration`

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3705]
When we try to update an Integration, the CLI reports that it has been updated, even if there is no update or changes:
```
kamel run ... 
Integration "promote-route" updated
```
we should warn the user that there are no changes to apply. We can use the same notation provided in `kubectl` CLI:
```
kamel run ...  -o yaml | kubectl apply -f -
integration.camel.apache.org/promote-route configured
kamel run ...  -o yaml | kubectl apply -f -
integration.camel.apache.org/promote-route unchanged
```

**Comment by Yavnikaa** [comment]
Hi! I am new here and was looking to contribute to Apache Camel-K. I am currently setting up the repository on my device. Can I please take this issue up?

**Comment by oscerd** [comment]
It's enough to leave a comment here

**Comment by Yavnikaa** [comment]
Thanks, working on it!
I wanted to know if it is necessary to install maven as well to make it work?

**Comment by tadayosi** [comment]
@Yavnikaa I suggest you start from reading this https://camel.apache.org/camel-k/next/contributing/developers.html

**Comment by Yavnikaa** [comment]
Alright, thankyou!

**Comment by Yavnikaa** [comment]
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

I get this warning when I am building the code, do we ignore it or is there a fix?

**Comment by tadayosi** [comment]
@Yavnikaa Yes, right now the `main` branch has this bug. Please change the string `/usr/bin/mvn` to `mvn` in the `maven_log_test.go` file locally to make it pass. Maybe it can be a good first exercise for you to interace with the Camel K code base.

**Comment by Yavnikaa** [comment]
Thankyou so much. I changed it in the codebase locally but I am still getting the same error while building on the terminal. Is there any other workaround?

**Comment by tadayosi** [comment]
@Yavnikaa Fix #3805 is merged. Please try it again.

**Comment by Yavnikaa** [comment]
I pulled the changes to my local and unfortunately, it still doesn't work, with the same error message. I am using WSL2. Could that be the cause of the issue?

**Comment by Yavnikaa** [comment]
Hi. Any ideas on how could I resolve the issue?

**Comment by tadayosi** [comment]
What error exactly are you seeing now?  Make sure you have `mvn` in the path. Since I don't have a Window environment I cannot help the troubleshooting further.

**Comment by Yavnikaa** [comment]
Yes , I have added `mvn` in tha path.

![Screenshot (302)](https://user-images.githubusercontent.com/56485761/201874454-df6c1a5b-ee88-4992-b720-80fb7d473137.png)

This is the exact error I am getting. Can I ask in some community forum by wsl users to help debug this?

**Comment by tadayosi** [comment]
Perhaps as the first step for contributing, you can try to understand what's really going on in this test and see why it's failing. Lines 33,34 are the assertions part. Instead of asking in a forum try to investigate why the assertions fail on your env.

```
	cmd := exec.CommandContext(context.Background(), "mvn", "package")
	err := util.RunAndLog(context.Background(), cmd, mavenLogHandler, mavenLogHandler)

	assert.NotNil(t, err)
	assert.ErrorContains(t, err, "[ERROR] The goal you specified requires a project to execute but there is no POM in this directory")
```

**Comment by Yavnikaa** [comment]
Alright!
I was getting the error message on line 34 before, but I fixed it by adding a pom.xml.
I tried modifying the `maven_log.go` file, to print the specific error message but it isn't behaving as expected. How can I print the specific error rather than "NotNil" ?

**Comment by tadayosi** [comment]
Camel K is a Go project. If you want to contribute to it, knowledge of Go is a must. You can start learning the basics of Go:
https://go.dev/doc/tutorial/getting-started
