### ISSUE TITLE
E2E native flaky tests

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3726]
Looks like there is something wrong with ([more detailed logs](https://github.com/apache/camel-k/actions/runs/3204088305/jobs/5234959608)):
```
❌ TestNativeBinding (30m15.6s)
 make: *** [Makefile:304: test-quarkus-native] Error 1
❌ TestNativeBinding/kamelet_binding_with_native_build (30m0.03s)
❌ TestNativeIntegrations (32m57.17s)
❌ TestNativeIntegrations/automatic_rollout_deployment_from_fast-jar_to_native_kit (30m46.38s)
```
This is happening both on `main` and `release-1.10.x`

**Comment by tadayosi** [comment]
Is it the same issue with #3715?  For relese-1.10.x, at least we can split the e2e into `install-it` and `native-it` as is in the main branch to remedy the failures.

**Comment by squakez** [comment]
Yes, the seems to be the same. I'll close this in favor of that one.
