### ISSUE TITLE
e2e testing: refactor to remove deprecated functions

### ISSUE THREAD

**Issue by phantomjinx** [apache/camel-k#3751]
The `set-output` and `save-state` functions are being removed and new environment variables added to replace their usage. All e2e actions use `set-output` so will need refactoring to update to the new syntax. See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands and https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files for details.

**Comment by phantomjinx** [comment]
Please assign to me. Thanx

**Comment by tadayosi** [comment]
fixed by #3823
