### ISSUE TITLE
Use `govulncheck` to check security vulnerabilities

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-k#3753]
It might be a good idea to have a make target that runs `govulncheck` and/or have a CI workflow to run it on the project periodically.
https://github.com/golang/vuln

Note that this command is available only from Go 1.18.

**Comment by gansheer** [comment]
I will take care of this.

**Comment by squakez** [comment]
Maybe we can run this only on PRs with dependency changes, ie https://github.com/apache/camel-k/blob/main/.github/workflows/coverage.yml#L22-L23 (instead we just checkout go.mod and go.sum). WDYT?

**Comment by gansheer** [comment]
It could be a good idea for the PR part, but I fear we will run in the case when it's always in warning if we find ourself in a case where it is a vulnerability from one of the golang libs that come with the golang version. It would be a clear signal that we need to upgrade golang but it would mean having check errors for PRs before the upgrade is done.

**Comment by squakez** [comment]
Considering all the importance security is getting lately, I'd try to do that on the PR. If we will in a situation where we cannot stay after it, we can easily turn the action into a nightly check. Or we can do the other way around. Feel free to do the way you prefer. Once the action is in place is relatively easily to adjust the process.
