### ISSUE TITLE
Deprecated Github actions / warnings

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3766]
It seems we have a few things to clean. For example:

* Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, AdoptOpenJDK/install-jdk, actions/setup-go, azure/setup-kubectl, actions/cache, actions/cache, actions/checkout
* The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
* The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

We may have to have a deeper look for anything else and solve before they are dropped.

**Comment by tadayosi** [comment]
Partially being addressed at #3751

**Comment by gansheer** [comment]
@squakez 
I will take care of the last point that still needs to be done : the Nodejs 12 actions dependencies.

**Comment by squakez** [comment]
No more warning, thanks!
