### ISSUE TITLE
E2E - No longer able to run native build tests with Quarkus 2.13.0 (Camel Catalog 1.15.x)

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-k#3773]
Related to #3715.

I've been investigating why the native build E2E tests keep failing on `release-1.10.x` whereas they don't on `main`.
https://github.com/apache/camel-k/actions/runs/3312246340/jobs/5468684587

I found that the key difference is the runtime versions used:
```
$ git diff release-1.10.x -- script/Makefile
...
-RUNTIME_VERSION := 1.15.1
+RUNTIME_VERSION := 1.14.0
```
So `release-1.10.x` is updated to Camel K runtime 1.15.1 while `main` remains with 1.14.0.

That means we will no longer be able to run native build tests with Quarkus 2.13.0 (Camel Catalog 1.15.x) or later. As soon as upgrading the runtime version used, we'll see the same failures with the `main` branch as well.

**Comment by squakez** [comment]
That's exactly the reason why I opened: https://github.com/apache/camel-k/pull/3764. We will see likely the errors also against `1.16.0-SNAPSHOT` then. Let's figure it out how to fix in `main` and `release-1.10.x` then.

**Comment by tadayosi** [comment]
Yes, I am aware of #3764. The exact reason why #3764 is failing at `native-it` is because of this issue.

And again, a simple fix of increasing timeout (40min -> 60min this time) seems to work #3774. I'll port #3774 to `main` as well.

**Comment by squakez** [comment]
Perfect. I'll wait that one to be merged and rebase the failing PR. Thanks @tadayosi!!
