### ISSUE TITLE
Unable to configure ServiceAccountName using Kamel run

### ISSUE THREAD

**Issue by Thomas9047** [apache/camel-k#3797]
Hello all,

First of all, I hope that this is the correct place. 
I am trying to configure the ServiceAccountName for an integration.
I have looked at the following issue: https://github.com/apache/camel-k/issues/305, but I can't find any documentation for this.

Is there an option to set the serviceAccountName using Kamel run? Maybe by using a pod trait?

Thanks in advance

**Comment by tadayosi** [comment]
Right now you'd need to manually modify the Integration CR to apply the serviceAccountName parameter, e.g.:
```
kubectl patch it <your-integration> -p '{"spec": {"serviceAccountName": "CUSTOM_SERVICE_ACCOUNT" }}'
```

**Comment by squakez** [comment]
Definitely it would be a good idea for a new trait. Feel free to contribute to it!
