### ISSUE TITLE
query regarding using camel k

### ISSUE THREAD

**Issue by manali-jambhale** [apache/camel-k#3815]
We see for apache camel-k that "this is the development version of camel k. It should not be used in production." as per the link  https://camel.apache.org/camel-k/1.10.x/index.html
But we see one of answered issue we see below
"In terms of community releases, we'll publish version 1.0.0 in the next weeks, so I don't expect someone being in production with the current pre-releases." in the link https://github.com/apache/camel-k/issues/1436
can you confirm if the understanding that "version (1.10.x) of Camel K can be used in production" is correct.

**Comment by squakez** [comment]
1.10.3 is the latest stable version: https://github.com/apache/camel-k/releases/tag/v1.10.3 - can you please tell me where you see that "Version 1.10.x is development version. It should not be used in production." statement?

**Comment by manali-jambhale** [comment]
Thank you for your quick response. I have updated the original question with link details.

**Comment by squakez** [comment]
Uh. That's not true. I guess we forgot to amend the documentation. Thanks for reporting. About the comment in #1436 it's quite old and it was referring to that period when we still were working on `0.x` version of the project. Since `1.x` you can consider any fixed release a production ready one.
