### ISSUE TITLE
Remove KEP cryptic message when installing

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3829]
`Warning: the operator won't be able to detect a local image registry via KEP-1755` message can be ignored most of the time but it can create a false sense of alarm to the user. We should either remove the message or provide a more meaningful message.

**Comment by johnpoth** [comment]
Agreed. Maybe on TRACE level and remove the "warning"

**Comment by Kaushik-Iyer** [comment]
Can I work on this? I don't know which file to change though

**Comment by squakez** [comment]
> Can I work on this? I don't know which file to change though

Sure. I guess you can look for the resource containing that trace and do the change.

**Comment by Kaushik-Iyer** [comment]
I can't find any such message in the resources folder files

**Comment by squakez** [comment]
https://github.com/apache/camel-k/blob/1bb415b01a6e1b01f31ec04194b81be19f33fbd5/pkg/install/operator.go#L302
