### ISSUE TITLE
Rethink E2E execution flow

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3847]
I made a quick search to see how many time we're installing Camel K operator in our suite of test: 101 times! If you really think about it, it should be enough to have it done just once (at least, once per every action we run). I think we can have a better way of running our suite of test by separating the Camel K build/installation phase from the real testing logic. By having this separation we should have great improvements in performance and also a simplification in how we startup/teardown resources.

Feedback welcome.

**Comment by squakez** [comment]
@tadayosi @phantomjinx @bouskaJ

**Comment by tadayosi** [comment]
I am not sure if I understand it correctly, but isn't it exactly what Paul had done a few months back?

After Paul's work, now basically we have two kinds of E2E tests, 1) **global** tests under `e2e/global`, and 2) **namespaced** tests under `e2e/namespace`. The global tests mean that they can run with a single global operator, whereas the namespaced tests mean that they require a dedicated operator per namespace to run for reasons.

So for the global tests, it should already install a global operator *only once per workflow*. The test code still have operator installation steps but if you look into the helper function further you'll see that the installation is skipped when the global test flag is `true`.

For the namespaced tests, they have reasons. It should be still helpful to review them and find possibility to move them to global, though.

**Comment by squakez** [comment]
I wasn't aware of this separation. I've just made a quick search and for me it seems there is still room for improvement. Even for the namespaced tests, let's say we have 10 different tests. Shouldn't we do as follow?
1. build and install Camel K operator
2. Run test 1
3. Clean namespace (`kamel reset`)
4. Run test 2
5. ...

**Comment by tadayosi** [comment]
I believe the most evident reason why the namespaced tests have to run with a dedicated operator is that they want to test specific configurations of the operator. For that reason I don't think the step 1 can be shared among the tests.

However, yeah it seems many of these ones may be moved to `e2e/global` for gaining additional test efficiency:
https://github.com/apache/camel-k/tree/main/e2e/namespace/install/cli

**Comment by squakez** [comment]
I agree that, if there is some specific configuration to test, we need to make a dedicated installation, but, take just as an example the `common` workflow. We use it as a basic smoke test for nightly release, so it's run every night. There are 100 tests, and, the operator is installed 45 times (at least, according to the log).

**Comment by tadayosi** [comment]
> but, take just as an example the common workflow. We use it as a basic smoke test for nightly release, so it's run every night. There are 100 tests, and, the operator is installed 45 times (at least, according to the log).

To be precise, it shouldn't be the operator deployments that are installed 45 times, but should be the `IntegrationPlatform` resources that are installed each time.
https://github.com/apache/camel-k/blob/main/e2e/support/test_support.go#L254

I don't think creating a CR per test run costs so much time, but if it doesn't make sense we can remove the installation step from the test support function.

**Comment by squakez** [comment]
Unfortunately it's not the case for the `common` flow. According to the log, when we skip the operator we should have:
```
$ kamel install --skip-operator-setup -n test
OLM is not available in the cluster. Fallback to regular installation.
Camel K operator installation skipped
Camel K installed in namespace test
```
But here we always have something like:
```
 OLM is not available in the cluster. Fallback to regular installation.
  Warning: the operator won't be able to detect a local image registry via KEP-1755
  Camel K installed in namespace test-2bb3139c-42f7-4882-81cb-b13313e5d638 
      test_support.go:2154: Clean up test namespace: test-2bb3139c-42f7-4882-81cb-b13313e5d638
...
```
If we do install the `IntegrationPlatform` I'd be fine with it, but the evidence I got from the log make me think differently :(
