### ISSUE TITLE
Deprecate `kamel install` and promote Kustomize-based installation to primary method

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-k#3865]
Similarly to #3790, it's good time to deprecate `kamel install` and promote [Kustomize-based installation](https://camel.apache.org/camel-k/next/installation/advanced/kustomize.html) to the primary method of Camel K installation.

There are two tasks we should perform:
- [ ] Mark deprecation to `kamel install` command, like `kamel init` and `kamel local`.
- [ ] Rewrite [documentation](https://camel.apache.org/camel-k/next/installation/advanced/kustomize.html) and restructure it so that it's seen as the primary method for Camel K installation.

**Comment by tadayosi** [comment]
Relates #1503

**Comment by squakez** [comment]
Do we have full feature parity if we adopt the Kustomize option?

**Comment by squakez** [comment]
One further consideration from Apache release process policy point of view. Right now we are releasing a binary following a release process that produces a CLI which configure the released container image. This combination of software is passing a voting system. How should we change this to be in line with the policy? I mean, I guess we need a clear deliverable (it could be even a repository tag) that will need to tested during the release voting process.

@oscerd wdyt?

**Comment by oscerd** [comment]
It's not a maven release, so there is no concept of staging repository, what we could do is creating a pre-release tag with everything in place and eventually create a tag from there once the vote passed.

**Comment by tadayosi** [comment]
> Do we have full feature parity if we adopt the Kustomize option?

Good point. Right now, only few `kamel install` flags are ported to the Kustomize method, while users are free to manually patch the resources under `install/` to achieve the same. So I agree that it's a bit too early to deprecate `kamel install`. At the same time, unless we try to push the Kustomize method as the primary method we won't fill the gap in the near term. At least I think we can start promoting it as one of the primary methods.

```
$ make help
...
operator        Install the operator deployment and related resources

                Cluster-admin privileges are required.

                NAMESPACE:          Set the namespace to install the operator into
                PLATFORM:           Override the discovered platform, if required
                GLOBAL:             Sets the operator to watch all namespaces for custom resources [true|false]
                CUSTOM_IMAGE:       Set a custom operator image name
                CUSTOM_VERSION:     Set a custom operator image version/tag
                ALWAYS_PULL_IMAGES: Sets whether to always pull the operator image [true|false]
                MONITORING:         Adds the prometheus monitoring resources
                MONITORING_PORT:    Set a custom monitoring port
                HEALTH_PORT:        Set a custom health port
                LOGGING_LEVEL:      Set the level of logging [info|debug]
                DRY_RUN:            Prints the resources to be applied instead of applying them
...
```

**Comment by squakez** [comment]
Okey, so, maybe we should do this development the other way around. We start changing the documentation in order to promote the `kustomize` way to install the operator. As soon as we have it, our user base will naturally ask to include such features in the kustomize (at least, I hope so!). Once we have a certain level of parity we will be able to deprecate officially the `kamel install`. However, we need to start to change the documentation for this to happen.

**Comment by tadayosi** [comment]
Hi @phantomjinx,

To complete the features of Kustomize installation, I'm trying to add `ENV_VARS` and `SKIP_DEFAULT_KAMELETS_SETUP` parameters to `make operator` as a starter. However, I found that implementing these in Makefile can be tricky, probably requiring a lot of bash,Makefile,sed,awk magic. Now I wonder if it's really the right direction to try to replicate every feature provided by `kamel install` in the `Makefile` for the Kustomize installation, as it doesn't seem like a good idea to use Makefile as a general programming language.

It seems that the Kustomize way is for users to directly create and customise their own patches either by hand or through `kustomize` command, rather than the tool to provide convenient parameters to customise everything for them.

What do you think about it?  Is it your original intention to provide every installation feature through the `Makefile`?

**Comment by lburgazzoli** [comment]
FWIW, we can add some pre-configured and opinionated kustomize overlay for dev/test/etc

**Comment by phantomjinx** [comment]
So @astefanutti and I thought that the kustomize/Makefile combination was always going to be a pairing of convenience designed to allow for the most common and simplest use-cases. Since kustomize can be so opinionated and uses can readily change the kustomize config files to suit their own objectives, it was therefore thought best not to implement every function and switch of the `kamel` binary, not least because the more advanced use-cases do not readily lend themselves to the Makefile syntax.

**Comment by tadayosi** [comment]
@lburgazzoli @phantomjinx Thanks for your inputs. Those really make sense.

So, instead of making it more feature-rich, we should rather keep the `Makefile` simple and then provide a sensible and useful set of predefined overlays for the base installation yaml files. And we should extend more about how to install specific configurations of Camel K with `kustomize` or `kubectl -k` in the documentation:
https://camel.apache.org/camel-k/next/installation/advanced/kustomize.html

**Comment by gansheer** [comment]
Can you assign this one to me @squakez please. I will see how to continue this subject.

**Comment by squakez** [comment]
@gansheer what's the status of this?

**Comment by gansheer** [comment]
I was waiting for advancement on https://github.com/apache/camel-k/issues/3397. But I wonder if I should not continue again because [#3397](https://github.com/apache/camel-k/issues/3397) looks like a long time development

**Comment by squakez** [comment]
> I was waiting for advancement on #3397. But I wonder if I should not continue again because [#3397](https://github.com/apache/camel-k/issues/3397) looks like a long time development

IMO they should independent. If there is any dependency, then, we can always adjust the development accordingly. The main reason to try closing this ASAP is to deprecate and remove the CLI definitively.

**Comment by squakez** [comment]
@gansheer I'm taking this over. Are you okay with that?

**Comment by squakez** [comment]
Closing this in favor to the discussion opened in #5615
