### ISSUE TITLE
Kustomize-based installation method doesn't provide uninstall

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-k#3866]
To fully substitute the current `kamel install/uninstall`, we'd need to provide uninstallation based on Kustomize like `make uninstall`. For using `kubectl`, it should be possible by doing `kubectl delete -k <target>` but should be documented.

Relates to #3865

**Comment by tadayosi** [comment]
@phantomjinx Does it make sense?

**Comment by phantomjinx** [comment]
> @phantomjinx Does it make sense?

Yes. That's logical. I wasn't aware that `kubectl` could utilise `delete` and `-k` for that purpose :-)
