### ISSUE TITLE
Saga example failing with version > 1.10

### ISSUE THREAD

**Issue by MotaOcimar** [apache/camel-k#3869]
I'm trying to run the [Saga Camel K example](https://github.com/apache/camel-k/tree/main/examples/saga), but I'm facing the folloing error on the `saga` service:

```
Failed to start application (with profile prod): org.apache.camel.NoSuchEndpointException:
No endpoint could be found for: direct://lra-compensation, please check your classpath contains the needed Camel component jar
```

Also, I tried to create the following route with an `direct://lra-compensation` endpoint just for testing:

```java
from("direct://lra-compensation")
.log("Hey, I shouldn't be here!");
```

And I get the error

```
Failed to start application (with profile prod): org.apache.camel.FailedToStartRouteException:
Failed to start route route4 because of Multiple consumers for the same endpoint is not allowed: direct://lra-compensation
```

This is so weird. After all, does the endpoint exist or not?

**Comment by squakez** [comment]
What version of Camel K are you using? I've just tested the following with version `1.10.3` and it works correctly:
```
      from("timer:java?period=1000")
        .setBody()
          .simple("Hello Camel K from ${routeId}")
        .to("direct://lra-compensation");

        from("direct://lra-compensation")
           .to("log:info");
```

**Comment by MotaOcimar** [comment]
I ran `kamel version` and got `Camel K Client 1.9.2`.

Oh, notice that the `direct://lra-compensation` endpoint probably is created by Camel. I dint't directly use that endpoint in my project.

**Comment by squakez** [comment]
I've tried to run the example with `1.10.3` but it fails to start. I think it should be reviewed with the newest syntaxt expected by Camel 3.18+ versions. As for the `direct` endpoint it works correctly.

**Comment by squakez** [comment]
Okey, I understand which is the problem now. The route is generated dynamically, and in that case we're not able to detect the components (https://github.com/apache/camel-k/issues/527). In order to workaround this, you need to run the Saga route with `-d camel:direct` and include the direct component dependency.

**Comment by MotaOcimar** [comment]
Ok, It worked, thanks!

I opened the #3883 PR to fix this issue.

**Comment by MotaOcimar** [comment]
Just an additional question. Here I had difficulties with the logs.
Sometimes it takes a long time to update the logs in the terminal.

Both the log with `kamel logs <service>` and the log with `kubectl logs <pod>` are not updated as often as expected (every 5 seconds).

Any guidance?

**Comment by squakez** [comment]
> Just an additional question. Here I had difficulties with the logs. Sometimes it takes a long time to update the logs in the terminal.
> 
> Both the log with `kamel logs <service>` and the log with `kubectl logs <pod>` are not updated as often as expected (every 5 seconds).
> 
> Any guidance?

I guess it depends on the kubernetes cluster. The `kamel logs` is using APIs exposed by `kubectl` if I am not wrong (so, they're equivalent)
