### ISSUE TITLE
Allow "kamel promote" integrate with GitOps styled deployments

### ISSUE THREAD

**Issue by agiertli** [apache/camel-k#3888]
Hi,

right now, to utilize kamel promote feature, it has to be executed as a CLI command directly via pipeline. This makes it hard to integrate it with a more modern way of deploying application which relies on GitOps paradigm.

This could be potentially mitigated if kamel promote came up with the "dry-run" option which would output set of valid k8s YAML manifests which would fully represent the promoted integration. This would allow to easily integrate "kamel promote" with GitOps styled repositories, so instead of promoting integration directly by calling "kamel promote" command, we would delegate this to GitOps solution which would simply apply the valid manifests of the promoted integration.

**Comment by tadayosi** [comment]
`kamel install` has `-o|--output {yaml|json}` option, so `kamel promote` should provide the same option as well.
