### ISSUE TITLE
Allow traits to be configured via configmap/secrets

### ISSUE THREAD

**Issue by agiertli** [apache/camel-k#3891]
Right now the trait configuration values are hardcoded in the Integration or KLB itself.

It would be useful to have a possibility to externalize that configuration. Example CLI command could look like:
`-t container.cpu={{configmap:mycm/cpu}}`

This is especially important in context of "kamel promote" feature, because if you can't externalise config, then you are forced to re-use the same trait configuration values across environment. Good example is container trait - where you typically have different values for mem/cpu/replicas across dev and prod.

**Comment by squakez** [comment]
It could be that one, or maybe also any properties available in `application.properties`, being the properties also configurable from a Configmap or a Secret.

**Comment by squakez** [comment]
With the presence of the dry-run provided in #4050 it should makes sense to post process any profile with Kustomization style approach. Ideally with the new feature, you will `kamel promote ... -o yaml` that would produce an Integration CR on top of which we can apply any customization via `kubectl apply -k`. I am closing this in favour of the aforementioned approach.
