### ISSUE TITLE
Important increase of size of apache/camel-k Docker image

### ISSUE THREAD

**Issue by apupier** [apache/camel-k#3925]
Between 1.10.1 and 1.10.2 https://hub.docker.com/r/apache/camel-k/tags , the size increased from 367Mo to 601Mo.

Based on commiter @squakez , "it is worth to have a look. I cannot recall anything important that doubled the size of the image"

**Comment by gansheer** [comment]
There is a clear difference in the image layers between [1.10.1](https://hub.docker.com/layers/apache/camel-k/1.10.1/images/sha256-45b5d4e32c3eb9231fc0c0870039c2966d6332260e096fa097b0076e51938159) and +[1.10.2](https://hub.docker.com/layers/apache/camel-k/1.10.2/images/sha256-26202410b504f01e966522ab713404050fb7e3f3c1bfce7d0a98019736d09292). 

I built the images locally for the v1.10.0, v1.10.1 and v1.10.2 tags from source and that resulted in container images with the sames layers and size range that the v1.10.2 that can be pulled from the official repos. I can't reproduce the original build images result for v1.10.1 and v1.10.0 from the sources.

I don't know how to interpret these observations, but it might be that the origin of the size increase is out of camel-k code (a change in a source image, the way images are built in the releasing process, ...).

**Comment by tadayosi** [comment]
Looking at the commit logs between v1.10.1 and v1.10.2, the only notable change made was upgrading Camel K Runtime 1.15.0 -> 1.15.1: https://github.com/apache/camel-k/commit/ba3912b758f01f48ca0c2bd3657029ee7e25293a I haven't looked into the Camel K Runtime side, but is it possible that the upgrade contributed to the size increase?

**Comment by squakez** [comment]
I think the point made by @gansheer is correct. There is a difference in the base layer we're using. Starting from the mandrel image used in version 1.10.2 there's a quite a lot of more statements. For instance, the following one:
```
COPY mandrel-java11-linux-amd64-21.3.0.0-Final.tar.gz /tmp/artifacts/ # buildkit
```
is used to copy some script and is not removed (it should be transparent to us). Maybe it should be checked directly with the support of Mandrel to see how they can shrink it accordingly.

**Comment by gansheer** [comment]
The difference started in 21.2.x, there is more or less 240M more on recent image.

![Capture d’écran du 2022-12-23 16-04-10](https://user-images.githubusercontent.com/6067789/209358030-6f9c7a30-14be-4afa-ad54-78b5c3dc0f82.png)

Do someone know what is the builder of theses quarkus mandrel images ?

**Comment by apupier** [comment]
I think it is build from here https://github.com/quarkusio/quarkus-images/tree/main/quarkus-mandrel-builder-image

**Comment by gansheer** [comment]
From the information given on the issue open in the quarkus mandrel images repository, I would say we can close this issue. Is this good for you @apupier ?

For anyone having some timeout deploying the operator (typically a `Error: ImagePullBackOff` after 2 minutes by default kubernetes timeout configuration) the recommended action is to ensure the image is pulled beforehand in the local/dedicated registry to have it available in your kubernetes.

**Comment by apupier** [comment]
> From the information given on the issue open in the quarkus mandrel images repository, I would say we can close this issue. Is this good for you @apupier ?

fine for me. Thanks for the investigation.

> For anyone having some timeout deploying the operator (typically a `Error: ImagePullBackOff` after 2 minutes by default kubernetes timeout configuration) the recommended action is to ensure the image is pulled beforehand in the local/dedicated registry to have it available in your kubernetes.

For convenience providing the information here for instance with minikube, it will be something like that: `minikube ssh docker pull apache/camel-k:1.11.0`
