### ISSUE TITLE
Add daily operator image builds

### ISSUE THREAD

**Issue by rhuss** [apache/camel-k#393]
For testing the latest release it would be wonderful if a `latest` operator image could be pushed on a daily basis to Docker Hub.

Ideally, this should be integrated into the CI system already used, but I'm not sure whether Travis supports daily (or scheduled) builds (or only triggered when a commit is pushed).

**Comment by astefanutti** [comment]
I think having the `latest` tag published after each successful build triggered by commit would do it.

**Comment by oscerd** [comment]
We will need to add credentials and to follow some steps for this

https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry

**Comment by squakez** [comment]
@oscerd I'm making some experiment. You're assigned to it. Do you mind if I got assigned instead?

**Comment by oscerd** [comment]
Assigned to you!
