### ISSUE TITLE
Smoke test error TestKameletBindingScale

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3959]
❌ TestKameletBindingScale/Scale_kamelet_binding_with_Camel_K_client (40ms)
      scale_binding_test.go:120: 
          Expected
              <v1.ConditionStatus>: False
          to equal
              <v1.ConditionStatus>: True

**Comment by squakez** [comment]
It was a flaky test apparently.

**Comment by tadayosi** [comment]
Why don't we fix the flakiness then? :-)

**Comment by squakez** [comment]
> Why don't we fix the flakiness then? :-)

Good one... I think this problem happened just once, so, it does not justify to invest more time on it. When the problem is repeated more than once I guess there is enough opportunity to reproduce the reason of the flakiness and try to fix it.
