### ISSUE TITLE
CXF Maven Dependency error while running the camel k on OpenShift

### ISSUE THREAD

**Issue by gtata007** [apache/camel-k#3961]
Hello Everyone,

While trying to run a java DSL sample program on OpenShift(CamelK 1.6.1) .  The program is trying to call a webservice invocation using cxf dependencies and it is failing at the Build Submitted phase. As per the operator logs, it shows us that it is unable to download the referenced CXF jars. I have tried to run the integration using the following command but it doesn't work.

**VERSION**
red-hat-camel-k-operator.v1.6.3
Camel K Client 1.6.1

**Command to produce the Issue**
kamel run TestWeb.java --dev -t logging.level=DEBUG

**Sample Program**

// camel-k: language=java
// camel-k: dependency=mvn:org.apache.camel:camel-cxf:3.9.0
import org.apache.camel.builder.RouteBuilder;

public class TestWeb extends RouteBuilder {
  @Override
  public void configure() throws Exception {
      // Write your routes here, for example:
      from("timer:java?period=1000")
        .routeId("java")
        .setBody()
          .simple("Hello Camel K from ${routeId}")
        .to("log:info");
  }
}

**Error Log:**
{"level":"error","ts":1672787680.4133232,"logger":"camel-k.maven.build","msg":"[ERROR] Some problems were encountered while processing the POMs:\n[ERROR] 'dependencies.dependency.artifactId' for org.apache.camel.quarkus:camel-quarkus-cxf:3.9.0:jar with value 'camel-quarkus-cxf:3.9.0' does not match a valid id pattern. @ line 34, column 19\n[ERROR] 'dependencies.dependency.version' for org.apache.camel.quarkus:camel-quarkus-cxf:3.9.0:jar is missing. @ line 32, column 17\n[ERROR] 'dependencies.dependency.version' for org.apache.camel:camel-cxf:jar is missing. @ line 60, column 17\n @ ","stacktrace":"github.com/apache/camel-k/pkg/util/log.Logger.Errorf\n\tgithub.com/apache/camel-k/pkg/util/log/log.go:60\ngithub.com/apache/camel-k/pkg/util/maven.normalizeLog\n\tgithub.com/apache/camel-k/pkg/util/maven/maven_log.go:62\ngithub.com/apache/camel-k/pkg/util/maven.(*Command).Do\n\tgithub.com/apache/camel-k/pkg/util/maven/maven_command.go:140\ngithub.com/apache/camel-k/pkg/builder.BuildQuarkusRunnerCommon\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:189\ngithub.com/apache/camel-k/pkg/builder.buildQuarkusRunner\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:163\ngithub.com/apache/camel-k/pkg/builder.(*builderStep).execute\n\tgithub.com/apache/camel-k/pkg/builder/steps.go:46\ngithub.com/apache/camel-k/pkg/builder.(*builderTask).Do\n\tgithub.com/apache/camel-k/pkg/builder/builder.go:125\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorRoutineAction).runBuild\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_routine.go:146"}

I am following the documentation for the cxf.
**https://camel.apache.org/components/3.20.x/cxf-component.html**

Best Regards,
Guru

**Comment by squakez** [comment]
Hello, the component supported by Camel Quarkus runtime is really `camel-quarkus-cxf-soap`, there is no support to the old plain `cxf`: https://camel.apache.org/camel-quarkus/next/reference/extensions/cxf-soap.html

Any camel dependency is converted into the related camel quarkus extension trasparently, so, you need to make sure the correspondent camel quarkus extension exists.

**Comment by gtata007** [comment]
Hi @squakez ,

Thank you for your response on this. I have changed the import statement as follows but still camel k operator is throwing the error.


**Sample Program**

// camel-k: language=java
// camel-k: dependency=mvn:org.apache.camel.quarkus:camel-quarkus-cxf-soap:2.14.0

import org.apache.camel.builder.RouteBuilder;

public class TestWeb extends RouteBuilder {
@OverRide
public void configure() throws Exception {
// Write your routes here, for example:
from("timer:java?period=1000")
.routeId("java")
.setBody()
.simple("Hello Camel K from ${routeId}")
.to("log:info");
}
}

**Error:**

{"level":"error","ts":1672937615.0208771,"logger":"camel-k.maven.build","msg":"[ERROR] Some problems were encountered while processing the POMs:\n[ERROR] 'dependencies.dependency.version' for org.apache.camel:camel-cxf-soap:jar is missing. @ line 56, column 17\n @ ","stacktrace":"github.com/apache/camel-k/pkg/util/log.Logger.Errorf\n\tgithub.com/apache/camel-k/pkg/util/log/log.go:60\ngithub.com/apache/camel-k/pkg/util/maven.normalizeLog\n\tgithub.com/apache/camel-k/pkg/util/maven/maven_log.go:62\ngithub.com/apache/camel-k/pkg/util/maven.(*Command).Do\n\tgithub.com/apache/camel-k/pkg/util/maven/maven_command.go:140\ngithub.com/apache/camel-k/pkg/builder.BuildQuarkusRunnerCommon\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:189\ngithub.com/apache/camel-k/pkg/builder.buildQuarkusRunner\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:163\ngithub.com/apache/camel-k/pkg/builder.(*builderStep).execute\n\tgithub.com/apache/camel-k/pkg/builder/steps.go:46\ngithub.com/apache/camel-k/pkg/builder.(*builderTask).Do\n\tgithub.com/apache/camel-k/pkg/builder/builder.go:125\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorRoutineAction).runBuild\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_routine.go:146"}

{"level":"error","ts":1672937615.024683,"logger":"camel-k.maven.build","msg":"    'dependencies.dependency.version' for org.apache.camel:camel-cxf-soap:jar is missing. @ line 56, column 17","stacktrace":"github.com/apache/camel-k/pkg/util/log.Logger.Errorf\n\tgithub.com/apache/camel-k/pkg/util/log/log.go:60\ngithub.com/apache/camel-k/pkg/util/maven.normalizeLog\n\tgithub.com/apache/camel-k/pkg/util/maven/maven_log.go:62\ngithub.com/apache/camel-k/pkg/util/maven.(*Command).Do\n\tgithub.com/apache/camel-k/pkg/util/maven/maven_command.go:140\ngithub.com/apache/camel-k/pkg/builder.BuildQuarkusRunnerCommon\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:189\ngithub.com/apache/camel-k/pkg/builder.buildQuarkusRunner\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:163\ngithub.com/apache/camel-k/pkg/builder.(*builderStep).execute\n\tgithub.com/apache/camel-k/pkg/builder/steps.go:46\ngithub.com/apache/camel-k/pkg/builder.(*builderTask).Do\n\tgithub.com/apache/camel-k/pkg/builder/builder.go:125\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorRoutineAction).runBuild\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_routine.go:146"}

**Comment by gtata007** [comment]
Hi @squakez ,

This looks like a bug and this feature is not supported in CamelK 1.6.1 version.
please confirm.

Regards,
Guru

**Comment by squakez** [comment]
The way you're declaring the dependency is incorrect. As it's a camel component it must be declared like `camel:cxf-soap`. The operator will care to convert to the proper camel dependency and version. Then, it's true, this Camel Quarkus extension is available since version 2.12, which is used by Camel K 1.8. If you upgrade and use the proper notation, it should work correctly (just tested against Camel K 1.11).

**Comment by gtata007** [comment]
Hi @squakez,

Thank you for your reply on this.

The release notes and instructions are given in the link **https://github.com/apache/camel-k/releases/tag/v1.6.0**
It is mentioned that the camel version it supports is: 
**[Apache Camel 3.11.1]
[Apache Camel Quarkus 2.2.0]**

So, Ideally, it should download the plugin version as mentioned. Also, it worked for us while mentioning the dependency before the import section. This is a kind of Bug I would say.

Regards,
Guru

**Comment by tadayosi** [comment]
@gtata007 We don't think it's a bug.

Firstly, 1.6.x is a bit too old. Please upgrade to Camel K 1.11.0.

Secondly, we don't recommend directly specifying a Camel component in a Maven GAV format, as it may specify a conflicting version with the internal Camel dependency catalog.
```
// camel-k: dependency=mvn:org.apache.camel.quarkus:camel-quarkus-cxf-soap:2.14.0
```
Instead, specify a dep as follows:
```
// camel-k: dependency=camel:cxf-soap
```

**Comment by squakez** [comment]
@gtata007 I've wrongly mentioned this was supported since Camel K version 1.8. It was really supported starting Camel K version 1.10. If you need to use such component, you should upgrade at least that version and use the notation we're suggesting.
