### ISSUE TITLE
Add spring-boot example in the examples directory

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#397]
It would be good if there was a Spring Boot @SpringBootApplication java file which you can quickly demo via the new spring boot support.

**Comment by lburgazzoli** [comment]
Spring boot support is very limited and we do not support adding your own main, what we do is running your route inside a spring boot application so you can leverage all the component auto configuration options that camel provides.

**Comment by lburgazzoli** [comment]
spring-boot support is gogin to be removed #534
