### ISSUE TITLE
camel-k 1.6.1 camel-xmljson dependency is failed to download

### ISSUE THREAD

**Issue by gtata007** [apache/camel-k#3971]
Hello, I'm trying to use xmljson in integration to convert the plain XML data to JSON format. Upon running this on OpenShift Camel-K is failing to download the dependency and error in the operator. Below is the code snippet and the commands I have tried.
Though the xmljson plugin is deprecated we have a requirement to convert the XML payload into JSON.

for your reference, maven dependency before the import statement is working fine on the Camel-K operation 1.6.1. We have some other applications running in a similar way(Able to download the SQL dependencies).

**Camel-k Version is 1.6.1.**

**Code:**
// camel-k: language=java
// camel-k: dependency=mvn:org.apache.camel:camel-xmljson:2.20.4
import org.apache.camel.builder.RouteBuilder;

public class Abc extends RouteBuilder {
  @Override
  public void configure() throws Exception {
      // Write your routes here, for example:
      from("timer:java?period=1000")
        .routeId("java")
        .setBody()
          .simple("Hello Camel K from ${routeId}")
        .to("log:info");
  }
}

Tried to run the integration using the below commands but nothing worked.

**Run Command**
1. kamel run -d camel:camel-xmljson TestWeb.java --dev -t logging.level=DEBUG
2. kamel run TestWeb.java --dev -t logging.level=DEBUG
3. kamel run -d mvn:org.apache.camel:camel-xmljson TestWeb.java --dev -t logging.level=DEBUG

Regards,
Guru

**Comment by tadayosi** [comment]
A few things to point out.

* Camel K 1.6.1 is a bit old. Please use as latest as possible, currently it's 1.11.0.
* Directly specifying a Camel dep with Maven GAV format is not recommended:
    ```
    // camel-k: dependency=mvn:org.apache.camel:camel-xmljson:2.20.4
    ```
    Use `camel:xxx` format instead.
* As you are aware, `camel:xmljson` is not available in Camel 3. Probably you can try the combination of `camel:jackson` and `camel:jacksonxml` to first convert XML to POJO and then to JSON.

**Comment by gtata007** [comment]
Hi @tadayosi, Thank you for your reply and suggestions.

I just wanted to try converting the XML data to JSON directly without any intermediatory POJO class. 
Because my XML file is too vague and sometimes dynamic. So, for this reasons, i would like to try camel:xmljson which converts xml to json directly. 

https://cwiki.apache.org/confluence/display/CAMEL/XmlJson#:~:text=Remember%20that%20this%20data%20format%20is%20available%20from%20Camel%202.10.

To achieve this, I upgraded the camel-K version to **1.12.0** and tried to use **camel:xmljson** plugin at the runtime. However, I am unable to run the sample program and it is throwing an error while finding the file in the repository.

Do you have any recommendations on this? Please throw some light on this to achieve a similar scenario.

Regards,
Guru

**Comment by gansheer** [comment]
Hello,

The Camel-k 1.12.x is dependent on Camel [3.20.x](https://camel.apache.org/components/3.20.x/index.html).

From what I know the recommended way to handle transformation between JSON and XML is the component [XJ](https://camel.apache.org/components/3.20.x/xj-component.html) so you might try this one. It require some XSL configuration but iff you don't want to do some precise xsl template you can use one very generice like this one : [identity.xsl](https://github.com/apache/camel/blob/main/components/camel-xj/src/main/resources/org/apache/camel/component/xj/identity.xsl).

**Comment by gtata007** [comment]
Thank you @gansheer for your inputs.

I am trying to run a sample java dsl program by adding the xj plugin in the command line argument but the pod is running into errors. Do you have any inputs on this? Below is the piece of code and the run command i am trying to execute.

 D:\CamelKWorkspace\Xml2JsonSample> kamel run -d camel:camel-xj TextXmlJson.java --dev -t logging.level=DEBUG

// camel-k: language=java

import org.apache.camel.builder.RouteBuilder;

public class TextXmlJson extends RouteBuilder {
  @Override
  public void configure() throws Exception {

      // Write your routes here, for example:
      from("timer:java?period=1000")
        .routeId("java")
        .setBody()
          .simple("Hello Camel K from ${routeId}")
        .to("log:info");

  }
}

**Comment by claudio4j** [comment]
@gtata007 you can use unmarshall/marshall to transform from xml to json, see an example 

```
from(fromFile)
.split().tokenizeXML("record").streaming()
    .unmarshal().jacksonXml()
    .marshal().json()
    .log("${body}")
.end();
```
