### ISSUE TITLE
Documentation: 3scale title trait invalid when generating documentation

### ISSUE THREAD

**Issue by gansheer** [apache/camel-k#3972]
The document generation make command `make generate` generates the `docs/modules/ROOT/nav.adoc` file with inside : 
```
...
 // Start of autogenerated code - DO NOT EDIT! (trait-nav)
** xref:traits:3scale.adoc[3Scale]
** xref:traits:affinity.adoc[Affinity]
...
```
The bug : 3**S**cale should be 3**s**cale  (small 's'): https://www.3scale.net/

The generation command use for the title:
* the following flag in trait comments:
https://github.com/apache/camel-k/blob/4024c6a037f04308c274c816b8be26f6ae916783/addons/threescale/3scale.go#L36
* the generation following code:
https://github.com/apache/camel-k/blob/4024c6a037f04308c274c816b8be26f6ae916783/cmd/util/doc-gen/generators/traitdocgen.go#L147-L154

Adding a way to override the default generation code for a specified code would fix the bug and help give mode flexibility.

Ref :  https://github.com/apache/camel-k/pull/3970#discussion_r1066596554

**Comment by squakez** [comment]
The trait is deprecated.
