### ISSUE TITLE
Set a more reasonable default for gomega eventually's polling interval

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#3992]
I noticed that in the e2e tests we don't set any value for the eventually's polling interval so by default is likely to be 10ms.
Given we have tests for which the timeout is  set to minutes it could make sense to set a more reasonable poll interval.

The default can be programmatic defined by using `SetDefaultEventuallyPollingInterval` :

```go
// SetDefaultEventuallyTimeout sets the default timeout duration for Eventually. Eventually will repeatedly poll your condition until it succeeds, or until this timeout elapses.
func SetDefaultEventuallyTimeout(t time.Duration) {
    Default.SetDefaultEventuallyTimeout(t)
}

// SetDefaultEventuallyPollingInterval sets the default polling interval for Eventually.
func SetDefaultEventuallyPollingInterval(t time.Duration) {
    Default.SetDefaultEventuallyPollingInterval(t)
}
```

or by setting some env vars:

```go
const (
    EventuallyTimeoutEnvVarName         = "GOMEGA_DEFAULT_EVENTUALLY_TIMEOUT"
    EventuallyPollingIntervalEnvVarName = "GOMEGA_DEFAULT_EVENTUALLY_POLLING_INTERVAL"

    ConsistentlyDurationEnvVarName        = "GOMEGA_DEFAULT_CONSISTENTLY_DURATION"
    ConsistentlyPollingIntervalEnvVarName = "GOMEGA_DEFAULT_CONSISTENTLY_POLLING_INTERVAL"
)

func FetchDefaultDurationBundle() DurationBundle {
    return DurationBundle{
        EventuallyTimeout:         durationFromEnv(EventuallyTimeoutEnvVarName, time.Second),
        EventuallyPollingInterval: durationFromEnv(EventuallyPollingIntervalEnvVarName, 10*time.Millisecond),

        ConsistentlyDuration:        durationFromEnv(ConsistentlyDurationEnvVarName, 100*time.Millisecond),
        ConsistentlyPollingInterval: durationFromEnv(ConsistentlyPollingIntervalEnvVarName, 10*time.Millisecond),
    }
}
```

**Comment by lburgazzoli** [comment]
What would be the preferred approach ? using env vars or adding something in the e2e support init methods ?

**Comment by squakez** [comment]
I don't have any preference. Maybe, using env vars makes it a bit more flexible as we can adjust the value depending on the test suite we run.

**Comment by tadayosi** [comment]
I personally think the default 10ms doesn't make much sense for Camel K E2E in any way, it's too frequent to hit K8s API. Probably a sensible default would be 1s or so. What about hardcoding the default interval to 1s (or other appropriate value) but also enabling us to adjust it via the env var?
