### ISSUE TITLE
Create a test for structured health check conditions when integrations are scaled > 1

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#3997]
Original discussion: https://github.com/apache/camel-k/pull/3977#issuecomment-1398432246

**Comment by lburgazzoli** [comment]
@rinaldodev

**Comment by squakez** [comment]
Great, thanks! @rinaldodev please, just comment so we can assign this issue to you.

**Comment by rinaldodev** [comment]
Please assign this one to me :)

**Comment by rinaldodev** [comment]
This can be closed now.
