### ISSUE TITLE
operator refers to a openjdk image tag not found in docker.io

### ISSUE THREAD

**Issue by rafaeltuelho** [apache/camel-k#3998]
Kamel `1.10.3` on Minikube `1.28.0`

I noticed that the Operator is trying to pull an base image using a tag not found in docker.io: `docker.io/adoptopenjdk/openjdk11:slim`

```json
{"level":"error","ts":1674317197.9308116,"logger":"camel-k.controller.build","msg":"Build kit-cf60qj6o1dcuah58crn0 failed: could not pull base image image docker.io/adoptopenjdk/openjdk11:slim: no child with platform {Architecture:amd64 OS:linux OSVersion: OSFeatures:[] Variant: Features:[]} in index docker.io/adoptopenjdk/openjdk11:slim","request-namespace":"knativetutorial","request-name":"kit-cf60qj6o1dcuah58crn0","api-version":"camel.apache.org/v1","kind":"Build","ns":"knativetutorial","name":"kit-cf60qj6o1dcuah58crn0","stacktrace":"github.com/apache/camel-k/pkg/controller/build.(*monitorRoutineAction).updateBuildStatus\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_routine.go:197\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorRoutineAction).runBuild\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_routine.go:181"}

```

**Comment by squakez** [comment]
Thanks for reporting. We have noticed this lately as well. It looks a problem after some rebuild of Openjdk. We're trying to figure it out what exactly it is and how to fix.

**Comment by gansheer** [comment]
An issue was open on the project in charge : AdoptOpenJDK/openjdk-docker#627.

**Comment by squakez** [comment]
Thanks @gansheer, we'll keep an eye on that.

In the while, as a **workaround** I suggest to switch the base image to some other JDK based image. Ie, you can use the `latest` instead of the `slim`. If you install from scratch:

`kamel install --operator-env-vars KAMEL_BASE_IMAGE=docker.io/adoptopenjdk/openjdk11:latest`

If you have a running operator, add the `KAMEL_BASE_IMAGE` env variable to your Camel K operator deployment.

**Comment by jerboaa** [comment]
`docker.io/adoptopenjdk/openjdk11:latest` are deprecated and actually contain Eclipse Temurin binaries. Please migrate to official temurin images here: https://hub.docker.com/_/eclipse-temurin when you get a chance. Thanks.

**Comment by squakez** [comment]
> `docker.io/adoptopenjdk/openjdk11:latest` are deprecated and actually contain Eclipse Temurin binaries. Please migrate to official temurin images here: https://hub.docker.com/_/eclipse-temurin when you get a chance. Thanks.

Yes, I'm already working on a refactoring where including Temurin distro, it should come within future releases.

**Comment by jerboaa** [comment]
> > `docker.io/adoptopenjdk/openjdk11:latest` are deprecated and actually contain Eclipse Temurin binaries. Please migrate to official temurin images here: https://hub.docker.com/_/eclipse-temurin when you get a chance. Thanks.
> 
> Yes, I'm already working on a refactoring where including Temurin distro, it should come within future releases.

Great, thanks!

**Comment by rafaeltuelho** [comment]
@squakez thanks for the workaround. I searched for a way to change the builder base image in the docs but could not find it. It would be great to have these `env vars` well documented in the docs.

**Comment by squakez** [comment]
Fixed in the original image.
