### ISSUE TITLE
Support set integration name for kamel run

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#40]
the `kamel run` command determine the integration name using the integration file name but it would be nice to let the user set the name of the integration with an additional flag.

**Comment by lburgazzoli** [comment]
@oscerd do you mind having a look ?

**Comment by nicolaferraro** [comment]
I'll add also that the current mapping is trivial, e.g. `MyIntegration.java` -> `myintegration`.

A better name would be `my-integration`. 

We should also make sure to respect Kubernetes conventions.

**Comment by lburgazzoli** [comment]
Thre is also a problem when the file is located on a different directory than the current one i,e `runtime/examples/Sample.java` becomes `runtimeexamplessample`

**Comment by oscerd** [comment]
Sure
