### ISSUE TITLE
Some API warnings reported while contributing operator 1.11.1

### ISSUE THREAD

**Issue by oscerd** [apache/camel-k#4016]
https://github.com/k8s-operatorhub/community-operators/pull/2212#issuecomment-1408231171

I think it could be useful to keep track of them

**Comment by claudio4j** [comment]
This can be closed as the apis for `poddisruptionbudgets`, `cronjobs`, `events` apis were migrated.
There were no [operator-sdk bundle validator issues for Camel K 1.12.0](https://github.com/k8s-operatorhub/community-operators/pull/2387)
