### ISSUE TITLE
Compatibility matrix show wrong kamelets version for camel-k releases 1.10.x and 1.11.x

### ISSUE THREAD

**Issue by gansheer** [apache/camel-k#4023]
The current [compatibility matrix](https://camel.apache.org/camel-k/1.11.x/#_compatibility_matrix) indicates "latest" as kamelets version for  camel-k 1.10.x and camel-k.1.11.x where it should be 0.9.4 (for camel-k 1.10.4) and 0.10.0 (for camel-k 1.11.1). The current version for camel-k works well.

Are there some backports missing on 1.10.x and 1.11.x ?

**Comment by squakez** [comment]
Yes, it was something I've fixed yesterday and should be fixed as soon as the Camel website is rebuilt: https://github.com/apache/camel-k/commit/b84f7059f76479ca77c456ca0458978ec1a72fb5 and https://github.com/apache/camel-k/commit/5bc40385696d89303a5d982052235b309119791a

Let's have a look later in the day but it should be solved accordingly.

**Comment by gansheer** [comment]
That's efficient :astonished: ! (or I should probably have checked the PR :flushed:).
Thank you!
