### ISSUE TITLE
YAKS test failure

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#4044]
It is happening on the `main` branch since a few days:
```
	Kamelet event data type conversion (kamelet-data-types.feature:8): Failure caused by com.consol.citrus.exceptions.TestCaseFailedException - Action timeout after 800000 milliseconds.
``

**Comment by squakez** [comment]
@christophd mind having a look?

**Comment by christophd** [comment]
@squakez yes, having a look

**Comment by oscerd** [comment]
Camel-Kamelets moved main to Camel 4, now the branch to target is 3.x just for information

**Comment by christophd** [comment]
@oscerd yes, thanks that's it
