### ISSUE TITLE
Helm Node Selector

### ISSUE THREAD

**Issue by tvblomberg** [apache/camel-k#4096]
Would it be possible to expose node selector in the helm chart for camel-k?

**Comment by oscerd** [comment]
It's possible to do it, are you working on that or do you expect it to be contributed by someone else? Thanks

**Comment by oscerd** [comment]
Ok. We could add some stuff and do a 1.12.1 release in the coming weeks.

**Comment by tvblomberg** [comment]
Just an update. I did make the code change in my fork yesterday and confirmed it's working. I still need to create a PR. I want to make sure I am following the dev PR rules. I'll try to finish that tonight.
