### ISSUE TITLE
Upgrade Operator Framework SDK version

### ISSUE THREAD

**Issue by gansheer** [apache/camel-k#4105]
The last released version of the operator framework SDK  is v1.26.1 : https://github.com/operator-framework/operator-sdk/releases/tag/v1.26.1.

The one we are using in the make scripts is :
https://github.com/apache/camel-k/blob/8056c0096dad112e95b7282f580c5a0a6801a1ed/script/Makefile#L31

Even if the script does not download this version if a newer one is already installed on the environment, we should probably upgrade considering the v1.16 was released in january 2022 https://github.com/operator-framework/operator-sdk/releases/tag/v1.16.0.

Is there a reason not to upgrade it ? What would be the impact of such an upgrade ?

**Comment by squakez** [comment]
We can give it a try, not aware of any reason not to bump.
