### ISSUE TITLE
Transition issue when native image takes over the non-native image

### ISSUE THREAD

**Issue by mertdotcc** [apache/camel-k#4125]
Hey everyone,

I have a quite simple integration and I am using the following command to run my integration:
```
kamel run \
--config configmap:some-config-file/some-config-parameter \
--config secret:some-secret-file/some-secret-parameter \
--open-api file:./resources/my-app.yaml \
--resource file:./resources/sample-error-response.json \
--resource file:./resources/mapping-template-file.json \
--trait container.enabled=true \
--trait container.request-cpu="250m" \
--trait container.request-memory="256Mi" \
--trait container.limit-cpu="500m" \
--trait container.limit-memory="512Mi" \
--trait container.port=8443 \
--trait health.enabled=true \
--trait health.liveness-probe-enabled=true \
--trait health.liveness-scheme="HTTP" \
--trait health.liveness-initial-delay=0 \
--trait health.liveness-timeout=10 \
--trait health.liveness-period=15 \
--trait health.liveness-success-threshold=1 \
--trait health.liveness-failure-threshold=3 \
--trait health.readiness-probe-enabled=true \
--trait health.readiness-scheme="HTTP" \
--trait health.readiness-initial-delay=0 \
--trait health.readiness-timeout=10 \
--trait health.readiness-period=15 \
--trait health.readiness-success-threshold=1 \
--trait health.readiness-failure-threshold=3 \
--trait knative-service.enabled=true \
--trait knative-service.autoscaling-class="kpa.autoscaling.knative.dev" \
--trait knative-service.autoscaling-metric="rps" \
--trait knative-service.autoscaling-target=100 \
--trait knative-service.min-scale=0 \
--trait knative-service.max-scale=20 \
--trait quarkus.enabled=true \
--trait quarkus.package-type=fast-jar \
--trait quarkus.package-type=native \
MyIntegration.java
```

What happens is:
1) Non-native image is built and the pod starts with no problems
2) I send requests to the pod ensuring that it works as intended
3) In the meantime, the native image is build built. The process takes around ~10 minutes. Once the native image is built, a new deployment starts using the native image, named xxx-deployment-3.
4) I send a request to my now-native application, ensuring that it works as intended.

BUT, I also get an intermediary deployment, named xxx-deployment-2, for some reason that I don't quite understand. The first version of the pod -the one using the non-native build- was named xxx-deployment-1. It worked. My native built is NOT named xxx-deployment-2 but it is named xxx-deployment-3. What's also weird is that this xxx-deployment-2 is stuck in `ContainerFailed` state. When I describe that pod, this is the error I see in the events section: `Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown`

What's happening here? Why do I get 3 deployments but not 2, as expected?

What I have to do to get rid of that failed pod, as I can't simply just delete it as it is backed by a deployment, is I delete that integration and then run my `kamel run` command again. As the native image is already built and present, my operator uses that image to deploy my integration, under only one deployment this time, as expected: xxx-deployment-1, and when I describe it, I can verify that it is indeed using the native image.

I am very confused by this intermediary deployment. What is it? I can provide more details and error logs if needed.

Thanks in advance!

**Comment by squakez** [comment]
Thanks for reporting. I wonder if it's a transient failure of really is a bug we should fix. The error you've reported makes me think it could have been some temporary problem in the native build. Would you mind retrying it with a clean state? if you confirm it's still there I'd label this as a bug for future development.

**Comment by mertdotcc** [comment]
Hey @squakez, thank you for the response! I am on PTO atm, I will provide more details on Monday, the 20th of March.

**Comment by claudio4j** [comment]
@mertdotcc what kubernetes platform you are using ?
Which Camel K version ?
Why would you have fast-jar and native ? Perhaps, only one of them is enough.
I couldn't reproduce it with Camel K 1.12.1. and this simple rest integration:
```
from("rest:get:hello")
    .transform().simple("Hello from http");
```
