### ISSUE TITLE
Bring an option to force an image build to the kamel run command

### ISSUE THREAD

**Issue by mertdotcc** [apache/camel-k#4126]
Hey everyone,

I have two very similar integrations:

IntegrationOne.java:
```
package com.myCompany.integrations;
// camel-k: language=java
// camel-k: name=integration-one

import org.apache.camel.LoggingLevel;
import org.apache.camel.builder.RouteBuilder;

public class IntegrationOne extends RouteBuilder {

    @Override
    public void configure() throws Exception {

        onException(Exception.class)
                .handled(true)
                .setHeader("CamelHttpResponseCode").constant("400")
                .setBody().simple("resource:file:/etc/camel/resources/sample-error-response.json")
                .log(LoggingLevel.ERROR, "exception", "${exception}").routeId("exception");

        from("direct://integrationOne").routeId("integrationOne")
                .log(LoggingLevel.INFO, "log-1", "headers: ${headers}; body: ${body}")
                .setBody().constant("resource:file:/etc/camel/resources/integration_one.json");
    }
}
```

I use the following command to run `IntegrationOne`:
```
kamel run \
--resource file:./resources/sample-error-response.json \
--resource file:./mappingresources/integration_one.json \
--trait container.enabled=true \
--trait container.request-cpu="250m" \
--trait container.request-memory="256Mi" \
--trait container.limit-cpu="500m" \
--trait container.limit-memory="512Mi" \
--trait container.port=8443 \
--trait health.enabled=true \
--trait health.liveness-probe-enabled=true \
--trait health.liveness-scheme="HTTP" \
--trait health.liveness-initial-delay=0 \
--trait health.liveness-timeout=10 \
--trait health.liveness-period=15 \
--trait health.liveness-success-threshold=1 \
--trait health.liveness-failure-threshold=3 \
--trait health.readiness-probe-enabled=true \
--trait health.readiness-scheme="HTTP" \
--trait health.readiness-initial-delay=0 \
--trait health.readiness-timeout=10 \
--trait health.readiness-period=15 \
--trait health.readiness-success-threshold=1 \
--trait health.readiness-failure-threshold=3 \
--trait knative-service.enabled=true \
--trait knative-service.autoscaling-class="kpa.autoscaling.knative.dev" \
--trait knative-service.autoscaling-metric="rps" \
--trait knative-service.autoscaling-target=100 \
--trait knative-service.min-scale=0 \
--trait knative-service.max-scale=20 \
--trait quarkus.enabled=true \
--trait quarkus.package-type=fast-jar \
--trait quarkus.package-type=native \
IntegrationOne.java
```

I have a second integration, that is very similar to my first integration. Almost identical. Except the last line of code in the DSL. Notice that they are using a different JSON file there as a body.

IntegrationTwo.java:
```
package com.myCompany.integrations;
// camel-k: language=java
// camel-k: name=integration-two

import org.apache.camel.LoggingLevel;
import org.apache.camel.builder.RouteBuilder;

public class IntegrationTwo extends RouteBuilder {

    @Override
    public void configure() throws Exception {

        onException(Exception.class)
                .handled(true)
                .setHeader("CamelHttpResponseCode").constant("400")
                .setBody().simple("resource:file:/etc/camel/resources/sample-error-response.json")
                .log(LoggingLevel.ERROR, "exception", "${exception}").routeId("exception");

        from("direct://integrationTwo").routeId("integrationTwo")
                .log(LoggingLevel.INFO, "log-1", "headers: ${headers}; body: ${body}")
                .setBody().constant("resource:file:/etc/camel/resources/integration_two.json");
    }
}
```

I use the following command to run `IntegrationTwo`:
```
kamel run \
--resource file:./resources/sample-error-response.json \
--resource file:./mappingresources/integration_two.json \
--trait container.enabled=true \
--trait container.request-cpu="250m" \
--trait container.request-memory="256Mi" \
--trait container.limit-cpu="500m" \
--trait container.limit-memory="512Mi" \
--trait container.port=8443 \
--trait health.enabled=true \
--trait health.liveness-probe-enabled=true \
--trait health.liveness-scheme="HTTP" \
--trait health.liveness-initial-delay=0 \
--trait health.liveness-timeout=10 \
--trait health.liveness-period=15 \
--trait health.liveness-success-threshold=1 \
--trait health.liveness-failure-threshold=3 \
--trait health.readiness-probe-enabled=true \
--trait health.readiness-scheme="HTTP" \
--trait health.readiness-initial-delay=0 \
--trait health.readiness-timeout=10 \
--trait health.readiness-period=15 \
--trait health.readiness-success-threshold=1 \
--trait health.readiness-failure-threshold=3 \
--trait knative-service.enabled=true \
--trait knative-service.autoscaling-class="kpa.autoscaling.knative.dev" \
--trait knative-service.autoscaling-metric="rps" \
--trait knative-service.autoscaling-target=100 \
--trait knative-service.min-scale=0 \
--trait knative-service.max-scale=20 \
--trait quarkus.enabled=true \
--trait quarkus.package-type=fast-jar \
--trait quarkus.package-type=native \
IntegrationTwo.java
```

The problem is that these two integrations want to use the same image and I can't seem to control this process and force a new image build for the second integration.

To be more specific: I first deploy my `IntegrationOne`, the image is built with no problem, and my pod is running as expected. Then when I run my `kamel run` command for my `IntegrationTwo` and I inspect my `Integrations` and `IntegrationKits` using `k9s`, I notice that the `Phase` of my `IntegrationTwo` switches from `Initializing` to `Running` automatically. It doesn't enter the `Build Running` phase. When I inspect, I realized that the `IntegrationTwo` is using the same `camel-k-kit` as my `IntegrationOne`.

Well, this is obviously an issue as the `camel-k-kit` that was built for my `IntegrationOne` doesn't contain the `resource` `integration_two.json` and thus I get the following error in my `IntegrationTwo` pod: 
```
2023-03-12 22:36:53,063 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]):
 java.io.FileNotFoundException: /etc/camel/resources/integration_two.json does not exists                                                                                                                                                    
 org.apache.camel.impl.engine.DefaultResourceResolvers$FileResolver$1.getInputStream(DefaultResourceResolvers.java:77)                                                
 org.apache.camel.support.ResourceHelper.resolveResourceAsInputStream(ResourceHelper.java:134)                                                                        
 org.apache.camel.support.ResourceHelper.resolveMandatoryResourceAsInputStream(ResourceHelper.java:112)                                                               
 org.apache.camel.support.ScriptHelper.resolveOptionalExternalScript(ScriptHelper.java:96)                                                                            
 org.apache.camel.support.ScriptHelper.resolveOptionalExternalScript(ScriptHelper.java:46)                                                                            
 org.apache.camel.reifier.language.ExpressionReifier.createExpression(ExpressionReifier.java:174)                                                                     
 org.apache.camel.reifier.AbstractReifier.createExpression(AbstractReifier.java:119)                                                                                  
 org.apache.camel.reifier.SetBodyReifier.createProcessor(SetBodyReifier.java:34)                                                                                      
 org.apache.camel.reifier.ProcessorReifier.makeProcessor(ProcessorReifier.java:857)                                                                                   
 org.apache.camel.reifier.ProcessorReifier.addRoutes(ProcessorReifier.java:598)                                                                                       
 org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:211)                                                                                           
 org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:75)                                                                                              
 org.apache.camel.impl.DefaultModelReifierFactory.createRoute(DefaultModelReifierFactory.java:49)                                                                     
 org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:937)                                                                        
 org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:800)                                                                        
 org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:3008)                                                                             
 org.apache.camel.quarkus.core.FastCamelContext.doInit(FastCamelContext.java:174)                                                                                     
 org.apache.camel.support.service.BaseService.init(BaseService.java:83)                                                                                               
 org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2679)                                                                               
 org.apache.camel.support.service.BaseService.start(BaseService.java:111)                                                                                             
 org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2698)                                                                              
 org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:262)                                                                                        
 org.apache.camel.quarkus.main.CamelMain.doStart(CamelMain.java:94)                                                                                                   
 org.apache.camel.support.service.BaseService.start(BaseService.java:119)                                                                                             
 org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:140)                                                                                              
 org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)                                                                                       
 org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)                                                                           
 io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy_0(Unknown Source)                                                                           
 io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy(Unknown Source)                                                                             
 io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)                                                                                                            
 io.quarkus.runtime.Application.start(Application.java:101)                                                                                                           
 io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)                                                                             
 io.quarkus.runtime.Quarkus.run(Quarkus.java:71)                                                                                                                      
 io.quarkus.runtime.Quarkus.run(Quarkus.java:44)                                                                                                                      
 io.quarkus.runtime.Quarkus.run(Quarkus.java:124)                                                                                                                     
 io.quarkus.runner.GeneratedMain.main(Unknown Source)                                                                                                                 
```

This whole problem is caused by Camel-K being super efficient and resourceful when it comes to building new images as it tries to re-use them as much as possible. 🙂 But for situations like these, can't we have a new flag in our `kamel run` command, something like `--forceImageBuild` and have it bypass all of Camel-K's efficient image re-use logic and force build a new image?

I am open to any questions/suggestions and I can provide more details/error logs if needed.

Many thanks in advance!

**Comment by squakez** [comment]
Hello. Indeed, the way Camel K is designed is to avoid rebuilding stuff when they are not needed. The reason is the fact we want to have a cloud native experience, so, a fast deploy is a must. The behavior you've described is correct, because the resource you're providing is a runtime resource, so, a rebuild is not needed. This should also be the case in Quarkus native mode. I guess there may be some bug here that requires some attention.

You can force the rebuild of your application by applying a simple workaround. Use a build time properties that everytime is different. I have one handy for this case `kamel run --build-property=quarkus.application.name=integrationTwo`.

However, in this case you can have a better design I think, making your route to depend on a generic file [1]:
```
.setBody().constant("resource:file:/tmp/integration.json");
```
then, you can use the destination path for the resource such as `--resource file:resources_one.json@/tmp/integration.json`

[1] https://camel.apache.org/camel-k/next/configuration/runtime-resources.html#runtime-resource-path

**Comment by mertdotcc** [comment]
Thanks for digging into the issue @squakez!

> Use a build time properties that everytime is different. I have one handy for this case `kamel run --build-property=quarkus.application.name=integrationTwo`.

We want to avoid this as much as possible since we want to stick to our strict naming conventions and not keen on the manual work of using a different build-time property for each run.

> Designing the route not to depend on a specific resource path could be a solution for now.

I agree, this is something that I will try. I'll also explore the generic file approach you mentioned [here](https://github.com/apache/camel-k/issues/4126#issuecomment-1465738335).

For the time being, would something like this be possible: I deploy my `IntegrationOne`, the operator builds the native image, `IntegrationOne` gets deployed using the image, all fine. Then I deploy my `IntegrationTwo`, it uses the native image built for `IntegrationOne` since they share a lot of logic, but detects that my `IntegrationTwo` uses a resource file that is not present in the image built for `IntegrationOne`, and then builds a new image that contains the first image, and just adds the missing resource file on top as a new layer? So that we could avoid another costly and timely native image build process, and stick to Camel-K's efficient image re-use and layering logic?

**Comment by mertdotcc** [comment]
Alright, I will try the generic file approach and share my findings.

> we should trigger by default a new build when we are in native mode

@squakez so what is the officially recommended approach when it comes to using native images for a wide set of integrations in production? 

The first time I tried running my integrations in native mode, I gave my operator the recommended minimum memory of `4Gi` and the whole build process took way too long for the type of operations I am running.

Then I bumped up the requested memory to `8Gi` and gave an upper memory limit of `12Gi`. Keep in mind that I didn't limit `CPU` at all.

During the build process, my operator uses all of the memory I basically allocate for it, in this case, all of the `12Gi`, and then takes around 10 minutes to build an image. Imagining a likely scenario of a decent-size team working on integrations and regularly committing their work, it is safe to assume that the operator will be constantly building images 24/7. 

Do you guys suggest that we only use the non-native build for `development`, `test`, `staging`, etc; and only enable the native build for the `production` environment? This would obviously take a big load off of our operator (and this is something we really need to keep an eye on since Camel-K doesn't support multi-operator high-availability atm) but then I would argue that maintaining and debugging things might get problematic as there _might_ be some different behaviors when we run an integration in native and non-native (see my other open issues), i.e., things working in non-native not properly working in native, etc.

Open to suggestions. Thanks in advance!

**Comment by squakez** [comment]
I've tested a similar scenario with 1.11 (on yaml as Java was not supported) and it seems that it was working as expected. I think that the introduction of the source during the build has this kind of side effect. @essobedo do you think it is strictly required to rebuild the native integration when we have the very same set of dependencies or can we still reuse the same approach as we had in 1.11 version?

**Comment by essobedo** [comment]
As soon as the Java code changes, you need to rebuild it since it is included in the native image that is why using the generic file approach to keep the exact same code, is the way to go.

**Comment by squakez** [comment]
> Yeah I know, with routes written in Yaml, the code is not part of the native image, it is actually interpreted at runtime that is why it works whereas, with routes written in Java, Groovy, and Kotlin, the code is compiled and included in the native image at build time.

Okey, so, would it make sense that we force rebuild when we include source, whilst we don't and we let the operator decide when there is no source? I recall we had that option in the catalog, right?

**Comment by mertdotcc** [comment]
> would it make sense that we force rebuild when we include source, whilst we don't and we let the operator decide when there is no source?

I think it does and it would help me a lot in my use case.

**Comment by essobedo** [comment]
> Okey, so, would it make sense that we force rebuild when we include source, whilst we don't and we let the operator decide when there is no source? I recall we had that option in the catalog, right?

Just to be clear what do you mean by "source" in this case?

**Comment by essobedo** [comment]
TBH, I don't know yet the logic in Camel-K allowing to decide when to build and when to reuse an existing image. In case, the sources are required at build time, we generate the hash of input the source code to know when to build or not, otherwise even with the generic file approach a build will be needed at each call while the code is the same.
