### ISSUE TITLE
Add message during Operator Installation that checks that Internal Image Registry is configured

### ISSUE THREAD

**Issue by timothydilbert** [apache/camel-k#4130]
When deploying the Camel K Operator, there should be a message on the KameletBinding tab that displays an error message (or disables the button) if the OpenShift Internal Registry has not been configured.

**Reason:**
Without this business logic, we get a misleading error message in OpenShift when trying to deploy a KameletBinding:
```
Integration "name" does not have a readiness condition.
```

**Steps to reproduce:**

1. Configure a net-new OpenShift cluster and do not configure the internal image registry.
2. Try to deploy a new KameletBinding.
3. Receive the above-mentioned "readiness condition" error.

**Comment by christophd** [comment]
I think this is not specific to KameletBinding. Camel K in general will not work without the image registry will it? What would be the use case to not use the registry?

**Comment by timothydilbert** [comment]
No use case justifying not having an image registry configured in OCP. 

In my opinion, the error message is misleading and doesn't point to the direct issue, which is that the internal registry was not configured, and that is a requirement in order to deploy a KameletBinding. 

I'm raising this issue because newcomers (who might have deployed OCP just to test Camel-K) might miss the step to configure the internal registry, thus running into this exact error message. 

When installing the Camel-K Operator (or while deploying the KameletBinding) there should be some business logic that checks the status of the internal registry. If not configured, you should not be able to deploy KameletBindings. This business logic will prevent further Red Hat tickets/Github Issues when future developers interested in Camel-K run into the same problem, and are configured and misled by an error unrelated to Camel-K but instead related to unfinished OCP deployment, exactly like I did.

**Comment by christophd** [comment]
I would say this should be a check added to installation of Camel K rather then performing the internal registry check on each deployment. 

Also I am not sure if checking the internal registry is an easy task for the Camel K operator. There might be (admin?) permissions required to actually do the check on the internal registry. I would avoid adding new permissions on the operator just for this quite specific error situation.

We could enhance the documentation clearly saying that Camel K requires the registry so users do have an idea upfront. WDYT?

**Comment by timothydilbert** [comment]
As I'm not experienced enough yet, I'm not able to comment on the difficulty/permissions required to check the internal registry. Hopefully, that changes shortly as I become more familiar with the project.

If permissions/difficulty checking the internal registry is an issue. Perhaps including logic that would attempt a KameletBinding immediately after the Camel K Operator installation could be an acceptable workaround? Basically, there would be logic in the Camel-K Operator installation that would immediately try to deploy a generic (and temporary) KameletBinding. If the KameletBinding deployment fails with the same message, then you know it is because of an incomplete/unconfigured internal registry. Just offering a scotch tape solution as a last resort.

Enhancing the documentation to spell that out would be good.
