### ISSUE TITLE
how to add custom component in camel-k

### ISSUE THREAD

**Issue by wuyexixi** [apache/camel-k#4145]
# camel-n: resource=file:DemoComponent/target/DemoComponent-1.0-SNAPSHOT.jar

- from:
    uri: "timer:tick"
    parameters:
      period: "1000"
    steps:
      - set-body:
          constant: "Hello Yaml ppp !!!"
      # - transform:
      #     simple: "${body.toUpperCase()}"
      - to: "demo:www"
      - to: "log:test?level=WARN"

when running "kamel run", it states demo component is not found.

**Comment by oscerd** [comment]
Custom component are not supported at this stage.

**Comment by wuyexixi** [comment]
oh. sorry to hear about that.
