### ISSUE TITLE
Unused parameter

### ISSUE THREAD

**Issue by realMartinez** [apache/camel-k#4152]
In https://github.com/apache/camel-k/blob/main/pkg/util/docker/docker_base.go 
function `RunImageArgs(imagePath string, imageTag string)` parameter `imageTag` is never used resulting in always getting `imageName:latest` as the return value.

**Comment by tsukasaI** [comment]
Hi.
Can I take this?

**Comment by tsukasaI** [comment]
I have opened PR https://github.com/apache/camel-k/pull/4155 .
Please check this.
Thank you!
