### ISSUE TITLE
Observability documentation - Update to micrometer extension

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#4157]
The links here has been removed as this breaks website build
https://github.com/apache/camel-k/commit/43fc8bc66d6168e253b47da1515cf8cb324f7261

In Quarkus 3 / Camel 4, then microprofile-metrics has been removed, and micrometer extension is its replacement.
So it may be worthwhile to update the camel-k observation page to refer to micrometer instead.

**Comment by gansheer** [comment]
We might have more to do in the camel-k project than documentation : #1773 .

**Comment by gansheer** [comment]
This has been solved with these:

- https://github.com/apache/camel-k/pull/4211
- https://github.com/apache/camel-k/pull/4273
