### ISSUE TITLE
Better naming for Integration phase when fast-jar is enabled

### ISSUE THREAD

**Issue by mertdotcc** [apache/camel-k#4171]
This is not an issue/bug per se, but me sharing my observations and opening up a discussion.

Right now when we enable `fast-jar`, we don't give any indication regarding there being 2 images (one native and one non-native) being built. Or when the non-native image is built first and the pod gets deployed but the native image keeps getting built, no indication of that. And finally, when the native image is ready, the promotion from non-native to native happens but we still give no indication of that. (I am referring to `Integration` and `IntegrationKit` phases and not the operator logs.)

Can we bring in 2-3 more integration phases to make these events more verbose and give a better developer experience? [Here](https://github.com/apache/camel-k/blob/6f0037aef8a87d56509f2168cb510cd08d564d46/pkg/apis/camel/v1/integration_types.go#L149) we could add new integration phases such as `BuildingNativeAndNonNative`, `NonNativeIsRunningNativeBuildInProgress`, and `PromotingToNativeImage` - excuse my dreadfully long and uncreative phase suggestions. 🥲

Having such verbose events could technically help with all sorts of metrics and monitoring operations and the end-users wouldn't have to go through the operator logs.

Related to [#4172](https://github.com/apache/camel-k/issues/4172).

**Comment by squakez** [comment]
For the Integration CR this could make sense. More than a Phase, maybe we could think of an additional condition that will help understanding that a pending Native build is ongoing. However it can be technically complex as we need to cascade this change along Build, IntegrationKit and Integration reconcilation cycles.

**Comment by christophd** [comment]
I am a bit puzzled. `fast-jar` package type should be the default. The user would need to define both `fast-jar` and `native` package type in order to have the scenario that you describe (arbitrary image is built first and while this is already running the native image get build) am I right?

Besides that +1 on the additional phases. We would need to brainstorm a bit on the naming and what phases to expose.

**Comment by squakez** [comment]
Let's also keep in mind that this would be specific of Camel Quarkus runtime. As we're talking to onboard any Camel runtime, the phases should be agnostic of the runtime details (native would be exclusive of the Camel Quarkus runtime). This is vaguely related to #4166 as we're planning to make trait also not dependent of runtime details.

**Comment by mertdotcc** [comment]
> For the Integration CR this could make sense. More than a Phase, maybe we could think of an additional condition that will help understanding that a pending Native build is ongoing. However it can be technically complex as we need to cascade this change along Build, IntegrationKit and Integration reconcilation cycles.

@squakez I don't think we need to unnecessarily overcomplicate things. I personally don't think that there is any need for an additional condition. Please correct me if I'm wrong or missing a point. The initial idea I had was, having 2-3 extra `Phase` conditions would be enough. (Enough for this multi-image configuration.)
