### ISSUE TITLE
Better naming of IntegrationKits to indicate whether the kit is native or non-native

### ISSUE THREAD

**Issue by mertdotcc** [apache/camel-k#4172]
Basically what the title says.

**Description:**
Right now when we do `kubectl get integrations`, the output looks something like this:
```
NAME           PHASE     KIT                        REPLICAS
integration1   Running   kit-cge7k7cvri59ugp5v3e0   1
integration2   Error     kit-cge4mdsvri59ugp5v2hg   0
integration3   Running   kit-cgfd73kvri59ugp5v3t0   0
```

**Proposal:**
(I am all for having the ability to name our integration kits whatever we want and not use the same `camel-k-kit` prefix for all of them. Maybe group them by integration names? But this deserves its own issue (I think it already has one open) so I will just stick to native vs non-native difference in this issue.)

Having a more verbose approach where a user could just look at the auto-generated integration kit name and understand whether the image is native or not, would come in super handy especially when the `fast-jar` is enabled.

Something like this:
```
NAME           PHASE     KIT                               REPLICAS
integration1   Running   native-kit-cge7k7cvri59ugp5v3e0   1
integration2   Error     jvm-kit-cge4mdsvri59ugp5v2hg      0
integration3   Running   native-kit-cgfd73kvri59ugp5v3t0   0
```

Related to [#4171](https://github.com/apache/camel-k/issues/4171).

**Comment by mertdotcc** [comment]
I like this approach. I think it would come in super handy!

Do you see a future where having integrationkit names like `database-sync-integration-kit-cge7k7cvri59ugp5v3e0`, `salesforce-integration-kit-cge4mdsvri59ugp5v2hg` is possible? Maybe a trait or a modeline configuration where we can configure a custom name prefix for these kits? It would be super helpful especially when its the time to do registry clean-up and get rid of bunch of unused kits/images. (Since Camel-K doesn't have a GC mechanism for unused kits _yet_.)

`kit-cge7k7cvri59ugp5v3e0` means nothing to me. But something like `test-integration-v1-kit-cge7k7cvri59ugp5v3e0` makes sense IMHO because we could take one look at it, and be like "okay we have the `v4` of that integration already, let's remove all these kits", or "let's keep the latest kit created for `test-integration` and delete anything prior".

What do you guys think?

**Comment by squakez** [comment]
It can make sense and I'd even bet some github issue with the feature request sticks out there (if not, feel free to create one so we can use it as a tracker for a new feature).

**Comment by mertdotcc** [comment]
Will do!
