### ISSUE TITLE
Kamelet development using Camel DSL instead of YAML DSL

### ISSUE THREAD

**Issue by mertdotcc** [apache/camel-k#4174]
Basically what the title says.

Is this possible? We have a big team of talented Java developers and would love to be able to develop our custom Kamelets using Java DSL. If not possible yet, is it on the roadmap? Is it something we can contribute towards?

Many thanks in advance.

**Comment by davsclaus** [comment]
No its not possible, kamelets are yaml spec. And its not on the roadmap, and it will not be.

**Comment by squakez** [comment]
Yes, I agree with Claus. I wrote an article some time ago [1]:

> A Kamelet is a document specifying an integration flow. A Kamelet uses Camel components and enterprise integration patterns (EIPs) to describe a system's behavior. You can reuse a Kamelet abstraction in any integration on top of a [Kubernetes](https://developers.redhat.com/topics/kubernetes) cluster. You can use any of Camel's domain-specific languages (DSLs) to write a Kamelet, but the most natural choice is the YAML DSL. The YAML DSL is designed to specify input and output formats, so any integration developer knows beforehand what kind of data to expect.

One of the advantages of Kamelets is to facilitate the design of an EDA, reason why a markup language is most suitable for the purpose.

[1] https://developers.redhat.com/blog/2021/04/02/design-event-driven-integrations-with-kamelets-and-camel-k

**Comment by mertdotcc** [comment]
Thanks for sharing @squakez, quite helpful!
