### ISSUE TITLE
Multierr dependency upgrade

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#4197]
Will require some work as not immediately compatible. Opening a new issue.

_Originally posted by @squakez in https://github.com/apache/camel-k/issues/4195#issuecomment-1489822574_

**Comment by gansheer** [comment]
To upgrade this dependency we would need to upgrade golang version to 1.19.

Is there something known that could prevent us from upgrading golang version to 1.19 ?

**Comment by squakez** [comment]
Nothing. We can upgrade if we want to. We just need to make sure to update all CI actions accordingly.

**Comment by squakez** [comment]
We're already on 1.20, we can work on it now.
