### ISSUE TITLE
Allow E2E suite test to run against a remote cluster

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#4207]
With a limited resource machine, then, you have no other option to delegate E2E work remotely. So, I am thinking that maybe we can introduce a couple of environment variables when installing the operator in the E2E suite [1] which can control the following parameters:
```
      --operator-image string                       Set the operator Image used for the operator deployment
      --operator-image-pull-policy string           Set the operator ImagePullPolicy used for the operator deployment
```
so, the final user can override them to look for a custom image (like in your case) or controlling the pull policy. I am opening an issue to work on this separately, and feel free to contribute to it as well. In the while, if you are not able to run things locally, I suggest to push the changes and have a look at the checks result. Fortunately now the time to complete a full cycle of test is less that 1 hour.

[1] https://github.com/apache/camel-k/blob/b79bb26893557d74613186363245cd3b4b882d54/e2e/support/test_support.go#L325

_Originally posted by @squakez in https://github.com/apache/camel-k/issues/4190#issuecomment-1491624489_

**Comment by squakez** [comment]
FYI @mertdotcc

**Comment by mertdotcc** [comment]
Thank you @squakez! Can't wait to try it out!
