### ISSUE TITLE
Non-existent make command listed in the docs

### ISSUE THREAD

**Issue by mertdotcc** [apache/camel-k#4212]
In the `minikube` section of the `contributing/e2e` page we have the following command listed: `make install-minikube` (see [here](https://github.com/apache/camel-k/blob/main/docs/modules/ROOT/pages/contributing/developers.adoc)).

However we don't have this command in our `Makefile`. We should either remove it from the docs as its confusing or provide the command.

Might be related: [#3873](https://github.com/apache/camel-k/issues/3873) and [#3800](https://github.com/apache/camel-k/issues/3800).

**Comment by squakez** [comment]
Yes, it is a leftover. It must be removed from doc.

**Comment by mertdotcc** [comment]
Alright, I can work on it.

**Comment by mertdotcc** [comment]
@squakez Remove it completely or add the minikube steps you listed in? [#4190 comment](https://github.com/apache/camel-k/pull/4190#issuecomment-1491423980)

**Comment by squakez** [comment]
> @squakez Remove it completely or add the minikube steps you listed in [#4190 comment](https://github.com/apache/camel-k/pull/4190#issuecomment-1491423980)?

I think you can link instead the local installation procedure in https://camel.apache.org/camel-k/next/contributing/local-development.html

**Comment by squakez** [comment]
It seems we have already cleaned that.
