### ISSUE TITLE
Local file in unit test leftover

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#4217]
I think that with https://github.com/apache/camel-k/pull/4154 we introduced a little regression as sometimes, the file created in `pkg/util/jvm/name` is listed by git for addition. It would be nice to keep the test but use a file path outside the git directory (`/tmp`?) to avoid pulling it in by mistake.

**Comment by squakez** [comment]
@realMartinez do you mind having a look?

**Comment by realMartinez** [comment]
yes I will take a look, I am a bit busy today, so either later in the
afternoon or tomorrow afternoon

Martin

**Comment by squakez** [comment]
No rush, you can do at your best convenience. I'll assign this to you and you work whenever you can, there is no deadline.

**Comment by realMartinez** [comment]
created a PR for this issue
