### ISSUE TITLE
enabling backlog tracing for routes

### ISSUE THREAD

**Issue by divyanshurai07** [apache/camel-k#4240]
Hi, 

is it possible to add/enable camel backlog tracing for routes so as to help in debugging.

BACKLOGTRACER
Camel supports a backlog tracer interceptor that is used for capturing a trace message of each message as they are routed in Camel. The trace message is stored in a backlog queue, which contains the last N messages for each node in the routes (by default 10).

**Comment by squakez** [comment]
In theory the feature [1] could be enabled. What I am not sure is if/how it would turn into the Camel Quarkus runtime. Feel free to run some experiment and use this issue to keep track of it.

[1] https://camel.apache.org/manual/backlog-tracer.html#_enabling
