### ISSUE TITLE
Upload local dependencies as maven artifact

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#4244]
With #1227 we've enabled the possibility to use local dependencies. However, the mechanism seems to be working only using "spectrum" strategy which won't let certain cluster (ie, OCP) to have the feature fully available. We are also performing this operation on the client side, which I think it create a certain coupling we need to avoid.

I wonder if we can rethink the implementation of the feature differently. I am thinking we could upload the dependency to the operator Pod and delegate to it the deployment to the local maven repo using the `maven deploy:deploy` [1]. As in version 2 we have a storage that will keep the dependencies, it could be a possible strategy to adopt.

[1] https://maven.apache.org/guides/mini/guide-3rd-party-jars-remote.html

**Comment by johnpoth** [comment]
Hi @squakez ! Great idea! I tested this against OCP in the past and it worked but it was a long time ago... will try to give it another try at some point....

How would the dependency be uploaded ? Via SCP? What is the storage planned for version 2 (haven't seen it mentioned in the roadmap)?

**Comment by squakez** [comment]
Hello. The storage implemantation was described in https://github.com/apache/camel-k/issues/3831 - about the possibility to upload to the operator, it's an implementation detail I haven't taken in consideration yet. I was thinking at high level details, where the CLI (or even directly the `kubectl`) would upload the dependency with the compatible kube mechanisms, and from there, the operator would deploy to its local maven repo.

**Comment by squakez** [comment]
This one probably does not make sense any longer. We should promote the usage of a Maven repository [1], in which case, uploading a dependency should be done over the repository.

[1] https://camel.apache.org/blog/2023/06/camel-k-maven-proxy/
