### ISSUE TITLE
Mention the published "generated extension" for Java in the docs

### ISSUE THREAD

**Issue by andreaTP** [apache/camel-k#4262]
Hi there 👋 

since #3994 this project started publishing a "generated extension" for fabric8 `kubernetes-client`, unfortunately, there are no user-facing docs mentioning it.

Do you think we can add a mention somewhere?
The intention should be to slowly fade away from the `fabric8` extension and direct users to this new package.
Thoughts? Ideas? Suggestions on where to place this information?

Thanks a lot in advance!

**Comment by andreaTP** [comment]
@oscerd not really, I was actually looking for guidance 🙂 

I can easily follow up with the deprecation in `fabric8` but I'm not familiar with this project docs/sites/etc.

**Comment by squakez** [comment]
Yeah, we have forgotten to add some note. Feel free to do it, I think it would be good under the "API" section.

**Comment by squakez** [comment]
@oscerd I see you're assigned to this. Would you mind if I take care and close it or do you have any pending work by any chance?

**Comment by oscerd** [comment]
Go for it and sorry
