### ISSUE TITLE
Failed to fetch data from Mysql database using camel-k

### ISSUE THREAD

**Issue by chander35** [apache/camel-k#4264]
As I was trying to fetch data from mysql database by using camel-k i am getting error message like "The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server." (iam trying same example that is available camel-k-example repository)
this is the code that i am using to fetch the data,(table name is "student")
<img width="476" alt="image" src="https://user-images.githubusercontent.com/128601152/233338794-074f399e-38c1-4317-9641-f4bf4077adf4.png">

and i have changed the datasource.properties file according to my local IP address as shown below.
(i have taken datasource as quarkus.datasource.camel.jdbc.url=jdbc:mysql://my-local-ip:3306/TestDb and TestDb is database, user as 'root' and password as 'hello')
<img width="494" alt="image" src="https://user-images.githubusercontent.com/128601152/233339389-9fa91233-4fc3-4f73-9e30-f23401215ebd.png">

and by using below command i have tried to execute the java service.
(kamel run PostgresDBAutoDatasource.java --dev --build-property quarkus.datasource.camel.db-kind=MySQL -p quarkus.datasource.camel.jdbc.url=jdbc:mysql://my-local-ip:33060/TestDb -p quarkus.datasource.camel.username=root -p quarkus.datasource.camel.password=hello -d mvn:io.quarkus:quarkus-jdbc-mysql:2.10.0.Final)

still im getting error as shown below
<img width="955" alt="image" src="https://user-images.githubusercontent.com/128601152/233341073-c5bf7628-bbb6-48bc-b005-d3e1daaaf487.png">
<img width="940" alt="image" src="https://user-images.githubusercontent.com/128601152/233341219-c979b510-1411-4c65-93ae-9e6ae50eeda5.png">

i have installed all images within the same namespace, camel-k is working properly and mysql is also working properly.

**Comment by squakez** [comment]
Hello. This kind of errors are likely network connection problems that requires some tuning on DB side. It does not seem specific to Camel or Camel K. Please, have a look at some thread found in the internet, describing this issue: https://stackoverflow.com/questions/2983248/com-mysql-jdbc-exceptions-jdbc4-communicationsexception-communications-link-fai - I think you need to include some parameter to your mysql connection in order to prevent that problem to happen.

**Comment by chander35** [comment]
The problem has resolved as i exposed default port for mysql (3306). once i used different command to install mysql in my docker it started working (docker run --name some-mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql).
