### ISSUE TITLE
error while increasing the consumer count in kafka

### ISSUE THREAD

**Issue by athira000babu** [apache/camel-k#4270]
while trying integration flows with kafka as consumer and update Database, i tried to increase the consumer count but it was throwing me error with duplicate key kind. Is this feature working in any scenarios and can you share the sample

**Comment by oscerd** [comment]
You should share your route.

**Comment by squakez** [comment]
Yes please. Any reproducer, example you're using and log with the error is required for us to understand what's going on.

**Comment by athira000babu** [comment]
in the kafka configuration i have added the consumer count as 2, then instead of load balancing they both are fetching the same records and giving duplicate error for primary key

**Comment by squakez** [comment]
According to the log, it seems some database configuration, as, it seems that the key used violates some SQL constraint. I am not very familiar with it tbh. If you share the configuration and the route you used, maybe we can provide some more hints.

**Comment by athira000babu** [comment]
- route:
    id: route-3816
    from:
      uri: kafka:books
      id: from-6b05
      parameters:
        brokers: '*******'
        consumersCount: 2
      steps:
        - log:
            message: ${body}
            id: log-a40e
        - to:
            uri: kamelet:postgresql-sink
            id: to-801b
            parameters:
              serverName: '******'
              serverPort: '*******'
              username: '******'
              password: '*******'
              query: >-
                insert into books values
                (:#id,:#author,:#title,:#genre,:#price,:#publish_date,:#description);

**Comment by athira000babu** [comment]
hi this is a sample yaml file which i have used but i have removed the server configurations. here when i am increasing the consumer count it is giving duplicate key error because i think both of them are trying to fetch the same record instead of load balancing and since i have 'id' as primary key it is giving duplicate error. do you have any suggestions on this.

**Comment by squakez** [comment]
I suggest you to evaluate properly the different configuration for Camel Kafka component. As you mentioned, the problem is happening because you have 2 `consumersCount` which lead to have:
```
The number of consumers that connect to kafka server. Each consumer is run on a separate thread, that retrieves and process the incoming data.
```
I think you may get better help reaching out wider Camel community in zulip chat (the main Camel room, not the Camel K one) or mailing list.
