### ISSUE TITLE
Camel-k install and uninstall on a fresh kind cluster in Linux

### ISSUE THREAD

**Issue by fvcortes** [apache/camel-k#4277]
### Description

There seems to be an odd behavior when using kamel install and kamel uninstall commands in a freshly created kind cluster on a Linux machine. This issue aims to provide clear and informative steps to reproduce the problem and seek clarification on the uninstallation behavior and any potential impact of the warning message on the integrations.

### Steps to Reproduce
Install a Kubernetes kind cluster with the following command:

```bash
$ kind create cluster
```
Install camel-k with basic configuration:

```bash
$ kamel install --registry registry-host.io --organization your-user-id-or-org --registry-secret-the-push-kubernetes-secret-name
```
```
OLM is not available in the cluster. Fallback to regular installation. Camel K installed in namespace default 
```
Wait for camel-k integration platform to be ready:

```bash
$ k get ip
```
```
NAME      PHASE
camel-k   Ready
```
Run kamel uninstall:

```bash
$ kamel uninstall
```
```
Camel K Integration Platform removed from namespace default
Camel K Config Maps removed from namespace default
Camel K Registry Secret removed from namespace default
Camel K Platform Kamelets removed from namespace default
Camel K Operator removed from namespace default
Camel K Role Bindings removed from namespace default
Camel K Roles removed from namespace default
Camel K Service Accounts removed from namespace default
```
Running kamel uninstall again, it returns the same message as before and adds a statement that no integration platform was found, even though it still says that the Integration Platform was removed:

```bash
$ kamel uninstall
```
```
No IntegrationPlatform resource in default namespace
Camel K Integration Platform removed from namespace default
Camel K Config Maps removed from namespace default
Camel K Registry Secret removed from namespace default
Camel K Platform Kamelets removed from namespace default
Camel K Operator removed from namespace default
Camel K Role Bindings removed from namespace default
Camel K Roles removed from namespace default
Camel K Service Accounts removed from namespace default
```
Repeating kamel uninstall reproduces the same message above. The behavior stops after running kamel uninstall --all:

```bash
$ kamel uninstall --all
```
```
No IntegrationPlatform resource in default namespace
Camel K Integration Platform removed from namespace default
Camel K Config Maps removed from namespace default
Camel K Registry Secret removed from namespace default
Camel K Platform Kamelets removed from namespace default
Camel K Operator removed from namespace default
Camel K Role Bindings removed from namespace default
Camel K Roles removed from namespace default
Camel K Service Accounts removed from namespace default
Camel K Custom Resource Definitions removed from cluster
Camel K Cluster Role Bindings removed from cluster
Camel K Cluster Roles removed from cluster
```
Run kamel uninstall again, which now returns an error:

```bash
$ kamel uninstall
```
```
Unable to retrieve the operator version: no matches for kind "IntegrationPlatform" in version "camel.apache.org/v1"
Error: the server could not find the requested resource (get integrationplatforms.camel.apache.org)
```
Install camel-k again after --all uninstallation, a warning message appears:

```bash
$ kamel install
```
```
OLM is not available in the cluster. Fallback to regular installation.
Warning: the operator won't be able to detect a local image registry via KEP-1755
Camel
```

I fear that this warning message has impacts on the Integrations I pretend to run on the cluster. Also would like to understand the uninstallation behaviour and if the warning message has to do with it.

The version of the components I used. I could also reproduce in recent camel-k and kubectl versions

```bash
$ kamel version
```
```
Camel K Client 1.12.0
```
```bash
$ kubectl version
```
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.25) exceeds the supported minor version skew of +/-1
```
```bash
$ kind version
```
```
kind v0.17.0 go1.20.1 linux/amd64
```

**Comment by christophd** [comment]
`kamel uninstall` removes the Camel K resources such as operator deployment, config maps, IntegrationPlatform and so on. But it keeps the cluster wide Camel K resources such as custom resource definitions, service accounts, roles and so on.

`kamel uninstall --all` removes all resources including CRDs and roles

The messages printed during uninstall like `Camel K Integration Platform removed from namespace default` are just informational and do not state the number of actually removed resources for instance.

What's the purpose of calling `uninstall` multiple times?

`KEP-1755` is a mechanism to detect the local registry on a cluster, see [KEP-1755](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/generic/1755-communicating-a-local-registry)

The warning message `the operator won't be able to detect a local image registry via KEP-1755` indicates that the operator was not able to install the required roles that enable access to the KEP-1755 local registry hosting config maps.

In general this will not harm the Camel K functionality. Instead of using KEP-1755 mechanism Camel K will fallback to arbitrary local registry lookup.

**Comment by squakez** [comment]
The KEP message was also removed in future Camel K versions: https://github.com/apache/camel-k/pull/4251
The info provided by @christophd should have clarified. Additionally you can find any more info in the official doc: https://camel.apache.org/camel-k/next/contributing/uninstalling.html

**Comment by fvcortes** [comment]
Thanks for the explanation, guys. In a simple reinstall I got the warning message. Since I'm planning to run Integrations in production clusters, I was afraid that the warning message could have any impact on image pull/push to remote registries. I also believe that reporting this behavior could help other people with some explanation if they bump with this message.
