### ISSUE TITLE
is there a component for kafka queue to create routes

### ISSUE THREAD

**Issue by athira000babu** [apache/camel-k#4279]

**Comment by squakez** [comment]
Hello, do you mind explaining it a bit better? I am not sure I do understand the question. Also some example would help clarifying the question.

**Comment by athira000babu** [comment]
means how can i give a queue instead of topic in kafka configuration

**Comment by squakez** [comment]
The full component configuration is the one you can find in Apache Camel framework: https://camel.apache.org/components/3.20.x/kafka-component.html

However, I think Kafka let you only specify topics, as queue looks more something in the JMS/AMQP domain.
