### ISSUE TITLE
Add statical check if integration refers to components supported by Camel K

### ISSUE THREAD

**Issue by lfabriko** [apache/camel-k#4283]
In the issue https://github.com/apache/camel-k/issues/4276 was referenced unsupported CEQ (`camel-spring-redis` isn't present in used Camel K runtime 1.17 - https://repo1.maven.org/maven2/io/quarkus/platform/quarkus-camel-bom/2.16.0.Final/quarkus-camel-bom-2.16.0.Final.pom), there was raised question how should user know he is about to use unsupported component (which resulted in later error).

If I may suggest to add a statical check of integration source code and compare it with list of supported components (currently only CEQs)

**Comment by squakez** [comment]
When you say "static" you mean to validate the Integration against the CamelCatalog ahead of time, is it that?

**Comment by lfabriko** [comment]
I meant CamelCatalog; it seems to me confusing that not all kamelets installed by Camel K operator can be used in integrations (only those filtered by presence of their components in the catalog).

**Comment by lfabriko** [comment]
Thank you for answer, I have no more suggestions.

**Comment by rovangju** [comment]
Yea I just got bit by this as well - it seems there's a quarkus oriented dependency in the catalog, but the OOTB-kamelet doesn't use it?

**Comment by rovangju** [comment]
`redis-sink` and `redis-source` kamelets have the spring dependency, but cannot be used in a binding with the camel-k installed quarkus-oriented catalog.

**Comment by rovangju** [comment]
Gotcha, my point is that it's installed with the camel-k / kamel cli and/or Helm chart, so when you list available kamelets that get installed, it looks like it's an option that will work with that specific installation. 

I'm not sure how to configure a spring-boot compatible runtime for camel-k, I'll do some digging I guess.

**Comment by claudio4j** [comment]
Camel K cannot run camel-spring-boot, currently it is tied to camel-quarkus.
Plain Camel (or camel jbang) can run kameletsbindings
