### ISSUE TITLE
Unable to reinstall the operator

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#43]
If trying to execute `kamel install` twice, the second installation fails for a issue while trying to update the service:

```
Service "camel-k-operator" is invalid: [metadata.resourceVersion: Invalid value: "": must be specified for an update, spec.clusterIP: Invalid value: "": field is immutable]
```

This is because the service gets assigned, after creation, a cluster IP that is not editable. We should either avoid replacing the cluster IP or avoid replacing the service if already present.

@dmvolod can you take a look?

**Comment by dmvolod** [comment]
@nicolaferraro , thanks I will take a look.
