### ISSUE TITLE
error  when moving file after processing in sftp

### ISSUE THREAD

**Issue by sreedeviMullaguri** [apache/camel-k#4306]
while creating integration with sftp , after processing file i tried to move it to archive folder from its source folder for that i was using move property but it was throwing cannot create directory due to denied permissions. is this working in any scenario and can you share any sample

**Comment by gansheer** [comment]
Thank you for reporting. 

Could you please should share your route. Any reproducer, example you're using and log with the error is required for us to understand what's going on.

Also, you should try your route out of camel-k with jbang like explained [here](https://camel.apache.org/blog/2022/11/camel-k-jbang/) to check if your route is actually valid in camel.
