### ISSUE TITLE
Passing image destination to build

### ISSUE THREAD

**Issue by kameshsampath** [apache/camel-k#437]
currently the build form source produces the `docker.io/apache/camel-k` image;  when testing builds and to enable using developer builds locally it will be better customize the image destination to be passed to the build. 

e.g. `make imageDestination=quay.io/myrepo images` should result in image with name `quay.io/myrepo/camel-k` being produced, if the parameter is not passed then it will default to `docker.io/apache/camel-k`

**Comment by lburgazzoli** [comment]
Fixed by #438
