### ISSUE TITLE
camel-k with spring config 

### ISSUE THREAD

**Issue by ajitghotane** [apache/camel-k#4376]
hello,
   import org.apache.camel.builder.RouteBuilder;
//import org.apache.camel.model.rest.RestBindingMode;
//import javax.enterprise.context.ApplicationScoped;
import io.quarkus.runtime.Quarkus;

public class Main extends RouteBuilder
{
    public void configure() {
        //restConfiguration().bindingMode(RestBindingMode.json);
       /* from("direct:start") 
        .to("camel-spring-cloud:config-client?uri=http://localhost:8888/application&profile=dev") 
        .to("log:info");
        */
        from("quarkus-spring-config:Welcome")
        .log("${body}");

    }
} 

by this code I am try to fetch the config from spring cloud config server by executing following command

kamel run Config.java --property file:./application.properties --dev -d mvn:io.quarkus:quarkus-camel-quarkus:2.16.0 -d mvn:io.quarkus:quarkus-spring-boot-starter:2.8.0.Final -d mvn:io.quarkus:quarkus-spring-cloud-config-client -d mvn:io.quarkus:quarkus-resteasy -d mvn:io.quarkus:quarkus-camel-core -d mvn:quarkus-spring-config 

but i am getting this

<img width="960" alt="image" src="https://github.com/apache/camel-k/assets/130899147/89523d55-3a4c-4f5c-b3f3-9ee8c7a4b8d7">

i am using quarks dependencies
and have the demo example to fetch the config from spring cloud config server  please share with me

**Comment by squakez** [comment]
As stated in the error condition, the component is not supported in Camel Quarkus catalog. This is the list of supported components: https://camel.apache.org/camel-quarkus/3.0.x/reference/components.html

**Comment by ajitghotane** [comment]
I tried with this rg.apache.camel.quarkus:camel-quarkus-consul dependency  which is in supported components and also this dependency support the spring cloud then also I am getting the error
<img width="938" alt="image" src="https://github.com/apache/camel-k/assets/130899147/238b9c96-f85e-49ac-97ee-d0aec91f2228">

**Comment by squakez** [comment]
The `camel-quarkus-consul` component and relative dependencies may be working and it should automatically resolved by Camel K when you use `consul:apiEndpoint` in your routes. If you use `spring-cloud-config:xyz` then, the operator will resolve to `camel-quarkus-spring-config` which is not supported.

**Comment by ajitghotane** [comment]
import org.apache.camel.builder.RouteBuilder;

public class MyCamelRoute extends RouteBuilder {
    @Override
    public void configure() throws Exception {
        from("consul:Welcome/application/dev")
            .to("quarkus-spring-config:application?springCloudConfigUrl=http://localhost:8888")
            .to("log:configurations");
    }
}
this is the code 
and this is the command  **kamel run MyCamelRoute.java --dev -d mvn:io.quarkus:quarkus-camel-quarkus:2.16.0 -d mvn:io.quarkus:quarkus-camel-core -d camel:consul**
but the issue is same

**Comment by ajitghotane** [comment]
any update on this?

**Comment by squakez** [comment]
I thought I was clear with my previous comment. The problem of your route is the presence of `.to("quarkus-spring-config:application?springCloudConfigUrl=http://localhost:8888/")` which won't work in Camel K because the `quarkus-spring-config` endpoint and related components are not supported in Camel Quarkus.

**Comment by oscerd** [comment]
I think you first need to understand the difference between Camel and Spring.

**Comment by ajitghotane** [comment]
Any another way to do this?
