### ISSUE TITLE
How to know a Component status at a time

### ISSUE THREAD

**Issue by kyleabcha** [apache/camel-k#44]
Hi,

I am having difficulty how to differ when a Component (DefaultComponent) is deployed (NEW) or when it is just restarted or undeployed (REMOVED completely). Could someone explain a bit?

Many thanks, Kyle

**Comment by oscerd** [comment]
Please ask on the users mailing list users at camel.apache.org

**Comment by kyleabcha** [comment]
thank you. the issue is closed.
