### ISSUE TITLE
Using an XSLT as a local dependency results in "unknown dependency error"

### ISSUE THREAD

**Issue by fhossfel** [apache/camel-k#4426]
I am trying to include an XSLT into the image build by Camel-K using the following mode-line:

// camel-k: dependency=file:common_json2xml.xslt:/etc/camel/resources/common_json2xml.xslt

This results in an error:

    {"level":"error","ts":1685453328.590157,"logger":"camel-k.controller.build","msg":"Build kit-chqvjflec46c73dffthg failed: unknown dependency type: file:common_json2xml.xslt:/etc/camel/resources/common_json2xml.xslt","request-namespace":"camel-k","request-name":"kit-chqvjflec46c73dffthg","api-version":"camel.apache.org/v1","kind":"Build","ns":"camel-k","name":"kit-chqvjflec46c73dffthg","stacktrace":"github.com/apache/camel-k/pkg/controller/build.(*monitorRoutineAction).updateBuildStatus\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_routine.go:197\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorRoutineAction).runBuild\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_routine.go:181"}
    
The documentation state that:

> You can also specify data files to be mounted in the running container:
>
> kamel run -d file://path/to/data.csv:path/in/container/data.csv Integration.java
>
> Specifying a directory with also work recursively.

I assumed that an XSLT falls under the description of a "data file." Is this a bug or is the documentation just unclear?

**Comment by squakez** [comment]
What version of Camel K are you using? the feature [1] is only available in non Openshift environment IIRC. There is also an issue #4398 that I vaguely remember was about something similar.

[1] https://camel.apache.org/camel-k/1.12.x/configuration/dependencies.html#dependencies-kind

**Comment by fhossfel** [comment]
Using `file://` instead of `file:` results in an even more interesting error:

    Error: IntegrationPlatform.camel.apache.org "camel-k" not found

**Comment by squakez** [comment]
That's because there is not an IntegrationPlatform called `camel-k` (which is the default one). Can you please provide the output of `kubectl get ip` in the namespace where you're working?

**Comment by fhossfel** [comment]
Camel K ist installed in the camel-k namespace but I am working in the dev ns.

    ~ % kubectl -n dev get ip
    No resources found in staging namespace.
     ~ % kubectl -n camel-k get ip
    NAME      PHASE
    camel-k   Ready
    ~ % 
    
If Itry to run the integration in the camel-k namespace I get the following error:

    ~ % kamel -n camel-k run test_error.groovy --dependency=file://common_json2xml.xslt:/etc/camel/resources/common_json2xml.xslt
    Error: Error trying to upload file://common_json2xml.xslt:/etc/camel/resources/common_json2xml.xslt to the Image Registry.: stat common_json2xml.xslt:/etc/camel/resources/common_json2xml.xslt: no such file or directory

**Comment by squakez** [comment]
Okey, I guess it's a global operator. Then you need to create an IntegrationPlatform in those namespaces where you want to run the integration as well:
```
kamel install --skip-operator-setup -n my-namespace
```

**Comment by johnpoth** [comment]
@fhossfel Yeah we [moved](https://github.com/apache/camel-k/commit/d545b70be9b7483716bf10c16fad3e05e9c09df7) to URI syntax so it should be:

```
kamel -n camel-k run test_error.groovy --dependency=file://common_json2xml.xslt?targetPath=/etc/camel/resources/common_json2xml.xslt
```

Looks like we need to update the docs on the website sorry about that ( the info in the CLI seems ok ...).

**Comment by fhossfel** [comment]
Sorry, for the late reply. I was on holiday.

@johnpoth: This works. I have created a new Integration Platform basically by running `kubectl get ip -o yaml | kubectl apply`. (Using kamel install did not work because I would have to respecify the Docker repo settings.)

Ist here any reason thy this does not work with a global operator? TBH this is a bit surprising TBH.

**Comment by johnpoth** [comment]
Hi @fhossfel , glad it works!

It should work with a global operator; are you getting a specific error ? 

Not sure about the way you are installing the Integration Platform, @squakez is this the correct way ?

Thanks !
