### ISSUE TITLE
--port flag not working while running kamel integration in debug mode 

### ISSUE THREAD

**Issue by simranjit11** [apache/camel-k#4443]
**commad I ran:**  
kamel debug my-connector --port 5000

**logs on terminal shows port 5005:**
Enabling debug mode on integration "my-connector"...
[1] Monitoring pod my-connector-00011-deployment-9dgb24h
[1] exec java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005 -Xmx269M

**Comment by simranjit11** [comment]
Tried with --remote-port. But it is still the same.

```
kamel debug my-connector --remote-port 5000
Enabling debug mode on integration "my-connector"...
[1] Monitoring pod my-connector-00002-deployment-86m2tgk
[1] exec java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005 -Xmx269M
```

**Comment by squakez** [comment]
Thanks, what Camel K version are you using?

**Comment by simranjit11** [comment]
@squakez  1.12.0
```
% kamel version
Camel K Client 1.12.0
```

**Comment by simranjit11** [comment]
@squakez , is someone working on this issue?

**Comment by squakez** [comment]
> @squakez , is someone working on this issue?

Hello. Not that I know, it's not assigned. If you're willing to contribute, just let me know and I will assign the issue to you. Thanks!

**Comment by simranjit11** [comment]
@gansheer , for me it does in output last three lines of port forwarding..

```
Forwarding from 127.0.0.1:5000 -> 5005
Forwarding from [::1]:5000 -> 5005
Handling connection for 5000
```

And when I try to connect remote JVM with the port specified for --port, it says connection refused

**Comment by gansheer** [comment]
@simranjit11 does it actually works on 5005 ? 

In any case we need more  detail how you are deploying your operator and integration to understand why it does not creates PortForward. It could be that you are missing permissions to create these forwarding.

**Comment by squakez** [comment]
Stale. Please reopen this issue if still happening with more recent Camel K versions.
