### ISSUE TITLE
Issue with connecting to microsoft sql server from camel-k

### ISSUE THREAD

**Issue by chander35** [apache/camel-k#4465]
Hi Team,

I am facing issue while connecting to mssql from camel-k,  Here I have taken a sample select query to fetch data from database but every time I am getting error as shown below 

code: 
<img width="333" alt="image" src="https://github.com/apache/camel-k/assets/128601152/95a40d4b-6b75-4c29-a20e-cdc58efa9e1b">

Command I am using to execute the code

**kamel run SelectQuery.java --dev -p 
quarkus.datasource.camel.db-kind=sqlserver -p 
quarkus.datasource.camel.jdbc.url=jdbc:sqlserver://localhost:1433/College -p 
quarkus.datasource.camel.username=sa -p 
quarkus.datasource.camel.password=******* -p 
mvn:com.microsoft.sqlserver:mssql-jdbc:12.2.0.jre11**

Error:
<img width="942" alt="image" src="https://github.com/apache/camel-k/assets/128601152/7450420b-d2e4-443c-8f67-8a7c72ccc5e7">

**### Please let me know if I am missing something or doing something wrong. Thanks.**

**Comment by oscerd** [comment]
If you're deploying on a cloud provider, using localhost to point the sqlserver will never work.

**Comment by squakez** [comment]
Yes. You need to review this property `quarkus.datasource.camel.jdbc.url=jdbc:sqlserver://localhost:1433/College` and change localhost value with the service location where your database is exposed. As an example, feel free to refer the PostgreSQL example to understand how to configure SQLServer to expose a service: https://github.com/apache/camel-k-examples/tree/main/generic-examples/databases

**Comment by chander35** [comment]
Yes, I have tried with exposed ip address (ex: quarkus.datasource.camel.jdbc.url=jdbc:sqlserver://192.168.1.4:1433/College) and I verified ip address by connecting it to DBeaver Application to access the database, It is connected and able to run commands also, but when tried from camel-k, It is showing same issue as mentioned above.

Do I need to add any dependencies otherthan mentioned?

**Comment by squakez** [comment]
According to the Quarkus documentation, database kind has to be `mssql`: https://es.quarkus.io/guides/datasource -  also, verify that the driver you're providing is the one containing the expected Quarkus extensions, it seems to me that the one you've provided is not a "Quark-ified" one. Unfortunately we cannot give you that much support here about these kind of problems, we don't have enough experience for that.

**Comment by chander35** [comment]
Hi @oscerd , I have gone through kamelet links that you shared, I'm able to understand but is there any reference page that I can refer and implement in my java code using kamelet. The above code is working fine for oracle DB and mysql DB but not for mssql.

**Comment by oscerd** [comment]
My suggestion is to set the url like it is done in the kamelet and use the driver for mssql from quarkus. You need to add the driver jar yourself for license reason

**Comment by chander35** [comment]
The problem is resolved after including "ex: mvn:io.quarkus:quarkus-jdbc-mssql:3.1.1.Final" dependency in the command. Thank you for your valuable suggestion.
