### ISSUE TITLE
Rework CLIs required by operator build process

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#4466]
Leftover from original #4326 

There are certain dependencies that are required by CLIs used by internal development tooling:

- github.com/shurcooL/httpfs v0.0.0-20190707220628-8d4bc4ba7749
- github.com/shurcooL/vfsgen v0.0.0-20181202132449-6a9ea43bcacd
- gengo

In #4326 we tried to remove the tools in ''/cmd` directory but it turns out they are required. Goal of this issue is to rework those tools and either remove their usage or use supported dependencies in order to have a safer maintenance.

**Comment by squakez** [comment]
cc @gansheer

**Comment by gansheer** [comment]
@squakez I will work on it

**Comment by gansheer** [comment]
The real solution for this issue is solving #3384. We need to switch to the standard `go:embed`

**Comment by squakez** [comment]
Good for spotting it. I'm closing this in favor of the one you've identified. If you're still working on it, let me know and I'll assign it to you.

**Comment by squakez** [comment]
> The real solution for this issue is solving #3384. We need to switch to the standard `go:embed`.
> 
> That brings me this question: what is the resources.go usage, why do we need it ?

Not really sure.

**Comment by claudio4j** [comment]
The resources.go stores files as byte representation for late retrieval, for example in master.go trait `data, err := resources.TemplateResource(fmt.Sprintf("/addons/master/%s", name), params)` it loads the embedded file. 
See the list of embedded files
```
resources/traits.yaml
resources/builder/builder-service-account.yaml
resources/builder/builder-role.yaml
resources/builder/builder-role-binding.yaml
resources/builder/builder-role-binding-openshift.yaml
resources/builder/builder-role-openshift.yaml
resources/camel-catalog-2.16.0-SNAPSHOT.yaml
resources/addons/master/master-role-configmap.tmpl
resources/addons/master/master-role-lease.tmpl
resources/addons/master/master-role-binding.tmpl
resources/viewer/user-global-platform-viewer-role-binding.yaml
resources/viewer/user-global-kamelet-viewer-role-binding.yaml
resources/viewer/user-global-platform-viewer-role.yaml
resources/viewer/user-global-kamelet-viewer-role.yaml
```

I think they can be replaced by `go:embed`
