### ISSUE TITLE
Issue while working on multiple endpoint in camel-k.

### ISSUE THREAD

**Issue by chander35** [apache/camel-k#4475]
Hi Team,

I have been facing an issue with endpoints as shown below.

<img width="356" alt="image" src="https://github.com/apache/camel-k/assets/128601152/2833279a-9016-4377-8301-e9e55b2acf52">

in this i'm trying to fetch data from multiple data sources(abc & def) and I have created a secret from application.property file, this property contains endpoint details for both abc and def as i shown below.

<img width="625" alt="image" src="https://github.com/apache/camel-k/assets/128601152/7e3736f3-bc46-4ebe-915d-911e13667858">

I ran the code by using the command as shown here, it was working fine when I ran individual routes, but it is failing when i run as a whole(two route).

kamel run Test.java --dev --build-property quarkus.datasource**.abc**.db-kind=oracle -p  quarkus.datasource.**def**.db-kind=mssql --config **secret:abcdef-datasource** -d mvn:io.quarkus:quarkus-jdbc-oracle:2.16.0.Final -d mvn:io.quarkus:quarkus-jdbc-mssql:3.1.1.Final

and the error i'm getting like 
"**ERROR [org.apa.cam.qua.mai.CamelMainRuntime] (main) Failed to start application: org.apache.camel.FailedToCreateRouteException: Failed to create route route1 at: >>> To[jdbc:def] <<< in route: Route(route1)[From[timer://sql-insert?period=30000] -> [SetB... because of Failed to resolve endpoint: jdbc://gdw due to: No bean could be found in the registry for: gdw of type: javax.sql.DataSource**"

Please help me to resolve.

**Comment by squakez** [comment]
I see something strange. Your exception complains about `jdbc://gdw` which does not really exist. Also, I wonder if both Quarkus SQL extensions can coexist without problems.

**Comment by chander35** [comment]
sorry. jdbc://gdw I renamed as jdbc://def

**Comment by squakez** [comment]
Okey, it seems you're not providing both as `build-property`. I think you need to run `--build-property quarkus.datasource.abc.db-kind=oracle --build-property quarkus.datasource.def.db-kind=mssql` as both properties are required at build time for Quarkus build.

**Comment by chander35** [comment]
Thank you @squakez , the java code started working properly after adding "--build-property" for both data sources, Now I am able to fetch data from both tables from different data sources. 👍 :)
