### ISSUE TITLE
Alter namespace where the Push of Operator sends the image generated

### ISSUE THREAD

**Issue by erick-leao** [apache/camel-k#4492]
Hi staff,

I would like to know if the option of configuration a kamel run I set the namespace where the image that generated by Operator will be pushed in some other namespace of registry?

ex:

```
kubernete namespace: my-camel-testes
registry:http://site.com/

and after the build o Operator execute:

... Pushing image site.com/my-camel-testes/camel-k-kit-ci6abnpcn3sd9fqa19b0:261541652 ...
```

But I need that this image "**camel-k-kit-ci6abnpcn3sd9fqa19b0:261541652**" is push for "**site.com/project-x/camel-k-kit-ci6abnpcn3sd9fqa19b0:261541652**"

There is to change "**my-camel-testes**" to "**project-x**" without me have that to change the namespace of kubernetes?

I read all --traits configuration and I did not find a response for this.

**Comment by gansheer** [comment]
Hello,

What you are missing is the organization part of the registry configuration. It is not available in traits but as integration platform configuration : [CONFIGURING REGISTRY
](https://camel.apache.org/camel-k/1.12.x/installation/registry/registry.html).

**Comment by erick-leao** [comment]
Hummm...

The IT area misconfigured even the registration part. I saw today that it has the registry setting.

Thansk @gansheer
