### ISSUE TITLE
Helm chart 0.13.1 failed to install

### ISSUE THREAD

**Issue by anhpngt** [apache/camel-k#4497]
I was unable to install camel-k Helm chart v0.13.1 and encountered the following error

```sh
Helm release camel-k not installed. Installing...
Error: INSTALLATION FAILED: failed to install CRD crds/crd-binding.yaml: no objects visited
deploying "camel-k": install: exit status 1
```

It seems like [this file](https://github.com/apache/camel-k/blob/23dfdea9f8e81cf5b5c12815f6c92f7b5245a9d5/helm/camel-k/crds/crd-binding.yaml) has no objects, which is not accepted by Helm.

**Comment by squakez** [comment]
It is strange that it fails against that version as that one should be pointing to release 1.12.1 which does not contain such leftover value.

**Comment by alagusundarams** [comment]
Even with 1.12.1 the same issue occurs and after removing the empty crd-binding.yaml it worked.

**Comment by squakez** [comment]
Thanks. Then we may have 2 problems. The first one is that we need to remove that `crd-binding.yaml` from `main`. The second one is that the installation should use the CRDs provided for the specific version, not the ones in `main`. I am not very familiar with the helm installation procedure, but we must make sure that every version is bundled or use the correct CRD definitions.

**Comment by squakez** [comment]
I've applied a patch that should work as soon as the repos are synched. However I'm leaving this issue open because we should find an automated way to add the correct chart when releasing from `release` branches. Moreover, we should have an E2E test to verify that the chart is working as expected before releasing.

**Comment by squakez** [comment]
Fixed:
```
$ helm install my-camel-k camel-k/camel-k --version 0.13.1 --set platform.build.registry.address=my-registry.io
NAME: my-camel-k
LAST DEPLOYED: Fri Jun 23 12:20:55 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Connect the world with Camel K on Kubernetes!
```
