### ISSUE TITLE
Question: use camel dependency version 3.20.3 or higher

### ISSUE THREAD

**Issue by romain-pfund** [apache/camel-k#4502]
Hi,

The current release of camel-k is using camel 3.20.1.
The problem is that I use azure service bus component and the "abandon message" feature on failure is implemented from camel 3.20.3.

Any chance that you upgrade the camel dependency version soon ?

thanks

**Comment by squakez** [comment]
Hello. I don't think so. The main limitation at this stage is that we need to use Camel Quarkus runtime, which is the one that really drives the Camel version adopted. In the future we should be a bit more free and be able to use other versions, but at this stage this is not available. Sorry.

**Comment by romain-pfund** [comment]
Ok thanks for the reply, I'll manage the error/failure in another way
