### ISSUE TITLE
Unable to update the secret when the integration is running.

### ISSUE THREAD

**Issue by chander35** [apache/camel-k#4508]
Hi Team,

I have created a secret using the file (e.g., application.properties file). The file contains endpoint details. I am able to access the endpoint using the secret, but I am facing an issue when I want to update the endpoint while the integration is running in the background.

I have tried different ways to update the secret and access it. For example, I deleted the existing secret and created a new secret with the same name and updated endpoint, while the integration is running. However, it is still not picking up the updated secret and it does not interrupt the running integration but it is picking up only when I restart the integration.

However, when I tried using a file (e.g., --property file:application.properties), it worked as expected. I am able to access the endpoint, even update it and I can see changes while the integration is running in the background.

Can you please help me how can I update the secret when integration is running.

**Comment by squakez** [comment]
> I have tried different ways to update the secret and access it. For example, I deleted the existing secret and created a new secret with the same name and updated endpoint, while the integration is running. However, it is still not picking up the updated secret and it does not interrupt the running integration but it is picking up only when I restart the integration.
> 

That's the current behavior. We have an issue to see if we can work on hot redeploy on cm/secrets changes: #2106

> However, when I tried using a file (e.g., --property file:application.properties), it worked as expected. I am able to access the endpoint, even update it and I can see changes while the integration is running in the background.
> 

I guess it's because you're also using `--dev` so the hot redeploy is detected by the CLI which restart the integration.

**Comment by squakez** [comment]
Hot deploy available as described in https://github.com/apache/camel-k/issues/2106
