### ISSUE TITLE
Allow to remote debug the Operator

### ISSUE THREAD

**Issue by essobedo** [apache/camel-k#4513]
Since the code refactoring for Camel-K 2, it is much harder to debug the operator, especially on MacOS. The goal of this task is to provide a way to remote debug the operator in order to be closer to the target environment and to be local OS agnostic.

**Comment by essobedo** [comment]
I don't see any doc about how to debug the operator with Minikube. I only see that https://camel.apache.org/camel-k/next/contributing/developers.html#debugging but it seems to be incomplete as it doesn't explain how to install camel-k without the operator like we had before in doc page that has been removed.

When I try to launch the operator like I did with v1, I meet many problems due to the fact that it assumes the location of different programs like `mvnw`.
For example:
```
{"level":"info","ts":1687796092.647079,"logger":"camel-k.maven.build","msg":"Executed command: /bin/cp --recursive /usr/share/maven/mvnw/. ."}
{"level":"info","ts":1687796092.6537018,"logger":"camel-k.maven.build","msg":"cp: illegal option -- -"}
{"level":"info","ts":1687796092.653837,"logger":"camel-k.maven.build","msg":"usage: cp [-R [-H | -L | -P]] [-fi | -n] [-aclpsvXx] source_file target_file"}
{"level":"info","ts":1687796092.653853,"logger":"camel-k.maven.build","msg":"       cp [-R [-H | -L | -P]] [-fi | -n] [-aclpsvXx] source_file ... target_directory"}
```

**Comment by essobedo** [comment]
Let's say that someone re-adapts the code to make it work as before, TBH, in practice who cares if the operator works properly on the local machine? What is important is that the operator works properly on its target environment which is at the end a docker container in a pod. 

So the idea of my proposal is to be able to remote debug directly from the cluster, WDYT? I have already something working, I can push branch to show you the idea if you want

**Comment by squakez** [comment]
Yeah, that would be perfect. The idea of removing the "support" of local running operator it's exactly that one, ie, the fact that it's difficult to support the operator running both in the cluster and in a local machine. If you manage to have the cluster debugging in the cluster it would be the perfect solution IMO. I'll have a look at the PR shortly, thanks a lot!

**Comment by lburgazzoli** [comment]
FWIW, I would be very cautious about removing support for local running operator as it would make the whole development process a lot slower and it would be yet another barrier for newcomers as opposed of may other operators I'm aware of.

Briefly looking at the root issue it seems that the major barrier is the process of building the _builder_ image which as previously discussed should happen only in rare cases ad should be provided out of the box so my recommendation would be to add support for remote debugging but also trying to fix the root issue instead of removing local development support

**Comment by essobedo** [comment]
This PR doesn't remove anything, it only adds a new way to debug the operator.

**Comment by lburgazzoli** [comment]
I was mainly looking at the discussion in this thread where I read:

> Let's say that someone re-adapts the code to make it work as before, TBH, in practice who cares if the operator works properly on the local machine?

> The idea of removing the "support" of local running operator it's exactly that one, ie, the fact that it's difficult to support the operator running both in the cluster and in a local machine

If the plan is only to add remote debugging, that's fine but the discussion was IMHO heading also to other discussions. It would be nice to open some issues about what does not work when running the operator locally and explore options to address them.

**Comment by squakez** [comment]
I agree that it would be nice to have full local support as it shows the business logic is very well encapsulated and easy to debug. However it's not easy to maintain full compatibility with Kubernetes (not to talk about the various K8S flavors) and a local execution as during the development of the operator we are making always the assumption we are in a K8S environment. This dynamic builder stuff is just one (and at this stage the most visible) limitation, but we have much more.

To me the point is that the operator needs anyhow a Kubernetes cluster to run (watch a namespace, CRDs, etc...). Running a Camel K Operator pod is fairly simple and limited in resource consumption. In my experience, I've found much easier to debug in a cluster (I use a local one) than when I used to run the operator binary in my machine.

Said that, I understand it's a matter of habits and tastes, so, nothing to argue against the possibility to support the local running.

**Comment by lburgazzoli** [comment]
to be clear, local run to me means running the operator outside the operator cluster, ideally as the operator talks to the k8s client, there should not be much difference in running inside or outside the cluster

I am missing something?

**Comment by squakez** [comment]
I think there are a couple of things to take into account as well. The CRDs needs to be installed. It happens to me several time that while debugging locally I forgot to refresh the CRDs. With an installation this is not happening. The access to registry or to maven repos sometimes is flaky. Then, talking about the needs to have a local set of runtime dependencies. The installation procedure takes care to bundle and refresh, so you always get the latest one available. If you run locally you need to remind to point to your local repository. I think they are little details, but in my experience enough to decide to always debug with the installer.

**Comment by johnpoth** [comment]
> FWIW, I would be very cautious about removing support for local running operator as it would make the whole development process a lot slower and it would be yet another barrier for newcomers as opposed of may other operators I'm aware of.
> 
+1000

**Comment by essobedo** [comment]
@claudio4j What do you use as cluster? Minikube?

**Comment by claudio4j** [comment]
This is the launch.json
```
        {
          "name": "Camel K Operator - cluster",
          "type": "go",
          "debugAdapter": "dlv-dap", // `legacy` by default
          "request": "attach",
          "mode": "remote",
          "port": 4040,
          "host": "127.0.0.1", // can skip for localhost
          "trace": "verbose",
          "showLog": true,
          "logOutput": "dap",
          "substitutePath": [
            { "from": "${workspaceFolder}/cmd/kamel/main.go", "to": "/usr/local/bin/kamel" },
          ]
      }
```
I didn't spend much time investigating.

**Comment by essobedo** [comment]
Try with this configuration
```
{
            "name": "Remote Debug",
            "type": "go",
            "request": "attach",
            "mode": "remote",
            "port": 4040,
            "host": "localhost",
            "cwd": "${workspaceFolder}",
            "trace": "verbose"
        }
```

**Comment by claudio4j** [comment]
It worked, thanks Nicolas.

**Comment by squakez** [comment]
The documentation supporting the local operator execution will be back as we have now removed the dynamic builder container generation.
