### ISSUE TITLE
Unable to run the code by adding Jar files as depedency

### ISSUE THREAD

**Issue by masterflux** [apache/camel-k#4524]
```
// camel-k: name=pojo-jar
// camel-k: dependency=camel-jackson
// camel-k: dependency=camel-quarkus-rest-openapi
// camel-k: dependency=mvn:org.projectlombok:lombok:1.18.22
// camel-k: resource=file:C:/beans/target/pojo-jar-1.0.0.jar
// camel-k: trait=jvm.classpath=/etc/camel/resources/pojo-jar-1.0.0.jar

package org.apache.camel;

import lombok.extern.slf4j.Slf4j;
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestBindingMode;
import org.apache.camel.model.rest.RestParamType;

@Slf4j
public class OpenApiRoute extends RouteBuilder {
    @Override
    public void configure() {
        getContext().getRegistry().bind("userService", new UserService());

        restConfiguration()
                .component("platform-http")
                .bindingMode(RestBindingMode.json)
                .dataFormatProperty("prettyPrint", "true")
                .apiContextPath("/api-doc")
                .apiProperty("api.title", "User API").apiProperty("api.version", "1.2.3")
                .apiProperty("cors", "true")
                .clientRequestValidation(true);

        rest("/users").description("User rest service")
                .consumes("application/json").produces("application/json")

                .get("/{id}").description("Find user by id").outType(User.class)
                .param().name("id").type(RestParamType.path).description("The id of the user to get").dataType("integer").endParam()
                .responseMessage().code(200).message("The user").endResponseMessage()
                .to("bean:userService?method=getUser(${header.id})")

                .put().description("Updates or create a user").type(User.class)
                .param().name("body").type(RestParamType.body).description("The user to update or create").required(true).endParam()
                .responseMessage().code(200).message("User created or updated").endResponseMessage()
                .to("bean:userService?method=updateUser")

                .get().description("Find all users").outType(User[].class)
                .responseMessage().code(200).message("All users").endResponseMessage()
                .to("bean:userService?method=listUsers")

                .get("/{id}/departments/{did}").description("Find all users").outType(User[].class)
                .param().name("id").type(RestParamType.path).description("The id of the user to get").dataType("integer").endParam()
                .param().name("did").type(RestParamType.path).description("The id of the department to get").dataType("integer").required(true).endParam()
                .responseMessage().code(200).message("All users").endResponseMessage()
                .to("bean:userService?method=listUsers");
    }
}
```
Issue is the same as the titles says I am using this command to run the code : `kamel run OpenApiRoute.java -d "file://C:/CAMEL-k/camel-k-examples/generic-examples/pojo-jar/target/pojo-jar-1.0.0.jar?targetPath=/etc/camel/resources/pojo-jar-1.0.0.jar&classpath=true"`

Below the SS of the issue where the code in stuck.
<img width="947" alt="image" src="https://github.com/apache/camel-k/assets/97143534/d2511390-6721-4957-ac77-b9d96bfbf811">

**Comment by masterflux** [comment]
We gave proper credentials 

<settings>
    <servers>
        <server>
            <id>image-registry</id>
            <username>username</username>
            <password>docker access token</password>
        </server>
    </servers>
</settings>

It is getting stucked in the building phase without throwing any error 

We've noticed the image registry is configured with a Secret [camel-k-registry-secret]
Please configure Docker authentication correctly or the operation will fail (by default it's $HOME/.docker/config.json).More information can be found here https://docs.docker.com/engine/reference/commandline/login/
spectrum - 2023/07/05 09:55:42 Pulling base image  (insecure=true)...
spectrum - 2023/07/05 09:55:42 Composing layers...
spectrum - 2023/07/05 09:55:42 Pushing image docker.io/vibwow/maven_org_apache_camel_pojo-jar_1_0_0_pojo-jar-1_0_0_pom:1.0.0 (insecure=false)...
spectrum - 2023/07/05 09:55:48 pushed blob: sha256:9bab4355d92e509f669d2e89845f5ba7dd36cf0c1bde2c49bd63a32ac4de4a7b
spectrum - 2023/07/05 09:55:48 pushed blob: sha256:123060af9d86e41b6a8cdbeabb0071c8e31e9639884f43c9538a5207a512dc2e
spectrum - 2023/07/05 09:55:49 docker.io/vibwow/maven_org_apache_camel_pojo-jar_1_0_0_pojo-jar-1_0_0_pom:1.0.0: digest: sha256:79265205e1aae7a4e2329d91bb4ccff043e2f84db00912e38e6a16f4311bcab4 size: 424
Uploaded: C:\Users\vkraft\AppData\Local\Temp\camel-k1646028551\pom.xml to docker.io/vibwow/maven_org_apache_camel_pojo-jar_1_0_0_pojo-jar-1_0_0_pom:1.0.0
spectrum - 2023/07/05 09:55:49 Pulling base image  (insecure=true)...
spectrum - 2023/07/05 09:55:49 Composing layers...
spectrum - 2023/07/05 09:55:49 Pushing image docker.io/vibwow/maven_org_apache_camel_pojo-jar_1_0_0_pojo-jar-1_0_0_pom_md5:1.0.0 (insecure=false)...
spectrum - 2023/07/05 09:55:51 pushed blob: sha256:651ceb4a7acced52e7a4106847feb5600aad3135776a4fb853097f4256b5dad0
spectrum - 2023/07/05 09:55:51 pushed blob: sha256:c75ee5f0f4b3dfe98db5518a5607a19db567986c608880155c8905158c8a3d6c
spectrum - 2023/07/05 09:55:51 docker.io/vibwow/maven_org_apache_camel_pojo-jar_1_0_0_pojo-jar-1_0_0_pom_md5:1.0.0: digest: sha256:ab9233399dda24809f58b8576db85217c8f7a56e40f63e61b63de55e5538c5f1 size: 423
spectrum - 2023/07/05 09:55:51 Pulling base image  (insecure=true)...
spectrum - 2023/07/05 09:55:51 Composing layers...
spectrum - 2023/07/05 09:55:51 Pushing image docker.io/vibwow/maven_org_apache_camel_pojo-jar_1_0_0_pojo-jar-1_0_0_pom_sha1:1.0.0 (insecure=false)...
spectrum - 2023/07/05 09:55:54 pushed blob: sha256:293aab29f1a5a310a275d4fe6eb6e9931be162c9636d506403fd7ee3104087d4
spectrum - 2023/07/05 09:55:55 pushed blob: sha256:ce1afb72f57fda429afb18014c8735c977a30f8d29b7859e6fd9580d449d4041
spectrum - 2023/07/05 09:55:55 docker.io/vibwow/maven_org_apache_camel_pojo-jar_1_0_0_pojo-jar-1_0_0_pom_sha1:1.0.0: digest: sha256:adbb15b964f3020ecebfa9c1e87f468c8b7834f3970a3f537ba6d659d65df7ff size: 423
Added mvn:org.apache.camel:pojo-jar:jar:1.0.0 to the Integration's dependency list
spectrum - 2023/07/05 09:55:55 Pulling base image  (insecure=true)...
spectrum - 2023/07/05 09:55:55 Composing layers...
spectrum - 2023/07/05 09:55:55 Pushing image docker.io/vibwow/maven_org_apache_camel_pojo-jar_1_0_0_pojo-jar-1_0_0_jar:1.0.0 (insecure=false)...
spectrum - 2023/07/05 09:55:58 pushed blob: sha256:c8747f49c8e56c42756f011a2bece16c748cb9d0f35eb03c98fa5bc444509ca1
spectrum - 2023/07/05 09:55:58 pushed blob: sha256:1e0546af557ff7fa50b2bf00f7e248d53c20e773415569c2bfe3e7fc7e26d7d4
spectrum - 2023/07/05 09:55:58 docker.io/vibwow/maven_org_apache_camel_pojo-jar_1_0_0_pojo-jar-1_0_0_jar:1.0.0: digest: sha256:cd1e53f8b50c5cadd118a51d1bc427f6c459999602f74ed656c279f8f7cd31ab size: 424
Uploaded: C:/Amway/CAMEL-k/camel-k-examples/generic-examples/pojo-jar/target/pojo-jar-1.0.0.jar to docker.io/vibwow/maven_org_apache_camel_pojo-jar_1_0_0_pojo-jar-1_0_0_jar:1.0.0
spectrum - 2023/07/05 09:55:58 Pulling base image  (insecure=true)...
spectrum - 2023/07/05 09:55:58 Composing layers...
spectrum - 2023/07/05 09:55:58 Pushing image docker.io/vibwow/maven_org_apache_camel_pojo-jar_1_0_0_pojo-jar-1_0_0_jar_md5:1.0.0 (insecure=false)...
spectrum - 2023/07/05 09:56:00 pushed blob: sha256:9c481d204db8657118bb7d3d39b2626cae00af510c577aa928430bf9fac2b247
spectrum - 2023/07/05 09:56:01 pushed blob: sha256:fc98221c7930f024a949e6d8f275d92a0c2ed7a779b761305619bd0cd9de341e
spectrum - 2023/07/05 09:56:01 docker.io/vibwow/maven_org_apache_camel_pojo-jar_1_0_0_pojo-jar-1_0_0_jar_md5:1.0.0: digest: sha256:7a6e7d6855bb1c878ee513096fad894ca651407bf758843d0c388d0250bd734c size: 423
spectrum - 2023/07/05 09:56:01 Pulling base image  (insecure=true)...
spectrum - 2023/07/05 09:56:01 Composing layers...
spectrum - 2023/07/05 09:56:01 Pushing image docker.io/vibwow/maven_org_apache_camel_pojo-jar_1_0_0_pojo-jar-1_0_0_jar_sha1:1.0.0 (insecure=false)...
spectrum - 2023/07/05 09:56:04 pushed blob: sha256:d2b0f97e87693c4989295bd41a440e16f9c4843e1fe0bdc440dc2cf8378a3340
spectrum - 2023/07/05 09:56:04 pushed blob: sha256:82829f1b82fa7f6f965524fb82afd0b463c43893ec33aebcad423c14ed91cb97
spectrum - 2023/07/05 09:56:04 docker.io/vibwow/maven_org_apache_camel_pojo-jar_1_0_0_pojo-jar-1_0_0_jar_sha1:1.0.0: digest: sha256:9c5bc9fc3b65296b36df46dcb62c1c182b11fb41d0458143dfecd8c97cafe14c size: 423
Integration "pojo-jar" created
Progress: integration "pojo-jar" in phase Initialization
Condition "IntegrationPlatformAvailable" is "True" for Integration pojo-jar: camelex/camel-k
Integration "pojo-jar" in phase "Initialization"
Progress: integration "pojo-jar" in phase Building Kit
Integration "pojo-jar" in phase "Building Kit"
Condition "IntegrationKitAvailable" is "False" for Integration pojo-jar: creating a new integration kit
Integration Kit "kit-ciif1n9no1t2d9khl850", created by Integration "pojo-jar", changed phase to "Build Submitted"
Run integration terminating

**Comment by squakez** [comment]
I find similarities as in #4398 - could you please check if the hints provided in the other issues are enough to solve your problems? Thanks.

**Comment by masterflux** [comment]
Thanks  for the help @squakez
