### ISSUE TITLE
Builder image name missing the organization configuration

### ISSUE THREAD

**Issue by gansheer** [apache/camel-k#4525]
**Version:** Camel-k main branch (2.x)

When installing Camel-k with a defined `organization` id/name with build strategy `pod` the builder image full name does not contains the `organization` id/name. I think it should (like with the kit image):

```
REPOSITORY                                               TAG               IMAGE ID       CREATED          SIZE
apache/camel-k                                           2.0.0-SNAPSHOT    abda4a06c8c4   15 minutes ago   637MB
10.100.246.9/myorg/camel-k-kit-cihsu2p5tpl20drnif60   <none>            a18953b17581   2 weeks ago      516MB
10.100.246.9/camel-k-runtime-quarkus-builder             2.16.0-snapshot   0a3d865dd0dc   2 months ago     1.08GB
```

The command used to install is:
```
kamel install --build-strategy pod --organization  myorg
```

**Comment by squakez** [comment]
I don't think the org should apply to the dynamic image builder. IMO we need the builder to be as much generic as possible and reused if we have several IntegrationPlatforms (hence, several organizations).

**Comment by gansheer** [comment]
What will happen if we have non-compatible registry configurations (example with auth) in different IntegrationPlatforms ? Do we rebuild the builder image ?

**Comment by squakez** [comment]
> What will happen if we have non-compatible registry configurations (example with auth) in different IntegrationPlatforms ? Do we generate a another builder image ?

Good point. In general we need to revisit the entire concept of the dynamic builder, which is something that may be just temporary. If we evaluate for now it requires some enhancement like the one you're proposing, probably it makes sense to do it. Thanks.

**Comment by squakez** [comment]
Trying to use a private registry we're getting some auth problems:
```
      message: 'HEAD https://index.docker.io/v2/library/camel-k-runtime-quarkus-builder/manifests/2.16.0-snapshot:
        unexpected status code 401 Unauthorized (HEAD responses have no body, use
        GET for details)'
```
