### ISSUE TITLE
Add `description` to KameletBinding and Integration

### ISSUE THREAD

**Issue by igarashitm** [apache/camel-k#4535]
While Kamelet allows to put `/spec/definition/description`, KameletBinding doesn't have an equivalent. It would be nice to have it for KameletBinding as well.

In addition to that, for Integration, although `route` has `description` property which allows users to put longer description onto each route, and it could be used in Integration CRD as well - since Integration CRD can have multiple routes, it would be nice to have CRD level description field as well.

**Comment by lburgazzoli** [comment]
What is the goal of having a "description" field in a KameletBinding ? 
Can the same been achieved by an annotation ?

**Comment by igarashitm** [comment]
I think annotation would be fine if it's well defined. The original motivation is to use it from tooling (and possibly runtime monitoring?), where user want to put a longer description next to name/title. It would be better to align where to put those info with Kamelet, either `/spec/definition`, `metadata` or `metadata/annotation`.

**Comment by igarashitm** [comment]
Actually even deeper root of this idea is that plain camel `route` has `description` property which allows users to put longer description onto each route, and it could be used in `Integration` CRD as well. Kamelet has `/spec/definition/description` however it looks like an exception as a part of [JSONSchemaProps](https://camel.apache.org/camel-k/1.12.x/apis/kamelets.html#_camel_apache_org_v1alpha1_JSONSchemaProps). Only KameletBinding doesn't have such property.

Looking at the schema, Kamelet also has `description` property right under `template` it seems
https://github.com/apache/camel/blob/main/dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camel-yaml-dsl.json#L2566

Lastly, since Integration CRD can have multiple routes, it would be nice to have CRD level description field as well.

**Comment by lburgazzoli** [comment]
I'm not sure about that is a good idea and I'm quite reluctant to add tooling specific field to the spec of Binding/Pieps/Integration as that has no value for the controller but still, if you change them, then the generation of the resource changes indicating that a reconcile loop should take place so it seems semantically incorrect to me especially as a binding/pipe/integration, as opposed to a Kamelet, results int a running POD and a change to the spec could lead to some disruption or in any case to some additional work for the controller without a clear benefit as opposed to use annotations.

I also don't see the pattern to add tooling specific field to specs which should be keep as minimal as possible and even Kubernetes uses annotation for some kind of tooling related stuffs (i.e. `kubectl.kubernetes.io/last-applied-configuration`). 

So of course fields can be added but IMHO, it should be the very very last option.

**Comment by igarashitm** [comment]
Closing - conclusion is to use such as `/metadata/annotations/tooling.specific.description`
