### ISSUE TITLE
Use custom component in camel K

### ISSUE THREAD

**Issue by hoangtuannguyen-manabie** [apache/camel-k#4539]
I wrote a custom component to use from doc in here https://camel.apache.org/manual/writing-components.html and can work normally with project camel by import jar file to camel project. But when we i add the this component to camel k by command:
```
kamel run --dev MyExample.java -t logging.level=DEBUG --dependency file://my-component-1.0.0.jar --property=file:application.properties
```
but it throw error
```
component not found for uri mycomponent  in camel catalog runtime version 1.17.0
```
i used kamel version 1.12.0

**Comment by squakez** [comment]
Camel K does not support custom components at the moment.

**Comment by hoangtuannguyen-manabie** [comment]
Do we have any workaround for it ?

**Comment by squakez** [comment]
Probably you need to edit the CamelCatalog and specify there which are the dependencies which are bound to the URI. However it's not really immediate workaround and you may also need to provide a Camel Quarkus extension for your component.

**Comment by hoangtuannguyen-manabie** [comment]
Ah thanks. let me consider other way

**Comment by usevalad-prus** [comment]
Hello @hoangtuannguyen-manabie, have you managed to create a custom quarkus extension and get it working?

**Comment by hoangtuannguyen-manabie** [comment]
not yet @usevalad-prus i used camel project instead
