### ISSUE TITLE
improve release process

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#458]
We need to improve the way the project is released as as today we have two competing tools when doing a release:

- maven 
- make/bash

And of course they do not play very well (i.e. both are supposed to tag and changes versions).

I think we need to separate operator and runtime release cycles and versions and/or move the runtime to a different repo (waiting to be mature enough to be moved to camel itself).

@nicolaferraro @oscerd @astefanutti thoughts ?

**Comment by oscerd** [comment]
+1

**Comment by astefanutti** [comment]
Agreed. I would use a git submodule to replace the `runtime` directory if that eases transitioning so we can externalise without touching the current build for the catalogs and images.

**Comment by lburgazzoli** [comment]
yes we also need to add an option similar to the camel-version one so we can break the latest thing that hard link go and java runtime
