### ISSUE TITLE
Image Vulnerability of Go package

### ISSUE THREAD

**Issue by ajbisht** [apache/camel-k#4581]
Hi

Please let me know when will be the next release of Camel K image will come as there is a critical vulnerability of Go package in 1.12.0 version

**Comment by oscerd** [comment]
There is a 1.12.1 release already

**Comment by ajbisht** [comment]
sorry my bad Vulnerabilities are in 1.12.1 only

**Comment by squakez** [comment]
We're planning to release Camel K 2 very soon. Stay tuned.

**Comment by ajbisht** [comment]
Hi,

Camel 2.0 has the same vulnerabilities.

**Comment by claudio4j** [comment]
@ajbisht how do you see the image vulnerability ?

**Comment by squakez** [comment]
@ajbisht please, send an email to private@camel.apache.org in order to provide all details related to the vulnerability you're referring to. Thanks.

**Comment by ajbisht** [comment]
@claudio4j  There is a Prisma Cloud Twistlock Image scanner in the Clients Infrastructure. 
 So when we try to push  the Public Docker image to nexus private registry, Jenkins sends scanning request for the public image and if we have Critical and High Vulnerabilities , Jenkins fails the pipeline.

@squakez Thanks. Will send the email with details.

**Comment by squakez** [comment]
Hi @ajbisht I think that one won't work as you need to be subscribed to lists before. You should follow the guidelines to [report a security issue](https://camel.apache.org/community/support/#reporting-security-issues). Please, provide all information over there and we'll be notify by the security team accordingly. Thanks!
