### ISSUE TITLE
Facing issue while Integrating Java Code and REST with JAR Dependencies

### ISSUE THREAD

**Issue by chander35** [apache/camel-k#4593]
Hi Team,

I have successfully created a JAR file from my Java code, and I have imported the classes from that JAR into another Java code, which is functioning as expected. However, I encountered an issue when attempting to access the latter Java code through a REST API. The problem is that the classes from the previously mentioned JAR file (".bean") are not accessible when using the REST API.

When I test the REST API using the Postman application, I receive a "500 internal server error." Interestingly, both the ".bean" and the REST API work flawlessly independently. The problem only arises when I attempt to combine them.

Here I am providing necessary dependencies while running the command, still unable to figure out what I missed or where I am going wrong. Please help on this.

**Comment by squakez** [comment]
Hello, please, provide a simple reproducer so we can see what's going on.
