### ISSUE TITLE
Include CRD yaml files in camel-k-crds maven artifact

### ISSUE THREAD

**Issue by igarashitm** [apache/camel-k#4655]
Currently camel-k-crds only contains generated Java model classes. It would be handy for tooling if the source CRD YAML file is also included next to those model classes(, or in a separate maven artifact, either way is fine).
https://github.com/apache/camel-k/tree/main/config/crd/bases

**Comment by squakez** [comment]
This one should be available in next 2.1.0 once it's merged. However you can check already in next nightly dependency which should be published tonight [1]. The CRDs will be included into the same dependency jar.

[1] https://repository.apache.org/content/repositories/snapshots/org/apache/camel/k/camel-k-crds/
