### ISSUE TITLE
IntegrationPlatform stucked in "status.phase: Starting"

### ISSUE THREAD

**Issue by ismailbaskin** [apache/camel-k#466]
I'm trying to install camel-k on GKE (1.11.7-gke.6) and followed each step on the documentation. But it does not work. integrationplatform/camel-k stuck in "status.phase: Starting". When investigating camel-k-operator pod logs I've noticed that error.

```json
{
  error:  "Get https://10.241.0.1:443/api?timeout=32s: dial tcp 10.241.0.1:443: connect: connection refused"   
  level:  "error"   
  logger:  "cmd"   
  msg:  ""   
  stacktrace:  "github.com/apache/camel-k/vendor/github.com/go-logr/zapr.(*zapLogger).Error
	/home/lburgazz/work/apache/dev/camel-k-go/src/github.com/apache/camel-k/vendor/github.com/go-logr/zapr/zapr.go:128
main.main
	/home/lburgazz/work/apache/dev/camel-k-go/src/github.com/apache/camel-k/cmd/manager/main.go:80
runtime.main
	/opt/data/sfw/lang/go/1.11.4/src/runtime/proc.go:201"   
  ts:  1550666236.7073588   
 }
```

After that I've run this command for ensuring and it works as expected.
`kubectl exec -it $(kubectl get pod -l name=camel-k-operator -o jsonpath="{.items[0].metadata.name}") -- curl --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt https://10.241.0.1:443/api?timeout=32s`

result:
```json
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "XX.XXX.XXX.XXX:443"
    }
  ]
}
```

Do you have any idea what caused this situation?

**Comment by astefanutti** [comment]
Thanks for the report. It seems similar to #431.

**Comment by ismailbaskin** [comment]
It is definitely the same error. I've missed that.

**Comment by astefanutti** [comment]
Let me close this and follow up in #431.
