### ISSUE TITLE
Tekton ServiceAccount missing camelcatalog access

### ISSUE THREAD

**Issue by gansheer** [apache/camel-k#4666]
When runing the `run-operator-build.yaml` sample for Tekton we have the following logs from the pod `operator-build-run-kamel-run-pod`:

```
Defaulted container "step-execute" out of: step-execute, prepare (init), place-scripts (init), working-dir-initializer (init)
Unable to retrieve the operator version: camelcatalogs.camel.apache.org is forbidden: User "system:serviceaccount:default:camel-k-tekton" cannot list resource "camelcatalogs" in API group "camel.apache.org" in the namespace "default"
Integration "routes" created
routesBuilding
```

The permission to list `camelcatalogs` to the Role in `cicd/tekton/kamel-run/0.1/support/camel-k-tekton.yaml` should be added.

**Comment by gansheer** [comment]
I could take care of it but I think it might need some change in this https://github.com/tektoncd/catalog/pull/1166.

**Comment by squakez** [comment]
Let's apply the changes in our repo first, as the PR in the catalog is not yet merged. I'll take care to move any change over there eventually.
