### ISSUE TITLE
Create a script to verify rbac from config/rbac to helm/camel-k/templates

### ISSUE THREAD

**Issue by claudio4j** [apache/camel-k#4674]
The script may be called from Makefile to check if there are missing configurations in helm based files.

**Comment by squakez** [comment]
I think that more than another script to maintain, we need an E2E test to verify all is working as expected: https://github.com/apache/camel-k/issues/4497#issuecomment-1604021492

**Comment by squakez** [comment]
https://github.com/apache/camel-k/pull/4684 introduced Helm installation test. If you think this is enough to spot possible Helm problems feel free to close this issue as well.

**Comment by claudio4j** [comment]
the elm install test is good for a basic install, but doesn't cover the rbac permissions to run pipes or knative routes.
This script is intended for a quick feedback while running make build.
