### ISSUE TITLE
Add GH issue template

### ISSUE THREAD

**Issue by claudio4j** [apache/camel-k#4675]
Add a GH issue template

There are many issue reports, which are in fact just user's questions that are suitable for a discussion forum or mailing list.
We should add a issue template, similar to jaeger, to let users have a good community experience in zulip chat room or mailing list.
https://github.com/jaegertracing/jaeger/issues/new/choose

And in the case of real bug report or feature request, ask the user to provide the detailed information about the bug, reproducers, versions, etc.
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by anishrajan25** [comment]
@claudio4j I would like to take this up! Could you please assign this to me?

**Comment by claudio4j** [comment]
Hi @anishrajan25 , assigned, thanks for the contribution.

**Comment by squakez** [comment]
IMO it's something we're not yet ready for, it feels like a entry barrier. This could be good for established projects or projects with a wide community. We're (still) a small community and I feel we should remove any barrier for feedback/question etc.

**Comment by claudio4j** [comment]
The intention is not to block users to seek help, but mostly a guideline on how to report bug reports, by providing the technical details and reproducers, etc. 
And if the user has general questions, they may use the other channels for a wider audience, but if desired they can open a GH issue.

**Comment by anishrajan25** [comment]
@claudio4j Could you please provide me with links to the slack channel or zulip chat and mailing list that you have mentioned in the issue description. 

Also I did not find any discussion page for Apache or camel-k. In case you have a link to that, could you share that as well? I will add an option for that as well in the template

**Comment by claudio4j** [comment]
https://camel.zulipchat.com/

https://camel.apache.org/community/mailing-list/
