### ISSUE TITLE
Camel-k 2.0 - helm change role bindings  from kameletbindings 

### ISSUE THREAD

**Issue by milank78git** [apache/camel-k#4676]
I have a question I don't understand why the role in the clusterrole was changed from kameletbindings to bindings and why there is no pipes resource in the clusterrole/role
When I installed camel-k via helm there were errors in the operator access . I returned roles and add pipes Operator is OK.

One last question. 
Why does the change crd  not changes  version . 
In every version of camel-k you change the crd but the version is still 0.6.1

**Comment by claudio4j** [comment]
> why the role in the clusterrole was changed from kameletbindings to bindings and why there is no pipes resource in the clusterrole/role
> When I installed camel-k via helm there were errors in the operator access

There may be some differences in the roles configuration provided by helm, there is this https://github.com/apache/camel-k/issues/4674 to verify if the roles are aligned, so we add them to the Makefile or a CI check to have them always aligned.

> Why does the change crd not changes version .

Which field represents the version you refers to ?
Provide the link to the actual file, and be more specific.

> In every version of camel-k you change the crd but the version is still 0.6.1

That is the kubebuilder annotation which is defined in [Makefile](https://github.com/apache/camel-k/blob/main/script/Makefile#L29), do you have any concern to it ?
```
controller-gen.kubebuilder.io/version: v0.6.1
```

Perhaps, these type of questions are more suitable for a discussion forum
https://camel.zulipchat.com/

I am closing this, but please open a new bug report with detailed information about the bug, like version, files, behavior, reproducers, etc.
