### ISSUE TITLE
Rearrange Go modules

### ISSUE THREAD

**Issue by claudio4j** [apache/camel-k#4686]
Given the recent problem with the [go module in camel-k 2.0](https://github.com/apache/camel-k/issues/4683), I see there is a problem related to the way the camel-k modules are defined and published,

There are the following modules
```
pkg/client/camel/go.mod:
  module github.com/apache/camel-k/v2/pkg/client/camel

pkg/apis/camel/go.mod:
    module github.com/apache/camel-k/v2/pkg/apis/camel

pkg/kamelet/repository/go.mod:
    module github.com/apache/camel-k/v2/pkg/kamelet/repository

go.mod:
    module github.com/apache/camel-k/v2
```

go modules documentation
https://github.com/golang/go/wiki/Modules#faqs--multi-module-repositories

These additional modules were created as a way to let the camel api to be imported independent of the camel-k-operator packages, but we haven't seen other projects importing the camel apis specifically.
Also, the other modules are sub-directories of the main go module, which seems to be not a good practice.

In name of making the project easier to maintain and release I propose to remove the modules from the subtree and have only the root module.

Note that any other project importing camel go apis, using the main module as `github.com/apache/camel-k/v2`

**Comment by lburgazzoli** [comment]
@astefanutti what do you think ?

**Comment by squakez** [comment]
Be mindful of the relationship that each module have with each other. I made some experiments in the past [1] and I was not able to have a full working version. I am okey with the proposal, we cannot have a repo only for API IMO. During development make sure to solve all the release process which are now in charge to sync the versioning among the modules.

[1] https://github.com/apache/camel-k/issues/4086#issuecomment-1450400534
