### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#4700]
See comment

**Comment by squakez** [comment]
@andreaTP could you please advice how to configure the plugin to generate some license header for all java classes?

**Comment by andreaTP** [comment]
@squakez I'll have a look 👍

**Comment by andreaTP** [comment]
Fixing it would be pretty straightforward, but my understanding is that license headers on each and every file are not a requirement anymore for Apache projects, cc. @oscerd

**Comment by oscerd** [comment]
It's required for ASF projects

**Comment by oscerd** [comment]
It's required for ASF projects as far as I know

**Comment by andreaTP** [comment]
I'm sure it was, but I'm convinced it's not anymore.

**Comment by oscerd** [comment]
Short license is still needed on top https://www.apache.org/legal/apply-license.html#new

**Comment by andreaTP** [comment]
@oscerd given that this code is automatically generated, and, assuming [this](https://github.com/apache/incubator-pekko/issues/38#issuecomment-1311468140) remains valid, I would add a `LICENSE` file in the `./java` folder.

That said, I'm not fussy about it, if you still believe that it has to be done I can have a look.

**Comment by oscerd** [comment]
For me it's the same. Thought @squakez ?

**Comment by squakez** [comment]
I'm good with that. In such case I can take care of adding that as we're already doing with CRDs files. I will also to change the check script, but I can work on it.

**Comment by andreaTP** [comment]
Let me know if you need any support @squakez 👍
