### ISSUE TITLE
Provide default value in a specific field for trait properties in CRD

### ISSUE THREAD

**Issue by apupier** [apache/camel-k#4726]
### Requirement

As a user I would like to have default value pre-filled

### Problem

the default value is provided inside the description text which is not convenient to read from for tooling that want to read/display the display value more prohemitently

**Comment by gansheer** [comment]
@apupier Just to clarify, you are expecting the default values only for trait fields declared in the documentation to be in the CRD ?

**Comment by apupier** [comment]
> you are expecting the default values only for trait fields declared in the documentation to be in the CRD ?

From Camel Language Server point of view, I identified only these ones missing. But if there are other places that are missing default values, it would be better to add them too.

**Comment by gansheer** [comment]
I added all the default values I could find/extract. Most of the others are either given by the Kubernetes Platform implementation either conditional.
@squakez this issue is fixed AFAIK.

**Comment by squakez** [comment]
We had to revert the change that fixed this issue. Still open.
