### ISSUE TITLE
add finalizer to ensure integration children are cleaned up

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#477]

**Comment by astefanutti** [comment]
Note that by default, owned resources are deleted prior to the owner and block its deletion base on the `ownerReference.blockOwnerDeletion` field, see:

https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#foreground-cascading-deletion

**Comment by lburgazzoli** [comment]
yes I think we need an option that set the cleanup policy:
- owned
- finalizer

**Comment by astefanutti** [comment]
There is a delete option (endpoint and kubectl) that changes the owner deletion behaviour: 

https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#background-cascading-deletion
