### ISSUE TITLE
Knative installation procedure

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#4779]
Camel K is very well suited to work with Knative. However we do miss some official documentation to promote such feature and we also miss some doc to explain how to install in Camel K. Depending on the installation procedure, the resources required by Camel K to work with Knative are not even considered (see #4716).

We also do not explain that if KNative is installed _after_ Camel K operator, we need to apply certain resources manually. This doc should take care of that part as well.

**Comment by mertdotcc** [comment]
I can take over this as I'm already working on [#4716](https://github.com/apache/camel-k/issues/4716).
