### ISSUE TITLE
Consider adding `/PipeSpec/traits`

### ISSUE THREAD

**Issue by igarashitm** [apache/camel-k#4780]
### Requirement

I want to configure `traits` at Pipe `/spec/trais`

Related to: https://github.com/apache/camel-k/issues/3479
This is to configure traits through k8s `objectMeta/annotations`, but `Integration` kind has explicit `/IntegrationSpec/traits`. It would be nice to also have a correspondance in PipeSpec as well, i.e. `/PipeSpec/traits`.

### Problem

Being a bit more consistent on trait configuration across CRDs, and get more information for trait configuration in the schema explicitly

**Comment by lburgazzoli** [comment]
Note: we should evaluate what trait we want to enable on Pipes as Pipes have been designed to be as simple as possible

**Comment by squakez** [comment]
Mind that you already have an IntegrationSpec that could be used for that purpose.

**Comment by squakez** [comment]
> @squakez yes but that embedded integration should go away at some point as it completely defeat the goal of a Pipe.

Agree, I was trying to figure it out why this detail slipped into the Pipe... In any case, going back to the original problem: should we let the user to provide any tuning in a Pipe? For instance, I am trying to figure it out how we can provide a parameter which may be required by a Kamelet, ie, a `Secret`. Or, thinking out loud, probably we should have Kamelets which have such level of configuration in their spec...

**Comment by lburgazzoli** [comment]
I think we need to reason about what option we really want to expose and what not.
Ideally a kamelet should never require a secret, only parameter, eventually a path to a a file mounted as a volume as kamelets are templates so there should not be any hardcoded value in them.

**Comment by squakez** [comment]
BTW, we also have the possibility to use trait via annotations: https://camel.apache.org/camel-k/next/kamelets/kamelets-user.html#_trait_via_annotations - maybe it makes sense to deprecate the IntegrationSpec favouring this last possible configuration method.
