### ISSUE TITLE
Upgrade to Go 1.21

### ISSUE THREAD

**Issue by gansheer** [apache/camel-k#4795]
### Requirement

We should upgrade the project to  the Go version 1.21 that has been [released](https://go.dev/blog/go1.21) in August.

### Problem

None, there is backward compatibility.

### Open questions

If there is anything that could prevent this upgrade don't hesitate to comment.

**Comment by squakez** [comment]
No hurry though, we can defer this one for 2.2 or 2.3.

**Comment by gansheer** [comment]
I'll take care of it

**Comment by squakez** [comment]
@gansheer I'm taking care of it if you don't mind as it's part of another thing I've stumbled upon. Thanks.
