### ISSUE TITLE
Improving kamel install

### ISSUE THREAD

**Issue by kameshsampath** [apache/camel-k#481]
Improving kamel install by make the application giving real time messages post install until all the required components are built

**Comment by astefanutti** [comment]
We could have a `kamel status` command that could be similar to what `oc rollout status` is doing.

**Comment by kameshsampath** [comment]
but the issue i need to issue another command for a better devx the install could all `status` automatically.. WDYT?

**Comment by lburgazzoli** [comment]
if you use -w the install process waits until it completes

**Comment by astefanutti** [comment]
Yes agreed. I think it's worth having a `status` command as user may want to get a pick a the platform status even after `install` command. But we could output the `status` command within / after the `install` command. We may want to have a `--watch option` added to the install, same for the `status` command.

Let's see what others think and bring that feature in.

**Comment by kameshsampath** [comment]
yes watch should be for all custom resources of camel-k as well. right now the kubectl get ictx -w does not work

**Comment by astefanutti** [comment]
> yes watch should be good. for all custom resources of camel-k as well. right now the kubectl get ictx -w does not work

I think standard `kubectl --watch` option only applies to `List` endpoints.
