### ISSUE TITLE
Camel K 2.1 documentation still contains information on using local files for runtime resources despite it is no more supported

### ISSUE THREAD

**Issue by apupier** [apache/camel-k#4853]
### What happened?

While deploying with resource which are not config or secret file
the deployment is failing
with error:
`Error: could not match config or secret configuration as file:/home/apupier/ws/single-file-without-extension-workspace/demo.camel.xml`

The documentation is stating: `The runtime resources are expected to be any resource type (text or binary content).` https://camel.apache.org/camel-k/2.0.x/configuration/runtime-resources.html

### Steps to reproduce

1. Create a Camel K integration file
2. Create a random file (which is not a config or secret file) like an xml file
3. try to deploy the integration with a command like: kamel run Demo.java --resource=file:/path/to/the/file.xml

### Relevant log output

```shell
`Error: could not match config or secret configuration as file:/home/apupier/ws/single-file-without-extension-workspace/demo.camel.xml`
```

### Camel K version

2.1.0

**Comment by gansheer** [comment]
Hi,

The change has been made in Camel K 2.0 when deprecated kamel command have been removed : [CAMEL K 2.0](https://camel.apache.org/blog/2023/07/camel-k-2-0/). I you want to provide a file you need to store it in a Configmap or Secret. This is why you no longer see any reference to "file:xxxx" in the documentation you are looking at.

**Comment by apupier** [comment]
I think the documentation needs a major update as it is still mentioning that the "most familiar way is to handle local file".

**Comment by gansheer** [comment]
@squakez I will fix the doc.

**Comment by MotaOcimar** [comment]
Oh man. My routes use some json and velocity (.vm) files to format responses. What would be the easiest way for my Camel-K routes to reference these files?

**Comment by squakez** [comment]
> Oh man. My routes use some json and velocity (.vm) files to format responses. What would be the easiest way for my Camel-K routes to reference these files?

Not sure to understand how this comment relates to this specific issue. Would you mind opening a separate issue with all the details about your request? thanks.
