### ISSUE TITLE
improve resource gc performances

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#487]
cleaning up old resources may take a little bit of time which increase the deployment time, we should optimize the algorithm we use to collect related resources.

**Comment by astefanutti** [comment]
One option may be to change the delete operation options to either use a `background` or `orphan` propagation policy. If that does not lead to a significant latency improvement, we'll have to change the algorithm to avoid discovering the resource types and use a hard-coded list of supported types.

**Comment by Emmerson-Miranda** [comment]
Congrats the project looks really good.

I want to evaluate if I can use It in production projects.

I wonder if you can provide an example about how to use "kamel run --repository" and how to use camel-binding to call java clases stored in custom jar libraries.

https://camel.apache.org/bean-binding.html
