### ISSUE TITLE
Native image builds failing with dependencies from private repository

### ISSUE THREAD

**Issue by hernanDatgDev** [apache/camel-k#4892]
### What happened?

I've been testing an integration that relies on dependencies from a private maven repository. The integration works as expected in non-native mode however when running in native mode, the builder pod is unable to resolve the external dependencies. It's _almost_ as if the builder pod is using different maven settings and is then unable to authenticate to the repo, but this is just a suspicion since the integration works when building within the operator.

### Steps to reproduce

1. Setup camel-k 2.1.0 in a cluster with maven settings that have access to a private repository
2. Create an integration that includes a dependency from the private repository
3. Run the integration in native build mode
4. Integration should fail while attempting to resolve the private dependencies

### Relevant log output

```shell
Logs from the builder pod running the native image build:

quarkus-native Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/camel/quarkus/camel-quarkus-groovy-dsl/3.2.0/camel-quarkus-groovy-dsl-3.2.0.jar (4.8 kB at 1.1 kB/s)
quarkus-native [INFO] ------------------------------------------------------------------------
quarkus-native [INFO] BUILD FAILURE
quarkus-native [INFO] ------------------------------------------------------------------------
quarkus-native [INFO] Total time:  33.819 s
quarkus-native [INFO] Finished at: 2023-11-02T15:33:18Z
quarkus-native [INFO] ------------------------------------------------------------------------
quarkus-native [ERROR] Failed to execute goal on project camel-k-integration: Could not resolve dependencies for project org.apache.camel.k.integration:camel-k-integration:jar:2.1.0: The following artifacts could not be resolved: com.backbase.gc.generic:grandcentral-kamelet-generic:jar:1.0.9-SNAPSHOT, com.backbase.grandcentral:grandcentral-connectors-generic:jar:1.0.11-SNAPSHOT-29: Could not find artifact com.backbase.gc.generic:grandcentral-kamelet-generic:jar:1.0.9-SNAPSHOT -> [Help 1]
quarkus-native [ERROR] 
quarkus-native [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
quarkus-native [ERROR] Re-run Maven using the -X switch to enable full debug logging.
quarkus-native [ERROR] 
quarkus-native [ERROR] For more information about the errors and possible solutions, please read the following articles:
quarkus-native [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

### Camel K version

v2.1.0

**Comment by hernanDatgDev** [comment]
Confirmed same failure in native mode with another private repository hosted by Code Artifact in AWS. Integration works in non-native mode and fails to resolve dependencies in native mode.

**Comment by squakez** [comment]
Yes, I confirm it's a regression. Thanks for reporting. We are trying to use a settings located in `settings.xml` instead of `maven/settings.xml`. I think, as a workaround while the issue is fixed, you can mitigate this by [adding a custom task](https://camel.apache.org/camel-k/2.1.x/pipeline/pipeline.html#add-custom-tasks) and copy the file to the expected location. You may add a custom task like `-t builder.tasks="workaround;alpine;cp maven/settings.xml settings.xml"`. It should work for now.

**Comment by hernanDatgDev** [comment]
Unfortunately the workaround proposed is not working as expected. It seems like the task "workaround" is being executed after the "builder" task and as a result it is failing. The builder task is pulling in all the dependencies and that is when it fails. I was looking for a way to potentially prioritize the custom tasks but I haven't seen any such functionality

**Comment by hernanDatgDev** [comment]
The workaround custom task is working as expected when I run the integration in non-native mode and with build-strategy=pod.

**Comment by hernanDatgDev** [comment]
Seems that the maven/settings file being copied might be incomplete and different to what camel-k was installed with.
maven/settings in builder pod is the following:
```
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <localRepository></localRepository>
  <servers></servers>
  <profiles>
    <profile>
      <id>camel-k</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <repositories>
        <repository>
          <id>central</id>
          <url>https://repo.maven.apache.org/maven2</url>
          <snapshots>
            <enabled>false</enabled>
            <checksumPolicy>fail</checksumPolicy>
          </snapshots>
          <releases>
            <enabled>true</enabled>
            <checksumPolicy>fail</checksumPolicy>
          </releases>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <id>central</id>
          <url>https://repo.maven.apache.org/maven2</url>
          <snapshots>
            <enabled>false</enabled>
            <checksumPolicy>fail</checksumPolicy>
          </snapshots>
          <releases>
            <enabled>true</enabled>
            <checksumPolicy>fail</checksumPolicy>
          </releases>
        </pluginRepository>
      </pluginRepositories>
    </profile>
  </profiles>
  <proxies></proxies>
  <mirrors></mirrors>

  <!-- log ends here; assuming end of file with </settings> -->
  </settings>
```

**Comment by squakez** [comment]
I think this is hiding some more severe problem. I'll have a look asap and try to fix. A more complex workaround is to use the same pipeline to make the settings file on your own with the expected format. I know it could be a little cumbersome, but in the while, I don't have any further suggestion.

**Comment by squakez** [comment]
Okey. I had a deeper look at this comparing the execution of version 2.0. We have the following:
```
camel-k-kit-cl4bpbehoqkc73fkocgg-builder builder {"level":"info","ts":1699265717.6614916,"logger":"camel-k.maven","msg":"executing: ./mvnw -V --no-transfer-progress -Dstyle.color=never package --global-settings /builder/kit-cl4bpbehoqkc73fkocgg/maven/settings.xml --settings /builder/kit-cl4bpbehoqkc73fkocgg/maven/user-settings.xml -Dmaven.artifact.threads=8 -T 8","MAVEN_OPTS":""}
```
where it show the usage of both a `global-settings` and a `user-settings`. We are probably swallowing the latter during the native build. As an immediate workaround you probably needs to execute `-t builder.tasks="workaround;alpine;cp maven/user-settings.xml settings.xml"` to use the custom settings vs the global ones.

**Comment by hernanDatgDev** [comment]
Thank you for your help @squakez, I appreciate it. 
For anyone following this issue, I tweaked the workaround so that the settings are copied in the same `maven` directory to get the expected behavior. The following worked for me in the modeline:
`// camel-k: trait=builder.tasks="copy-settings;alpine;cp maven/user-settings.xml maven/settings.xml"`
Looking forward to future releases 👍
