### ISSUE TITLE
kamel run should support adding dependencies

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#49]
Something like:

    kamel run --dependency something Source.java

Dependency should be provided in the for of a URI like:

    mvn:org.apache.camel/camel-mail/2.20.1
    camel:mail
    file:/path/to/dep.jar?id=my.company:my-dep:version

**Comment by oscerd** [comment]
Since we are using Camel it makes sense to specify the Camel version as flag and then a list of dependencies using that property under the hood.

**Comment by jehanzebqayyum** [comment]
How would you add custom jar dependency? does file:...jar works?
