### ISSUE TITLE
camel-k on Openshift Container Platform 3.11

### ISSUE THREAD

**Issue by marcredhat** [apache/camel-k#493]
I set up camel-k on Openshift Enterprise 3.11.59
Works like a charm (see https://bit.ly/2Nrieca) but some of the steps below were not obvious (to me).
The first step below can be automated. 
The other two steps can be included in the documentation as examples (not for production).

1) stuck at "waiting for platform" until I manually pulled gcr.io/kaniko-project/executor
2) create a local docker registry
docker pull docker.io/registry
docker run --privileged -d -p 5000:5000 --restart=always --name registry_private  registry:latest
3) change to use local registry localhost:5000 instead of the local registry defined in /etc/origin/master/master-config.yaml
 cat /etc/origin/master/master-config.yaml | grep internalRegistry
internalRegistryHostname: docker-registry.default.svc:5000
My quick and dirty solution was to set in /etc/hosts on the master: 127.0.0.1 docker-registry.default.svc  docker-registry.default.svc.cluster.local

Thanks,
Marc Chisinevski

**Comment by nicolaferraro** [comment]
I've not tried it on Openshift Enterprise, but I assume it ships with S2I and a namespaced imagestream registry where S2I pushes images to. So technically you don't need to use kaniko to push and pull images. The builder should configure itself to using the S2I binary strategy. Can you provide your `oc get integrationplatform -o yaml`?

`docker-registry.default.svc` hence should be the name of the Openshift embedded registry iirc (it is so on dev and staging clusters).

**Comment by marcredhat** [comment]
Sure:
oc get integrationplatform -o yaml
apiVersion: v1
items:
- apiVersion: camel.apache.org/v1alpha1
  kind: IntegrationPlatform
  metadata:
    creationTimestamp: 2019-02-24T06:48:29Z
    generation: 2
    labels:
      app: camel-k
    name: camel-k
    namespace: camel
    resourceVersion: "202019"
    selfLink: /apis/camel.apache.org/v1alpha1/namespaces/camel/integrationplatforms/camel-k
    uid: 31bd7c6b-3800-11e9-9a2f-00155d18b803
  spec:
    build:
      baseImage: fabric8/s2i-java:3.0-java8
      camelVersion: ~2.23.x
      localRepository: /tmp/artifacts/m2
      publishStrategy: S2I
    cluster: OpenShift
    profile: OpenShift
    resources: {}
  status:
    phase: Ready
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**Comment by marcredhat** [comment]
This is how I deployed OCP 3.11: https://github.com/marcredhat/openshiftonhyperv/commit/9b4975927366e0fe6e4620eb9244171239740ec7

**Comment by ShravanGeek** [comment]
@marcredhat Hi Marc, I'd like to know the steps how did you perform making Camel-k running on Openshift. I have stucked with "Waiting for Platform". Could you please provide the steps you have implemented to resolve the issue? Thank you.

**Comment by marcredhat** [comment]
1) manually pulled gcr.io/kaniko-project/executor
2) create a local docker registry
docker pull docker.io/registry
docker run --privileged -d -p 5000:5000 --restart=always --name registry_private registry:latest
3) change to use local registry localhost:5000 instead of the local registry defined in /etc/origin/master/master-config.yaml
cat /etc/origin/master/master-config.yaml | grep internalRegistry
internalRegistryHostname: docker-registry.default.svc:5000
My quick and dirty solution was to set in /etc/hosts on the master: 127.0.0.1 docker-registry.default.svc docker-registry.default.svc.cluster.local

Hope this helps,
Marc

**Comment by ShravanGeek** [comment]
Hi @marcredhat I'm not able to find this file "/etc/origin/master/master-config.yaml" in my instance. I have installed openshift 3.11 on Ubuntu 18.04. Could you guide me on how to find that file? or is there any another option available to successfully run the camel-k? Thanks for your time.

**Comment by marcredhat** [comment]
Hi @ShravanGeek, 

You should find it on the master, please see https://docs.openshift.com/container-platform/3.11/install_config/master_node_configuration.html.

Please create a new issue at https://github.com/apache/camel-k/issues.
Feel free to link to this one as you see fit.

Thanks,
Marc
