### ISSUE TITLE
Wildcards in Routes Sources

### ISSUE THREAD

**Issue by MotaOcimar** [apache/camel-k#4941]
### Requirement

As a user seeking simplicity in Camel K Integration configuration,
I want the ability to create Integrations from all files in a directory using a wildcard,
so that I can avoid dealing with a lengthy command line or multiple lines in the kamel-config.yaml file.

### Problem

When we have several source files we end up with a huge command line (or several lines in the kamel-config.yaml file).

For example:

```sh
kamel run --name=my-integration ./routes/file1.xml ./routes/file2.xml ./routes/file3.xml ./routes/file4.xml
```

### Proposal

This could be extremely simplified with a wildcard.

For the example shown previously, we could have the following:

```sh
kamel run --name=my-integration ./routes/*
```

**Comment by squakez** [comment]
Thanks for reporting. Feel free to contribute, it does seem a good first issue case.

**Comment by claudio4j** [comment]
At least in linux when you use the wildcard, bash does the completion expansion and your example actually works.
However I am unsure about wildcard expansion in windows or macos.

**Comment by rinaldodev** [comment]
@squakez @claudio4j can you assign this one to me?

**Comment by squakez** [comment]
Done. Mind that we are under the effort to migrate the CLI to Camel JBang (see https://github.com/apache/camel/pull/12474). However I think it is still a good exercise to get used to the source code and be able to do other contributions. Thanks.
