### ISSUE TITLE
Minimum Kubernetes version

### ISSUE THREAD

**Issue by kameshsampath** [apache/camel-k#495]
Due to a bug with CoreDNS that is shipped for mac and minikube iso ref: https://github.com/knative/serving/issues/3067 its worth updating the documentation for minimum k8s version to be > v1.12.0

**Comment by squakez** [comment]
Maybe we can provide some automation to recover the value we set in [CVS](https://github.com/apache/camel-k/blob/main/config/manifests/bases/camel-k.clusterserviceversion.yaml#L153) in the [compatibility matrix](https://github.com/apache/camel-k/blob/main/docs/modules/ROOT/pages/index.adoc#compatibility-matrix) in documentation.

@astefanutti is that value something we use to update manually? is the value provided there still actual?

**Comment by AghaSaad04** [comment]
Hi, I am interested in resolving this issue. Can anyone assign this to me. 
Moreover, I believe this value will be updating with time. How are we gonna automate this? Will we be fetching it from somewhere and passing to docs? Kindly show some pointers so that I can fix this. Thanks

**Comment by astefanutti** [comment]
The current `minKubeVersion` value from the CSV manifest is not up-to-date. If I remember correctly, it used to be a mandatory field for OperatorHub, but it doesn't seem to be required anymore, and was never updated. So I'd be inclined to removed it from the CSV, and have the supported Kubernetes versions documented in the compatibility matrix.

**Comment by squakez** [comment]
@AghaSaad04 as pointed by @astefanutti , we can remove it from the manifest config file and for the moment include an entry to the documentation which we will have to update manually.
