### ISSUE TITLE
Ability to apply node selectors/affinity configuration

### ISSUE THREAD

**Issue by lsergio** [apache/camel-k#4958]
### Requirement

As I developer, I wish I could apply node selectors and affinity configuration to the builder pod so that I can guarantee that it will or won't run in specific nodes of the cluster.

### Problem

In my specific case, I have karpenter running on the same cluster as camel k to manage nodes, and I don't want builders and integrations to run on the karpenter dedicated node.
So I would block the pods from running in nodes with specific label

### Proposal

We may add the new configuration to the BuilderTrait crd to support such configuration.

**Comment by squakez** [comment]
Makes sense. Feel free to contribute to the feature if you can.
