### ISSUE TITLE
Upgrade to Knative  > v0.3.0

### ISSUE THREAD

**Issue by kameshsampath** [apache/camel-k#497]
As knative v0.4.0 its out, it is better to have the camel-k apis upgraded to use minimum v0.3.0 of Knative API.

It will be nicer if v0.4.0 is done as there some new features introduced such as volume mounts

**Comment by lburgazzoli** [comment]
@nicolaferraro can you have a look at upgrading to knative 0.3.0 ?

**Comment by nicolaferraro** [comment]
Yes, I'll work on it.

**Comment by kameshsampath** [comment]
thanks guys. also it will be great if we can  make CE v0.2 as default
