### ISSUE TITLE
Azure Key Vault Trait: Support Azure Identity as authentication method

### ISSUE THREAD

**Issue by oscerd** [apache/camel-k#4983]
### Requirement

This is a request coming from:https://camel.zulipchat.com/#narrow/stream/257299-camel-k/topic/Azure.20KeyVault.20Authentication.20Using.20Managed.20Identity

### Problem

At this stage we are not supporting the Managed Identity, this means we are not supporting the DefaultAzureCredential chain: https://learn.microsoft.com/en-us/java/api/overview/azure/identity-readme?view=azure-java-stable#defaultazurecredential

### Proposal

Through CAMEL-20220 I added the support for this, but it will be in 4.4.0, so this feature request is a placeholder for the moment when 4.4.0 will be released and camel-k will switch.

**Comment by oscerd** [comment]
We are about to release Camel 4.4.0, so I guess I can start to add the support for this in the trait.

**Comment by squakez** [comment]
Completed by #5244
