### ISSUE TITLE
Quarkus buildMode should sort JVM before Native execution

### ISSUE THREAD

**Issue by lsergio** [apache/camel-k#5001]
### What happened?

I created an Integration and specified that both the jvm and native builds should run:
```
traits:
    quarkus:
      buildMode:
      - native
      - jvm
```
As I understood, as soon as the jvm build is complete, the integration pod should start, and then be replaced when the native build is complete.

However, the integration pod only started after both builds finished.

### Steps to reproduce

1. Create an Integration that specifies both buildModes
2. Wait for the jvm build to finish
3. Check that the integration does not start
4. Wait for native build to finish
5. Check that now it started

### Camel K version

2.1.0 and 2.2.0-nightly

**Comment by squakez** [comment]
I think this could be because of the execution order provided. Try switching order (`jvm`, then `native`) and see if it solves. If that's the case we either need to document this or to add a little tweak to make sure jvm is always coming before native. Please, check if changing the order solves.

**Comment by lsergio** [comment]
@squakez Indeed, switching the order fixed the issue. thanks!

**Comment by squakez** [comment]
I'll keep this open as a future improvement.

**Comment by squakez** [comment]
BTW, feel free to contribute. This one looks quite simple to do.

**Comment by michalvavrik** [comment]
> BTW, feel free to contribute. This one looks quite simple to do.

I'll try if not urgent. Can't do it in a few days.

**Comment by squakez** [comment]
> > BTW, feel free to contribute. This one looks quite simple to do.
> 
> I'll try if not urgent. Can't do it in a few days.

Sure, there's no hurry to have this completed. Let us know if you need any support while developing.
