### ISSUE TITLE
Nightly SBOM procedure should not run if there are no changes

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#5033]
The procedure is running and it recreate a different SBOM every night. Although it does not harm, it makes no sense and the nightly generation of commits pollute the git history with meaningless information.

**Comment by squakez** [comment]
Okey, the problem is that every night we add a new commit, so, the night after it [recalculates the sbom main app version](https://github.com/CycloneDX/cyclonedx-gomod#version-detection). I think that, in order to be consistent, we need to move this process into the release process and make sure that it uses the tag version which has been released.

**Comment by squakez** [comment]
@oscerd what would you say if, instead of committing the SBOM to the project, we publish as a resource along the release artifacts?

**Comment by oscerd** [comment]
For me it's fine. But for having a way of knowing the vulnerabilities status during the development I'd prefer to have a job updating the SBOM on the repository once a week, so we could check if we are vulnerable to something with dependency track or other tools.
