### ISSUE TITLE
Include the operator node-selector in the helm chart

### ISSUE THREAD

**Issue by lsergio** [apache/camel-k#5103]
### Requirement

The kamel cli has the `--node-selector` option, but there's not such an option in the helm template (https://github.com/apache/camel-k/blob/main/helm/camel-k/templates/operator.yaml).
My idea is to add this option to the yaml file.

### Problem

It blocks me from using helm to install Camel K as I'm using then node selector option.

### Proposal

Add the node Selector as optional parameter to the chart template.

**Comment by lsergio** [comment]
I can work on that if approved.

**Comment by aeciopires** [comment]
Hi @lsergio!
Thanks for open this issue. 
It will solve the problem when we want install camel-k in Kubernetes cluster with [Karpenter](https://karpenter.sh/) that have different labels in the nodes.

**Comment by squakez** [comment]
Please, feel free to contribute the change. I'm assigning this to you @lsergio, thanks!
