### ISSUE TITLE
Update github actions to a version that use node 20

### ISSUE THREAD

**Issue by valdar** [apache/camel-k#5130]
As mentioned in a warning when running github actions, some needs to be updated to a version that uses node 20 before it gets removed.

**Comment by gansheer** [comment]
@squakez I'll take care of it, there is probably the setup-go action that was failing and was excluded from upgrades.

**Comment by gansheer** [comment]
Upgrade of release-action tracked here : https://issues.apache.org/jira/browse/INFRA-25547

**Comment by gansheer** [comment]
All actions has been upgraded to node20.
