### ISSUE TITLE
Allow customization of Pipe's pod template via annotations trait.

### ISSUE THREAD

**Issue by eshepelyuk** [apache/camel-k#5136]
### Requirement

Allow customization of Pipe's pod template via annotations trait. For example

* add `initContainer`
* add env variables via Downward API
* etc

Related Zulip conversation:

https://camel.zulipchat.com/#narrow/stream/257299-camel-k/topic/How.20to.20customize.20podTemplate.20of.20a.20Pipe.20via.20trait.20annotation/near/419577461

### Problem

Currently pod template can not be customized for `Pipe` CRD, since `integration: IntegrationSpec` is deprecated.

### Proposal

Allow providing customization YAML template to `Pipe` via annotation trait, to be uniformed with other customizations.

**Comment by squakez** [comment]
Relates #4780
