### ISSUE TITLE
Kamel delete KameletBinding only removes integration resource

### ISSUE THREAD

**Issue by christophd** [apache/camel-k#5156]
### What happened?

The kamel CLI delete command only removes the Integration resource when the target is a KameletBinding. The KameletBinding resource is not removed and as a result it recreates the Integration shortly after the deletion.

### Steps to reproduce

* Create a KameletBinding `test-binding`
* run `kamel delete test-binding`
* See the Integration being removed and recreated shortly after the command

### Camel K version

2.2

**Comment by squakez** [comment]
Is it possible it only affects "Pipe" and related "Integration". We probably need to keep the deletion of KameletBindings while they exists.

**Comment by christophd** [comment]
Yes, the Pipe is working correctly it is not working only for the KameletBinding
