### ISSUE TITLE
Install operator image according to the target architecture

### ISSUE THREAD

**Issue by tdiesler** [apache/camel-k#5169]
On MacOS (M2) ...

```
> minikube start --addons registry
> kamel install --olm=false
Camel K installed in namespace default 

> CAMEL_K_POD=$(kubectl get pods --selector='name=camel-k-operator' --output=jsonpath='{.items[*].metadata.name}')
> kubectl logs $CAMEL_K_POD
exec /usr/local/bin/kamel: exec format error
```

This happens with 2.2.0 and the latest [2.3.0-nightly](https://github.com/apache/camel-k/releases/tag/2.3.0-nightly)

**Comment by tdiesler** [comment]
merci, that worked

**Comment by tdiesler** [comment]
Do we already have an issue about improving 

```
```

**Comment by tdiesler** [comment]
PR: https://github.com/apache/camel-k/pull/5200

**Comment by squakez** [comment]
As mentioned in the PR, we should publish manifests accordingly to solve this issue: https://github.com/apache/camel-k/pull/5200#pullrequestreview-1906815706

**Comment by tdiesler** [comment]
Is a dependency of https://github.com/apache/camel-k/issues/5238

**Comment by tdiesler** [comment]
Done
