### ISSUE TITLE
Mount configmap/secret resources to a dedicated resources.d durectory

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#5181]
### Requirement

As today, resources are mounted in the [conf.d path](https://github.com/apache/camel-k/blob/08582b2397cefdb5249880378cfd0a043248688f/pkg/util/camel/camel_util.go#L36), however it would be better to create a new `resources.d` sub-directory and mount any additional resource.

### Problem

Resources should not be mixed up with configurations

**Comment by squakez** [comment]
@gansheer are you actively work on this or planning to work for next minor delivery?

**Comment by gansheer** [comment]
Planning for next minor.

**Comment by gansheer** [comment]
Im curious about the resources, we have 3 path for them:
* ./resources
* /etc/camel/resources
* /etc/camel/[conf.d -> resources.d]/_resources

Do you know for what each one is used ?

**Comment by squakez** [comment]
> Im curious about the resources, we have 3 path for them:
> 
>     * ./resources
> 
>     * /etc/camel/resources
> 
>     * /etc/camel/[conf.d -> resources.d]/_resources
> 
> 
> Do you know for what each one is used ?

I think the first two are legacy leftover. You may try to temporarily remove them to see if all tests are passing (or fix any legacy test if we want to remove). Later, we'd need to pass to a deprecation notice time to avoid causing disruptions to users that may be mounting directly their volumes on those directories. Finally, in a couple of minor releases we can get rid off them.
