### ISSUE TITLE
Upgrade controller-runtime to latest version

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#5211]
### Requirement

Upgrade controller-runtime to latest version

### Problem

The current controller-runtime version in camel-k is v0.15.2 whereas the latest released version is 0.17.2, we should try stay closed with the releases to reduce the complexity of migration

**Comment by lburgazzoli** [comment]
@valdar ^^

**Comment by gansheer** [comment]
From what I can see:
* v0.16.x relies on Kubernetes 1.28 libraries 
* v0.17.x relies on Kubernetes 1.29 librairies

@squakez @lburgazzoli 
is there something that would prevent us from bumping the Kubernetes API ?

**Comment by lburgazzoli** [comment]
According to the [kubernetes-version-compatibility](https://github.com/kubernetes-sigs/kubebuilder-release-tools/blob/master/VERSIONING.md#kubernetes-version-compatibility), we would support kubernetes from 1.25 to 1.29. As long as that range falls into also the OpenShift supported version e should probably be ok

**Comment by squakez** [comment]
@gansheer FYI, there are a few dependencies which will require attention once we bump to `0.16`. They should be good to upgrade once the ctrl-runtime is updated.
