### ISSUE TITLE
Camelk | AtlasMap Support

### ISSUE THREAD

**Issue by yuvanmytri** [apache/camel-k#5261]
### Requirement

Seems like AtlasMap is no longer listed as supported component on Camel 4.x, Is there anything changed with AtlasMap as a roadmap for Camelk and data mapping?
https://github.com/KaotoIO/kaoto-next/issues/961
https://camel.apache.org/components/3.22.x/atlasmap-component.html

### Problem

Seems like AtlasMap is no longer listed as supported component on Camel 4.x, Is there anything changed with AtlasMap as a roadmap for Camelk and data mapping?
https://github.com/KaotoIO/kaoto-next/issues/961
https://camel.apache.org/components/3.22.x/atlasmap-component.html

### Open questions

Seems like AtlasMap is no longer listed as supported component on Camel 4.x, Is there anything changed with AtlasMap as a roadmap for Camelk and data mapping?
https://github.com/KaotoIO/kaoto-next/issues/961
https://camel.apache.org/components/3.22.x/atlasmap-component.html

**Comment by oscerd** [comment]
Atlasmap is not a supported component in Camel 4.x because it has been discontinued. The last release if from October 2022. https://github.com/atlasmap/atlasmap/tags
