### ISSUE TITLE
OS platform not considered during "make build"

### ISSUE THREAD

**Issue by christophd** [apache/camel-k#5288]
### What happened?

The Makefile `make build` used to build kamel CLI binaries for the individual platform (e.g. linux/amd64 vs. darwin/amd64). The process was to build the linux platform binary statically for the Docker image and at the same time build a platform specific binary for execution on the host machine (e.g. darwin).

This process has been changed so currently `make build` only statically builds the linux binary, which is good for the Docker image but insufficient for the host to run the kamel CLI binary during development when the platform is other than linux. 

Developers running on platforms other than linux would need to cross compile and manually add the platform specific binary to the host PATH for local development.

### Steps to reproduce

1. run `make build` on host other than linux
2. run any kamel CLI command on the resulting kamel binary (e.g. `kamel version`)
3. built kamel binary is not runnable on platforms other than linux

**Comment by tdiesler** [comment]
Yes, indeed that is the case. I currently do `make images && go build ./cmd/kamel`
