### ISSUE TITLE
Flaky TestOperatorBasic

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#5326]
```
❌ TestOperatorBasic (25.76s)
...
      operator_test.go:80: 
          Expected
              <string>: 
          to equal
              <string>: kind-registry:5000
```
Seen several time already. Last time in https://github.com/apache/camel-k/actions/runs/8566597132/job/23476649796

**Comment by oscerd** [comment]
Please don't use downstream issues in upstream.

**Comment by christophd** [comment]
This is a racing condition on a slow performing e2e test environment. The test complains about empty registry address assertion but in the following namespace dump I can see the IntegrationPlatform printed and the registry address is set to the expected value already.

I suppose to use an `Eventually` assertion that waits some time for the registry address to be set properly and only fails after a timeout when the condition is not met.
