### ISSUE TITLE
Add docker image creation date

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#5385]
The images the operator creates are created without a date:
```
$ docker inspect 69cdd648323b
[
...
        "RepoDigests": [
            "10.103.186.147/default/camel-k-kit-cogif7of9h2c73aouqu0@sha256:95a9182e20446cc6b8ea387365348bf7e9712a95bc59d848263e3b9e7d82366f"
        ],
...
        "Created": "1970-01-01T00:00:00Z",
```
 This is not a strong requirement, but I think that, in order to have a better image management and a clear audit when the images where really created, we should add the real creation date.

**Comment by squakez** [comment]
Related to #3645 - if any development, we can bundle it together.

**Comment by claudio4j** [comment]
The 1970 date is [intentional for reproducibility reasons](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#why-is-my-image-created-48-years-ago). It may be investigated if setting the date may interfere with the container build cache.

**Comment by squakez** [comment]
> The 1970 date is [intentional for reproducibility reasons](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#why-is-my-image-created-48-years-ago). It may be investigated if setting the date may interfere with the container build cache.

I think in our case we don't need to care of this kind of container reproducibility. I mean, we already reuse a container that present the same characteristics, so, whenever we build we'd always do it from scratch with a brand new container (which always changes the name and digest anyway). Layering caching should not be affected if we introduce this change.

**Comment by lburgazzoli** [comment]
We could add those information as a label but I would really recommend not to change this in particular given the fact that we are moving to the direction to delegate the build part to external entities as much as possible so we should reduce camel-k specific behavior.
