### ISSUE TITLE
Expand Integration pod template spec

### ISSUE THREAD

**Issue by hernanDatgDev** [apache/camel-k#5395]
### Requirement

We have security requirements for production deployments that require modifications the integration pods/containers. For example, being able to configure `automountServiceAccountToken` to the deployed integration pod. Currently this is the only field that we cannot configure, however we expect more to come in the future as our requirements evolve.

Zulip thread:
https://camel.zulipchat.com/#narrow/stream/257299-camel-k/topic/Integration.20PodTemplate.20uses.20custom.20PodSpec

### Problem

Currently the framework is using a [custom PodSpec](https://camel.apache.org/camel-k/2.2.x/apis/camel-k.html#_camel_apache_org_v1_PodSpec) which is a subset of the official Kubernetes [PodSpec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#podspec-v1-core). Many fields are simply not available, for example `automountServiceAccountToken` and there isn't any other way to configure this field from within the framework.

### Proposal

Configure more fields from the Kubernetes PodSpec and add them to the subset PodSpec that camel-k is using. Ideally the whole K8 PodSpec would be available for maximum customization. If not, perhaps we could streamline the process for adding additional fields to the PodSpec as the requirements come up.

**Comment by squakez** [comment]
Thanks for reporting. Please, let us know if you're planning to work on this by any chance.

**Comment by hernanDatgDev** [comment]
Hi @squakez I created a draft PR for this: https://github.com/apache/camel-k/pull/5445
I had a question on how I edited one of the files regarding `protobuf`. It's in the PR
