### ISSUE TITLE
Release 0.3.1

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#540]
We should release version 03.1 which includes the following fix/enhancements:

- label propagation 82c1a87f23ef035b44db28d4617301289f1e3a12
- ordered delete 2a9584dfa5a88580abe296ef8bead393dd84cf9a
- support for incremental builds when using kaniko 7bd061dec315bd98f017eeb794787bbe05933dc6
- support for probes (liveness, readiness)

TODO:

- [x] update runtime to 0.3.1

**Comment by nicolaferraro** [comment]
Doing some tests and starting the release...

**Comment by lburgazzoli** [comment]
https://github.com/apache/camel-k/releases/tag/0.3.1
