### ISSUE TITLE
Missing license header files

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#5433]
```
file ./e2e/advanced/files/deploy.yaml does not contain license
file ./.github/workflows/comment-pr.yaml does not contain license
```

**Comment by gansheer** [comment]
How did you find these ? I used the check_licenses.sh script and it did not see these files.

**Comment by squakez** [comment]
> How did you find these ? I ran the check_licenses.sh script and it did not see these files.

During release process. I think it is the same script, but not sure 100%.

**Comment by gansheer** [comment]
Ok, I found my issue, I have some temp files not without license so it block the full code scan.
