### ISSUE TITLE
Remove health readiness workaround when fixed in Camel

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#5451]
The behavior was temporarily fixed in https://github.com/apache/camel-k/pull/5450

However, the properties must be removed when https://issues.apache.org/jira/browse/CAMEL-20244 and we default to the Camel version that has this fixed.

**Comment by gansheer** [comment]
Could this issue have been fixed by https://github.com/apache/camel-k/commit/5ceed9d0fbdbad486117b6318adc8a1797580aaa ?

**Comment by squakez** [comment]
Good catch, yes.
