### ISSUE TITLE
Review CI setup and test executions scrips/make targets

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#5463]
### Requirement

Make it easy to run e2e tests locally

### Problem

As today, a lot CI/testing logic and indirection is hidden in the` .github/workflows` and `.github/actions` which make testing and developing quite confusing. 

Ideally, it should be possible to easily run almost all the tests executed from the CI locally with minimal configuration.
I would suggest that we wrap all the e2e tests and related setup as `Makefile` targets

i.e. once checked out, a developer should be able to do something like:

```
make setup/knative
make test/e2e/knative
```

The same should happen in the CI pipeline instead of having everything wrapped as an action.

**Comment by squakez** [comment]
We already have a structure of tests grouped and executable by kind: https://camel.apache.org/camel-k/2.3.x/contributing/e2e.html#testing-e2e-structure - what we miss is the automation to install Knative, Telemetry or OLM configuration. However if the user has them installed, the test execution should go through correctly.

**Comment by lburgazzoli** [comment]
I saw that, but as stated by the document,  they may not work out of the box and the` .github/actions` is IMHO, quite a mess, so I'd love to see something simpler and that works with minimal setup.

**Comment by squakez** [comment]
Happy to receive contributions, thanks!

**Comment by squakez** [comment]
Just mind that you'd need to take in consideration the situation where, as a user, you already have Knative installed, as a second installation may mess up your local setup.

**Comment by tdiesler** [comment]
PR: https://github.com/apache/camel-k/pull/5573

**Comment by tdiesler** [comment]
There are now setup scripts for [knative](https://github.com/apache/camel-k/blob/main/e2e/knative/files/setup.sh) and [yaks](https://github.com/apache/camel-k/blob/main/e2e/yaks/files/setup.sh). Anything else?

**Comment by tdiesler** [comment]
You can now do ...

```
./e2e/knative/files/setup.sh
./e2e/yaks/files/setup.sh
```

If there is nothing else, this can be closed.

**Comment by tdiesler** [comment]
PR: https://github.com/apache/camel-k/pull/5661
