### ISSUE TITLE
Investigste TestRunIncrementalBuildRoutine flakiness

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#5485]
### What happened?

The `TestRunIncrementalBuildRoutine` sometimes fails with no clear explanation

### Steps to reproduce

Seen latest time in https://github.com/apache/camel-k/actions/runs/9008778242/job/24765909747?pr=5480

### Relevant log output

```shell
❌ TestRunIncrementalBuildRoutine (10m24.24s)
      incremental_build_test.go:55: 
          Timed out after 300.000s.
          Expected
              <string>: kind-registry:5000/test-0c69be85-3121-48a6-9228-5e055a1f5b24/camel-k-kit-cou7vd3ia7ns738hnbl0@sha256:ef37351cef1b88365a6c1e9399fa028d03a763ade86ff06d609068552bd5697e
          to equal
              <string>: eclipse-temurin:17
```
```


### Camel K version

_No response_

**Comment by squakez** [comment]
As you're tracking these kind of failures as well, please, link the action so it is easier to follow it up and get the log dump for a more clear analysis. Thanks!

**Comment by valdar** [comment]
This might be fixed by https://github.com/apache/camel-k/pull/5494
