### ISSUE TITLE
Align the Hashicorp Vault Add-on to CAMEL-20775

### ISSUE THREAD

**Issue by oscerd** [apache/camel-k#5527]
### Requirement

https://issues.apache.org/jira/browse/CAMEL-20775

We need to remove the engine property, since it's not used anymore.

### Problem

We need to remove the engine property, since it's not used anymore.

### Proposal

Align once we support Camel 4.7.0

**Comment by squakez** [comment]
We need to do the change in a backward compatible way. Remind that, although the parameter may not be longer used after Camel 4.7.0, the operator can still run previous runtimes version which are making use of that parameter. I think the best approach is to deprecated and eventually remove when we bump to a major Kubernetes API upgrade.

**Comment by squakez** [comment]
Vaults are deprecated in favor of plain Camel configuration.
