### ISSUE TITLE
Inject CamelContext into Java DSL RouteBuilder

### ISSUE THREAD

**Issue by jcordes73** [apache/camel-k#563]
For configuring components (f.e. JMS) manipulating the CamelContext could be handy. Right now it seems that the CamelContext is not available in the RouteBuilder when using the Java DSL.

**Comment by lburgazzoli** [comment]
hi @jcordes73 I had a look at the code and the context is actually set to the RouteBuilder so can you give more information about the runtime version you are testing against and if possible an example that shows the misbehaviour ?

**Comment by davsclaus** [comment]
Yeah it should be there as `context()` method in the `RouteBuilder` class from its `configure` method.

**Comment by hguerrero** [comment]
@davsclaus @lburgazzoli can you add an example of how to configure the context with a connection factory using Java DSL?

**Comment by lburgazzoli** [comment]
@jcordes73 can we close this one ?

**Comment by lburgazzoli** [comment]
@hguerrero I think you did it https://github.com/apache/camel-k/blob/master/examples/AMQPBindToRegistry.java
