### ISSUE TITLE
Add support for mounting volumes with mount trait

### ISSUE THREAD

**Issue by hernanDatgDev** [apache/camel-k#5654]
### Requirement

As a developer I want a way to add volume references to my integrations and also use the mount trait to mount configmaps/secrets. Currently this is not possible without interfering with the mount trait.

### Problem

The pod template can be used to add volume references to an integration however this overrides any volumes/mounts that are set with the mount trait. This leaves a situation where a configmap can be mounted through the mount trait, a pod template can define an `emptyDir` volume and only the `emptyDir` from the template will actually propagate to the integration pod resulting in failures.

### Proposal

A suggestion from [Zulip](https://camel.zulipchat.com/#narrow/stream/257299-camel-k/topic/pod.20template.20volume.20overrides.20mount.20trait/near/444404000) is to enhance the mount trait to allow for volume support in addition to the existing persistent-volume-claim support.

**Comment by mdebarros** [comment]
Hi @squakez,

Do you have a target release for this feature?

This feature is currently needed to enabled several Sourceless capabilities:
1. Security hardening to support `readOnlyRootFilesystem=false`, based on this discussion --> https://camel.zulipchat.com/#narrow/stream/257299-camel-k/topic/pod.20template.20volume.20overrides.20mount.20trait/near/444404000
2. This would also enable some other use-cases where we want to use init-containers to inject jvmAgents, such as Jolokia.

It would be awesome if we could target this to be part of 2.4.0.

Kind Regards,
Miguel

**Comment by hernanDatgDev** [comment]
Hey @squakez I started work on this and have basically added a case for the emptyDir volume in `pkg/trait/trait_types.go getVolume()` alongside the other types: configmap, secret, and pvc
I'm in the process of creating a PR but want to get some feedback if this is the expected approach for adding the volume support.

**Comment by gansheer** [comment]
Hi @hernanDatgDev, thank you for taking care of it! Don't hesitate to submit a PR even if you are still working on it.

**Comment by hernanDatgDev** [comment]
@gansheer Thanks for the heads up. Just created a PR with some comments: https://github.com/apache/camel-k/pull/5709
I did run into what I believe is a bug with the `kamel promote` command. Will be creating a ticket for it.
