### ISSUE TITLE
Jolokia trait failure

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#5666]
I've started to see this recently:
```
❌ TestHealthTrait (0s)
❌ TestHealthTrait/Readiness_condition_with_stopped_route_scaled (0s)
...
❌ TestJolokiaTrait (0s)
❌ TestJolokiaTrait/Run_Java_with_Jolokia (0s)
```
This seems to be because jolokia agent is not properly started. For some reason, the dependency has started failing suddenly and was never detected previously by tests.

**Comment by squakez** [comment]
The error we're getting is the following one:
```
jolokia integration I> No access restrictor found, access to any MBean is allowed
jolokia integration Could not start Jolokia agent: java.lang.IllegalStateException: Cannot load service org.jolokia.service.serializer.JolokiaSerializer,10 defined in jar:file:/deployments/dependencies/lib/main/org.jolokia.jolokia-agent-jvm-2.0.2-javaagent.jar!/META-INF/jolokia/services-default : java.lang.IllegalArgumentException: Can not instantiate org.jolokia.service.serializer.JolokiaSerializer: java.lang.reflect.InvocationTargetException. Aborting
```
The strange thing is that this started out of the blue, without apparently any change on our side. @tadayosi do you have any clue what could be the root cause by any chance?

**Comment by squakez** [comment]
The problem is some kind of classpath issue, as it seems we must include the agent in the classpath by specifying it explicitly. Running the application with these parameters is working:
```
    - -javaagent:dependencies/lib/main/org.jolokia.jolokia-agent-jvm-2.0.2-javaagent.jar=discoveryEnabled=false,host=*,port=8778
    - -cp
    - ./resources:/etc/camel/application.properties:/etc/camel/resources:/etc/camel/resources.d/_configmaps:/etc/camel/resources.d/_secrets:/etc/camel/sources/camel-k-embedded-flow.yaml:dependencies/lib/main/org.jolokia.jolokia-agent-jvm-2.0.2-javaagent.jar:dependencies/*:dependencies/app/*:dependencies/lib/boot/*:dependencies/lib/main/*:dependencies/quarkus/*
    - io.quarkus.bootstrap.runner.QuarkusEntryPoint
```
We can certainly workaround that. However, it is still unanswered why this problems happened from one moment to another. I thought it may be some change in the jdk base docker image, but, trying the application with some older image is having the same effect.

**Comment by tadayosi** [comment]
Hmm, not sure. Could it be related to this issue?
- https://github.com/quarkusio/quarkus/issues/39022

**Comment by squakez** [comment]
> Hmm, not sure. Could it be related to this issue?
> 
>     * [`JAVA_APP_DIR` should be set for container images quarkusio/quarkus#39022](https://github.com/quarkusio/quarkus/issues/39022)

Thanks for looking. No, it seems a different kind of problem. More something directly related to Java and classpaths probably.

**Comment by tadayosi** [comment]
I wonder if this issue can be reproduced locally with the same set of exec parameters.

**Comment by squakez** [comment]
It can be reproduced. The non working classpath is:
```
    - ./resources:/etc/camel/application.properties:/etc/camel/resources:/etc/camel/resources.d/_configmaps:/etc/camel/resources.d/_secrets:/etc/camel/sources/camel-k-embedded-flow.yaml:dependencies/lib/main/org.jolokia.jolokia-agent-jvm-2.0.2-javaagent.jar:dependencies/*:dependencies/app/*:dependencies/lib/boot/*:dependencies/lib/main/*:dependencies/quarkus/*
 ```
 and the working one requires the jolokia agent to be specified:
 ```
     - ./resources:/etc/camel/application.properties:/etc/camel/resources:/etc/camel/resources.d/_configmaps:/etc/camel/resources.d/_secrets:/etc/camel/sources/camel-k-embedded-flow.yaml:dependencies/*:dependencies/app/*:dependencies/lib/boot/*:dependencies/lib/main/*:dependencies/quarkus/*
```
what is strange is that the second classpath was working until a couple of days ago. The only thing that may have changed without our control is the base JDK image.

**Comment by squakez** [comment]
Another way to have this working is adding:
```
- -Xbootclasspath/a:"dependencies/lib/main/org.jolokia.jolokia-agent-jvm-2.0.2-javaagent.jar"
```
I think the root problem may be solved by adding the boot-classpath to the manifest: 
> Boot-Class-Path
    A list of paths to be searched by the bootstrap class loader. Paths represent directories or libraries (commonly referred to as JAR or zip libraries on many platforms). These paths are searched by the bootstrap class loader after the platform specific mechanisms of locating a class have failed. Paths are searched in the order listed. Paths in the list are separated by one or more spaces. A path takes the syntax of the path component of a hierarchical URI. The path is absolute if it begins with a slash character ('/'), otherwise it is relative. A relative path is resolved against the absolute path of the agent JAR file. Malformed and non-existent paths are ignored. When an agent is started sometime after the VM has started then paths that do not represent a JAR file are ignored. This attribute is optional. 
    
Extract taken from: https://docs.oracle.com/javase%2F9%2Fdocs%2Fapi%2F%2F/java/lang/instrument/package-summary.html
