### ISSUE TITLE
OpenAPI & Telemetry traits skipped for sourceless

### ISSUE THREAD

**Issue by hernanDatgDev** [apache/camel-k#5680]
### What happened?

OpenAPI & Telemetry traits are not applied as expected when using sourceless integrations. This is believed to be a regression after a [previous patch](https://github.com/apache/camel-k/pull/5524). The following are 2 scenarios describing use of these two traits with sourceless integrations as well as the versions of camel-k that were used for testing.

**Scenario 1**:

Run a sourceless integration with openApi and telemetry traits.
An [application.properties](http://application.properties/) file is created with relevant openAPI and telemetry fields
File is mounted in the pod
Works as expected in v2.2.0 and v2.3.0
Fails in v2.3.2, v2.3.3, v2.4.0-SNAPSHOT:
[application.properties](http://application.properties/) is mounted but only has openAPI fields, not the telemetry fields.

**Scenario 2**: (sourceless image refactored to include openAPI spec and openAPI trait not needed)

Run a sourceless integration with telemetry trait, not the openAPI trait
An [application.properties](http://application.properties/) file is created with relevant Telemetry fields
File is mounted in the pod
Works as expected in v2.2.0 and v2.3.0
Fails in v2.3.2, v2.3.3, v2.4.0-SNAPSHOT:
[application.properties](http://application.properties/) includes relevant Telemetry fields but is not mounted

### Steps to reproduce

Described above ^

### Camel K version

2.2.x, 2.3.x, 2.4.0-SNAPSHOT

**Comment by hernanDatgDev** [comment]
Originally posted in Zulip: https://camel.zulipchat.com/#narrow/stream/257299-camel-k/topic/application.2Eproperties.20conflict.20with.20Telemetry.20trait

**Comment by squakez** [comment]
Thanks for reporting. Feel free to have a look if you can. We are tentatively going to add this before releasing 2.4 at the end of the month. Thanks.

**Comment by mdebarros** [comment]
There is also a 3rd issue here...

**Scenario 3. When enabling both Telemetry and OpenAPI traits simultaneously.**
The application.properties only contains the OpenAPI properties, meaning that the Telemetry properties are being dropped and not merged into the final application.properties. However, the application.properties are correctly mounted into the Integration pod.

**Comment by hernanDatgDev** [comment]
@gansheer I took a look at this and it seems that the `isForcefullyEnabled()` approach from https://github.com/apache/camel-k/pull/5524 also works when applied to the Telemetry trait. I was wondering if this approach might be good enough to apply to other traits that also use an `auto` feature.

**Comment by hernanDatgDev** [comment]
Also it turns out that this regression doesn't actually have anything to do with the openApi trait and it's just a regression of the telemetry trait. When using the telemetry trait w/ a sourceless integration:
The camel catalog is available until the integration reaches the `deploying` stage, after which the catalog from the environment variable is `nil`. Because of this, down the road the `application.properties` that had previously been configured with telemetry fields is overwritten, essentially removing the fields. The configmap (with telemetry removed) is then mounted into the pod without telemetry configuration which is not desired.
