### ISSUE TITLE
Camel ftp issue in writing file

### ISSUE THREAD

**Issue by Rizzid761** [apache/camel-k#5682]
### What happened?

Iam facing issue in camel ftp it is able to connect but while writing file .it is throwing  error writing failed , connection closed . With same cred .net application is able to write 

Please note : tried with passsivemode  true.

### Camel K version

2.32

**Comment by squakez** [comment]
Thanks for reporting. Can you please provide a sample of the failing application? also it would be good to have some log to troubleshoot.

**Comment by squakez** [comment]
Assuming you're trying to execute something like in the issue #620 - I've tried the following:
```
import org.apache.camel.builder.RouteBuilder;

public class Test extends RouteBuilder {
    @Override
    public void configure() throws Exception {
        from("timer:poll?period=10s")
        .setBody().constant("FTP Test")
        .to("ftps://admin@localhost:2222/public/camel?username=my@user.com&password=admin&fileName=foo.bar&transferLoggingLevel=DEBUG&transferLoggingIntervalSeconds=1&transferLoggingVerbose=false&passiveMode=true")
        .to("log:info");
    }
}
```
This one seems to work correctly. Could you please try it (changing the credentials and the ftp server host) and provide here the error you get? Thanks.

**Comment by Rizzid761** [comment]
Thank you , Yes but Im trying with camel xml dsi.i could see the file in directory but its 0 kb 
In logs details like
Connected to server 
About to store file 
Ftp returned false 
Writing file failed

**Comment by squakez** [comment]
Okey. I bet it's some permission issue then. Make sure the user has the right privileges to write files on such a folder. As you are correctly connecting to the server, it does not seem related directly to Camel K.

**Comment by Rizzid761** [comment]
but in .net application  with same credentials  its working fine
