### ISSUE TITLE
Nightly github action workflows failure

### ISSUE THREAD

**Issue by gansheer** [apache/camel-k#5696]
### What happened?

The github action workflows `Nightly check against latest runtime` and `Nightly release` have been failing for at least 2 weeks.

### Camel K version

main

**Comment by squakez** [comment]
I think this is now solved, right @gansheer?

**Comment by gansheer** [comment]
More or less, I did some workaround, but the fact remains that there is some serious issue with how we manage the parallelism.

**Comment by squakez** [comment]
I guess it's a matter of finding the right tuning with the resources we have available in GH actions.
