### ISSUE TITLE
kamel run runtime/examples/Sample.java fails with java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by dmvolod** [apache/camel-k#57]
Exception in thread "main" org.joor.ReflectException: java.lang.reflect.InvocationTargetException
--
  | at org.joor.Reflect.on(Reflect.java:781)
  | at org.joor.Reflect.call(Reflect.java:463)
  | at org.joor.Compile.compile(Compile.java:73)
  | at org.joor.Reflect.compile(Reflect.java:77)
  | at org.apache.camel.k.jvm.RoutesLoaders$2.load(RoutesLoaders.java:90)
  | at org.apache.camel.k.jvm.Application.main(Application.java:34)
  | Caused by: java.lang.reflect.InvocationTargetException
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.joor.Reflect.on(Reflect.java:777)
  | ... 5 more
  | Caused by: java.lang.NoClassDefFoundError: etc/camel/Sample (wrong name: Sample)
  | at java.lang.ClassLoader.defineClass1(Native Method)
  | at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  | at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
  | ... 10 more

**Comment by nicolaferraro** [comment]
Same here. @lburgazzoli wdyt?

**Comment by lburgazzoli** [comment]
I need to check how the things are compiled now, can you try to set the class package as `etc.camel` ?

**Comment by dmvolod** [comment]
@lburgazzoli I tried with package and it's working fine, but don't know why this default package?

**Comment by lburgazzoli** [comment]
It is because I've changed how the integration is given to the runtime images: before it was included as a resource, now it is on the file system and the class name is computed from the path, I need to re-think how this is computed, maybe using an env var to tell the image the base path for integrations.

**Comment by oscerd** [comment]
This seems to be fixed.

**Comment by nicolaferraro** [comment]
Still happening...
