### ISSUE TITLE
Provide Helm Artefacts as part of snapshots, pre-releases and final-releases

### ISSUE THREAD

**Issue by mdebarros** [apache/camel-k#5740]
### Requirement

As a `Tester` I want to have `packaged Helm Charts as part of daily-snapshot-releases, pre-releases and final-releases` so that `I can test the Camel-K Operator installed via Helm`

### Problem

Helm charts are only published on final releases.

To be able to test daily-snapshot-releases, and pre-releases using Helm installations - one must manually pull the associated "tag" from Github and build the Helm Chart, and override the image on the Helm `values.yaml`. When testing with this approach using IaC, it is also necessary to manually publish the Helm Chart to an intermediate Helm repo. 

The Helm Chart should instead be made available as part of the release process, similar to a Docker Image.

#### Summary

Publish a Helm Chart whenever a Docker Image is published.

#### Suggested approach:

1. As part of all daily-snapshot-releases, pre-releases and final-releases, Helm Charts should be published to the applicable Helm repository (i.e. https://apache.github.io/camel-k/charts) whenever a Docker image is published to either official or test Docker repositories (i.e. https://hub.docker.com/r/camelk/camel-k/tags or https://hub.docker.com/r/testcamelk/camel-k/tags). 

2. Utilise Helm's support for "[development versions](https://helm.sh/docs/helm/helm_install/#:~:text=%2D%2Ddevel%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20use%20development%20versions%2C%20too.%20Equivalent%20to%20version%20%27%3E0.0.0%2D0%27.%20If%20%2D%2Dversion%20is%20set%2C%20this%20is%20ignored)" for daily-snapshot-releases:

```
      --devel                                      use development versions, too. Equivalent to version '>0.0.0-0'. If --version is set, this is ignored

```

3. All Github releases (inc daily-snapshots, pre, and final releases) should include the packaged Helm Chart as part of the attached artefacts.

4. Candidate releases are currently released as a tag on Github, but I propose that they should similarly be created as a Github release marked as a `pre-release`. Upon official release this should instead be removed, and marked as `latest` instead.

**Comment by squakez** [comment]
This is partially completed. The nightly now offers all the artifacts required to install, see https://github.com/apache/camel-k/releases/tag/v2.5.0-nightly
