### ISSUE TITLE
Camel runtime 3.13.0 nightly failure

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#5746]
Something changed in the runtime that has to be fixed:
```

❌ TestKameletTrait (3m24.25s)
❌ TestKameletTrait/discover_kamelet_capabilities (3m17.19s)
❌ TestMasterTrait (4m25.03s)
❌ TestMasterTrait/master_works (4m17.97s)
```
Seen in https://github.com/apache/camel-k/actions/runs/10241694963/job/28330359066#step:4:3608

**Comment by claudio4j** [comment]
I noticed
```
Unrecognized configuration key "quarkus.camel.cluster.kubernetes.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo

```
probably due to https://github.com/apache/camel-quarkus/pull/5922

**Comment by gansheer** [comment]
I am progressing on the fix. One thing I am wondering about : with this fix https://github.com/apache/camel-quarkus/issues/5739 is there any point to the MasterContextCustomizer.java code from camel-k-runtime ?

**Comment by squakez** [comment]
> I am progressing on the fix. One thing I am wondering about : with this fix [apache/camel-quarkus#5739](https://github.com/apache/camel-quarkus/issues/5739) is there any point to the `MasterContextCustomizer.java` code from camel-k-runtime ?

I don't think it is any longer used within the latest changes we did on Camel K side.

**Comment by gansheer** [comment]
They are still some "customize" versions in the code (except if I am missing something): https://github.com/apache/camel-k/blob/20b7dcf9b2b45d99bd8ab7144cb94a7e268b6ea9/addons/master/master.go#L178-L201

**Comment by gansheer** [comment]
Yes, I'm on it don't worry. I was expecting it to still fail.
