### ISSUE TITLE
Add ingressClassName field to Ingress trait

### ISSUE THREAD

**Issue by lsergio** [apache/camel-k#5793]
### Requirement

The [Ingress spec](https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressSpec) has the ingressClassName field which is a replacement for the [deprecated](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation) `kubernetes.io/ingress.class` annotation.
I think it might be interesting to add the ingressClassName field to the Ingress trait to be compatible with the recommended way of defining the class name.

### Problem

It doesn't really block me from creating the Ingress. It will be a problem if the deprecated annotation someday becomes unsupported.

### Proposal

Just add the field to the Ingress trait as a non-required information and copy it to the corresponding Ingress attribute.

**Comment by lsergio** [comment]
I can work on that if it's a good idea.

**Comment by squakez** [comment]
Yeah thanks, it would be great.
