### ISSUE TITLE
Add health checks and additional monitoring

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#58]
If we postpone the compilation of the source file after the image build, we may not be able to detect failures such as compilation errors.
We should improve the monitoring phase to detect cases where the pod is failing and also add health checks to the runtime, so that we can detect when the pod is completely ready.

**Comment by lburgazzoli** [comment]
liveness and readiness probes can now be set-up, we need to add checks to the routes and context

**Comment by WillemJiang** [comment]
With the help of unit test, we could do some basic check of routes and context.  But how can we verify if the camel route fits for the whole system? Can we run the accept test in this case?

**Comment by lburgazzoli** [comment]
@nicolaferraro I guess we can close this one as we can use yaks for testing and we do have support for health checks
