### ISSUE TITLE
Integration logging configuration

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#580]
We could add a trait that enables to configure logging for integration, e.g. format, level. It should ideally be agnostic from the logging backend and the integration runtime.

**Comment by davsclaus** [comment]
Yeah lets get this into 1.1. For centralized logging (such as FluentD, ES and Kibana) then we may need to output in a format that it can import such as json.

**Comment by astefanutti** [comment]
Yes, we need to have an option for structured logging.

**Comment by lburgazzoli** [comment]
I guess this is a good candidate when moving to quarkus as default runtime

**Comment by viacheslav-fomin-main** [comment]
Hello! Is there a way to use a custom logging appender and stuff? I have my own logback.xml file which I would like to use for camel k integration.

**Comment by lburgazzoli** [comment]
No, the logging engine is now the one provided by quarkus, see https://quarkus.io/guides/logging

**Comment by viacheslav-fomin-main** [comment]
<img width="621" alt="image" src="https://user-images.githubusercontent.com/18006133/115591357-af25ea80-a2da-11eb-9979-e87acf94b171.png">

The url says it supports SLF4J. How can I configure it? I want to add the xml configuration file.

**Comment by lburgazzoli** [comment]
it supports SLF4J APIs but the configuration happens through properties as described int he logging guide (at least that is my understanding)

**Comment by viacheslav-fomin-main** [comment]
@lburgazzoli thanks for the clarification! I want to try https://github.com/quarkiverse/quarkus-logging-json and its custom log handler. I am not sure how to use CDI to inject JsonProvider.. Does not seem to work for me.. Can you please advise?

**Comment by lburgazzoli** [comment]
In such case you need to bring the handler as part of a custom artifact as camel-k does not expose CDI facilities (at least for now). Be aware that you need to index the artifact using Jandex or add a beans.xml to get quarkus be able to find your handler.

**Comment by orpiske** [comment]
I'm looking at this.

**Comment by orpiske** [comment]
These PRs mentioned throughout this discussion have added the support for the logging trait. As discussed w/ @astefanutti, now that the documentation is in place, we can close this.
