### ISSUE TITLE
camel-k-operator ready for running integration when camel-k-* builds are still fails

### ISSUE THREAD

**Issue by dmvolod** [apache/camel-k#582]
Hi!

The situation are very simple, for example one or more builds can not be run with Complete state and fails during different problems. It can be docker or maven repo unavailable, internal or external docker repo for OpenShift are not ready, or anything else.
But camel-k-operator not signalling about the problems and not logging errors info and ready for integration running.
What do you think about catch this situation or this is in the roadmap already?

**Comment by lburgazzoli** [comment]
As today it should move the context and the integration first to "build failure recovery" and then to "Error" state, it should also log something but maybe it is not so clear.

**Comment by nicolaferraro** [comment]
> As today it should move the context and the integration first to "build failure recovery" and then to "Error" state, it should also log something but maybe it is not so clear.

It means it tries twice to build the context, then stops?

**Comment by lburgazzoli** [comment]
At the moment it is hard-coded but it tries five times with back-off then it stops

**Comment by dmvolod** [comment]
Thanks for feedback.
I will provide screens shortly.
My situation is not so ordinal, but can be in any env and diagnosis is not so easy.

**Comment by dmvolod** [comment]
Thanks for feedback.
I will provide screens shortly.
My situation is not so ordinal, but can be in any env and diagnosis is not so easy.
