### ISSUE TITLE
on-premises: mount rwx volume

### ISSUE THREAD

**Issue by Scisci75** [apache/camel-k#587]
Hi, on-premises cluster is it possible, when we start a job, mount a rwx volume as input for a route with file2 component? we have nfs/cifs share were users puts files and some camel route split/enrichment and save on db.
Thanks Mirko

**Comment by nicolaferraro** [comment]
That makes sense and allows using the file component in the cloud.

**Comment by nicolaferraro** [comment]
We can use a docker-like syntax for it. E.g.

```
kamel run -v pvname:/container/path integration.groovy
```

@Scisci75 do you want to try adding this feature? That's a nice first issue for newcomers :smile:

**Comment by jamesnetherton** [comment]
I can take a look at this if nobody else is working on it
