### ISSUE TITLE
Support new Camel 3 webhooks

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#597]
Camel part: https://issues.apache.org/jira/browse/CAMEL-13401

From the issue:
> In Camel K mode, automatic registration is disabled by default, because the deployment can be scale up/down (especially in Knative mode, where this happens automatically):
> - Camel K will setup a webhook subscription resource that takes care of externally registering/deregistering the webhook when the integration is created/edited/deleted (will use the webhook component API for this)
>
>
> With this meta-component, in Camel K + Knative mode, we can create integrations from telegram, slack, github, twitter, dropbox, .... that can scale down to 0 when not used.

We should figure out what's the best strategy, but at high level Camel K should define a new custom resource e.g. `WebhookRegistration` that will create a pod with the role of configuring the routes as in the main integration but not starting them: routes will be used to register/deregister all webhooks.
Deregistration will be triggered by a finalizer in the `WebhookRegistration` resource.

**Comment by squakez** [comment]
@christophd @claudio4j do you think this is still relevant?

**Comment by claudio4j** [comment]
I have not used this camel-webhook before, but it is an interesting idea.
From camel side, only telegram component is able to have the webhook configured.
From camel-k perspective I think this is relevant, because it adds the async behavior to integrations.
