### ISSUE TITLE
Camel K with Java routes without public class and imports ...

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#605]
I wonder if we can add support for Java routes to be even shorter if you do not have any public class, so you can just write the Camel DSL directly ala you can do for java script

    from("timer:foo")
      .log("Hello World");

Then we can detect that there is no public class, and automatic add that and put the code inside the configure method.

Of course this is for very simple routes, where most of the code is just out of the box EIPs and their configurations. And this is also good for demos :)

Any thoughts?

**Comment by lburgazzoli** [comment]
just use groovy :)

I did tough about it and it is not easy at the moment but it maybe better when we switch to java > 8 as we may use jshell

**Comment by davsclaus** [comment]
ah yeah then its more baked in from the jvm itself
