### ISSUE TITLE
Kamel binary install on Windows 10 with Minikube

### ISSUE THREAD

**Issue by pchakina** [apache/camel-k#619]
Hi, 
I am working with  Windows 10 Enterprise edition with Minikube. I installed Minikube on windows 10 .

Step1 : minikube start : it looks good
Stpe 2:  minikube addons enable registry  :    
       -   registry was successfully enabled ....message displayed on screen
Step 3: I have downloaded camel-k-client-0.3.2-windows-64bit for Kamel binary
Step 4:  Updated windows system path variable to points to Kamel binary directory
Step 5: kamel install   Here i found issue....unable to install kamel binary.....system is showing pop-up window  with notepad ....etc ...options to open... Please find attached image for details.

Can you help me out on this to install kamel binary.

Thanks,
Pchakina

[
![Kamel Install error using Minikube on windows 10 Enterprise edition](https://user-images.githubusercontent.com/3655422/56262285-0a99be00-60ac-11e9-8a35-251b39a55fa1.jpg)
](url)

**Comment by zregvart** [comment]
@pchakina what does `where kamel` and `echo %PATH%` output? You might need to logout and login again to get the `PATH` environment variable to update.

**Comment by pchakina** [comment]
Hi ,
Thanks for the reply. i have verified path variable and logged out and login again ...i am not seeing any difference.  What is the extension of Kamel binary ...? Please find attached image.
i am seeing this error ....even setting Kamel  binary  file path in windows environment variable also ... Its windows 10 Professional environment

'kamel' is not recognized as an internal or external command,
operable program or batch file.

![KAMEL on windows 10 screen](https://user-images.githubusercontent.com/3655422/56482990-0ea35280-6495-11e9-9af1-83f14b3b1b14.jpg)
![path screen settings ](https://user-images.githubusercontent.com/3655422/56483034-575b0b80-6495-11e9-8a84-628bfbe7fb8e.jpg)
![Kamel binary path location](https://user-images.githubusercontent.com/3655422/56483189-48288d80-6496-11e9-8f94-f17e7c6b3a30.jpg)

Thanks,
pchakina

**Comment by jamesnetherton** [comment]
I think this happens because there is no file extension on the kamel binary. So Windows is not sure of how to handle it. If you rename the the file to `kamel.exe`, you should find that it starts working.

To fix this in future releases, I could tweak the `cross_compile.sh` script to add a `.exe` extension to the Windows kamel binary.
