### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Emmerson-Miranda** [apache/camel-k#653]
Congrats the project looks really good.

I want to evaluate if I can use It in production projects.

I wonder if you can provide an example about how to use "kamel run --repository" and how to use camel-binding to call java clases stored in custom jar libraries.

https://camel.apache.org/bean-binding.html

**Comment by oscerd** [comment]
The actual documentation is at: 
https://github.com/apache/camel/blob/master/core/camel-core/src/main/docs/eips/bean-eip.adoc

**Comment by Emmerson-Miranda** [comment]
Thanks,

The documentation example use "ExampleBean", however what happen is the "ExampleBean" is inside a MyCustomLibrary.jar.

Assuming I want to use "ExampleBean" from printer.groovy (see examples) how I can run kamel command line? can we do something like following:

$kamel run printer.groovy --library-dependency MyCustomLibrary.jar

**Comment by lburgazzoli** [comment]
Your library need to be hosted on an maven repo then you can run

    kamel run --dependency mvn:your.company/your.artifact/version printer.groovy

If the library is not on maven central:

    kamel run --repository http://your.repo --dependency mvn:your.company/your.artifact/version printer.groovy

**Comment by Emmerson-Miranda** [comment]
Hello I tried with "camel-activemq" dependency to connect to ActiveMQ 5.15.9 (not Artemis) but is not working.

The command line I run is:-
$ kamel run --dependency mvn:org.apache.camel/camel-activemq/3.0.0-M2 --dev  MyActiveMQPublisherRoute.java

Please find attached the source code.
[MyActiveMQPublisherRoute.java.zip](https://github.com/apache/camel-k/files/3189441/MyActiveMQPublisherRoute.java.zip)

**Comment by nicolaferraro** [comment]
I think you need to set the integration platform to use Camel 3.0.0-M2 too. You cannot mix Camel 2 and Camel 3 libs.

Can you try to:
```
kubectl edit integrationplatform
```

Then change the camelVersion to `3.0.0-M2`. Then redeploy the integration.

We're going to set Camel 3 as default from next release.

**Comment by Emmerson-Miranda** [comment]
Great, is working.

In my case I have minishift and use **oc** command
```
oc edit integrationplatform
```
