### ISSUE TITLE
Do not rebuild knative integrations when changing sink

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#662]
We should optimize trait management: distinguish build time traits from deployment time.

I've 2 integrations, setting differently some Knative options.

Case 1:
```
    Knative:
      Configuration:
        Channel - Sinks:     
        Channel - Sources:   
        Enabled:             true
        Endpoint - Sinks:    
        Endpoint - Sources:  default
```

Case 2:
```
    Knative:
      Configuration:
        Channel - Sinks:     
        Channel - Sources:   camel
        Enabled:             true
        Endpoint - Sinks:    
        Endpoint - Sources:  default
```

That's the only difference, they use the same libs.
I run integration 1 and a context is built for it.

I run integration 2 and a new context is built again.

That's because traits explicitly set in the integration are reported into the context.
But it does not make sense to create a new image, because the knative trait does not influence build time properties of the image.

**Comment by nicolaferraro** [comment]
It happens that when I change sink of a knative integration, the kit is rebuilt because the Knative trait configuration is contained in the kit. But it should not..

**Comment by lburgazzoli** [comment]
I think we had an issue related to this in the past but I'm unable to find it any more

**Comment by nicolaferraro** [comment]
Verified it's no more present

**Comment by nicolaferraro** [comment]
Still present, but not on pure camel k but in knative sources. I.e. when tre knative trait config is filled-in and not computed automatically by the camel k operator.

Any source is rebuilt when changing the sink.
