### ISSUE TITLE
Error creating integration context with buildStrategy: routine on minikube

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#665]
Installed camel-k on a brand new installation of minikube v1.0.1 with the following add-ons installed:

- addon-manager: enabled
- dashboard: enabled
- default-storageclass: enabled
- ingress: enabled
- registry: enabled
- storage-provisioner: enabled

When running an integration, the related context fails to be created because of:

    "error":"stat /workspace: no such file or directory"

Full stack-trace:

```
{"level":"error","ts":1558282189.3706098,"logger":"camel-k","msg":"Unexpected error while creating a temporary dir","error":"stat /workspace: no such file or directory","stacktrace":"github.com/apache/camel-k/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/apache/camel-k/pkg/util/log.Logger.Error\n\t/home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/pkg/util/log/log.go:70\ngithub.com/apache/camel-k/pkg/util/log.Error\n\t/home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/pkg/util/log/log.go:191\ngithub.com/apache/camel-k/pkg/builder.(*defaultBuilder).Build\n\t/home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/pkg/builder/builder.go:66\ngithub.com/apache/camel-k/pkg/controller/build.(*scheduleRoutineAction).build\n\t/home/nferraro/gopaths/camel-k/src/github.com/apache/camel-k/pkg/controller/build/schedule_routine.go:107"}
```

/cc @astefanutti

**Comment by astefanutti** [comment]
The `routine` build strategy is currently not supported with the `kaniko` publish strategy. The main reason is to support different installation paths, like OLM, in addition to `kamel` CLI, that prevent creating resources like PVCs before hand.

I plan to work on a `service` build strategy that would off-load the build controller in a separate service and _decorate_ the `routine` build strategy.

In the meantime, we may want to improve the error handling, and fail fast when the `--build-strategy` option is set to `routine` for Kubernetes / Kaniko.

**Comment by lburgazzoli** [comment]
Relates to #681
