### ISSUE TITLE
Insufficient permission when installing 0.3.3 from operatorhub

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#686]
I get the following state:

```
apiVersion: camel.apache.org/v1alpha1
kind: IntegrationContext
metadata:
  creationTimestamp: '2019-05-27T12:51:57Z'
  generation: 1
  labels:
    app: camel-k
    camel.apache.org/context.created.by.kind: Operator
    camel.apache.org/context.created.by.name: camel-k-operator
    camel.apache.org/context.type: platform
  name: jvm
  namespace: nicola
  resourceVersion: '40117'
  selfLink: /apis/camel.apache.org/v1alpha1/namespaces/nicola/integrationcontexts/jvm
  uid: 35ff3e93-807e-11e9-abf2-02a6b1608572
spec:
  dependencies:
    - 'runtime:jvm'
    - 'camel:core'
status:
  camelVersion: 2.23.2
  digest: vVSq1WGo9KKN03F7GSda6IWQMWi4Fp7IYpZtqYCPO2B8
  failure:
    reason: >-
      cannot delete build config: buildconfigs.build.openshift.io "camel-k-jvm"
      is forbidden: User "system:serviceaccount:nicola:camel-k-operator" cannot
      delete resource "buildconfigs" in API group "build.openshift.io" in the
      namespace "nicola"
    recovery:
      attempt: 5
      attemptMax: 5
      attemptTime: '2019-05-27T12:54:53Z'
    time: '2019-05-27T12:52:10Z'
  phase: Error
  runtimeVersion: 0.3.2

```

There are no buildconfigs in the ns, but the operator should be allowed to delete them if present.
I'm installing the operatorhub.io version on OCP. Isn't the operatorhub.io version supposed to work on both Kube and Openshift? @astefanutti

**Comment by astefanutti** [comment]
Current manifest for operatorhub.io is only compatible for Kubernetes.

We may want to test that adding OpenShift specific group does not affect Kubernetes compatibility and have a single manifest for both Kubernetes and OpenShift.

**Comment by nicolaferraro** [comment]
Yeah, it should work, but better trying it.. We may release an update after next Camel K release.

**Comment by astefanutti** [comment]
Yes, that was the rational of quickly delivering Camel K into operatorhub.io that primarily targets Kubernetes.

There is another manifest for Openshift in community operator.

Work has been done to unify the deployment in #661, so it should only be a matter of merging the roles. But better testing than saying 😉.

**Comment by nicolaferraro** [comment]
I've not done tests on kube, but I've added all knative permission to the operator role, on a OCP cluster that does not know anything about knative, and the role has been installed correctly and platform is now ready.

**Comment by astefanutti** [comment]
Thanks for the feedback, that's good news. I think it'd be better maintaining only one CSV. I can merge the OpenShift roles in the CSV during the next release cycle.
