### ISSUE TITLE
`make generate` does not work with new module structure

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#699]
It does `operator-sdk generate k8s` under the hood.

It does not work even with `go mod vendor`.
I did a `dep ensure` in gopath to download the `k8s.io/code-generator` files.
It seems a common issue: https://github.com/kubernetes/kubernetes/issues/67566

**Comment by lburgazzoli** [comment]
Some additional info: 

    https://github.com/kubernetes/sample-apiserver/#when-using-go-111-modules
