### ISSUE TITLE
Setup the maven proxy inside of the builder

### ISSUE THREAD

**Issue by WillemJiang** [apache/camel-k#706]
It could be helpful if kamel can provide an option to setup the [proxy](https://maven.apache.org/settings.html#Proxies) in the maven setting.xml. 

We could do it by overriding the base image maven setting, but it could be much handy if we can change it through kamel command.

Any thought?

**Comment by nicolaferraro** [comment]
There's an option to set the Maven mirror/repositories (`--repository`) but not the proxy. I think it's something worth adding.
