### ISSUE TITLE
Cannot reinstall the kamel in minikube

### ISSUE THREAD

**Issue by WillemJiang** [apache/camel-k#711]
Once uninstall the kamel with below command in minikube
```
kubectl delete all,pvc,configmap,rolebindings,clusterrolebindings,secrets,sa,roles,clusterroles,crd -l 'app=camel-k'
```
The pod "camel-k-cache"  is in pending states after I reinstall the kamel with below commands
```
kamel install
kamel  run examples/simple.groovy --dev
```
I found this error when running "kubectl describe pod camel-k-cache"
```
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  9s (x11 over 91s)  default-scheduler  persistentvolumeclaim "camel-k" is being deleted
```
How can I reinstall kamel without restart the minikube?

**Comment by WillemJiang** [comment]
It looks like using "kamel reset, kamel install" can reinstall the camel-k. 
@nicolaferraro  Could you confirm it?

**Comment by davsclaus** [comment]
Yeah using the CLI should be the more correct way of re-installing. Also we should maybe have an uninstall command ?

**Comment by ipolyzos** [comment]
@WillemJiang @davsclaus @nicolaferraro

Is this issue still valid?

**Comment by davsclaus** [comment]
Yeah lets close this
