### ISSUE TITLE
Update Camel K tagline in Kamel CLI

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#732]
$ kamel
Apache Camel K is a lightweight integration framework
built from Apache Camel that runs natively on Kubernetes and is
specifically designed for serverless and microservice architectures.

That should be using the new tag line which you can see on the front page on github

**Comment by WillemJiang** [comment]
As we don't have admin right of github repo,  I just created an Infra JIRA [INFRA-18591](https://issues.apache.org/jira/browse/INFRA-18591) for updating the github description info of camel-k.

**Comment by WillemJiang** [comment]
FYI, the github project description of camel-k was updated.

**Comment by davsclaus** [comment]
@WillemJiang it was the old tagline, it should have been

-> Apache Camel K is a lightweight integration platform, born on Kubernetes, with serverless superpowers.

**Comment by WillemJiang** [comment]
@davsclaus OK, I will update the JIRA  with this now tagline.
