### ISSUE TITLE
Automatically create catalogs from maven

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#744]
Cannot the catalog be created by the operator if not present in the cluster?
It seems to me a simple maven build and it saves a lot of work when people want to try a version of camel for which we don't provide the catalog out of the box.

Wdyt @lburgazzoli , @valdar ?

**Comment by lburgazzoli** [comment]
yes that's possible, I did it locally in the past but I've removed it when we moved to semver matching

**Comment by nicolaferraro** [comment]
An error happens when using e.g. runtime 1.0.6 (from staging) and camel 3.0.0-RC1

**Comment by astefanutti** [comment]
That part has been reworked as part of the Quarkus support and that issue should be fixed with #1013.

**Comment by astefanutti** [comment]
This should now be fixed as #1013 has been merged.
