### ISSUE TITLE
Add a --global install option

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#745]
We have a "--skip-operator-setup" flag to install only the platform resource, but not a "--global" flag to install the operator in a fixed namespace (e.g. "camel-k") and configure it to watch all namespaces.

The setting is only supported on operatorhub for now.

**Comment by jamesnetherton** [comment]
Just want to check that my understanding of what the workflow would look like for this is correct. I was thinking something like:

1. Install the operator 'globally':

```
kamel install --global --namespace camel-k
```
2. Install platform into secondary namespace(s):

```
kamel install --skip-operator-setup --namespace namespace-1
```
```
kamel install --skip-operator-setup --namespace namespace-2
```

3. Create integration(s):

```
kamel run example-java.java --namespace namespace-1
```
```
kamel run example-js.js --namespace namespace-2
```

**Comment by nicolaferraro** [comment]
Yes, sounds good.
I think we need also a way to make sure global operator and local operator don't conflict if both are installed, but I'll open another ticket for that.
