### ISSUE TITLE
Make sure global and local operators can cohexist

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#751]
Don't know if this is needed or can be manager completely within OLM, but if installed manually, two operators (a global and a local one) in a cluster can have issues.

We can add a check that is activated only in global mode, to dynamically blacklist some namespaces if there's already an local operator.

**Comment by nicolaferraro** [comment]
https://github.com/operator-framework/operator-sdk/issues/2508

**Comment by lburgazzoli** [comment]
looks like there won't be any solution form the operator-sdk

**Comment by nicolaferraro** [comment]
Solution reported from them is to use OLM to avoid overlapping configurations. So we do.

**Comment by nicolaferraro** [comment]
Maybe we can do better, adding a guard ourselves can help. Currently I need an empty cluster if I want to check that global mode works, but this can be avoided with some simple checks in the global operator.
