### ISSUE TITLE
Propagate build errors up to the integration

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#763]
If a build fail, the related kit will be marked as failing (after a number of attempt to recovery from the error) but the integration that has triggered the creation of the kit and the build, will stuck in "building kit" phase

**Comment by jamesnetherton** [comment]
I was going to take a look into this but seems it was already taken care of in https://github.com/apache/camel-k/commit/d7086fdbc8ca240a2cd39751c08b322df567cd68. See [here](https://github.com/apache/camel-k/blob/master/pkg/controller/integration/build_kit.go#L78).

I tested and it works as expected.

**Comment by lburgazzoli** [comment]
So I've fixed it by chance :)
