### ISSUE TITLE
All links of the documentation are missing spaces before and after displayed text

### ISSUE THREAD

**Issue by apupier** [apache/camel-k#794]
for instance https://camel.apache.org/staging/camel-k/latest/installation/minikube.html
![image](https://user-images.githubusercontent.com/1105127/60512912-2d646780-9cd6-11e9-8b6c-d6f0f500bfa5.png)

in source code, the space seems correct
https://github.com/apache/camel-k/edit/antora/docs/modules/ROOT/pages/installation/minikube.adoc
![image](https://user-images.githubusercontent.com/1105127/60513030-70bed600-9cd6-11e9-9c15-d181b6f46db3.png)

**Comment by astefanutti** [comment]
It seems it's been fixed. Let me close this. Feel free to re-open if needed.
