### ISSUE TITLE
one page of documentation to install Camel-K on Minikube is incorrect

### ISSUE THREAD

**Issue by apupier** [apache/camel-k#798]
this page https://camel.apache.org/staging/camel-k/latest/installation/minikube.html 

![image](https://user-images.githubusercontent.com/1105127/60518170-40c90000-9ce1-11e9-8d33-2de165f1b651.png)

is mentioning nothing about the extra parameter to provide that are mentioned on https://github.com/apache/camel-k/blob/master/docs/cluster-setup.adoc#minikube

![image](https://user-images.githubusercontent.com/1105127/60518189-4de5ef00-9ce1-11e9-93ea-37a9062e9b98.png)

it is quite important to fix it because there is no errors during installation and some parts of the deployment are reporting success. You need to dig into some pod logs to finally find a totally unrelated error (at least from a newcomer point of view). An error like:

`error pushing image: failed to push to destination 10.103.185.129/default/camel-k-ctx-bkdlhuftt2idjd0d2ia0:3107: Head http://10.103.185.129/v2/default/camel-k-ctx-bkdlhuftt2idjd0d2ia0/blobs/sha256:b6ea704449b4b3b4fc99025edc9aea6cc5ec26660a40e57523bff8f13eb088e2: dial tcp 10.103.185.129:80: connect: connection refused`

**Comment by lburgazzoli** [comment]
@apupier the documentation has been re-factored can you check if there is anything that is still missing and eventually amen this issue ?

**Comment by apupier** [comment]
working fine.

tested with:
- kamel 1.0.0
- minikube 1.8.2
- unset of all minikube config ( `minikube config view` is returning nothing)
