### ISSUE TITLE
Wrong links from second page on

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#827]
Some links point to the wrong location.

E.g.
"Minikube" on the home page is ok.
"Minikube" from the "Local cluster setup guide" is wrong ("/installation/installation/...").

@zregvart any clue? Does it work on Antora?

**Comment by zregvart** [comment]
I'll have a look, I had some issues rebasing so I probably overlooked this.

**Comment by zregvart** [comment]
I've had a look, the links work fine from the rendered Antora, the `xref:` links in Antora are specified [from the module path](https://docs.antora.org/antora/2.0/page/page-id/#important) onward. The only way I see this to work across GitHub and rendered Antora is to flatten all documents into `docs/modules/ROOT/pages` and not use topics to organize content.

How important is that the links work on GitHub? Perhaps we can change the links in the README.adoc to point to the [staging site](https://camel.apache.org/staging/camel-k/latest/)?

**Comment by nicolaferraro** [comment]
Yeah, I had a similar issue when I tried the first migration to Antora.

Linking staging (and later the main website) from the main README.adoc sounds like a good plan.
