### ISSUE TITLE
GC trait fails on some installations

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#832]
I attach an issue occurred to @burrsutter on try.openshift.io.

https://gist.github.com/burrsutter/74117d90bcfca403a5f70e4fc240c14e

**Comment by astefanutti** [comment]
Some aggregated APIs may not support the `list` operation the GC trait performs to discover Camel K resources to be GCed. One option would be to ignore the error, so it be useful to get the HTTP error code, maybe a 503. I've asked @burrsutter for some details.

**Comment by burrsutter** [comment]
I have been trying to use an OCP4 created via tryopenshift.com 
oc version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.0-201905191700+82e7b55-dirty", GitCommit:"82e7b55", GitTreeState:"dirty", BuildDate:"2019-05-20T00:17:47Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+838b4fa", GitCommit:"838b4fa", GitTreeState:"clean", BuildDate:"2019-05-19T23:51:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}


oc new-project myintegrations
kamel install
kamel run hello.groovy

but the pod fails to come to life, the build happens, but no resulting pod

**Comment by astefanutti** [comment]
This should effectively be fixed with #950.
