### ISSUE TITLE
Fails to run build after install with  javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name

### ISSUE THREAD

**Issue by dmvolod** [apache/camel-k#84]
[INFO] Building camel-k-integration 0.0.2-SNAPSHOT
--
  | [INFO] ------------------------------------------------------------------------
  | Downloading: https://repo.maven.apache.org/maven2/org/apache/camel/camel-groovy/2.22.1/camel-groovy-2.22.1.pom
  | [INFO] ------------------------------------------------------------------------
  | [INFO] BUILD FAILURE
  | [INFO] ------------------------------------------------------------------------
  | [INFO] Total time: 1.163 s
  | [INFO] Finished at: 2018-09-17T13:12:44+00:00
  | [INFO] Final Memory: 13M/293M
  | [INFO] ------------------------------------------------------------------------
  | [ERROR] Failed to execute goal on project camel-k-integration: Could not resolve dependencies for project org.apache.camel.k.integration:camel-k-integration:jar:0.0.2-SNAPSHOT: Failed to collect dependencies at org.apache.camel:camel-groovy:jar:2.22.1: Failed to read artifact descriptor for org.apache.camel:camel-groovy:jar:2.22.1: Could not transfer artifact org.apache.camel:camel-groovy:pom:2.22.1 from/to central (https://repo.maven.apache.org/maven2):  handshake alert:  unrecognized_name -> [Help 1]
  | org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project camel-k-integration: Could not resolve dependencies for project org.apache.camel.k.integration:camel-k-integration:jar:0.0.2-SNAPSHOT: Failed to collect dependencies at org.apache.camel:camel-groovy:jar:2.22.1
  | at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
  | at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
  | at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:257)
  | at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
  | at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
  | at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
  | at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
  | at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
  | at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
  | at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
  | at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
  | at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
  | at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
  | at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
  | at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
  | at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
  | at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
  | at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
  | at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
  | Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.apache.camel.k.integration:camel-k-integration:jar:0.0.2-SNAPSHOT: Failed to collect dependencies at org.apache.camel:camel-groovy:jar:2.22.1
  | at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:180)
  | at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
  | ... 23 more
  | Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.apache.camel:camel-groovy:jar:2.22.1
  | at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
  | at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
  | at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:172)
  | ... 24 more
  | Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.apache.camel:camel-groovy:jar:2.22.1
  | at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:302)
  | at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:218)
  | at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
  | at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
  | at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
  | at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
  | at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
  | at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
  | ... 26 more
  | Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.apache.camel:camel-groovy:pom:2.22.1 from/to central (https://repo.maven.apache.org/maven2):  handshake alert:  unrecognized_name
  | at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
  | at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
  | at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
  | at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:287)
  | ... 33 more
  | Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.apache.camel:camel-groovy:pom:2.22.1 from/to central (https://repo.maven.apache.org/maven2):  handshake alert:  unrecognized_name
  | at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
  | at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
  | at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
  | at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
  | at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
  | at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
  | at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
  | ... 36 more
  | Caused by: org.apache.maven.wagon.TransferFailedException: handshake alert:  unrecognized_name
  | at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1066)
  | at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:960)
  | at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
  | at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
  | at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
  | at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
  | at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
  | at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
  | at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
  | at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
  | ... 41 more
  | Caused by: javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name
  | at sun.security.ssl.ClientHandshaker.handshakeAlert(ClientHandshaker.java:1446)
  | at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2026)
  | at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1135)
  | at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
  | at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
  | at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
  | at org.apache.maven.wagon.providers.http.httpclient.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:275)
  | at org.apache.maven.wagon.providers.http.httpclient.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:254)
  | at org.apache.maven.wagon.providers.http.httpclient.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
  | at org.apache.maven.wagon.providers.http.httpclient.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
  | at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
  | at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
  | at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
  | at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec.execute(RetryExec.java:86)
  | at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
  | at org.apache.maven.wagon.providers.http.httpclient.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
  | at org.apache.maven.wagon.providers.http.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
  | at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:832)
  | at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:983)
  | ... 50 more
  | [ERROR]

**Comment by nicolaferraro** [comment]
I don't think we specify the maven repository somewhere in the project. Is it due to your config or a project conf @dmvolod ?

**Comment by dmvolod** [comment]
@nicolaferraro this occurs on ./kamel install and not related to the integration run. I'm using oc cluster wrapper.

**Comment by dmvolod** [comment]
@lburgazzoli , yes, by default maven uses https and I don't know why oc cluster up become fails with https. I will try to change repoin the project to use http instead of https and test it on cluster up.

**Comment by onderson** [comment]
the reason of https failure may be SSL certificate of maven repo needs to be imported into jvm's trusted CA certificates file

**Comment by dmvolod** [comment]
It was my problem with DNS outside the office in oc cluster up. Thanks to all.
