### ISSUE TITLE
service and route not created when using --open-api parameter

### ISSUE THREAD

**Issue by brunoNetId** [apache/camel-k#843]
As discussed with:
@lburgazzoli 

A camel route like this:
  <from uri="undertow:http://0.0.0.0:8080/hello"/>

creates both a service and a route

but when using the parameter --open-api and defining the route as:
   <from uri="direct:restOperationId"/>

the service and route seem not to be created, and the Integration shows as follows:
![image](https://user-images.githubusercontent.com/14263485/61523376-89d4c000-aa14-11e9-8962-5146c71d4842.png)

**Comment by lburgazzoli** [comment]
I did run the `greetings` with the latest code with the following command:

```
kamel run \
    --dev \
    --name greetings \
    --dependency camel-undertow \
    --dependency camel:rest \
    --dependency mvn:org.apache.camel.k/camel-k-loader-xml \
    --property camel.rest.port=8080 \
    --open-api examples/greetings-api.json \
    --logging-level org.apache.camel.k=DEBUG \
    examples/greetings.groovy 
```

And what I have on minishift is:

![image](https://user-images.githubusercontent.com/1868933/61576687-5447d980-aadd-11e9-8918-9d9ea266ced8.png)

There is an [issue](https://github.com/apache/camel-k/issues/839) that prevents the generated Rest DSL to be taken into account by the source analyzer so the following two dependencies are needed:

```
    --dependency camel:rest \
    --dependency mvn:org.apache.camel.k/camel-k-loader-xml \
```

**Comment by lburgazzoli** [comment]
@brunoNetId can we close this one ?
