### ISSUE TITLE
Upgrade operator sdk to 0.9.0

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#845]
https://github.com/operator-framework/operator-sdk/releases/tag/v0.9.0

**Comment by lburgazzoli** [comment]
@astefanutti do you mind having a look ?

**Comment by astefanutti** [comment]
@lburgazzoli yes, let me work on it.

**Comment by astefanutti** [comment]
It should fix #699 and #702, and it should be possible to remove `vendor` directory pre-build generation altogether: 

https://github.com/apache/camel-k/blob/d33cc45d2e16d021bbeabe0522b916c5d197c508/script/Makefile#L159-L160
