### ISSUE TITLE
make images fail on resolve of camel-k-maven-plugin

### ISSUE THREAD

**Issue by ipolyzos** [apache/camel-k#869]
``` $ make images``` fails on the latest master due to unable to resolve maven artifact.

Please see the error message below for more

> [INFO] ------------< org.apache.camel.k:camel-k-catalog-generator >------------
> [INFO] Building camel-k-catalog-generator 1.0.0
> [INFO] --------------------------------[ jar ]---------------------------------
> [INFO]
> [INFO] --- maven-dependency-plugin:3.1.1:copy-dependencies (default-cli) @ camel-k-catalog-generator ---
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy-dependencies (default-cli) on project camel-k-catalog-generator: Error resolving project artifact: Could not find artifact org.apache
> .camel.k:camel-k-maven-plugin:pom:1.0.0-20190723.194340-25 for project org.apache.camel.k:camel-k-maven-plugin:maven-plugin:1.0.0-SNAPSHOT -> [Help 1]                                                                          
> [ERROR]                                                 

You can also refer to the following link for the full log output 
https://pastebin.com/hxsiu5TR

**Comment by dmvolod** [comment]
Before this, you to build camel-k-runtime repo

**Comment by lburgazzoli** [comment]
afaik, `make images` does not require to download any java bit

**Comment by ipolyzos** [comment]
@dmvolod, indeed building the [camel-k runtime ](https://github.com/apache/camel-k-runtime)solves this issue.
 Thank you

**Comment by ipolyzos** [comment]
A new issue later on the compilation of _pkg/trait/knative.go_ stops from completing the images-dev build please see the log below

> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  2.670 s
> [INFO] Finished at: 2019-07-25T10:54:47+01:00
> [INFO] ------------------------------------------------------------------------
> mkdir -p build/_maven_output
> mkdir -p build/_output/bin
> cp builder build/_output/bin
> operator-sdk build docker.io/apache/camel-k:1.0.0-M1-SNAPSHOT
> # github.com/apache/camel-k/pkg/trait
> pkg/trait/knative.go:301:52: cannot use *status.RouteStatusFields.Address (type "knative.dev/pkg/apis/duck/v1alpha1".Addressable) as type "github.com/knative/pkg/apis/duck/v1alpha1".Addressable in argument to buildServiceDefinition
> pkg/trait/knative.go:309:16: addressable.URL undefined (type "github.com/knative/pkg/apis/duck/v1alpha1".Addressable has no field or method URL)
> pkg/trait/knative.go:310:88: addressable.URL undefined (type "github.com/knative/pkg/apis/duck/v1alpha1".Addressable has no field or method URL)
> pkg/trait/knative_service.go:209:7: cannot use "github.com/knative/serving/pkg/apis/serving/v1beta1".RevisionSpec literal (type "github.com/knative/serving/pkg/apis/serving/v1beta1".RevisionSpec) as type "knative.dev/serving/pkg/apis/serving/v1beta1".RevisionSpec in field value
> Error: failed to build operator binary: (failed to exec []string{"go", "build", "-o", "/home/ipolyzos/repositories/camel-k/build/_output/bin/camel-k", "-gcflags", "all=-trimpath=/home/ipolyzos/repositories", "-asmflags", "all=-trimpath=/home/ipolyzos/repositories", "-mod=vendor", "github.com/apache/camel-k/cmd/manager"}: exit status 2)
> Usage:
>   operator-sdk build <image> [flags]
> 
> Flags:
>       --go-build-args string      Extra Go build arguments as one string such as "-ldflags -X=main.xyz=abc"
>   -h, --help                      help for build
>       --image-build-args string   Extra image build arguments as one string such as "--build-arg https_proxy=$https_proxy"
>       --image-builder string      Tool to build OCI images. One of: [docker, podman, buildah] (default "docker")
> 
> Global Flags:
>       --verbose   Enable verbose logging
> 
> make: *** [Makefile:170: images-dev] Error 1
>

**Comment by dmvolod** [comment]
@ipolyzos what is your operator-sdk version?

**Comment by dmvolod** [comment]
Also please pull latest commits from upstream as some changes related to build process were made

**Comment by ipolyzos** [comment]
$ operator-sdk version                                                                                                                  git:(master|… 
operator-sdk version: v0.9.0, commit: 560208dc998de497bbf59fea1b63426aec430934

**Comment by ipolyzos** [comment]
I can confirm that this issue is not present in a fresh copy. 

Please see the log below:
> ....
>  ---> e17c53f10082
> Step 6/7 : ADD build/_output/bin/camel-k /usr/local/bin/camel-k
>  ---> fbae7e310acf
> Step 7/7 : ADD build/_output/bin/builder /usr/local/bin/camel-k-builder
>  ---> b89050cbfaa8
> Successfully built b89050cbfaa8
> Successfully tagged apache/camel-k:1.0.0-M1-SNAPSHOT
> INFO[0021] Operator build complete.   

@dmvolod  thanks
