### ISSUE TITLE
Kamel reset should delete builds as well as kits

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#875]

**Comment by ipolyzos** [comment]
I could not replicate the issue. In a sample scenario with a _reset_ after running the [simple.groovy](https://github.com/apache/camel-k/blob/master/examples/simple.groovy) example shows _builds_ to be removed.

Please see the log output at [pastebin.com/kU1eeazx](https://pastebin.com/kU1eeazx)

**Comment by nicolaferraro** [comment]
Thanks @ipolyzos for verifying. We can close this.
