### ISSUE TITLE
kamel --output option should not need deploy resources to cluster

### ISSUE THREAD

**Issue by chirino** [apache/camel-k#886]
running: 

```
oc delete crd -l app=camel-k
kamel install --cluster-setup -o yaml 
```

results in:

```
Error: cannot check CRD installation after 25 seconds
```

From my point of view, --output should not actually be installed or assume the CRDs are installed in the cluster.  Someone might do this to get the k8s config into a file they send to an admin that wants to manually install the resources.

**Comment by squakez** [comment]
I can have a look at this if nobody else is working on it.
