### ISSUE TITLE
Improve kamel "get" to enable specifying integration name

### ISSUE THREAD

**Issue by bfitzpat** [apache/camel-k#893]
Right now calling `kamel get` returns a list of all integrations and their status:
```
$ kamel get
NAME    PHASE   CONTEXT
sample  Running kit-bl0tq3m6e0nii5b92dhg
simple  Running kit-bl10do66e0nii5b92dj0
```

It would be great to be able to focus on a single integration to get the status. Something like:
```
$ kamel get simple
NAME    PHASE   CONTEXT
simple  Running kit-bl10do66e0nii5b92dj0
```

**Comment by bfitzpat** [comment]
Currently if I pass an integration name to the command, I just get:
```
$ kamel get simple
NAME    PHASE   CONTEXT
sample  Running kit-bl0tq3m6e0nii5b92dhg
simple  Running kit-bl10do66e0nii5b92dj0
```

**Comment by bfitzpat** [comment]
(Version 1.0.0-M1)

**Comment by jamesnetherton** [comment]
Should be simple enough to add support for providing the integration name. I'll take a look.

**Comment by bfitzpat** [comment]
I believe that `kubectl get integration [name]` returns the same information, but it would be nice to have in the kamel executable as well.
