### ISSUE TITLE
Road Map about Yaml DSL

### ISSUE THREAD

**Issue by WillemJiang** [apache/camel-k#902]
I noticed that camel-k support yaml DSL recently. Is there any road map of it?
Currently we are try to build DSL from the json definition, it looks like using the yaml DSL directly could save us some efforts to do the DSL generation. so I just want to double check if we have long time support of it.

**Comment by lburgazzoli** [comment]
The goal is to move it to apache camel once it becomes and stable enough and feature complete so yes you’ll have LTS :)

**Comment by WillemJiang** [comment]
Yeah, it's a good news.

**Comment by rejimathews** [comment]
thats great! having a yaml dsl to code camel integrations. !
