### ISSUE TITLE
Dev mode doesn't show if the build failed

### ISSUE THREAD

**Issue by tim-hellhake** [apache/camel-k#906]
Although the build failed the dev mode is still in interactive mode with the last phase `Building Kit`.
I would expect the dev mode to be terminated or at least an error message. 
```
> kamel run examples/Sample.java --dev

integration "sample" created
integration "sample" in phase Waiting For Platform
integration "sample" in phase Initialization
integration "sample" in phase Building Kit
```
![image](https://user-images.githubusercontent.com/17127122/62950744-f9a65280-bde8-11e9-8054-700c7b90734c.png)

**Comment by jamesnetherton** [comment]
Seems the watch that gets set up on the integration exceeds its timeout, as the build error recovery loop can take a while to exhaust all of its retry attempts.

When I force the watch timeout to 5 minutes, I can then see the error status:

```
integration "sample" in phase Error
integration deployment failed
```
