### ISSUE TITLE
Update Camel-K/Knative examples for 1.0.0-M1 release

### ISSUE THREAD

**Issue by mgencur** [apache/camel-k#908]
The goal is to update https://github.com/apache/camel-k/tree/1.0.0-M1/examples/knative so that it works with the latest 1.0.0-M1 release.
Currently, I'm getting this error when running the examples:
```
Exception in thread "main" org.apache.camel.RuntimeCamelException: java.lang.IllegalArgumentException:
Unable to find loader for: Source{location='file:/etc/camel/sources/i-source-000/source.flow', language=flow ,
compressed=false} at org.apache.camel.RuntimeCamelException.wrapRuntimeCamelException(RuntimeCamelException.java:52) at 
```
According to @lburgazzoli the examples need to be updated because "the flow does not exists anymore and we now have a full yaml DSL for Camel"

**Comment by sully6768** [comment]
@mgencur, I have been running the knative examples with 1.0.0-M1 for a few days now sorting out a few issues. I haven't seen this one though. Which source file were you running? And in which variation of Kube are you running it in (minishift, codeready, minikube, full OCP/OKD, etc)?

**Comment by mgencur** [comment]
@sully6768 actually, it's probably not caused by examples from the URL above, I'm doing this:
```
camelSource, err := ctx.Clients.Namespaced.Knative.CamelSourceInterface.Create(&camel.CamelSource{
		ObjectMeta: meta.ObjectMeta{
			Name: "camel-timer-source",
		},
		Spec: camel.CamelSourceSpec{
			Source: camel.CamelSourceOriginSpec{
				Component: &camel.CamelSourceOriginComponentSpec{
					URI: "timer:tick?period=3s",
				},
			},
			Sink: test.ChannelReference(channel),
		},
	})
```

Right now I"m not sure what could cause the issue. I think we'll need to investigate more on our side.

We're running on OCP 4.1.11

**Comment by maschmid** [comment]
That part comes from the Knative Eventing Camel Source sample, not the camel-k sample.

https://knative.dev/docs/eventing/samples/apache-camel-source/
https://knative.dev/docs/eventing/samples/apache-camel-source/source_timer.yaml

**Comment by astefanutti** [comment]
@mgencur could you specify what version of Knative and Knative Camel sources you use?

**Comment by lburgazzoli** [comment]
@mgencur is this still an issue ?
