### ISSUE TITLE
Knative route from AWS S3 endpoint immediatly stops after starting

### ISSUE THREAD

**Issue by lubuxnl** [apache/camel-k#919]
In order to do the [Red Hat Knative tutorial](https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial/0.7.x/index.html) I created a [Vagrant box](https://github.com/lubuxnl/ubuntu-minikube/tree/knative) with Virtualbox on Windows 10 Pro. In the VM I'm running Minikube v1.3.1 with the none driver and with this setup I was able to do the exercises with Knative serving and eventing v0.7.1. To do the exercises with Camel-K I installed camel-k v0.3.4 and ran several of the examples from the camel-k git repo successfully, including the Knative examples. When running the first example from the Knative tutorial however, I noticed the route starts successfully, but then immediately stops. After stopping the log shows an UnresolvedAddressException (see attached [logfile](https://github.com/apache/camel-k/files/3563801/cartoon-message-mover.txt)). I found a similar issue (#506) in this repo, but that issue was apparently fixed in camel-k-runtime 0.3.1, while camel-k v0.3.4 uses version 0.3.3 of camel-k-runtime. Any ideas how to fix this?

**Comment by nicolaferraro** [comment]
Hi @lubuxnl , camel k version that is compatible with Knative 0.7.1 is v 1.0.0-M1. Can you try with that?

Also it does not matter how you call the knative listener service, if it doesn't work, can you try to replace:

from("knative:endpoint/s3filelogger")

With:

from("knative:endpoint/default")

**Comment by lubuxnl** [comment]
Thanks for your feedback @nicolaferraro As you suggested I upgraded my camel-k installation to v1.0.0-M1 and tried to run the example again. This time however the route didn't even start, because a class (org.apache.camel.processor.idempotent.MemoryIdempotentRepository) couldn't be found (see attached [logfile](https://github.com/apache/camel-k/files/3566679/cartoon-message-mover.txt)). Really strange, because the Camel jars seem to be in the classpath. Any ideas what is causing this error? In the meanwhile I will go back to the previous camel-k version and try changing the name of the endpoint.

**Comment by nicolaferraro** [comment]
Probably because v1.0.0-M1 uses camel 3 by default.

You should reinstall deleting the platform configuration:
```
kubectl delete integrationplatform --all
kamel install
```

**Comment by lburgazzoli** [comment]
looks like the tutorial need to be updated to reflect the changes in camel 3.x as MemoryIdempotentRepository has been moved to a different package `org.apache.camel.support.processor.idempotent`

**Comment by lubuxnl** [comment]
Thanks for your tips @nicolaferraro and @lburgazzoli After updating the package of the MemoryIdempotentRepository class the knative route starts fine :-)
