### ISSUE TITLE
Camel-K build fails with error: open /workspace/builder-656588331/package/context/Dockerfile: no such file or directory

### ISSUE THREAD

**Issue by lubuxnl** [apache/camel-k#923]
I am running Camel-K 1.0.0-M1 with Knative serving and eventing 0.7.1 on Minikube 1.3.1. With this setup I can run the Knative examples from this repository as well as some of the Camel-K examples of the [Red Hat Knative tutorial](https://github.com/redhat-developer-demos/knative-tutorial/tree/master/advanced/camel-k) (with a few [changes](https://github.com/lubuxnl/knative-tutorial/tree/master/advanced/camel-k), because these examples were created for a previous Camel-K version). For some other examples from this tutorial however, especially the [Cartoon Messages Downloader](https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-camelk/0.3.3/poll-enrich.html) and the [Cartoon Genre Router](https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-camelk/0.3.3/content-based-router.html#cbr-cartoon-genre-router), the build fails with the message that it can't find the Dockerfile in the workspace directory (see the [logfile](https://github.com/apache/camel-k/files/3569901/camel-k-kit-bln75t60fdln57f5a9lg-builder.log) of the latter example). I suppose this Dockerfile should have been created by the builder, but for some reason it didn't for these examples. Any ideas on how to make this work?

**Comment by vinayakadkoli** [comment]
Thanks for bringing this up, even i'm stuck at the same step

**Comment by lubuxnl** [comment]
I just recreated my [Vagrant/Virtualbox/Minikube](https://github.com/lubuxnl/ubuntu-minikube/tree/knative) VM from scratch and installed Istio, Knative and Camel-K. I then tried to run the printer, splitter and feed routes from the [examples/knative](https://github.com/apache/camel-k/tree/master/examples/knative) folder of this repo. This time the printer and feed routes built and ran fine, but the splitter route encountered the same error as reported in this issue during the build (see [logfile](https://github.com/apache/camel-k/files/3595383/camel-k-kit-splitter-builder.log)). Previously also this route ran fine, so apparently the problem is not with the route itself, but some specific condition. Is it possible to get logging at debug level for the build process, that might help explain the condition that caused the build to fail?

**Comment by asifdxtreme** [comment]
Even I am facing the same issue when running multiple integrations parallely with similar set of dependencies.

**Comment by lubuxnl** [comment]
Still didn't find a solution, but I found a workaround for this issue: I was able to run the Cartoon Messages Downloader and Cartoon Genre Router examples from the Red Hat Knative tutorial by using the integration kits of the CartoonMessagesMover and ComedyGenreHandler respectively (by adding --kit <integration kit> to the kamel run command).
I also uninstalled Camel-K and reinstalled it and after that I installed the Cartoon Genre Router example first. This time the integration built successfully. Apparently it depends on which integration kits are already available in the platform whether or not this problem occurs.

**Comment by lburgazzoli** [comment]
@lubuxnl @asifdxtreme is this still an issue ?

**Comment by lubuxnl** [comment]
@lburgazzoli I didn't try this anymore. Currently I am focusing on other technologies, so I probably won't retry in the near future. Sorry.

**Comment by lburgazzoli** [comment]
no worries, going to close this and you can reopen in the future when you'll get back to camel-k :)
