### ISSUE TITLE
Is there a way to co-locate the camel-k-operator, builder and PV in the same node

### ISSUE THREAD

**Issue by asifdxtreme** [apache/camel-k#924]
Say I have a multi-cluster K8s env and I have a local storage provisoner which provisions a volume in a particular node so is there a way I can instruct `kamel  install` to make sure camel-k-operator/builder/PV resides in that particular pod.  I think we can do this by adding an extra config in `kamel install` for label selector but I am not sure if this will be the right thing to do. If the adding a new config for label selctor is the only way then I can submit a PR for that.

**Comment by nicolaferraro** [comment]
What's the problem you're trying to solve @asifdxtreme ? I think when you switch to creating builders that are external to the operator, they are automatically co-located with the data PV.

This is done e.g. to make sure a maven builder can pass data to a Kaniko pod in order to push a new image.

**Comment by lburgazzoli** [comment]
@astefanutti can we close this one after all the changes we made to the builder ?

**Comment by astefanutti** [comment]
Yes, collocation requirements for the builds are automatically handled by the operator.
