### ISSUE TITLE
Add Kamel CLI download link in OpenShift Web console

### ISSUE THREAD

**Issue by astefanutti** [apache/camel-k#939]
The OpenShift Web console exposes a CRD to add custom download links for CLI tools like Knative and Tekton CLIs. It'd be cool to add a link for users to be able to download the `kamel` CLI as well.

**Comment by nicolaferraro** [comment]
Nice, where did you find doc about it?

**Comment by astefanutti** [comment]
There may not be any official documentation yet, though the CRD is explicit enough: openshift/console#1441.

It is part of OpenShift 4.2 so the presence of the CRD must be checked.

**Comment by nicolaferraro** [comment]
@astefanutti are you working on this. I was planning to start releasing 1.0.0-M2 this afternoon. We can move it to M3 if you prefer.

**Comment by astefanutti** [comment]
@nicolaferraro I'm working on it but still testing and polishing. Better move it to M3 and release M2 ASAP.
