### ISSUE TITLE
Release Camel K 1.0.0-M2

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#944]
Time for a M2 release. Let's plan it for next Thrusday.

I'm going to create a milestone so we can track issues that we want to be included.

**Comment by oscerd** [comment]
+1

**Comment by oscerd** [comment]
We still have some pending PRs

**Comment by nicolaferraro** [comment]
Let's postpone release by a week to have more time to fix and tests issues in: https://github.com/apache/camel-k/milestone/4

**Comment by nicolaferraro** [comment]
## New Features

- Added support for using kamel CLI in Tekton Pipelines ([#943](https://github.com/apache/camel-k/pull/943), [@nicolaferraro](https://github.com/nicolaferraro))
- Improved kamel CLI experience with remote clusters (90% faster) ([#940](https://github.com/apache/camel-k/pull/940), [@nicolaferraro](https://github.com/nicolaferraro))
- Added automatic resolution of dependencies for language expressions ([#957](https://github.com/apache/camel-k/pull/957), [@jamesnetherton](https://github.com/jamesnetherton))
- Added support for Knative (Serving and Eventing) 0.8.x and 0.9.x ([#961](https://github.com/apache/camel-k/pull/961), [@nicolaferraro](https://github.com/nicolaferraro))
- Added support for proxy servers in Kaniko builds ([#905](https://github.com/apache/camel-k/pull/905), [@jamesnetherton](https://github.com/jamesnetherton))


## Bug Fixes

- Dev mode now shows if the build failed ([#927](https://github.com/apache/camel-k/pull/927), [@jamesnetherton](https://github.com/jamesnetherton))
- Restricted gc discovery to listable types ([#917](https://github.com/apache/camel-k/pull/917), [@astefanutti](https://github.com/astefanutti))
- Fixed issue which prevented creating builds on GKE ([#979](https://github.com/apache/camel-k/pull/979), [@nicolaferraro](https://github.com/nicolaferraro))
- Fixed Jolokia and Prometheus traits configuration ([#954](https://github.com/apache/camel-k/pull/954), [@astefanutti](https://github.com/astefanutti))
- Updated 'CONTEXT' column header in 'kamel get' output to 'KIT' ([#964](https://github.com/apache/camel-k/pull/964), [@jamesnetherton](https://github.com/jamesnetherton))


## Other Notable Changes

- Release notes are now auto-generated ([#963](https://github.com/apache/camel-k/pull/963), [@nicolaferraro](https://github.com/nicolaferraro))
- Improve "kamel get" command to enable specifying integration name ([#897](https://github.com/apache/camel-k/pull/897), [@jamesnetherton](https://github.com/jamesnetherton))
- Removed usage of hostnames instead of IP addresses when referencing the internal registry on Knative profile ([#916](https://github.com/apache/camel-k/pull/916), [@astefanutti](https://github.com/astefanutti))
- Upgrade to Operator SDK 0.10.0 ([#949](https://github.com/apache/camel-k/pull/949), [@astefanutti](https://github.com/astefanutti))
