### ISSUE TITLE
Include camel-k-runtime version in camel-catalog

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#959]
We need to include the camel-k-runtime version in camel catalog and use it to match the right catalog for an integration

**Comment by lburgazzoli** [comment]
https://github.com/apache/camel-k-runtime/issues/141

**Comment by nicolaferraro** [comment]
@lburgazzoli I see some commits going around.. do you plan to solve this today or we move it to M3?

**Comment by lburgazzoli** [comment]
not today, likely next week
