### ISSUE TITLE
Build completes OK but integration shows ERROR

### ISSUE THREAD

**Issue by steveww** [apache/camel-k#965]
[build.log](https://github.com/apache/camel-k/files/3663356/build.log)

$ kamel get
Shows error and the pod is not running, but no errors in the log???

[foo.txt](https://github.com/apache/camel-k/files/3663369/foo.txt)

**Comment by jamesnetherton** [comment]
Looks like https://github.com/apache/camel-k/issues/960.

The same error is present in the build log:

```
{"level":"info","ts":1569596803.3845682,"logger":"camel-k.builder","msg":"step done in 0.009136 seconds","step":"github.com/apache/camel-k/pkg/builder/IncrementalPackager","phase":30,"kit":"kit-bm725sq7e5omlm5uhsmg"}
{"level":"info","ts":1569596803.3845954,"logger":"camel-k.builder","msg":"executing step","step":"github.com/apache/camel-k/pkg/builder/kaniko/Publisher","phase":40,"kit":"kit-bm725sq7e5omlm5uhsmg"}
{"level":"info","ts":1569596803.384622,"logger":"camel-k.builder","msg":"step failed with error: open /workspace/builder-333639899/package/context/Dockerfile: no such file or directory","step":"github.com/apache/camel-k/pkg/builder/kaniko/Publisher","phase":40,"kit":"kit-bm725sq7e5omlm5uhsmg"}
```

**Comment by steveww** [comment]
May be I should try with an older version of K8s?

**Comment by nicolaferraro** [comment]
@steveww I see you're using Camel K 1.0.0-M1, so it's probably something that broke in recent versions of Kube.

What kubernetes version are you using? Minikube?

**Comment by steveww** [comment]
Minikube 1.4 IIRC with K8s 1.16.

**Comment by nicolaferraro** [comment]
> Minikube 1.4 IIRC with K8s 1.16.
> […](#)
> Sent from my iPhone
> On 27 Sep 2019, at 18:29, Nicola Ferraro ***@***.***> wrote: @steveww I see you're using Camel K 1.0.0-M1, so it's probably something that broke in recent versions of Kube. What kubernetes version are you using? Minikube? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Yes, same as mine... I get the same error
