### ISSUE TITLE
Able to set custom camel-k-operator image name and location 

### ISSUE THREAD

**Issue by dmvolod** [apache/camel-k#97]
In some cases, for example in disconnected mode, it's unable to download image from docker.io
It wold be nice to have an option for 'kamel install' to define image name, location and version.
@nicolaferraro , what do you think about it?

**Comment by nicolaferraro** [comment]
@dmvolod when you're connected or disconnected you can always attach to the same docker daemon used by Minishift/Minikube and build a image as `docker.io/apache/camel-k:0.0.2-SNAPSHOT` or tag a different image with that name (this is what these [two lines](https://github.com/apache/camel-k/blob/1bf909cb10759e7334dcc38af9f4672f38c3b5f9/build/install_minishift.sh#L14-L15) are doing).

The `Deployment` resource that instantiates the operator is set with a `imagePullPolicy: IfNotPresent`, meaning that it will try to contact Docker Hub only when there are no corresponding images in the local store. This means that docker hub will never be contacted if you provide a image for `docker.io/apache/camel-k:0.0.2-SNAPSHOT`. I think there's no need to use a different name...

**Comment by jcordes73** [comment]
What if access to docker.io is blocked and I want to use an intermediate docker repository as a proxy (f.e. Nexus)? IMO providing a "custom" location would be a good solution.

**Comment by lburgazzoli** [comment]
as today you can override the almost all the option at build time:

    make ... IMAGE_NAME=your.registry/your.org/camel-k
