### ISSUE TITLE
Remove references to host that did compilation in stacktraces

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#972]
I thought we already did it in previous releases, but I continue to see references to my host machine (nferraro) even on 1.0.0-M1.

Probably due to the switch to go modules.

**Comment by lburgazzoli** [comment]
Yep, we do remove the result of $(shell go env GOPATH)

**Comment by nicolaferraro** [comment]
So I need to set gopath next time I release..

**Comment by lburgazzoli** [comment]
Maybe we only need to use the `-trimpath` flag without arguments

**Comment by lburgazzoli** [comment]
looks like go 1.13 has introduced a `-trimpath` flag for the `build` sub command that does the trick
