### ISSUE TITLE
Wrong behavior of global mode wrt kaniko cache warmer and platform

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#984]
When doing `kamel install --global`, the operator should be installed in global mode in the current namespace (message should mention the "global" mode) and I think there's no need to create the integration platform there, since you're going to create an integration platform in other ns probably (the fact that platform has not been installed can be also mentioned).

The strange thing I've noticed is that the kaniko warmer is started in the namespace where I install the global operator.

But when I run `kamel install --skip-operator-setup` in another ns, no warmer pod is started.

**Comment by astefanutti** [comment]
Currently, the Kaniko warmer pod is co-located to the operator so that it can be co-located with build pods, to share the default host path persistent volume.

I think we could create one Kaniko warmer pod per integration platform, then co-locate build pods with the corresponding warmer pod.

**Comment by nicolaferraro** [comment]
Yeah, there's no need in general to co-locate it with operator since we don't use the routine build process anymore on kube
