### ISSUE TITLE
support for quarkus in native mode

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k#991]
Quarkus support would really shine in native mode in combination of Knative auto-scaling. 

The process of building native images is still very heavy and it may not be the best fit with Camel K incremental build mechanism, still Time-To-First-Bytes is deemed critical for serverless applications. 

One approach would be to schedule a native build in parallel of the JVM mode build, and perform a rollout deployment once the native build has completed.

**Comment by ogomezdi** [comment]
It'll great having this feature, resource consumption reduce significantly in native mode, not only in terms of execution time or  throughput, but also in memory consumption making the same infrastructure able to increase the number of microservices deployed, which is in my case one of the biggest problems.

**Comment by lburgazzoli** [comment]
@astefanutti @jamesnetherton @ppalaga anyone interested in implementing this issue ?

**Comment by astefanutti** [comment]
@lburgazzoli happy to work on it, or help if @jamesnetherton @ppalaga you want to do it. 

It seems building Quarkus applications in native mode on OpenShift has been smoothed: https://www.openshift.com/blog/introducing-the-quarkus-helm-chart.

**Comment by ppalaga** [comment]
@astefanutti feel free to go ahead!
